PROGRAM TEST_LOAD_MODEL

USE TYPE_MODEL
USE GEOMETRY_MOD       

USE UTIL_MODEL_MOD
USE UTIL_GEOMETRY_MOD
USE UTIL_MODEL_DYNAMICS_TYPE_MOD
USE UTIL_TDYN_MOD

IMPLICIT NONE

TYPE (MODEL) :: YLMODEL
TYPE (GEOMETRY) :: YLGEOMETRY

CHARACTER*32 :: CLFILE
INTEGER :: ILUN
INTEGER*8 :: ISIZE
INTEGER :: I

ILUN = 77

CALL GETARG (1, CLFILE)
OPEN (UNIT=ILUN, FILE=TRIM (CLFILE), FORM='UNFORMATTED')
CALL LOAD (ILUN, YLMODEL)
CLOSE (UNIT=ILUN)

ISIZE = SIZE (YLMODEL, "YLMODEL", .TRUE.)
PRINT *, " SIZE (YLMODEL) = ", ISIZE

ISIZE = SIZE (YLMODEL%YRML_DYN, "YLML_DYN", .TRUE.)
PRINT *, " SIZE (YLML_DYN) = ", ISIZE

ISIZE = SIZE (YLMODEL%YRML_DYN%YRDYN, "YLDYN", .TRUE.)
PRINT *, " SIZE (YLDYN) = ", ISIZE

CALL COPY (YLMODEL) 

PRINT *, " NTSHM        = ", YLMODEL%YRML_PHY_MF%YRPHY2%NTSHM
PRINT *, " NTSML        = ", YLMODEL%YRML_PHY_MF%YRPHY2%NTSML
PRINT *, " TSPHY        = ", YLMODEL%YRML_PHY_MF%YRPHY2%TSPHY
PRINT *, " XMUCVPP      = ", YLMODEL%YRML_PHY_MF%YRPHY2%XMUCVPP
PRINT *, " XMULAF       = ", YLMODEL%YRML_PHY_MF%YRPHY2%XMULAF
PRINT *, " XDAMP        = ", YLMODEL%YRML_PHY_MF%YRPHY2%XDAMP
PRINT *, " HCLP         = ", YLMODEL%YRML_PHY_MF%YRPHY2%HCLP
PRINT *, " HTCLS        = ", YLMODEL%YRML_PHY_MF%YRPHY2%HTCLS
PRINT *, " HVCLS        = ", YLMODEL%YRML_PHY_MF%YRPHY2%HVCLS
PRINT *, " HTSHM        = ", YLMODEL%YRML_PHY_MF%YRPHY2%HTSHM
PRINT *, " HTSML        = ", YLMODEL%YRML_PHY_MF%YRPHY2%HTSML
PRINT *, " HWMOHIGH     = ", YLMODEL%YRML_PHY_MF%YRPHY2%HWMOHIGH
PRINT *, " HWMOLOW      = ", YLMODEL%YRML_PHY_MF%YRPHY2%HWMOLOW
PRINT *, " GZ0RAF       = ", YLMODEL%YRML_PHY_MF%YRPHY2%GZ0RAF
PRINT *, " FACRAF       = ", YLMODEL%YRML_PHY_MF%YRPHY2%FACRAF
PRINT *, " FACRAFCV     = ", YLMODEL%YRML_PHY_MF%YRPHY2%FACRAFCV
PRINT *, " FACRAFDCAPE  = ", YLMODEL%YRML_PHY_MF%YRPHY2%FACRAFDCAPE
PRINT *, " GCAPERAF     = ", YLMODEL%YRML_PHY_MF%YRPHY2%GCAPERAF
PRINT *, " HTKERAF      = ", YLMODEL%YRML_PHY_MF%YRPHY2%HTKERAF
PRINT *, " LRAFTUR      = ", YLMODEL%YRML_PHY_MF%YRPHY2%LRAFTUR
PRINT *, " LMULAF       = ", YLMODEL%YRML_PHY_MF%YRPHY2%LMULAF
PRINT *, " LWMOCLOUD    = ", YLMODEL%YRML_PHY_MF%YRPHY2%LWMOCLOUD
PRINT *, " LRAFTKE      = ", YLMODEL%YRML_PHY_MF%YRPHY2%LRAFTKE

!$acc serial present (YLMODEL)
PRINT *, " NTSHM        = ", YLMODEL%YRML_PHY_MF%YRPHY2%NTSHM
PRINT *, " NTSML        = ", YLMODEL%YRML_PHY_MF%YRPHY2%NTSML
PRINT *, " TSPHY        = ", YLMODEL%YRML_PHY_MF%YRPHY2%TSPHY
PRINT *, " XMUCVPP      = ", YLMODEL%YRML_PHY_MF%YRPHY2%XMUCVPP
PRINT *, " XMULAF       = ", YLMODEL%YRML_PHY_MF%YRPHY2%XMULAF
PRINT *, " XDAMP        = ", YLMODEL%YRML_PHY_MF%YRPHY2%XDAMP
PRINT *, " HCLP         = ", YLMODEL%YRML_PHY_MF%YRPHY2%HCLP
PRINT *, " HTCLS        = ", YLMODEL%YRML_PHY_MF%YRPHY2%HTCLS
PRINT *, " HVCLS        = ", YLMODEL%YRML_PHY_MF%YRPHY2%HVCLS
PRINT *, " HTSHM        = ", YLMODEL%YRML_PHY_MF%YRPHY2%HTSHM
PRINT *, " HTSML        = ", YLMODEL%YRML_PHY_MF%YRPHY2%HTSML
PRINT *, " HWMOHIGH     = ", YLMODEL%YRML_PHY_MF%YRPHY2%HWMOHIGH
PRINT *, " HWMOLOW      = ", YLMODEL%YRML_PHY_MF%YRPHY2%HWMOLOW
PRINT *, " GZ0RAF       = ", YLMODEL%YRML_PHY_MF%YRPHY2%GZ0RAF
PRINT *, " FACRAF       = ", YLMODEL%YRML_PHY_MF%YRPHY2%FACRAF
PRINT *, " FACRAFCV     = ", YLMODEL%YRML_PHY_MF%YRPHY2%FACRAFCV
PRINT *, " FACRAFDCAPE  = ", YLMODEL%YRML_PHY_MF%YRPHY2%FACRAFDCAPE
PRINT *, " GCAPERAF     = ", YLMODEL%YRML_PHY_MF%YRPHY2%GCAPERAF
PRINT *, " HTKERAF      = ", YLMODEL%YRML_PHY_MF%YRPHY2%HTKERAF
PRINT *, " LRAFTUR      = ", YLMODEL%YRML_PHY_MF%YRPHY2%LRAFTUR
PRINT *, " LMULAF       = ", YLMODEL%YRML_PHY_MF%YRPHY2%LMULAF
PRINT *, " LWMOCLOUD    = ", YLMODEL%YRML_PHY_MF%YRPHY2%LWMOCLOUD
PRINT *, " LRAFTKE      = ", YLMODEL%YRML_PHY_MF%YRPHY2%LRAFTKE
!$acc end serial


CALL GETARG (2, CLFILE)
OPEN (UNIT=ILUN, FILE=TRIM (CLFILE), FORM='UNFORMATTED')
CALL LOAD (ILUN, YLGEOMETRY)
CLOSE (UNIT=ILUN)

ISIZE = SIZE (YLGEOMETRY, "YLGEOMETRY", .TRUE.)
PRINT *, " SIZE (YLGEOMETRY) = ", ISIZE

PRINT *, " ASSOCIATED (YLGEOMETRY%YRELBC_GEO) = ", &
& ASSOCIATED (YLGEOMETRY%YRELBC_GEO)

DO I = LBOUND (YLGEOMETRY%YRVAB%VALH, 1), UBOUND (YLGEOMETRY%YRVAB%VALH, 1)
PRINT *, " YLGEOMETRY%YRVAB%VALH = ", I, YLGEOMETRY%YRVAB%VALH (I)
ENDDO

CALL COPY (YLGEOMETRY) 

!$acc serial present (YLGEOMETRY)
PRINT *, " ASSOCIATED (YLGEOMETRY%YRELBC_GEO) = ", &
& ASSOCIATED (YLGEOMETRY%YRELBC_GEO)
DO I = LBOUND (YLGEOMETRY%YRVAB%VALH, 1), UBOUND (YLGEOMETRY%YRVAB%VALH, 1)
PRINT *, " YLGEOMETRY%YRVAB%VALH = ", I, YLGEOMETRY%YRVAB%VALH (I)
ENDDO
!$acc end serial

END PROGRAM
