SUBROUTINE APL_ARPEGE_CLOUDINESS (YDMF_PHYS_BASE_STATE, YDCPG_DIM, YDCPG_MISC, YDMF_PHYS, YDVARS,   &
& YDMODEL, LDREDPR, PAIPCMT, PBLH, PDECRD, PFLU_QSAT, PHUC, PMSC_QW, PNEBC0, PNEBCH, PNEBS, PNEBS0, &
& PNEB_CVPP, PPFL_FPLCH, PQI, PQL, PQLIS, PQLIS0, PQLI_CVP, PQLI_CVPP, PQV, PUNEBH, PVETAF)

USE PARKIND1, ONLY : JPIM, JPRB

USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_MISC_TYPE, CPG_DYN_TYPE, &
                              & CPG_SL2_TYPE, CPG_GPAR_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT(IN)    :: YDMF_PHYS_BASE_STATE
TYPE(CPG_DIM_TYPE),             INTENT(IN)    :: YDCPG_DIM
TYPE(CPG_MISC_TYPE),            INTENT(INOUT) :: YDCPG_MISC
TYPE(MF_PHYS_TYPE),             INTENT(INOUT) :: YDMF_PHYS
TYPE(FIELD_VARIABLES),          INTENT(INOUT) :: YDVARS
TYPE(MODEL),                    INTENT(IN)    :: YDMODEL
LOGICAL,                        INTENT(IN)    :: LDREDPR
REAL(KIND=JPRB),                INTENT(IN)    :: PAIPCMT(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PBLH(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PDECRD(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_QSAT (YDCPG_DIM%KLON, 1:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PHUC(YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PMSC_QW (YDCPG_DIM%KLON, 1:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PNEBC0(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PNEBCH(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PNEBS(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PNEBS0(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PNEB_CVPP(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PPFL_FPLCH (YDCPG_DIM%KLON, 0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQI(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQL(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PQLIS(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PQLIS0(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQLI_CVP(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQLI_CVPP(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQV(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PUNEBH(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PVETAF(YDCPG_DIM%KFLEVG)

#include "acnebcond.intfb.h"
#include "acnebn.intfb.h"
#include "acnpart.intfb.h"

REAL(KIND=JPRB) :: ZICEFR1(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)! Resolved Condensate ice fraction
REAL(KIND=JPRB) :: ZRHCRI(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG) ! Smith scheme critical RH
REAL(KIND=JPRB) :: ZQSATS(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG) ! QSAT of resolved cond./evap. scheme
REAL(KIND=JPRB) :: ZRH(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)    ! Temporar storage for updated PRH
REAL(KIND=JPRB) :: ZCLCT_RAD(YDCPG_DIM%KLON) ! total cloud cover for radiation

INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JLON

! CLOUDINESS COMPUTATION
CALL ACNEBCOND ( YDMODEL%YRML_GCONF%YRRIP, YDMODEL%YRML_PHY_MF, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON,  &
& YDMODEL%YRML_PHY_MF%YRTOPH%NTPLUI, YDCPG_DIM%KFLEVG, LDREDPR, PHUC, PVETAF, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI,   &
& YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP, &
& YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%R, YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%DELP, YDCPG_MISC%RH, PBLH,                &
& PQV, PQI, PQL, PMSC_QW, YDMF_PHYS_BASE_STATE%T, PNEBCH, YDVARS%GEOMETRY%GM%T0, YDMF_PHYS_BASE_STATE%YGSP_RR%T,   &
& PQLIS, PNEBS, ZRHCRI, ZRH, ZQSATS, ZICEFR1, PQLIS0, PNEBS0)



IF(YDMODEL%YRML_PHY_MF%YRPHY%LNEBN) THEN
  CALL ACNEBN ( YDMODEL%YRML_PHY_MF, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON, YDMODEL%YRML_PHY_MF%YRTOPH%NTNEBU, &
  & YDCPG_DIM%KFLEVG, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP, PQV,                      &
  & PQL, PQI, PFLU_QSAT, YDMF_PHYS_BASE_STATE%T, PPFL_FPLCH, YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%DELP,                      &
  & YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%RDELP, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, PUNEBH, PNEBS0,                       &
  & PQLIS0, PQLI_CVP, PNEB_CVPP, PQLI_CVPP, PAIPCMT, YDCPG_MISC%NEB, PNEBC0, YDCPG_MISC%QICE, YDCPG_MISC%QLI,             &
  & PHUC, PVETAF)
  DO JLEV=YDCPG_DIM%KTDIA,YDCPG_DIM%KFLEVG
!DEC$ IVDEP
    DO JLON=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
      YDCPG_MISC%NEB(JLON,JLEV)=YDCPG_MISC%NEB(JLON,JLEV)*YDMODEL%YRML_PHY_MF%YRPHY0%GAEPS
    ENDDO
  ENDDO
ENDIF

!         Diagnostique de nebulosite partielle.
CALL ACNPART(YDMODEL%YRML_PHY_MF, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON, YDMODEL%YRML_PHY_MF%YRTOPH%NTNEBU,            &
& YDCPG_DIM%KFLEVG, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, &
& PDECRD, YDCPG_MISC%NEB, YDMF_PHYS%OUT%CLCH, YDMF_PHYS%OUT%CLCM, YDMF_PHYS%OUT%CLCL, YDCPG_MISC%CLCT,                            &
& ZCLCT_RAD, PCLCC=YDMF_PHYS%OUT%CLCC, PNEBC=PNEBC0, PTOPC=YDMF_PHYS%OUT%CTOP)  


END SUBROUTINE
