SUBROUTINE APL_AROME_CALC_IPGFL (YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDMODEL, KPGFL)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK

USE PARKIND1, ONLY : JPIM, JPRB

USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE),INTENT(IN)   :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),INTENT(IN)   :: YDCPG_OPTS
TYPE(MODEL)       ,INTENT(IN)    :: YDMODEL
INTEGER(KIND=JPIM) :: KPGFL(YDMODEL%YRML_GCONF%YGFL%NUMFLDS)


INTEGER (KIND=JPIM) :: JGFL

REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('APL_AROME_CALC_IPGFL', 0, ZHOOK_HANDLE)

! * Calculation of IPGFL, since the old pointers
!   MSLB1[X]9 (=MSLB1GFL9+IP[X]) do not exist any longer in PTRSLB1.

! usefull pointer for new version of cputqy

DO JGFL=1,YDMODEL%YRML_GCONF%YGFL%NUMFLDS
  IF ((YDMODEL%YRML_GCONF%YGFL%YCOMP(JGFL)%MP1 > 0) .AND. (YDMODEL%YRML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1 > 0)) THEN
     KPGFL(YDMODEL%YRML_GCONF%YGFL%YCOMP(JGFL)%MP1) = (YDMODEL%YRML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDCPG_OPTS%KFLEVG+2*YDGEOMETRY%YRDIMV%NFLSUL)
  ENDIF   
ENDDO  


IF (LHOOK) CALL DR_HOOK ('APL_AROME_CALC_IPGFL', 1, ZHOOK_HANDLE)

END SUBROUTINE
