SUBROUTINE APL_ARPEGE_AEROSOLS_FOR_RADIATION (YDMF_PHYS_BASE_STATE, YDCPG_DIM, YDMF_PHYS_SURF, &
& YDMODEL, PAEDES, PAELAN, PAER, PAERINDS, PAESEA, PAESOO, PAESUL, PAEVOL)

USE PARKIND1, ONLY : JPIM, JPRB

USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT(IN)    :: YDMF_PHYS_BASE_STATE
TYPE(CPG_DIM_TYPE),             INTENT(IN)    :: YDCPG_DIM
TYPE(MF_PHYS_SURF_TYPE),        INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(MODEL),                    INTENT(IN)    :: YDMODEL
REAL(KIND=JPRB),                INTENT(OUT)   :: PAEDES(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PAELAN(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PAER(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG,6)
REAL(KIND=JPRB),                INTENT(OUT)   :: PAERINDS(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PAESEA(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PAESOO(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PAESUL(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PAEVOL(YDCPG_DIM%KLON)

#include "radaer.intfb.h"

INTEGER (KIND=JPIM) :: JLON
LOGICAL :: LLAERO


! COMPUTATION OF AEROSOLS (FOR RADIATION)

LLAERO=YDMODEL%YRML_PHY_MF%YRPHY%LAEROSEA.AND.YDMODEL%YRML_PHY_MF%YRPHY%LAEROLAN.AND.YDMODEL%YRML_PHY_MF%YRPHY%LAEROSOO.AND.YDMODEL%YRML_PHY_MF%YRPHY%LAERODES

IF (((MOD(YDCPG_DIM%KSTEP,YDMODEL%YRML_PHY_RAD%YRERAD%NRADFR) == 0))) THEN
  IF (LLAERO) THEN
    DO JLON = YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
      PAESEA(JLON) = YDMF_PHYS_SURF%GSD_VA%PSEA(JLON)
      PAELAN(JLON) = YDMF_PHYS_SURF%GSD_VA%PLAN(JLON)
      PAESOO(JLON) = YDMF_PHYS_SURF%GSD_VA%PSOO(JLON)
      PAEDES(JLON) = YDMF_PHYS_SURF%GSD_VA%PDES(JLON)
    ENDDO
  ELSE
    DO JLON = YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
      PAESEA(JLON) = 0.0_JPRB
      PAELAN(JLON) = 0.0_JPRB
      PAESOO(JLON) = 0.0_JPRB
      PAEDES(JLON) = 0.0_JPRB
    ENDDO
  ENDIF
    
  DO JLON = YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
    PAESUL(JLON) = 0.0_JPRB
  ENDDO       
  DO JLON = YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
    PAEVOL(JLON) = 0.0_JPRB
  ENDDO
    
  IF ( ( (YDMODEL%YRML_PHY_RAD%YRERAD%NAER /= 0)).AND.LLAERO )  THEN
    CALL RADAER ( YDMODEL%YRML_PHY_RAD%YREAERD, YDMODEL%YRML_PHY_RAD%YRERAD, YDMODEL%YRML_PHY_MF%YRPHY,         &
    & YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON, YDCPG_DIM%KFLEVG, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, &
    & YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, YDMF_PHYS_BASE_STATE%T, YDMF_PHYS_BASE_STATE%YGSP_RR%T,            &
    & PAESEA, PAELAN, PAESOO, PAEDES, PAESUL, PAEVOL, PAER, PAERINDS)
  ENDIF
ENDIF ! FOR AEROSOLS



END SUBROUTINE
