SUBROUTINE APL_WIND_GUST (YDMF_PHYS_BASE_STATE, YDCPG_DIM, YDCPG_OPTS, YDMF_PHYS, YDVARS, YDXFU, YDMODEL, KMOC_CLPH, PBLH, PDCAPE)

USE PARKIND1, ONLY : JPIM, JPRB

USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE YOMXFU             , ONLY : TXFU
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT(IN)    :: YDMF_PHYS_BASE_STATE
TYPE(CPG_DIM_TYPE),             INTENT(IN)    :: YDCPG_DIM
TYPE(CPG_OPTS_TYPE),            INTENT(IN)    :: YDCPG_OPTS
TYPE(MF_PHYS_TYPE),             INTENT(INOUT) :: YDMF_PHYS
TYPE(FIELD_VARIABLES),          INTENT(INOUT) :: YDVARS
TYPE(TXFU),                     INTENT(IN)    :: YDXFU
TYPE(MODEL),                    INTENT(IN)    :: YDMODEL
INTEGER (KIND=JPIM),            INTENT(OUT)   :: KMOC_CLPH (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PBLH(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PDCAPE(YDCPG_DIM%KLON)

#include "accldia.intfb.h"

! WIND GUST COMPUTATION
IF (YDMODEL%YRML_PHY_MF%YRPHY2%LRAFTKE) THEN
  YDMF_PHYS%OUT%CAPE(:)=0._JPRB
  PDCAPE(:)=0._JPRB
  CALL ACCLDIA(YDXFU, YDMODEL%YRML_PHY_MF%YRPHY, YDMODEL%YRML_PHY_MF%YRPHY2, YDMODEL%YRML_PHY_MF%YRTOPH, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON, YDCPG_DIM%KFLEVG,       &
  & YDMF_PHYS%OUT%UCLS, YDMF_PHYS%OUT%VCLS, YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, YDMF_PHYS%OUT%CAPE, PDCAPE, YDMF_PHYS_BASE_STATE%TKE, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDVARS%GEOMETRY%OROG%T0, &
  & YDMF_PHYS%OUT%UGST, YDMF_PHYS%OUT%VGST, PBLH, KMOC_CLPH)
ENDIF


END SUBROUTINE
