SUBROUTINE APL_ARPEGE_SURFACE (YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_DIM, YDCPG_MISC, YDCPG_GPAR, &
& YDMF_PHYS, YDMF_PHYS_SURF, YDVARS, YDSURF, YDMODEL, LDCONFX, PALBD, &
& PALBP, PALPHA1, PCDROV, PCEROV, PCFATH, PCFAU, &
& PCFBTH, PCFBU, PCFBV, PCHROV, PCOEFA, PCOEFN, PCP, PDIFEXT, &
& PDIFWQ, PDIFWS, PDQSTS, PDSA_CPS, PDSA_LHS, PDTMSE, PEDMFQ, PEDMFS, PEDMFU, PEDMFV, &
& PFLU_CD, PFLU_CDN, PFLU_EMIS, PFLU_FEVI, PFLU_NEIJ, PFLU_QSATS, PFLU_VEG, &
& PHQ, PHTR, PHU, PKQLROV, PKQROV, PKTROV, PKUROV, PLVT, PMF_UP, PNEBCH, PNEBDIFF, PNEBS, PPOID, &
& PQI, PQICE, PQL, PQV, PRDG_MU0, PRDG_MU0N, PRHGMT, PSC_FCLL, PSC_FCLN, PSC_FEVI, &
& PSC_FEVN, PSFSWDIF, PSFSWDIR, PSGROUPEL, PSRAIN, PSSNOW, PSTATI, &
& PTSN, PXDROV, PXHROV, PXQRO, PXTRO, PXTROV, PXURO, PXUROV)

USE PARKIND1, ONLY : JPIM, JPRB

USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_MISC_TYPE, CPG_DYN_TYPE, &
                              & CPG_SL2_TYPE, CPG_GPAR_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_MISC_TYPE, CPG_DYN_TYPE, &
                              & CPG_SL2_TYPE, CPG_GPAR_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE TYPE_MODEL         , ONLY : MODEL
USE YOMRIP0            , ONLY : NINDAT
USE YOMCST             , ONLY : RG       
USE YOMCT0             , ONLY : LCALLSFX 


IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT(IN)    :: YDMF_PHYS_BASE_STATE
TYPE(GEOMETRY),                 INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_DIM_TYPE),             INTENT(IN)    :: YDCPG_DIM
TYPE(CPG_MISC_TYPE),            INTENT(INOUT) :: YDCPG_MISC
TYPE(CPG_GPAR_TYPE),            INTENT(INOUT) :: YDCPG_GPAR
TYPE(MF_PHYS_TYPE),             INTENT(INOUT) :: YDMF_PHYS
TYPE(MF_PHYS_SURF_TYPE),        INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(FIELD_VARIABLES),          INTENT(INOUT) :: YDVARS
TYPE(TSURF),                    INTENT(IN)    :: YDSURF
TYPE(MODEL),                    INTENT(IN)    :: YDMODEL
LOGICAL,                        INTENT(IN)    :: LDCONFX
REAL(KIND=JPRB),                INTENT(INOUT) :: PALBD(YDCPG_DIM%KLON,YDCPG_DIM%KSW)
REAL(KIND=JPRB),                INTENT(INOUT) :: PALBP(YDCPG_DIM%KLON,YDCPG_DIM%KSW)
REAL(KIND=JPRB),                INTENT(OUT)   :: PALPHA1(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PCDROV(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PCEROV(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PCFATH(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PCFAU(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PCFBTH(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PCFBU(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PCFBV(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PCHROV(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PCOEFA (YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PCOEFN(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PCP(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PDIFEXT(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG,YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)
REAL(KIND=JPRB),                INTENT(OUT)   :: PDIFWQ (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PDIFWS (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PDQSTS(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PDSA_CPS (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PDSA_LHS (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PDTMSE
REAL(KIND=JPRB),                INTENT(IN)    :: PEDMFQ(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PEDMFS(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PEDMFU(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PEDMFV(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_CD (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_CDN (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PFLU_EMIS (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PFLU_FEVI (YDCPG_DIM%KLON, 1:YDCPG_DIM%KTSSG+1)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_NEIJ (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_QSATS (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_VEG (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PHQ(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PHTR(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PHU(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PKQLROV(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PKQROV(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PKTROV(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PKUROV(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PLVT (YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PMF_UP(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PNEBCH(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PNEBDIFF(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PNEBS(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PPOID(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQI(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PQICE  (YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQL(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQV(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PRDG_MU0 (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PRDG_MU0N (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PRHGMT
REAL(KIND=JPRB),                INTENT(OUT)   :: PSC_FCLL(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PSC_FCLN(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PSC_FEVI (YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PSC_FEVN(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PSFSWDIF (YDCPG_DIM%KLON,YDCPG_DIM%KSW)
REAL(KIND=JPRB),                INTENT(INOUT) :: PSFSWDIR (YDCPG_DIM%KLON,YDCPG_DIM%KSW)
REAL(KIND=JPRB),                INTENT(INOUT) :: PSGROUPEL(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PSRAIN(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PSSNOW(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PSTATI
REAL(KIND=JPRB),                INTENT(INOUT) :: PTSN(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PXDROV(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PXHROV(YDCPG_DIM%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PXQRO(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PXTRO(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PXTROV(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PXURO(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PXUROV(YDCPG_DIM%KLON,0:YDCPG_DIM%KFLEVG)

#include "acaa1.intfb.h"
#include "acdifv1.intfb.h"
#include "acdifv2.intfb.h"
#include "aro_ground_diag.h"
#include "aro_ground_diag_2isba.h"
#include "aro_ground_param.h"
#include "arp_ground_param.intfb.h"

REAL(KIND=JPRB) :: ZZS(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZTWSNOW(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZTOWNS(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZSVM (YDCPG_DIM%KLON,1,1)
REAL(KIND=JPRB) :: ZSSO_STDEV(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZSFSV (YDCPG_DIM%KLON,1)
REAL(KIND=JPRB) :: ZSFCO2(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZRHODREFM(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZQT(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZHV2(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZFMDV(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZFMDU(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZFEVS(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZFEV(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZFCLL  (YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZDSE(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZDEPTH_HEIGHT(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZCFBSV(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG,1:YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)
REAL(KIND=JPRB) :: ZCFBS(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZCFBQ(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZCFASV(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG,1:YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)
REAL(KIND=JPRB) :: ZCFAS(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZCFAQ(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZCD(YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZBUDTH (YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZBUDSO (YDCPG_DIM%KLON)
REAL(KIND=JPRB) :: ZCARDI
INTEGER(KIND=JPIM) :: IRR
INTEGER(KIND=JPIM) :: JLEV
INTEGER(KIND=JPIM) :: JLON
INTEGER(KIND=JPIM) :: JSG


! VERTICAL DIFFUSION AND IMPLICIT SURFACE
!   Sauvegarde temporaire de l'ancien acdifus pour les besoins du Climat
    
CALL ACDIFV1 ( YDMODEL%YRML_GCONF%YGFL, YDMODEL%YRML_PHY_MF, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON, YDCPG_DIM%KTDIA,                    &
& YDCPG_DIM%KFLEVG, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, PCP, YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%DELP, PKTROV, PKQROV, PKUROV, PQV, PQL, PQI, YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%RDELP, &
& YDMF_PHYS_BASE_STATE%T, YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, ZSVM, PXTROV, PXUROV, PXDROV, PXHROV, PEDMFS, PEDMFQ, PEDMFU, PEDMFV, PMF_UP, PXURO,                              &
& PXQRO, PXTRO, ZCFAQ, ZCFAS, PCFATH, PCFAU, ZCFASV, ZCFBQ, ZCFBS, PCFBTH, PCFBU, PCFBV, ZCFBSV,                                &
& ZDSE, ZQT)   
        
IF ( YDMODEL%YRML_PHY_MF%YRARPHY%LMSE.AND.LCALLSFX ) THEN
  ZCARDI=YDMODEL%YRML_PHY_RAD%YRERDI%RCARDI
  DO JLON=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
    ZRHODREFM(JLON)=YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF(JLON,YDCPG_DIM%KFLEVG)/(YDMF_PHYS_BASE_STATE%T(JLON,YDCPG_DIM%KFLEVG)*YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%R(JLON,YDCPG_DIM%KFLEVG))
    ZDEPTH_HEIGHT(JLON,:)=(YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF(JLON,:)-YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI(JLON,YDCPG_DIM%KFLEVG))/RG
    ZZS(JLON)=YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI(JLON,YDCPG_DIM%KFLEVG)/RG
  ENDDO

  IRR=2

  CALL ARO_GROUND_PARAM( YDCPG_DIM%KBL, YDCPG_DIM%KGPCOMP, YDCPG_DIM%KFDIA-YDCPG_DIM%KIDIA+1, YDCPG_DIM%KIDIA,                                             &
  & YDCPG_DIM%KFDIA, YDCPG_DIM%KSTEP, IRR, YDMODEL%YRML_PHY_RAD%YRERAD%NSW, YDMODEL%YRML_GCONF%YGFL%NGFL_EXT, YDGEOMETRY%YRDIM%NDGUNG, YDGEOMETRY%YRDIM%NDGUXG, YDGEOMETRY%YRDIM%NDLUNG, YDGEOMETRY%YRDIM%NDLUXG,                                                                  &
  & YDMODEL%YRML_PHY_MF%YRARPHY%LSURFEX_KFROM, YDMODEL%YRML_PHY_MF%YRARPHY%LMPA, YDMODEL%YRML_PHY_MF%YRARPHY%CCOUPLING, LDCONFX, NINDAT, PRHGMT, PSTATI, YDMODEL%YRML_GCONF%YRRIP%RSOVR, YDMODEL%YRML_GCONF%YRRIP%RCODEC, YDMODEL%YRML_GCONF%YRRIP%RSIDEC, YDVARS%GEOMETRY%RINDX%T0(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),     &
  & YDVARS%GEOMETRY%RINDY%T0(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS_BASE_STATE%U(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG),                     &
  & YDMF_PHYS_BASE_STATE%V(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG), YDMF_PHYS_BASE_STATE%T(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG),        &
  & YDMF_PHYS_BASE_STATE%Q(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG), ZSVM,                                                      &
  & ZCARDI, ZRHODREFM(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG),                        &
  & YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG), PDTMSE, ZDEPTH_HEIGHT(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG),   &
  & ZZS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMODEL%YRML_PHY_MF%YRMSE%XZSEPS, PRDG_MU0(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), PRDG_MU0N(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                   &
  & YDVARS%GEOMETRY%GELAM%T0(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDVARS%GEOMETRY%GEMU%T0(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                                   &
  & YDMODEL%YRML_PHY_MF%YRPARAR%XSW_BANDS, PSRAIN(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), PSSNOW(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), PSGROUPEL(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),               &
  & YDMF_PHYS%OUT%FRTHDS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), PSFSWDIF(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1:YDMODEL%YRML_PHY_RAD%YRERAD%NSW),                                               &
  & PSFSWDIR(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1:YDMODEL%YRML_PHY_RAD%YRERAD%NSW), ZCFAQ(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG),                           &
  & PCFATH(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG), PCFAU(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG), &
  & ZCFBQ(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG), PCFBTH(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG), &
  & PCFBU(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG), PCFBV(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG:YDCPG_DIM%KFLEVG),  &
  & YDMF_PHYS%OUT%FCS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1), ZFEV(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                                                          &
  & ZSFSV, ZSFCO2(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), ZFMDU(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), ZFMDV(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                        &
  & PALBP(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1:YDMODEL%YRML_PHY_RAD%YRERAD%NSW), PALBD(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1:YDMODEL%YRML_PHY_RAD%YRERAD%NSW),  &
  & PFLU_EMIS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),              &
  & PTSN(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS%OUT%FRTH(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG, 1)                                        &
  & )               !orographic shadowing

! Opposite water vapor flux
        ZFEVS(:)=-ZFEV(:)

  CALL ARO_GROUND_DIAG( YDCPG_DIM%KBL, YDCPG_DIM%KGPCOMP, YDCPG_DIM%KFDIA-YDCPG_DIM%KIDIA+1, YDCPG_DIM%KIDIA,                                           &
  & YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG, -1, YDGEOMETRY%YRDIM%NDGUNG, YDGEOMETRY%YRDIM%NDGUXG, YDGEOMETRY%YRDIM%NDLUNG, YDGEOMETRY%YRDIM%NDLUXG, YDMODEL%YRML_PHY_MF%YRARPHY%LSURFEX_KFROM, ZZS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                         &
  & ZFEVS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS_BASE_STATE%U(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1:YDCPG_DIM%KFLEVG),                                                    &
  & YDMF_PHYS_BASE_STATE%V(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1:YDCPG_DIM%KFLEVG), ZDEPTH_HEIGHT(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1:YDCPG_DIM%KFLEVG),                        &
  & YDMF_PHYS%OUT%FRTH(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG, 1), YDMF_PHYS%OUT%FRSO(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG, 1), &
  & YDVARS%GEOMETRY%RINDX%T0(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDVARS%GEOMETRY%RINDY%T0(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                               &
  & YDCPG_MISC%QS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS%OUT%GZ0(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                                                 &
  & YDMF_PHYS%OUT%GZ0H(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS%OUT%TCLS (YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                                          &
  & YDMF_PHYS%OUT%QCLS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS%OUT%RHCLS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                                          &
  & YDMF_PHYS%OUT%UCLS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS%OUT%VCLS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                                           &
  & YDMF_PHYS%OUT%NUCLS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS%OUT%NVCLS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                                         &
  & YDMF_PHYS%OUT%FCLL(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1), YDMF_PHYS%OUT%FCLN(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1),                                     &
  & YDMF_PHYS%OUT%FEVL(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1), YDMF_PHYS%OUT%FEVN(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1),                                     &
  & ZSSO_STDEV(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), ZTWSNOW(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), ZBUDTH(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                     &
  & ZBUDSO(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), ZFCLL(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), ZTOWNS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),                           &
  & ZCD(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA)                        )

  DO JLON=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
    YDCPG_GPAR%GZ0(JLON)   = YDMF_PHYS%OUT%GZ0 (JLON)
    YDCPG_GPAR%GZ0H(JLON)  = YDMF_PHYS%OUT%GZ0H(JLON)
    YDCPG_GPAR%VEMIS(JLON) = PFLU_EMIS(JLON)
    YDCPG_GPAR%VQS(JLON)   = YDCPG_MISC%QS  (JLON)
    YDCPG_GPAR%CD(JLON)    = ZCD  (JLON)
  ENDDO

  DO JSG=1,YDMODEL%YRML_PHY_RAD%YRERAD%NSW
    YDCPG_GPAR%ALBSCA(:,JSG) = PALBD(:,JSG)
    YDCPG_GPAR%ALBDIR(:,JSG) = PALBP(:,JSG)
  ENDDO

  DO JSG  = 1, YDMODEL%YRML_PHY_G%YRDPHY%NTSSG+1
    DO JLEV = 0, YDCPG_DIM%KFLEVG
      DO JLON = YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA
        YDMF_PHYS%OUT%FRTH(JLON,JLEV,JSG)=YDMF_PHYS%OUT%FRTH(JLON,JLEV,JSG)+ZBUDTH(JLON)
      ENDDO
    ENDDO
  ENDDO

! calculation of variables for the old "ISBA" atmosphere scheme
        
  CALL ARO_GROUND_DIAG_2ISBA( YDCPG_DIM%KBL, YDCPG_DIM%KGPCOMP, YDCPG_DIM%KFDIA-YDCPG_DIM%KIDIA+1, YDCPG_DIM%KIDIA,                        &
  & YDCPG_DIM%KFDIA, YDGEOMETRY%YRDIM%NDGUNG, YDGEOMETRY%YRDIM%NDGUXG, YDGEOMETRY%YRDIM%NDLUNG, YDGEOMETRY%YRDIM%NDLUXG, YDMODEL%YRML_PHY_MF%YRARPHY%LSURFEX_KFROM, YDVARS%GEOMETRY%RINDX%T0(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA),             &
  & YDVARS%GEOMETRY%RINDY%T0(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS_SURF%GSD_VF%PLSM, YDMF_PHYS_SURF%GSD_VV%PARG,                     &
  & YDMF_PHYS_SURF%GSD_VV%PSAB, YDMF_PHYS_SURF%GSD_VV%PD2, PTSN, ZTWSNOW, YDMF_PHYS_SURF%GSP_SB%PT_T1(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1), &
  & YDMF_PHYS_SURF%GSP_RR%PW_T1(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS_SURF%GSP_SB%PQ_T1(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1),         &
  & YDMF_PHYS_SURF%GSP_RR%PIC_T1(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS_SURF%GSP_SB%PTL_T1(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1),       &
  & YDMF_PHYS_SURF%GSP_RR%PFC_T1(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA), YDMF_PHYS_SURF%GSP_SG%PA_T1(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1),        &
  & YDMF_PHYS_SURF%GSP_SG%PR_T1(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA, 1), ZHV2 )
  DO JLON=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
    YDMF_PHYS_SURF%GSD_VV%PHV(JLON) = ZHV2(JLON)
  ENDDO        

  IF (.NOT.YDMODEL%YRML_PHY_MF%YRPHY%LNODIFQC) THEN
    CALL ACAA1 ( YDMODEL%YRML_PHY_MF, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON, YDCPG_DIM%KTDIA, &
    & YDCPG_DIM%KFLEVG, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, PCOEFN, YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP, &
    & PQL, PQI, YDMF_PHYS_BASE_STATE%T, PALPHA1, PCOEFA, PLVT, PQICE)
  ENDIF

ELSEIF (.NOT.YDMODEL%YRML_PHY_MF%YRARPHY%LMSE) THEN
  IF(YDMODEL%YRML_PHY_MF%YRPHY%NDIFFNEB == 5) THEN
    PNEBDIFF(:,:)=PNEBS(:,:)
  ELSEIF(YDMODEL%YRML_PHY_MF%YRPHY%NDIFFNEB == 2) THEN
    PNEBDIFF(:,:)=YDCPG_MISC%NEB(:,:)
  ELSEIF(YDMODEL%YRML_PHY_MF%YRPHY%NDIFFNEB == 3) THEN
    PNEBDIFF(:,:)=PNEBS(:,:)+(1.0_JPRB-PNEBS(:,:))*PNEBCH(:,:)
  ENDIF

             
  CALL ARP_GROUND_PARAM ( YDMODEL%YRML_AOC%YRMCC, YDMODEL%YRML_PHY_MF, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON,                             &
  & YDCPG_DIM%KTDIA, YDCPG_DIM%KFLEVG, YDSURF%YSP_SBD%NLEVS, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI, PCP, YDMF_PHYS%OUT%FRSO, PQV, YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%RDELP, &
  & YDMF_PHYS_BASE_STATE%T, YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, PXURO, PXQRO, PXTRO, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, PQL, PQI, PNEBDIFF, PFLU_CD, PFLU_CDN, PCDROV, PCHROV,                                  &
  & PCEROV, PDSA_CPS, YDMF_PHYS%OUT%CT, PDQSTS, PFLU_EMIS, YDMF_PHYS_SURF%GSD_VH%PSPSH, PHQ, PHTR,                                  &
  & PHU, YDMF_PHYS_SURF%GSD_VV%PHV, YDMF_PHYS_SURF%GSD_VF%PLSM, YDMF_PHYS_SURF%GSD_VV%PIVEG,                                        &
  & PFLU_NEIJ, YDCPG_MISC%QS, PFLU_QSATS, YDMF_PHYS_BASE_STATE%YGSP_SB%T, YDMF_PHYS_BASE_STATE%YGSP_RR%T,                           &
  & PFLU_VEG, PXDROV, PXHROV, YDMF_PHYS_BASE_STATE%YGSP_RR%W, YDMF_PHYS_BASE_STATE%YGSP_RR%IC, ZDSE,                                &
  & ZCFAS, PCFAU, ZCFBS, PCFBU, PCFBV, ZCFBQ, PCOEFA, PALPHA1, PLVT, PQICE, PDIFWQ, PDIFWS, ZFMDU,                                  &
  & ZFMDV, PSC_FEVI, PSC_FEVN, PSC_FCLL, PSC_FCLN, YDMF_PHYS%OUT%FCHSP, YDMF_PHYS%OUT%FCLL, YDMF_PHYS%OUT%FCLN,                     &
  & YDMF_PHYS%OUT%FCS, PFLU_FEVI, YDMF_PHYS%OUT%FEVL, YDMF_PHYS%OUT%FEVN, YDMF_PHYS%OUT%FEVV, YDMF_PHYS%OUT%FTR,                    &
  & PDSA_LHS, YDMF_PHYS_SURF%GSD_VH%PQSH, YDMF_PHYS%OUT%FRTH, YDMF_PHYS_SURF%GSD_VF%PZ0F, YDMF_PHYS_SURF%GSD_VV%PZ0H                &
  & )

  DO JLON=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
    YDMF_PHYS%OUT%DIFTQ(JLON,YDCPG_DIM%KFLEVG)=PDIFWQ(JLON)
    YDMF_PHYS%OUT%DIFTS(JLON,YDCPG_DIM%KFLEVG)=PDIFWS(JLON)
  ENDDO
             
ELSEIF (.NOT. LCALLSFX) THEN
  YDMF_PHYS%OUT%FCS(:,:) = 0.0_JPRB
  ZFEV(:)   = 0.0_JPRB

ENDIF  !LMSE.AND.LCALLSFX

CALL ACDIFV2 ( YDMODEL%YRML_GCONF%YGFL, YDMODEL%YRML_PHY_MF, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON, YDCPG_DIM%KTDIA, &
& YDCPG_DIM%KFLEVG, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, ZCFAQ, ZCFAS, PCFAU, ZCFASV, ZCFBQ, ZCFBS, PCFBU, PCFBV, ZCFBSV, PKTROV,          &
& PKQROV, PKQLROV, PKUROV, ZDSE, ZQT, YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, PPOID, YDMF_PHYS_BASE_STATE%T, PQL, PQI, YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%RDELP,  &
& PCOEFA, PALPHA1, PLVT, PQICE, ZSFSV, YDMF_PHYS%OUT%FCS, ZFEV, ZFMDU, ZFMDV, PTSN, PXHROV, PDIFEXT,         &
& YDMF_PHYS%OUT%DIFTQ, YDMF_PHYS%OUT%DIFTS, YDMF_PHYS%OUT%STRTU, YDMF_PHYS%OUT%STRTV, YDMF_PHYS%OUT%DIFTQL,  &
& YDMF_PHYS%OUT%DIFTQN, YDMF_PHYS%OUT%DIFCQ, YDMF_PHYS%OUT%DIFCS, YDMF_PHYS%OUT%STRCU, YDMF_PHYS%OUT%STRCV,  &
& YDVARS%SHTUR%T0          )
      
IF ( YDMODEL%YRML_PHY_MF%YRARPHY%LMSE ) THEN
  DO JLON=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
    YDCPG_GPAR%VTS(JLON) = PTSN (JLON)
    YDMF_PHYS_SURF%GSP_SG%PF_T1(JLON,1) = ZTWSNOW (JLON)
  ENDDO
ENDIF



END SUBROUTINE
