#ifdef RS6K
@PROCESS NOCHECK
#endif
SUBROUTINE APLSIM(YDGEOMETRY, YDCPG_DIM, YDCPG_MISC, YDCPG_PHY0, YDCPG_PHY9, &
& YDMF_PHYS, YDMF_PHYS_TMP, YDCPG_DYN0, YDCPG_DYN9, YDMF_PHYS_SURF, YDVARS, &
& YDMODEL, PDTPHY, YDCPG_SL1, PTRAJ_PHYS)

!**** *APLSIM* METEO-FRANCE PHYSICS.

!     Purpose.
!     --------
!         Call METEO-FRANCE physics and physical tendencies.

!**   Interface.
!     ----------
!        *CALL* *APLSIM(...)*

!        Explicit arguments :
!        --------------------

!     INPUT:
!     ------
!        PDTPHY    : timestep used in the physics.

! End Modifications
!-------------------------------------------------------------------------------

USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE, MF_PHYS_TMP_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_DYN_TYPE, CPG_PHY_TYPE, &
                              & CPG_MISC_TYPE, CPG_SL1_TYPE
USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE TYPE_MODEL         , ONLY : MODEL
USE PARKIND1           , ONLY : JPIM     ,JPRB
USE YOMHOOK            , ONLY : LHOOK,   DR_HOOK

USE YOMCT0             , ONLY : LTWOTL
USE YOMTRAJ            , ONLY : TRAJ_PHYS_TYPE, LPRTTRAJ
USE YOMLUN             , ONLY : NULOUT

USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_NEXT_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_NEXT_STATE_TYPE
!     -------------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_DIM_TYPE),INTENT(IN)    :: YDCPG_DIM
TYPE(CPG_MISC_TYPE),INTENT(INOUT):: YDCPG_MISC
TYPE(CPG_PHY_TYPE),INTENT(INOUT), TARGET :: YDCPG_PHY0
TYPE(CPG_PHY_TYPE),INTENT(INOUT), TARGET :: YDCPG_PHY9
TYPE(MF_PHYS_TYPE),INTENT(INOUT) :: YDMF_PHYS
TYPE(MF_PHYS_TMP_TYPE), INTENT(INOUT) :: YDMF_PHYS_TMP
TYPE(CPG_DYN_TYPE),INTENT(INOUT), TARGET :: YDCPG_DYN0
TYPE(CPG_DYN_TYPE),INTENT(INOUT), TARGET :: YDCPG_DYN9
TYPE(MF_PHYS_SURF_TYPE),INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDTPHY 
TYPE(CPG_SL1_TYPE),INTENT(INOUT) :: YDCPG_SL1
TYPE (TRAJ_PHYS_TYPE), INTENT(INOUT) :: PTRAJ_PHYS

!     ------------------------------------------------------------------
INTEGER(KIND=JPIM) :: IFIELDSS

INTEGER(KIND=JPIM) :: INSTEP_DEB,INSTEP_FIN
INTEGER(KIND=JPIM) :: JROF

!     --- UPPER AIR PHYSICAL TENDENCIES.
REAL(KIND=JPRB) :: ZTENDH(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)     ! Enthalpy tendency.
REAL(KIND=JPRB) :: ZTENDQ(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)     ! Moisture tendency.

!     --- RADIATION COEFFICIENTS FOR SIMPLIFIED PHYSICS IN GRID-POINT ---
REAL(KIND=JPRB) :: ZAC_HC(YDCPG_DIM%KFLEVG+1,YDCPG_DIM%KFLEVG+1)           ! horizontally-constant field for ZAC.

REAL(KIND=JPRB) :: ZCOR   (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAB3C (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAB3N (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAB4C (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAB4N (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAB6C (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAB6N (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAT1C (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAT1N (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAT2C (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAT2N (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAT3C (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAT3N (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAT4C (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAT4N (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAT5C (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZRAT5N (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL(KIND=JPRB) :: ZQS1   (YDCPG_DIM%KLON)

TYPE (MF_PHYS_BASE_STATE_TYPE) :: YLMF_PHYS_BASE_STATE
TYPE (MF_PHYS_NEXT_STATE_TYPE) :: YLMF_PHYS_NEXT_STATE
REAL(KIND=JPRB) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "aplpars.intfb.h"
#include "aplpassh.intfb.h"
#include "cpphinp.intfb.h"
#include "cppsolan.intfb.h"
#include "cptendsm.intfb.h"
#include "cputqys.intfb.h"
#include "mf_phys_init.intfb.h"
#include "rdradcoef.intfb.h"
#include "wrphtrajm.intfb.h"
#include "mf_phys_transfer.intfb.h"
#include "mf_phys_precips.intfb.h"
#include "mf_phys_cvv.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('APLSIM', 0, ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM, YDDIMV=>YDGEOMETRY%YRDIMV, YDGSGEOM=>YDGEOMETRY%YRGSGEOM(YDCPG_DIM%KBL),                  &
& YDOROG=>YDGEOMETRY%YROROG(YDCPG_DIM%KBL), YDPHY=>YDMODEL%YRML_PHY_MF%YRPHY, YDPTRSLB1=>YDMODEL%YRML_DYN%YRPTRSLB1,         &
& YDPTRSLB2=>YDMODEL%YRML_DYN%YRPTRSLB2, YDTOPH=>YDMODEL%YRML_PHY_MF%YRTOPH, YDSIMPHL=>YDMODEL%YRML_PHY_MF%YRSIMPHL,         &
& YDMDDH=>YDMODEL%YRML_DIAG%YRMDDH, YDRCOEF=>YDMODEL%YRML_PHY_RAD%   YRRCOEF, YDARPHY=>YDMODEL%YRML_PHY_MF%YRARPHY,          &
& YDDPHY=>YDMODEL%YRML_PHY_G%YRDPHY, YDLDDH=>YDMODEL%  YRML_DIAG%YRLDDH, YDPHY2=>YDMODEL%YRML_PHY_MF%YRPHY2,                 &
& YGFL=>YDMODEL%YRML_GCONF%YGFL, YDEPHY=>  YDMODEL%YRML_PHY_EC%YREPHY, YDPARAR=>YDMODEL%YRML_PHY_MF%YRPARAR,                 &
& YDPRECIPS=>YDMODEL%YRML_PHY_MF%   YRPHY%YRDPRECIPS, YDSTOPH=>YDMODEL%YRML_PHY_STOCH%YRSTOPH)

ASSOCIATE(TSPHY=>YDPHY2%TSPHY, NTSSG=>YDDPHY%NTSSG, LTRAJPS=>YDSIMPHL%LTRAJPS,       &
& LRAYSP=>YDSIMPHL%LRAYSP, LEDR=>YDPHY%LEDR, LSDDH=>YDLDDH%LSDDH, HDSF=>YDMDDH%HDSF, LRCOEF =>YDRCOEF%LRCOEF, &
& LTLADDIA=>YDRCOEF%LTLADDIA, NG3SR=>YDRCOEF%NG3SR)

CALL YLMF_PHYS_BASE_STATE%INIT (LTWOTL, YDCPG_DYN0, YDCPG_DYN9, YDCPG_PHY0, YDCPG_PHY9, YDVARS, &
& YDMF_PHYS_SURF, YDMODEL=YDMODEL)

CALL YLMF_PHYS_NEXT_STATE%INIT (YDCPG_SL1, YDVARS, YDMODEL)

!     ------------------------------------------------------------------

!        1.    Preliminary calculations necessary
!              for all types of physics.
!              ------------------------------------


INSTEP_DEB=1
INSTEP_FIN=1

IF (LRAYSP.AND.(YDCPG_DIM%KSTEP >= INSTEP_DEB .AND. YDCPG_DIM%KSTEP <= INSTEP_FIN)) THEN  
  CALL CPPSOLAN(YDGEOMETRY%YRDIM, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDGSGEOM%GEMU, YDGSGEOM%GELAM, YDMF_PHYS_TMP%RDG%MMU0&
  & )
  IF (.NOT.LSDDH) THEN
!-----------INITIALIZING THE WEIGHT VECTORS-------------
    DO JROF=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
      YDCPG_MISC%DHSF(JROF)=HDSF(JROF+YDCPG_DIM%KSTGLO-1)
    ENDDO
!-------------------------------------------------------
  ENDIF
ENDIF

CALL CPPHINP(YDGEOMETRY, YDMODEL, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDGSGEOM%GEMU, YDGSGEOM%GELAM, YDVARS%U%T0, &
& YDVARS%V%   T0, YDVARS%Q%T0, YDVARS%Q%DL, YDVARS%Q%DM, YDVARS%CVGQ%DL, YDVARS%CVGQ%DM, YDCPG_PHY0%XYB%RDELP,  &
& YDCPG_DYN0%CTY%EVEL, YDVARS%CVGQ%T0, YDMF_PHYS_TMP%RDG%MU0, YDMF_PHYS_TMP%RDG%MU0LU, YDMF_PHYS_TMP%RDG%MU0M,  &
& YDMF_PHYS_TMP%RDG%MU0N, YDMF_PHYS_TMP%RDG%CVGQ)
YDMF_PHYS_TMP%RDG%LCVQ(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,1:YDCPG_DIM%KFLEVG)=YDMF_PHYS_TMP%RDG%CVGQ(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,1:YDCPG_DIM%KFLEVG)

! * In some cases, some pseudo-historic surface buffers (like z0) should
!   not be modified between the entrance and the output of APLSIM
!   (this is the case for example if LDCONFX=T).
!   For the time being, we must save:
!   - HV (group VV) : resistance to evapotranspiration
!   - Z0F (group VD): gravity * surface roughness length
!   - Z0H (group VV): gravity * roughness length for heat
!   - PBLH (group VH): PBL height
!   - SPSH (group VH):
!   - QSH (group VH):

CALL MF_PHYS_INIT ( YGFL, YDARPHY, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON, YDCPG_DIM%KFLEVG,                  &
& NTSSG, YDCPG_DIM%KSBDLEV, YDMF_PHYS%OUT%DIFCQ, YDMF_PHYS%OUT%DIFCQN, YDMF_PHYS%OUT%DIFCQL, YDMF_PHYS%OUT%DIFCS,       &
& YDMF_PHYS%OUT%DIFTQ, YDMF_PHYS%OUT%DIFTQN, YDMF_PHYS%OUT%DIFTQL, YDMF_PHYS%OUT%DIFTS, YDMF_PHYS%OUT%FCCQL,            &
& YDMF_PHYS%OUT%FCCQN, YDMF_PHYS%OUT%FCSQL, YDMF_PHYS%OUT%FCSQN, YDMF_PHYS%OUT%FCQNG, YDMF_PHYS%OUT%FCQNNG,             &
& YDMF_PHYS%OUT%FCQLNG, YDMF_PHYS%OUT%FCQRNG, YDMF_PHYS%OUT%FCQSNG, YDMF_PHYS%OUT%FCQGNG, YDMF_PHYS%OUT%FPLCL,          &
& YDMF_PHYS%OUT%FPLCN, YDMF_PHYS%OUT%FPLCG, YDMF_PHYS%OUT%FPLCH, YDMF_PHYS%OUT%FPLSL, YDMF_PHYS%OUT%FPLSN,              &
& YDMF_PHYS%OUT%FPLSG, YDMF_PHYS%OUT%FPLSH, YDMF_PHYS%OUT%FRSO, YDMF_PHYS%OUT%FRSOC, YDMF_PHYS%OUT%FRTH,                &
& YDMF_PHYS%OUT%FRTHC, YDMF_PHYS%OUT%STRCU, YDMF_PHYS%OUT%STRCV, YDMF_PHYS%OUT%STRDU, YDMF_PHYS%OUT%STRDV,              &
& YDMF_PHYS%OUT%STRTU, YDMF_PHYS%OUT%STRTV, YDMF_PHYS%OUT%STRMU, YDMF_PHYS%OUT%STRMV, YDMF_PHYS%OUT%FRMH,               &
& YDMF_PHYS%OUT%DIFCQLC, YDMF_PHYS%OUT%DIFCQIC, YDMF_PHYS%OUT%FIMCC, YDMF_PHYS%OUT%FEDQLC, YDMF_PHYS%OUT%FEDQIC,        &
& YDMF_PHYS%OUT%FEDQRC, YDMF_PHYS%OUT%FEDQSC, YDMF_PHYS%OUT%FCNEGQLC, YDMF_PHYS%OUT%FCNEGQIC, YDMF_PHYS%OUT%FCNEGQRC,   &
& YDMF_PHYS%OUT%FCNEGQSC, YDMF_PHYS%OUT%FCHOZ, YDCPG_MISC%NEB, YDCPG_MISC%QICE, YDCPG_MISC%QLI, YDCPG_MISC%RH,          &
& YDMF_PHYS%OUT%ALB, YDMF_PHYS%OUT%CT, YDMF_PHYS%OUT%FCHSP, YDMF_PHYS%OUT%FCLL, YDMF_PHYS%OUT%FCLN, YDMF_PHYS%OUT%FCS,  &
& YDMF_PHYS%OUT%FEVL, YDMF_PHYS%OUT%FEVN, YDMF_PHYS%OUT%FEVV, YDMF_PHYS%OUT%FLASH, YDMF_PHYS%OUT%FTR,                   &
& YDMF_PHYS%OUT%FLWSP, YDMF_PHYS%OUT%FONTE, YDMF_PHYS%OUT%FGEL, YDMF_PHYS%OUT%FGELS, YDMF_PHYS%OUT%FRSGNI,              &
& YDMF_PHYS%OUT%FRSDNI, YDMF_PHYS%OUT%FRSODS, YDMF_PHYS%OUT%FRSOPS, YDMF_PHYS%OUT%FRSOPT, YDMF_PHYS%OUT%FRSOLU,         &
& YDMF_PHYS%OUT%FRTHDS, YDMF_PHYS%OUT%FPFPSL, YDMF_PHYS%OUT%FPFPSN, YDMF_PHYS%OUT%FPFPSG, YDMF_PHYS%OUT%FPFPCL,         &
& YDMF_PHYS%OUT%FPFPCN, YDMF_PHYS%OUT%FPEVPSL, YDMF_PHYS%OUT%FPEVPSN, YDMF_PHYS%OUT%FPEVPSG, YDMF_PHYS%OUT%FPEVPCL,     &
& YDMF_PHYS%OUT%FPEVPCN, YDMF_PHYS%OUT%FPEVPCG, YDMF_PHYS%OUT%GZ0, YDMF_PHYS%OUT%GZ0H, YDCPG_MISC%QS,                   &
& YDMF_PHYS%OUT%RUISL, YDMF_PHYS%OUT%RUISP, YDMF_PHYS%OUT%RUISS, YDMF_PHYS%OUT%UCLS, YDMF_PHYS%OUT%VCLS,                &
& YDMF_PHYS%OUT%NUCLS, YDMF_PHYS%OUT%NVCLS, YDMF_PHYS%OUT%TCLS, YDMF_PHYS%OUT%MRT, YDMF_PHYS%OUT%QCLS,                  &
& YDMF_PHYS%OUT%RHCLS, YDCPG_MISC%CLCT, YDMF_PHYS%OUT%CLCH, YDMF_PHYS%OUT%CLCM, YDMF_PHYS%OUT%CLCL, YDMF_PHYS%OUT%CLCC, &
& YDMF_PHYS%OUT%CAPE, YDMF_PHYS%OUT%CTOP, YDMF_PHYS%OUT%CLPH, YDMF_PHYS%OUT%VEIN, YDMF_PHYS%OUT%UGST,                   &
& YDMF_PHYS%OUT%VGST, YDMF_PHYS%OUT%DIAGH, YDMF_PHYS%OUT%EDR, YDMF_PHYS%OUT%VISICLD, YDMF_PHYS%OUT%VISIHYD,             &
& YDMF_PHYS%OUT%MXCLWC, YDMF_PHYS%OUT%MOCON)

!        2.9  Computation of evolution of T, u, v and Q.
!             ------------------------------------------

!       2.9b Prognostic convection etc.
!            --------------------------

! TRANSFER NOT ADVECTED VARIABLES INTO PGFLT1
CALL MF_PHYS_TRANSFER (YDCPG_DIM, YDVARS, YDMODEL)

CALL MF_PHYS_CVV (YDCPG_DIM, YDVARS, YDMODEL)

!    -------------------------------------------------------------------

!*       3.    Simplified physics.
!              -------------------

!        3.1  Preliminary calculations necessary for simplified physics.
!             ----------------------------------------------------------


  ! * read grid-point transmission coefficients for simplified physics.
IF (LRAYSP.AND.LRCOEF.AND.(YDCPG_DIM%KSTEP > 1.OR.LTLADDIA)) THEN
  IFIELDSS=NG3SR*YDCPG_DIM%KFLEVG
  CALL RDRADCOEF(YDGEOMETRY, YDRCOEF, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KSTGLO, IFIELDSS, &
  & ZCOR, ZRAB3C, ZRAB3N, ZRAB4C, ZRAB4N, ZRAB6C, ZRAB6N, ZRAT1C, ZRAT1N, ZRAT2C, ZRAT2N, ZRAT3C,   &
  & ZRAT3N, ZRAT4C, ZRAT4N, ZRAT5C, ZRAT5N, ZAC_HC)
ENDIF


!        3.2  Simplified physics.
!             -------------------

TSPHY = MAX(PDTPHY,1.0_JPRB)

CALL APLPASSH (YDPHY, YDMODEL%YRML_PHY_MF%YRPHY1, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON, YDCPG_DIM%KFLEVG, &
& YLMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, YLMF_PHYS_BASE_STATE%Q, YDMF_PHYS_SURF%GSP_SG%PF_T1, YDMF_PHYS_SURF%GSP_RR%PT_T1,       &
& YDMF_PHYS_SURF%GSP_RR%PW_T1, YDMF_PHYS_SURF%GSD_VF%PLSM, YDMF_PHYS_SURF%GSD_VF%PVEG, ZQS1)  

CALL APLPASSH (YDPHY, YDMODEL%YRML_PHY_MF%YRPHY1, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON, YDCPG_DIM%KFLEVG, &
& YLMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, YLMF_PHYS_BASE_STATE%Q, YLMF_PHYS_BASE_STATE%YGSP_SG%F, YLMF_PHYS_BASE_STATE%YGSP_RR%T,           &
& YLMF_PHYS_BASE_STATE%YGSP_RR%W, YDMF_PHYS_SURF%GSD_VF%PLSM, YDMF_PHYS_SURF%GSD_VF%PVEG, YDCPG_MISC%QS)  

CALL APLPARS(YDGEOMETRY, YDRCOEF, YDMODEL%YRML_PHY_MF, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KLON,               &
& 1, YDCPG_DIM%KFLEVG, NTSSG, YDCPG_DIM%KSTEP, YLMF_PHYS_BASE_STATE%YCPG_DYN%PHI, YLMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD,          &
& YLMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YLMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, YLMF_PHYS_BASE_STATE%YCPG_PHY%XYB%DELP,                  &
& YLMF_PHYS_BASE_STATE%YCPG_PHY%XYB%RDELP, YLMF_PHYS_BASE_STATE%U, YLMF_PHYS_BASE_STATE%V, YLMF_PHYS_BASE_STATE%T, YLMF_PHYS_BASE_STATE%Q,      &
& YLMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP, YDMF_PHYS_TMP%RDG%CVGQ, YLMF_PHYS_BASE_STATE%YGSP_SG%F, YLMF_PHYS_BASE_STATE%YGSP_RR%T,       &
& YDCPG_MISC%QS, YDMF_PHYS_SURF%GSP_RR%PT_T1, ZQS1, YDMF_PHYS_SURF%GSD_VF%PGETRL, YDMF_PHYS_SURF%GSD_VF%PLSM,          &
& YDMF_PHYS_SURF%GSD_VF%PZ0F, YDMF_PHYS_SURF%GSD_VF%PVRLAN, YDMF_PHYS_SURF%GSD_VF%PVRLDI, YDMF_PHYS_SURF%GSD_VF%PALBF, &
& YDMF_PHYS_TMP%RDG%MU0, YDGSGEOM%GM, ZAC_HC, ZCOR, ZRAB3C, ZRAB3N, ZRAB4C, ZRAB4N, ZRAB6C, ZRAB6N,                    &
& ZRAT1C, ZRAT1N, ZRAT2C, ZRAT2N, ZRAT3C, ZRAT3N, ZRAT4C, ZRAT4N, ZRAT5C, ZRAT5N, YDMF_PHYS%OUT%DIFCQ,                 &
& YDMF_PHYS%OUT%DIFCS, YDMF_PHYS%OUT%DIFTQ, YDMF_PHYS%OUT%DIFTS, YDMF_PHYS%OUT%FCCQL, YDMF_PHYS%OUT%FCCQN,             &
& YDMF_PHYS%OUT%FCSQL, YDMF_PHYS%OUT%FCSQN, YDMF_PHYS%OUT%FPLCL, YDMF_PHYS%OUT%FPLCN, YDMF_PHYS%OUT%FPLSL,             &
& YDMF_PHYS%OUT%FPLSN, YDMF_PHYS%OUT%FRSO, YDMF_PHYS%OUT%FRTH, YDMF_PHYS%OUT%STRCU, YDMF_PHYS%OUT%STRCV,               &
& YDMF_PHYS%OUT%STRDU, YDMF_PHYS%OUT%STRDV, YDMF_PHYS%OUT%STRTU, YDMF_PHYS%OUT%STRTV, YDMF_PHYS%OUT%STRMU,             &
& YDMF_PHYS%OUT%STRMV, YDMF_PHYS%OUT%FRMH)

!        3.3  Store the model trajectory at t-dt (leap-frog) or t (sl2tl).
!             ------------------------------------------------------------

IF (LTRAJPS) THEN
  PTRAJ_PHYS%PQSSMF(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA)=YDCPG_MISC%QS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA)
  PTRAJ_PHYS%PTSMF(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA) =YLMF_PHYS_BASE_STATE%YGSP_RR%T(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA)
  PTRAJ_PHYS%PSNSMF(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA)=YLMF_PHYS_BASE_STATE%YGSP_SG%F(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,1)

  IF (.NOT. LTWOTL) THEN
    CALL WRPHTRAJM(YDGEOMETRY, YDSIMPHL, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, PTRAJ_PHYS, YDVARS%U%T9, YDVARS%V%T9, &
    & YDVARS%T%T9, YDVARS%Q%T9, YDVARS%L%T9, YDVARS%I%T9, YDVARS%SP%T9)  
  ENDIF

  IF (LPRTTRAJ.AND.PTRAJ_PHYS%LASTCHUNK) WRITE(NULOUT,*)'GREPTRAJ STORE TRAJ_PHYS in APLSIM'
ENDIF

!        3.4  Computation of tendencies T,u,v and Q.
!             --------------------------------------

TSPHY = MAX(PDTPHY,1.0_JPRB)

CALL CPTENDSM (YDPHY, YDCPG_DIM%KLON, YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA, YDCPG_DIM%KFLEVG, YDMF_PHYS%OUT%DIFCQ,          &
& YDMF_PHYS%OUT%DIFCS, YDMF_PHYS%OUT%DIFTQ, YDMF_PHYS%OUT%DIFTS, YDMF_PHYS%OUT%FCCQL, YDMF_PHYS%OUT%FCCQN,              &
& YDMF_PHYS%OUT%FCSQL, YDMF_PHYS%OUT%FCSQN, YDMF_PHYS%OUT%FPLCL, YDMF_PHYS%OUT%FPLCN, YDMF_PHYS%OUT%FPLSL,              &
& YDMF_PHYS%OUT%FPLSN, YDMF_PHYS%OUT%FRSO, YDMF_PHYS%OUT%FRTH, YDMF_PHYS%OUT%STRCU, YDMF_PHYS%OUT%STRCV,                &
& YDMF_PHYS%OUT%STRDU, YDMF_PHYS%OUT%STRDV, YDMF_PHYS%OUT%STRTU, YDMF_PHYS%OUT%STRTV, YDMF_PHYS%OUT%STRMU,              &
& YDMF_PHYS%OUT%STRMV, YDMF_PHYS%OUT%FRMH, YLMF_PHYS_BASE_STATE%YCPG_PHY%XYB%RDELP, YLMF_PHYS_BASE_STATE%YCPG_DYN%PHIF,           &
& YLMF_PHYS_BASE_STATE%U, YLMF_PHYS_BASE_STATE%V, YLMF_PHYS_BASE_STATE%T, YLMF_PHYS_BASE_STATE%Q, YDCPG_MISC%QS, YLMF_PHYS_BASE_STATE%YGSP_RR%T, &
& YDOROG%OROG, YDMF_PHYS%OUT%TENDU, YDMF_PHYS%OUT%TENDV, ZTENDH, ZTENDQ, YDMF_PHYS%OUT%FHPCL, YDMF_PHYS%OUT%FHPCN,      &
& YDMF_PHYS%OUT%FHPSL, YDMF_PHYS%OUT%FHPSN, YDMF_PHYS%OUT%FHSCL, YDMF_PHYS%OUT%FHSCN, YDMF_PHYS%OUT%FHSSL,              &
& YDMF_PHYS%OUT%FHSSN)  


!        3.5  Computation of evolution of T, u, v and Q.
!             ------------------------------------------

CALL CPUTQYS(YDCPG_DIM, YLMF_PHYS_BASE_STATE, YLMF_PHYS_NEXT_STATE, YDSTOPH, YDPHY2, &
& PDTPHY, ZTENDH, ZTENDQ, YDMF_PHYS%OUT%TENDU,     &
& YDMF_PHYS%OUT%TENDV, YDMF_PHYS%FOR%U, YDMF_PHYS%FOR%V, YDMF_PHYS%FOR%T, YDMF_PHYS%FOR%Q, &
& YDMF_PHYS%OUT%FDIS)


!     ------------------------------------------------------------------

!*       5.    Final calculations.
!              -------------------

IF (LEDR) THEN
  YDMF_PHYS_SURF%GSD_DI%PXEDR(:,:)=YDMF_PHYS%OUT%EDR(:,:)
ENDIF

CALL MF_PHYS_PRECIPS (YDCPG_DIM, YDMF_PHYS_TMP%PRC%DPRECIPS, YDMF_PHYS_TMP%PRC%DPRECIPS2, YDMF_PHYS_SURF, YDMODEL)

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('APLSIM', 1, ZHOOK_HANDLE)
END SUBROUTINE APLSIM
