SUBROUTINE MF_PHYS_TRANSFER (YDCPG_BNDS, YDCPG_OPTS, YDVARS, YDPHY, YDGFL)

!**** *MF_PHYS_TRANSFER*

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 28-04-2021

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE YOMPHY             , ONLY : TPHY
USE YOM_YGFL           , ONLY : TYPE_GFLD

IMPLICIT NONE

TYPE(CPG_BNDS_TYPE),   INTENT(IN)    :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),   INTENT(IN)    :: YDCPG_OPTS
TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
TYPE(TPHY),            INTENT(IN)    :: YDPHY
TYPE(TYPE_GFLD),       INTENT(IN)    :: YDGFL

REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('MF_PHYS_TRANSFER', 0, ZHOOK_HANDLE)

!=PARALLEL

IF (YDPHY%LCVPRO.OR.YDPHY%LGPCMT) THEN
   IF (.NOT.YDGFL%YUAL%LADV) THEN
      YDVARS%UAL%T1(:,:)=YDVARS%UAL%T0(:,:)
      YDVARS%UOM%T1(:,:)=YDVARS%UOM%T0(:,:)
   ENDIF
   IF (YDPHY%LCDDPRO) THEN
    IF (.NOT.YDGFL%YDAL%LADV) THEN
      YDVARS%DAL%T1(:,:)=YDVARS%DAL%T0(:,:)
      YDVARS%DOM%T1(:,:)=YDVARS%DOM%T0(:,:)
    ENDIF
   ENDIF
ENDIF
IF (YDGFL%YUNEBH%LACTIVE.AND..NOT.YDGFL%YUNEBH%LADV)THEN
   YDVARS%UNEBH%T1(:,:)=YDVARS%UNEBH%T0(:,:)
ENDIF
IF (YDGFL%YUEN%LACTIVE.AND..NOT.YDGFL%YUEN%LADV) THEN
   YDVARS%UEN%T1(:,:)=YDVARS%UEN%T0(:,:)
ENDIF
IF (YDGFL%YTTE%LACTIVE.AND..NOT.YDGFL%YTTE%LADV) THEN
   YDVARS%TTE%T1(:,:)=YDVARS%TTE%T0(:,:)
ENDIF
IF (YDGFL%YMXL%LACTIVE.AND..NOT.YDGFL%YMXL%LADV) THEN
   YDVARS%MXL%T1(:,:)=YDVARS%MXL%T0(:,:)
ENDIF
IF (YDGFL%YSHTUR%LACTIVE.AND..NOT.YDGFL%YSHTUR%LADV) THEN
   YDVARS%SHTUR%T1(:,:)=YDVARS%SHTUR%T0(:,:)
ENDIF
IF (YDGFL%YFQTUR%LACTIVE.AND..NOT.YDGFL%YFQTUR%LADV) THEN
   YDVARS%FQTUR%T1(:,:)=YDVARS%FQTUR%T0(:,:)
ENDIF
IF (YDGFL%YFSTUR%LACTIVE.AND..NOT.YDGFL%YFSTUR%LADV) THEN
   YDVARS%FSTUR%T1(:,:)=YDVARS%FSTUR%T0(:,:)
ENDIF
IF (YDGFL%YRKTH%LACTIVE)THEN
   YDVARS%RKTH%T1(:,:)=YDVARS%RKTH%T0(:,:)
ENDIF
IF (YDGFL%YRKTQV%LACTIVE)THEN
   YDVARS%RKTQV%T1(:,:)=YDVARS%RKTQV%T0(:,:)
ENDIF
IF (YDGFL%YRKTQC%LACTIVE)THEN
   YDVARS%RKTQC%T1(:,:)=YDVARS%RKTQC%T0(:,:)
ENDIF

!=END PARALLEL

IF (LHOOK) CALL DR_HOOK ('MF_PHYS_TRANSFER', 1, ZHOOK_HANDLE)

END SUBROUTINE
