SUBROUTINE MF_PHYS_SAVE_PHSURF_PART1 (YDCPG_DIM, YDMF_PHYS_TMP, YDMF_PHYS_SURF, YDVARS, YDSURF, YDMODEL)

USE PARKIND1, ONLY : JPIM, JPRB

USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TMP_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE(CPG_DIM_TYPE),INTENT(IN)    :: YDCPG_DIM
TYPE(MF_PHYS_TMP_TYPE),INTENT(INOUT) :: YDMF_PHYS_TMP
TYPE(MF_PHYS_SURF_TYPE),INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
TYPE(TSURF)       ,INTENT(INOUT) :: YDSURF
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL

ASSOCIATE (YDPHY=>YDMODEL%YRML_PHY_MF%YRPHY)

ASSOCIATE (LCDDPRO=>YDPHY%LCDDPRO, LCVPRO=>YDPHY%LCVPRO, LGPCMT=>YDPHY%LGPCMT)

  IF(YDSURF%YSD_VV%YHV%LSET) YDMF_PHYS_TMP%SAV%HV(1:YDCPG_DIM%KLON)=YDMF_PHYS_SURF%GSD_VV%PHV(1:YDCPG_DIM%KLON)
  IF(YDSURF%YSD_VF%YZ0F%LSET) YDMF_PHYS_TMP%SAV%GZ0F(1:YDCPG_DIM%KLON)=YDMF_PHYS_SURF%GSD_VF%PZ0F(1:YDCPG_DIM%KLON)
  IF(YDSURF%YSD_VV%YZ0H%LSET) YDMF_PHYS_TMP%SAV%GZ0HF(1:YDCPG_DIM%KLON)=YDMF_PHYS_SURF%GSD_VV%PZ0H(1:YDCPG_DIM%KLON)
  IF(YDSURF%YSD_VH%YPBLH%LSET) YDMF_PHYS_TMP%SAV%PBLH(1:YDCPG_DIM%KLON)=YDMF_PHYS_SURF%GSD_VH%PPBLH(1:YDCPG_DIM%KLON)
  IF(YDSURF%YSD_VH%YSPSH%LSET) YDMF_PHYS_TMP%SAV%FHPS(1:YDCPG_DIM%KLON)=YDMF_PHYS_SURF%GSD_VH%PSPSH(1:YDCPG_DIM%KLON)
  IF(YDSURF%YSD_VH%YQSH%LSET) YDMF_PHYS_TMP%SAV%QSH(1:YDCPG_DIM%KLON)=YDMF_PHYS_SURF%GSD_VH%PQSH(1:YDCPG_DIM%KLON)
  IF(YDSURF%YSD_VK%YUDGRO%LSET) YDMF_PHYS_TMP%SAV%UDGRO(1:YDCPG_DIM%KLON)=YDMF_PHYS_SURF%GSD_VK%PUDGRO(1:YDCPG_DIM%KLON)
  IF(LCVPRO.OR.LGPCMT) THEN
    YDMF_PHYS_TMP%SAV%UDAL(:,:)=YDVARS%UAL%T0(:,:)
    YDMF_PHYS_TMP%SAV%UDOM(:,:)=YDVARS%UOM%T0(:,:)
    IF(LCDDPRO) THEN
      YDMF_PHYS_TMP%SAV%DDAL(:,:)=YDVARS%DAL%T0(:,:)
      YDMF_PHYS_TMP%SAV%DDOM(:,:)=YDVARS%DOM%T0(:,:)
    ENDIF
  ENDIF
  IF(YDMODEL%YRML_GCONF%YGFL%YUNEBH%LACTIVE) YDMF_PHYS_TMP%SAV%UNEBH(:,:)=YDVARS%UNEBH%T0(:,:)
  IF(YDMODEL%YRML_GCONF%YGFL%YUEN%LACTIVE)   YDMF_PHYS_TMP%SAV%ENTCH(:,:)=YDVARS%UEN%T0(:,:)

END ASSOCIATE

END ASSOCIATE

END SUBROUTINE
