SUBROUTINE MF_PHYS_FPL_PART1 (YDCPG_DIM, PPFL_FPLCH, PPFL_FPLSH, PCPF_T0, PSPF_T0, YDMODEL)

USE PARKIND1, ONLY : JPIM, JPRB

USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE(CPG_DIM_TYPE),INTENT(IN)    :: YDCPG_DIM

REAL (KIND=JPRB),  INTENT(OUT)   :: PPFL_FPLCH (YDCPG_DIM%KLON, 0:YDCPG_DIM%KFLEVG)
REAL (KIND=JPRB),  INTENT(OUT)   :: PPFL_FPLSH (YDCPG_DIM%KLON, 0:YDCPG_DIM%KFLEVG)

REAL (KIND=JPRB),  INTENT(IN)    :: PCPF_T0 (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)    :: PSPF_T0 (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)
TYPE(MODEL)       ,INTENT(IN)    :: YDMODEL


INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF


DO JROF=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
  PPFL_FPLCH(JROF,0)=0.0_JPRB
  PPFL_FPLSH(JROF,0)=0.0_JPRB
ENDDO

IF(YDMODEL%YRML_PHY_MF%YRPHY%LNEBN.OR.YDMODEL%YRML_PHY_MF%YRPHY%LNEBR.OR.YDMODEL%YRML_PHY_MF%YRPHY%LRRGUST) THEN
  DO JLEV=1,YDCPG_DIM%KFLEVG
    DO JROF=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
      PPFL_FPLCH(JROF,JLEV)=PCPF_T0(JROF,JLEV)
    ENDDO
  ENDDO
ENDIF

IF(YDMODEL%YRML_PHY_MF%YRPHY%LRRGUST) THEN
  DO JLEV=1,YDCPG_DIM%KFLEVG
    DO JROF=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
      PPFL_FPLSH(JROF,JLEV)=PSPF_T0(JROF,JLEV)
    ENDDO
  ENDDO
ENDIF



END SUBROUTINE
