SUBROUTINE MF_PHYS_PRECIPS (YDCPG_DIM, PPRC_DPRECIPS, PPRC_DPRECIPS2, YDMF_PHYS_SURF, YDMODEL)

USE PARKIND1, ONLY : JPIM, JPRB

USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE(CPG_DIM_TYPE),INTENT(IN)    :: YDCPG_DIM

REAL (KIND=JPRB),  INTENT(IN)    :: PPRC_DPRECIPS  (YDCPG_DIM%KLON, 1:YDCPG_DIM%KDTPREC)
REAL (KIND=JPRB),  INTENT(IN)    :: PPRC_DPRECIPS2 (YDCPG_DIM%KLON, 1:YDCPG_DIM%KDTPREC2)
TYPE(MF_PHYS_SURF_TYPE),INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL




IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS) THEN
  YDMF_PHYS_SURF%GSD_XP%PPRECIP(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDMODEL%YRML_PHY_MF% &
& YRPHY%YRDPRECIPS%           &
& NDTPRECCUR)=PPRC_DPRECIPS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDMODEL%YRML_PHY_MF% &
& YRPHY%YRDPRECIPS%           &
& NDTPRECCUR)
ENDIF

IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS2) THEN
  YDMF_PHYS_SURF%GSD_XP2%PPRECIP2(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDMODEL%YRML_PHY_MF% &
& YRPHY%YRDPRECIPS%NDTPRECCUR2)=PPRC_DPRECIPS2(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDMODEL%YRML_PHY_MF% &
& YRPHY%YRDPRECIPS%NDTPRECCUR2)
ENDIF



END SUBROUTINE
