SUBROUTINE MF_PHYS_FPL_PART2 (YDCPG_DIM, PPFL_FPLCH, PPFL_FPLSH, YDVARS, YDMODEL)

USE PARKIND1, ONLY : JPIM, JPRB

USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : APLPAR_TMP_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE(CPG_DIM_TYPE),INTENT(IN)    :: YDCPG_DIM

REAL (KIND=JPRB),  INTENT(IN)    :: PPFL_FPLCH (YDCPG_DIM%KLON, 0:YDCPG_DIM%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)    :: PPFL_FPLSH (YDCPG_DIM%KLON, 0:YDCPG_DIM%KFLEVG)
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL


INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF


!        2.9a Evolution of precipitation fluxes
!             ------------------------------------------

IF(YDMODEL%YRML_PHY_MF%YRPHY%LNEBN.OR.YDMODEL%YRML_PHY_MF%YRPHY%LNEBR.OR.YDMODEL%YRML_PHY_MF%YRPHY%LRRGUST) THEN
  DO JLEV=1,YDCPG_DIM%KFLEVG
    DO JROF=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
      YDVARS%CPF%T1(JROF,JLEV)=PPFL_FPLCH(JROF,JLEV)
    ENDDO
  ENDDO
ENDIF

IF(YDMODEL%YRML_PHY_MF%YRPHY%LRRGUST) THEN
  DO JLEV=1,YDCPG_DIM%KFLEVG
    DO JROF=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
      YDVARS%SPF%T1(JROF,JLEV)=PPFL_FPLSH(JROF,JLEV)
    ENDDO
  ENDDO
ENDIF

END SUBROUTINE
