SUBROUTINE MF_PHYS_NHQE_PART2 (YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, PNHQ_TT0, PNHQ_TT0L, PNHQ_TT0M, &
& PNHQ_TT9, YDVARS)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK
USE PARKIND1, ONLY : JPIM, JPRB

USE YOMCT0             , ONLY : LTWOTL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES


IMPLICIT NONE

TYPE(GEOMETRY),     INTENT(IN)   :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE),INTENT(IN)   :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),INTENT(IN)   :: YDCPG_OPTS

REAL (KIND=JPRB),  INTENT(IN)    :: PNHQ_TT0  (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)    :: PNHQ_TT0L (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)    :: PNHQ_TT0M (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)    :: PNHQ_TT9  (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS

INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF

REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('MF_PHYS_NHQE_PART2', 0, ZHOOK_HANDLE)


  ! At instant t (with the derivatives):
  DO JLEV=1,YDCPG_OPTS%KFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDVARS%T%T0(JROF,JLEV)=PNHQ_TT0(JROF,JLEV)
      YDVARS%T%DL(JROF,JLEV)=PNHQ_TT0L(JROF,JLEV)
      YDVARS%T%DM(JROF,JLEV)=PNHQ_TT0M(JROF,JLEV)
    ENDDO
  ENDDO
  ! At instant t-dt for leap-frog advections (without the derivatives):
  IF (.NOT.LTWOTL) THEN
    DO JLEV=1,YDCPG_OPTS%KFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDVARS%T%T9(JROF,JLEV)=PNHQ_TT9(JROF,JLEV)
      ENDDO
    ENDDO
  ENDIF
  
IF (LHOOK) CALL DR_HOOK ('MF_PHYS_NHQE_PART2', 1, ZHOOK_HANDLE)

END SUBROUTINE MF_PHYS_NHQE_PART2
