SUBROUTINE MF_PHYS_NHQE_PART1 (YDGEOMETRY, YDMF_PHYS, YDVARS, YDMODEL, KST, KEND, PGFL)

USE PARKIND1, ONLY : JPIM, JPRB

USE YOMCT0             , ONLY : LTWOTL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(MF_PHYS_TYPE),INTENT(INOUT) :: YDMF_PHYS
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KEND
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)

#include "gnhqe_conv_tempe.intfb.h"

INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF

  ! Valid for NPDVAR=2 only.
  ! At instant t (with the derivatives):
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=KST,KEND
      YDMF_PHYS%TMP%NHQ%TT0(JROF,JLEV)=YDVARS%T%T0(JROF,JLEV)
      YDMF_PHYS%TMP%NHQ%TT0L(JROF,JLEV)=YDVARS%T%DL(JROF,JLEV)
      YDMF_PHYS%TMP%NHQ%TT0M(JROF,JLEV)=YDVARS%T%DM(JROF,JLEV)
    ENDDO
  ENDDO
  CALL GNHQE_CONV_TEMPE(YDGEOMETRY,.TRUE.,YDMODEL%YRML_GCONF%YGFL%NDIM,KST,KEND,&
   & YDVARS%SPD%T0,YDVARS%SP%T0,YDVARS%T%T0,&
   & KGFLTYP=0,PGFL=PGFL,KDDER=2,PQCHAL=YDVARS%SPD%DL,PQCHAM=YDVARS%SPD%DM,&
   & PTL=YDVARS%T%DL,PTM=YDVARS%T%DM)
  ! At instant t-dt for leap-frog advections (without the derivatives):
  IF (.NOT.LTWOTL) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=KST,KEND
        YDMF_PHYS%TMP%NHQ%TT9(JROF,JLEV)=YDVARS%T%T9(JROF,JLEV)
      ENDDO
    ENDDO
    CALL GNHQE_CONV_TEMPE(YDGEOMETRY,.TRUE.,YDMODEL%YRML_GCONF%YGFL%NDIM,KST,KEND,&
     & YDVARS%SPD%T9,YDVARS%SP%T9,YDVARS%T%T9,&
     & KGFLTYP=9,PGFL=PGFL)
  ENDIF
  

END SUBROUTINE
