SUBROUTINE MF_PHYS_NHQE_PART2 (YDGEOMETRY, YDCPG_DIM, YDMF_PHYS, YDVARS)

USE PARKIND1, ONLY : JPIM, JPRB

USE YOMCT0             , ONLY : LTWOTL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES


IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_DIM_TYPE),INTENT(IN)    :: YDCPG_DIM
TYPE(MF_PHYS_TYPE),INTENT(INOUT) :: YDMF_PHYS
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS




INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF

  ! At instant t (with the derivatives):
  DO JLEV=1,YDCPG_DIM%KFLEVG
    DO JROF=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
      YDVARS%T%T0(JROF,JLEV)=YDMF_PHYS%TMP%NHQ%TT0(JROF,JLEV)
      YDVARS%T%DL(JROF,JLEV)=YDMF_PHYS%TMP%NHQ%TT0L(JROF,JLEV)
      YDVARS%T%DM(JROF,JLEV)=YDMF_PHYS%TMP%NHQ%TT0M(JROF,JLEV)
    ENDDO
  ENDDO
  ! At instant t-dt for leap-frog advections (without the derivatives):
  IF (.NOT.LTWOTL) THEN
    DO JLEV=1,YDCPG_DIM%KFLEVG
      DO JROF=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
        YDVARS%T%T9(JROF,JLEV)=YDMF_PHYS%TMP%NHQ%TT9(JROF,JLEV)
      ENDDO
    ENDDO
  ENDIF
  

END SUBROUTINE
