SUBROUTINE MF_PHYS_PRECIPS (YDCPG_DIM, YDCPG_OPTS, PPRC_DPRECIPS, PPRC_DPRECIPS2, PGSD_XP_PPRECIP, PGSD_XP2_PPRECIP2, YDMODEL)

USE PARKIND1, ONLY : JPIM, JPRB

USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE, CPG_OPTS_TYPE
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE(CPG_DIM_TYPE),INTENT(IN)    :: YDCPG_DIM
TYPE(CPG_OPTS_TYPE),INTENT(IN)   :: YDCPG_OPTS

REAL (KIND=JPRB),  INTENT(IN)    :: PPRC_DPRECIPS  (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC)
REAL (KIND=JPRB),  INTENT(IN)    :: PPRC_DPRECIPS2 (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC2)
REAL(KIND=JPRB),   INTENT(OUT)   :: PGSD_XP_PPRECIP (YDCPG_OPTS%KLON, YDCPG_OPTS%YRSURF_DIMS%YSD_XPD%NLEVS)
REAL(KIND=JPRB),   INTENT(OUT)   :: PGSD_XP2_PPRECIP2 (YDCPG_OPTS%KLON, YDCPG_OPTS%YRSURF_DIMS%YSD_XP2D%NLEVS)
TYPE(MODEL)       ,INTENT(IN)    :: YDMODEL




IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS) THEN
  PGSD_XP_PPRECIP(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDMODEL%YRML_PHY_MF% &
& YRPHY%YRDPRECIPS%           &
& NDTPRECCUR)=PPRC_DPRECIPS(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDMODEL%YRML_PHY_MF% &
& YRPHY%YRDPRECIPS%           &
& NDTPRECCUR)
ENDIF

IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS2) THEN
  PGSD_XP2_PPRECIP2(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDMODEL%YRML_PHY_MF% &
& YRPHY%YRDPRECIPS%NDTPRECCUR2)=PPRC_DPRECIPS2(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDMODEL%YRML_PHY_MF% &
& YRPHY%YRDPRECIPS%NDTPRECCUR2)
ENDIF



END SUBROUTINE
