SUBROUTINE MF_PHYS_NHQE_PART1 (YDGEOMETRY, YDCPG_DIM, YDMF_PHYS_TMP, YDVARS, YDMODEL, PGFL)

USE PARKIND1, ONLY : JPIM, JPRB

USE YOMCT0             , ONLY : LTWOTL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TMP_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_DIM_TYPE),INTENT(IN)    :: YDCPG_DIM
TYPE(MF_PHYS_TMP_TYPE),INTENT(INOUT) :: YDMF_PHYS_TMP
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL


REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGFL(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)

#include "gnhqe_conv_tempe.intfb.h"

INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF

  ! Valid for NPDVAR=2 only.
  ! At instant t (with the derivatives):
  DO JLEV=1,YDCPG_DIM%KFLEVG
    DO JROF=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
      YDMF_PHYS_TMP%NHQ%TT0(JROF,JLEV)=YDVARS%T%T0(JROF,JLEV)
      YDMF_PHYS_TMP%NHQ%TT0L(JROF,JLEV)=YDVARS%T%DL(JROF,JLEV)
      YDMF_PHYS_TMP%NHQ%TT0M(JROF,JLEV)=YDVARS%T%DM(JROF,JLEV)
    ENDDO
  ENDDO
  CALL GNHQE_CONV_TEMPE(YDGEOMETRY,.TRUE.,YDMODEL%YRML_GCONF%YGFL%NDIM,YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA,&
   & YDVARS%SPD%T0,YDVARS%SP%T0,YDVARS%T%T0,&
   & KGFLTYP=0,PGFL=PGFL,KDDER=2,PQCHAL=YDVARS%SPD%DL,PQCHAM=YDVARS%SPD%DM,&
   & PTL=YDVARS%T%DL,PTM=YDVARS%T%DM)
  ! At instant t-dt for leap-frog advections (without the derivatives):
  IF (.NOT.LTWOTL) THEN
    DO JLEV=1,YDCPG_DIM%KFLEVG
      DO JROF=YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA
        YDMF_PHYS_TMP%NHQ%TT9(JROF,JLEV)=YDVARS%T%T9(JROF,JLEV)
      ENDDO
    ENDDO
    CALL GNHQE_CONV_TEMPE(YDGEOMETRY,.TRUE.,YDMODEL%YRML_GCONF%YGFL%NDIM,YDCPG_DIM%KIDIA,YDCPG_DIM%KFDIA,&
     & YDVARS%SPD%T9,YDVARS%SP%T9,YDVARS%T%T9,&
     & KGFLTYP=9,PGFL=PGFL)
  ENDIF
  

END SUBROUTINE
