SUBROUTINE MF_PHYS_CORWAT (YDCPG_DIM, YDMF_PHYS, YDMF_PHYS_SURF)

USE PARKIND1, ONLY : JPIM, JPRB

USE CPG_DIM_TYPE_MOD   , ONLY : CPG_DIM_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE


IMPLICIT NONE

TYPE(MF_PHYS_TYPE),INTENT(INOUT) :: YDMF_PHYS
TYPE(CPG_DIM_TYPE),INTENT(IN)    :: YDCPG_DIM
TYPE(MF_PHYS_SURF_TYPE),INTENT(INOUT) :: YDMF_PHYS_SURF






  YDMF_PHYS_SURF%GSD_VH%PPSL(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA) = YDMF_PHYS%OUT%FPLSL(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDCPG_DIM%KFLEVG)
  YDMF_PHYS_SURF%GSD_VH%PPCL(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA) = YDMF_PHYS%OUT%FPLCL(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDCPG_DIM%KFLEVG)
  YDMF_PHYS_SURF%GSD_VH%PPSN(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA) = YDMF_PHYS%OUT%FPLSN(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDCPG_DIM%KFLEVG)
  YDMF_PHYS_SURF%GSD_VH%PPCN(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA) = YDMF_PHYS%OUT%FPLCN(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,YDCPG_DIM%KFLEVG)
  YDMF_PHYS_SURF%GSD_VH%PEVA(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA) = YDMF_PHYS%OUT%FEVN(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,1)-YDMF_PHYS%OUT%FEVL(YDCPG_DIM%KIDIA:YDCPG_DIM%KFDIA,1)
  

END SUBROUTINE
