SUBROUTINE MF_PHYS_CVV (YDCPG_BNDS, YDCPG_OPTS, PCVV_T0, PCVV_T1, YDMODEL)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK
USE PARKIND1, ONLY : JPIM, JPRB

USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE(CPG_BNDS_TYPE),INTENT(IN)   :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),INTENT(IN)   :: YDCPG_OPTS
REAL (KIND=JPRB),  INTENT(IN)    :: PCVV_T0 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(OUT)   :: PCVV_T1 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
TYPE(MODEL),       INTENT(IN)    :: YDMODEL


INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF

REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('MF_PHYS_CVV', 0, ZHOOK_HANDLE)

!        2.11 Evolution of CVV (GY)
!             ---------------------

IF(YDMODEL%YRML_PHY_MF%YRPHY%LCVPGY) THEN
  DO JLEV=1,YDCPG_OPTS%KFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      PCVV_T1(JROF,JLEV)=PCVV_T0(JROF,JLEV)
    ENDDO
  ENDDO
ENDIF

IF (LHOOK) CALL DR_HOOK ('MF_PHYS_CVV', 1, ZHOOK_HANDLE)

END SUBROUTINE MF_PHYS_CVV
