SUBROUTINE MF_PHYS_PRECIPS (YDCPG_BNDS, YDCPG_OPTS, PPRC_DPRECIPS, PPRC_DPRECIPS2, PGSD_XP_PPRECIP, &
& PGSD_XP2_PPRECIP2, YDMODEL)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK
USE PARKIND1, ONLY : JPIM, JPRB

USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE TYPE_MODEL         , ONLY : MODEL


IMPLICIT NONE

TYPE(CPG_BNDS_TYPE),INTENT(IN)   :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),INTENT(IN)   :: YDCPG_OPTS

REAL (KIND=JPRB),  INTENT(IN)    :: PPRC_DPRECIPS  (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC)
REAL (KIND=JPRB),  INTENT(IN)    :: PPRC_DPRECIPS2 (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC2)
REAL(KIND=JPRB),   INTENT(OUT)   :: PGSD_XP_PPRECIP (YDCPG_OPTS%KLON, YDCPG_OPTS%YRSURF_DIMS%YSD_XPD%NLEVS)
REAL(KIND=JPRB),   INTENT(OUT)   :: PGSD_XP2_PPRECIP2 (YDCPG_OPTS%KLON, YDCPG_OPTS%YRSURF_DIMS%YSD_XP2D%NLEVS)
TYPE(MODEL)       ,INTENT(IN)    :: YDMODEL

REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('MF_PHYS_PRECIPS', 0, ZHOOK_HANDLE)

IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS) THEN
  PGSD_XP_PPRECIP(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,YDCPG_OPTS%NDTPRECCUR)=&
 & PPRC_DPRECIPS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,YDCPG_OPTS%NDTPRECCUR)
ENDIF

IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS2) THEN
  PGSD_XP2_PPRECIP2(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,YDCPG_OPTS%NDTPRECCUR2)=&
 & PPRC_DPRECIPS2(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,YDCPG_OPTS%NDTPRECCUR2)
ENDIF

IF (LHOOK) CALL DR_HOOK ('MF_PHYS_PRECIPS', 1, ZHOOK_HANDLE)

END SUBROUTINE MF_PHYS_PRECIPS
