!OPTIONS XOPT(NOEVAL)
SUBROUTINE SUPHY0(YDGEOMETRY,YDML_PHY_MF,KULOUT)

!**** *SUPHY0*   - Initialize common YOMPHY0 physics atmospheric
!                  constants

!     Purpose.
!     --------
!           Initialize YOMPHY0, the common that contains the parameters
!           for the atmospheric part of the physics of the model.

!**   Interface.
!     ----------
!        *CALL* *SUPHY0(...)

!        Explicit arguments :
!        --------------------
!        KULOUT : Logical unit for the output

!        Implicit arguments :
!        --------------------
!        COMMON YOMPHY0

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------

!     Reference.
!     ----------
!        Documentation ARPEGE

!     Author.
!     -------
!        J.-F. Geleyn .
!        Original : 90-9-1

!     Modifications.
!     --------------
!        Modified by J.M. Piriou: 2001-04-05 (introduce GCVMLT).
!        Modified by Y. Bouteloup:2002-06-14 (introduce RCVEVAP).
!        Modified by F. Bouyssel: 2002-06-25 (introduce UTILGUST, RRGAMMA, RRSCALE).
!        Modified by J.M. Piriou: 2002-08-19 (introduce GPBLH*).
!        Modified by D. Banciu:   2002-12-09 (introduce GCVPSIE).
!        R. El Khatib : 2001-08-07 Pruning options
!        J.M. Piriou  : 2002-01-10 set default values to operational ones.
!        03-06, move rnlcurv rnegat into yomphy0 (F. Bouyssel, C. Fischer)
!        E. Bazile : 2004-02-24 (introduce EDK).
!        M.Hamrud      01-Oct-2003 CY28 Cleaning
!        E. Bazile : 2004-06-30 (inroduces XKLM).
!        R. Brozkova : 2004-11 modifs for Xue-Randall cloud. scheme
!        P. Marquet & F.Bouyssel : 2004-08-18 (Lopez)
!        F.Bouyssel : 2005-07-18 (new defaults and new parameters for Lopez)
!        F.Bouyssel : 2006-01-25 (new defaults for Lopez!)
!        F. Vana    : 2006-01-30 tunables for pTKE.
!        R.Brozkova : 2006-03-03 : tuning constants for mixing lengths and Charnock formulae
!        A.Alias    : 2006-03-10 renaming KDN in RKDN
!        Modified by GMGEC/EAC  : 2006-05 list of modif.
!                    V. Lorant  : 99-01-05 (new mixing length profile).
!                    M. Deque   : 00-03-21 (new entrainment rate VL  ).
!                    P. Marquet : 2002-11-05 TRENTRVL=0. if not ACPBLH
!                    P. Marquet : 2004-05-27 TFVR and TFVS for ADVPRC.
!                    P. Marquet : 2004-10-13 RAUTEFR for snow (ACMICRO).
!                    P. Marquet : 2004-10-14 RAUTSBET for snow (ACMICRO).
!                    A. Alias   : 2005-06-23 (param. for ACCVIMPGDY)
!        E. Bazile & P. Marquet : 2006-04-11 AGRE1,AGRERICR,AJBUMIN,RCOFLM
!                                  for LPBLE.
!        F.Bouyssel : 2006-10-30 RQLCV,RQICVMAX,RQICVMIN,RHEVAP
!        M. Bellus  : 03-Oct-2006 : ALARO-0 phasing (defaults for prognostic
!                                   convection, pTKE and PIL microphysics)
!        A.Alias     : 2006-07   FEVAPC added for ACCVIMPGY (JF Gueremy)
!        F.Bouyssel : 2007-05-21 Change writing format of some variables
!        E. Bazile   : 2006-10   RTKFBCVPP added for LCVPPKF and GCVHMIN.
!        A.Alias     : 2007-03   RLMLHx tuning for ACNEBR (P.Marquet)
!        A.Alias     : 2007-10   Add printing TRENTRV/TENTRVL
!        E. Bazile   : 2008-04-28 Coef. for thermal production (LECT)
!        F. Bouyssel : 2008-06 Coef. for KFB shallow clouds
!        Y. Bouteloup: 2008-07 Change implicit value for TKE tuning parameters
!                              RTKFBCVPP becomes RKFBTAU
!        F. Bouyssel : 2008-10 Coef. for ECUME (RFLCHCE)
!        F. Vana     : 21-Jan-2009 tuning parameters for p/eTKE
!        C. Wittmann : 2009-03 WMXOV for LACPANMX
!        F. Bouyssel : 2009-11 ECTMAX for CBR scheme
!        I. Bastak Duran + F. Vana : 12-Oct-2009  p/eTKE tunables update
!        K. Yessad (Jan 2010): remove useless variables.
!        F. Bouyssel : 2010-04 New sedimentation coefficients
!        F. Bouyssel : 2010-05 Parameters for saturation deficit
!        I. Bastak Duran + F. Vana : 22-Feb-2011  TOUCANS defaults
!        F. Bouyssel : 2011-01 Intro. GCVOMGE, GCVOMGQ
!        F. Bouyssel : 2011-03 Intro. GCVOMGS, GCVOMGP
!        O. Riviere  : 2011-06 Intro. RSMOOTHMELT
!        J.M. Piriou : 2011-09-21 Introduce PCMT convection scheme parameters.
!        JF. Gueremy : 2011-11 Dry Conv. Adj. (AJ1PEPS,AJ1MEPS,NAJITER)
!        S.Martinez  : 2011-09 put writes related to "Alaro TOUCANS/pTKE scheme" under key LCOEFKTKE
!        I. Bastak-Duran, F. Vana : 26-Jan-2012 Update of Toucans/pTKE setup
!        JF. Gueremy : 2012-10 Autoconv ratio Conv/Stra, supercooled rain (RRAUTCS,RSPCRR)
!        T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!        JF. Gueremy : 2014-05 GCVCINC CIN threshold for triggering condition
!        I. Beau     : 2015-05 Convective detrainment of precipitations
!        J.M. Piriou : 2015-09 Phasing PCMT/NWP and PCMT/Climat
!        JF. Gueremy : 2015-11 GCVIMPT implication factor for convective
!                              transport in combined (cv-turb) computation
!        L. Bengtsson: 2014-08 Update to CA setup
!        L. Gerard: 2016-03 NS-downdraft, CSD+triggering setup
!        J. Masek : 2016-04 Exponential-random overlap and true direct
!                   flux for ACRANEB2 radiation.
!        R. Roehrig : 2018-09 GCVTURB value of minimum turbulence (from JF Guérémy)
!        JF. Gueremy : 2019-08 GCVTSMO,RKDX,LCAPCIN,GREDDL/I/R/S,LCORSEDIM
!        P. Marquet : 2017-05-22 NCAPEMOD WCAPEMOD RENTRMOD for the model-CAPE
!        P. Marquet : 2018-05 GCVOMDPS GCVOMGSX GCVRHMIN GCVRHMAX
!        L. Descamp : 2018-05 GCVOMCA GCVOMCC
!        J. Masek : 2020-10 Introduced ETKE_CRIT and ETKE_DELTA for TTE scheme.
!        M. Hrastinski : 2020-10 Introduced ETKE_GB08A and ETKE_GB08B for
!                        new EL2 mixing length (Grisogono and Belusic 2008).
! ------------------------------------------------------------------------

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM     ,JPRB
USE YOMHOOK  , ONLY : LHOOK    ,DR_HOOK
USE YOMLUN   , ONLY : NULNAM
USE YOMCST   , ONLY : ROMEGA
USE YOMCT0   , ONLY : LECMWF

! ------------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_PHYSICS_MF_TYPE),TARGET,INTENT(INOUT):: YDML_PHY_MF
INTEGER(KIND=JPIM), INTENT(IN) :: KULOUT
INTEGER(KIND=JPIM) :: ITTYPE
REAL(KIND=JPRB) :: ZNUPTKE4,ZLAMBDA,ZSF,ZLAMF_X,ZSM0
REAL(KIND=JPRB) :: ZHOOK_HANDLE
CHARACTER(LEN=200) :: CLERR

! ------------------------------------------------------------------------

#include "abor1.intfb.h"
#include "posnam.intfb.h"

LOGICAL , POINTER ::  LCVUVM
REAL (KIND=JPRB) , POINTER ::  GPEIPHI, GPETAU, GPEFDC, GENVSRH
REAL(KIND=JPRB) , POINTER ::  XMAXLM
REAL(KIND=JPRB)   , POINTER ::  GSDAMAX
REAL(KIND=JPRB) , POINTER ::  GCVNU
REAL(KIND=JPRB)    , POINTER ::  GCVHMIN
REAL(KIND=JPRB) , POINTER ::  EVAP
REAL(KIND=JPRB) , POINTER ::  TFVI
REAL(KIND=JPRB)    , POINTER ::  TCTC
REAL(KIND=JPRB) , POINTER ::  REFLRHC
REAL(KIND=JPRB) , POINTER ::  AGREF
REAL(KIND=JPRB) , POINTER ::  ETKE_CG03
REAL(KIND=JPRB) , POINTER ::  GCVOMGQ
REAL(KIND=JPRB) , POINTER ::  A0ML_BT
REAL(KIND=JPRB) , POINTER ::  AGRE1
REAL(KIND=JPRB) , POINTER ::  RNINTR
REAL(KIND=JPRB) , POINTER ::  QSMIN
REAL(KIND=JPRB)   , POINTER ::  AJ1MEPS
REAL(KIND=JPRB) , POINTER ::  RRAUTCS
REAL(KIND=JPRB) , POINTER ::  USURICL
REAL(KIND=JPRB) , POINTER ::  TKEMULT
REAL(KIND=JPRB) , POINTER ::  ETKE_ENTRN
REAL(KIND=JPRB) , POINTER ::  GPBLHK0
REAL(KIND=JPRB) , POINTER ::  GWDCD
INTEGER (KIND=JPIM) , POINTER ::  NCVENTR
REAL(KIND=JPRB) , POINTER ::  EDD
REAL(KIND=JPRB) , POINTER ::  AECLS4
REAL(KIND=JPRB) , POINTER ::  GPBLHRA
REAL(KIND=JPRB) , POINTER ::  BEDIFV
REAL(KIND=JPRB) , POINTER ::  AKN
REAL(KIND=JPRB) , POINTER ::  TCT
REAL(KIND=JPRB) , POINTER ::  TRENTRV
REAL(KIND=JPRB)   , POINTER ::  GCVTAUREM
REAL (KIND=JPRB) , POINTER ::  TUDFR, TDDFR
REAL(KIND=JPRB) , POINTER ::  RSPCRR
REAL(KIND=JPRB) , POINTER ::  XWSBLM
REAL(KIND=JPRB) , POINTER ::  ETKE_RIFC_MAF
REAL(KIND=JPRB) , POINTER ::  GCVADS
REAL(KIND=JPRB) , POINTER ::  RDECRD
REAL(KIND=JPRB) , POINTER ::  RDECRD1
REAL(KIND=JPRB) , POINTER ::  RDECRD2
REAL(KIND=JPRB) , POINTER ::  RDECRD3
REAL(KIND=JPRB) , POINTER ::  RDECRD4
REAL(KIND=JPRB) , POINTER ::  RDECRDRED
REAL(KIND=JPRB) , POINTER ::  RHCRIT2
REAL(KIND=JPRB) , POINTER ::  XNBMAX
REAL(KIND=JPRB) , POINTER ::  ACBRPHIM
REAL(KIND=JPRB) , POINTER ::  SNNBCO
REAL(KIND=JPRB)   , POINTER ::  GCVWEXC
REAL(KIND=JPRB) , POINTER ::  RQLCV
REAL(KIND=JPRB) , POINTER ::  GCVMLT
REAL(KIND=JPRB) , POINTER ::  GRHCMOD
REAL(KIND=JPRB) , POINTER ::  RDPHIC
REAL(KIND=JPRB) , POINTER ::  GCISMIN
REAL(KIND=JPRB) , POINTER ::  ETKE_ENTRX
REAL(KIND=JPRB) , POINTER ::  SCO
REAL(KIND=JPRB) , POINTER ::  A0ML_BU
REAL(KIND=JPRB) , POINTER ::  GWDBC
REAL(KIND=JPRB) , POINTER ::  GCVPSI
REAL(KIND=JPRB) , POINTER ::  GWDVALI
REAL(KIND=JPRB) , POINTER ::  ALMAVE
INTEGER (KIND=JPIM) , POINTER ::  NCVSIG
REAL(KIND=JPRB) , POINTER ::  USHEARM
REAL(KIND=JPRB)   , POINTER ::  GEXPKD
REAL(KIND=JPRB) , POINTER ::  GDDEVA
REAL(KIND=JPRB) , POINTER ::  RPHIR
REAL(KIND=JPRB) , POINTER ::  ETKE_GAMD
REAL(KIND=JPRB) , POINTER ::  ETKE_LAM0
REAL(KIND=JPRB)   , POINTER ::  GNHDTAT
REAL(KIND=JPRB) , POINTER ::  XMINLM
REAL(KIND=JPRB) , POINTER ::  AHCLPV
REAL(KIND=JPRB)   , POINTER ::  GCVENTRN
REAL(KIND=JPRB) , POINTER ::  QXRHX
REAL(KIND=JPRB) , POINTER ::  XBLM
REAL(KIND=JPRB) , POINTER ::  ARSCQ
REAL(KIND=JPRB) , POINTER ::  QXRAL
REAL (KIND=JPRB) , POINTER ::  GCVTAUDE
REAL(KIND=JPRB) , POINTER ::  GWDSE
REAL(KIND=JPRB) , POINTER ::  AGRE2
REAL(KIND=JPRB) , POINTER ::  AERCS1
REAL(KIND=JPRB)    , POINTER ::  TVFC
REAL(KIND=JPRB) , POINTER ::  HUTIL2
REAL(KIND=JPRB) , POINTER ::  ALMAV
REAL(KIND=JPRB) , POINTER ::  QSSC
REAL(KIND=JPRB) , POINTER ::  QSMODC
REAL(KIND=JPRB) , POINTER ::  REVGSL
REAL(KIND=JPRB)   , POINTER ::  GCVENTR_MIN
REAL (KIND=JPRB) , POINTER ::  NWEIGHT, NCATAU, NCAPEMAX, NCVGMAX
REAL(KIND=JPRB)   , POINTER ::  GALMIN
REAL(KIND=JPRB)    , POINTER ::  RKFBNBX
REAL(KIND=JPRB)    , POINTER ::  RNEBCX
REAL(KIND=JPRB) , POINTER ::  RPHI0
REAL(KIND=JPRB) , POINTER ::  SCLESPR
INTEGER (KIND=JPIM) , POINTER ::  NAJITER
INTEGER (KIND=JPIM) , POINTER ::  NCVCLOS
REAL(KIND=JPRB)   , POINTER ::  GCVORGED
REAL(KIND=JPRB) , POINTER ::  RTCAPE
REAL(KIND=JPRB) , POINTER ::  RCOFLM
REAL(KIND=JPRB) , POINTER ::  EFFCOLL
REAL(KIND=JPRB) , POINTER ::  RICRET
REAL(KIND=JPRB) , POINTER ::  RCIN
REAL(KIND=JPRB) , POINTER ::  ARSC1
REAL(KIND=JPRB)    , POINTER ::  ALFX
REAL(KIND=JPRB)    , POINTER ::  ALFX_LR
REAL(KIND=JPRB)    , POINTER ::  ALFX_HR
REAL(KIND=JPRB)    , POINTER ::  GCVRESN
REAL(KIND=JPRB)    , POINTER ::  GCVRESX
REAL(KIND=JPRB)    , POINTER ::  GMIRH
REAL(KIND=JPRB)    , POINTER ::  GCVGAX
REAL(KIND=JPRB)    , POINTER ::  GCVGAW
REAL(KIND=JPRB) , POINTER ::  QSUSXC
INTEGER (KIND=JPIM) , POINTER ::  NSMTPA
REAL(KIND=JPRB) , POINTER ::  UPRETMAX
LOGICAL , POINTER ::  LCVEOD
LOGICAL , POINTER ::  LGPRONI1
INTEGER(KIND=JPIM), POINTER ::  NPRONI
REAL(KIND=JPRB) , POINTER ::  GPRONI
REAL(KIND=JPRB) , POINTER ::  TVF
REAL(KIND=JPRB) , POINTER ::  QSSUSC
REAL(KIND=JPRB) , POINTER ::  ADISI
REAL(KIND=JPRB) , POINTER ::  XKLM
REAL(KIND=JPRB) , POINTER ::  QSUSXS
REAL(KIND=JPRB) , POINTER ::  USDMLT
LOGICAL , POINTER ::  LCVTADV
REAL(KIND=JPRB) , POINTER ::  RWBF2
REAL(KIND=JPRB) , POINTER ::  HUTIL
LOGICAL , POINTER ::  LCVMICC
REAL(KIND=JPRB) , POINTER ::  RQCRNS
REAL(KIND=JPRB)    , POINTER ::  RKFBTAU
REAL(KIND=JPRB) , POINTER ::  GCVPSIE
REAL(KIND=JPRB) , POINTER ::  HOBST
REAL(KIND=JPRB)   , POINTER ::  GNHDSMOS
REAL(KIND=JPRB) , POINTER ::  RCVEVAP
REAL(KIND=JPRB) , POINTER ::  ETKE_ALPH0
REAL(KIND=JPRB) , POINTER ::  RQICVMAX
REAL(KIND=JPRB) , POINTER ::  ETKE_BETA_EPS
REAL(KIND=JPRB) , POINTER ::  RQLCR
REAL(KIND=JPRB)   , POINTER ::  RSMOOTHMELT
REAL(KIND=JPRB)   , POINTER ::  GSDMAX
REAL(KIND=JPRB)   , POINTER ::  RPRTH
REAL(KIND=JPRB)   , POINTER ::  GCVTEXC
LOGICAL , POINTER ::  LCVFEVV
REAL(KIND=JPRB) , POINTER ::  ETKE_CG01
REAL(KIND=JPRB) , POINTER ::  RQICVMIN
REAL(KIND=JPRB) , POINTER ::  EDK
REAL(KIND=JPRB) , POINTER ::  A0ML_AU
REAL(KIND=JPRB) , POINTER ::  TFVR
REAL(KIND=JPRB) , POINTER ::  VKARMN
REAL(KIND=JPRB)   , POINTER ::  GNHDTAU
REAL(KIND=JPRB) , POINTER ::  AJBUMIN
REAL(KIND=JPRB) , POINTER ::  RQICRSN
REAL(KIND=JPRB)   , POINTER ::  GSDAMIN
LOGICAL , POINTER ::  LCVNAUV
REAL(KIND=JPRB)   , POINTER ::  GNHDEV
REAL(KIND=JPRB) , POINTER ::  GCVOMGS
REAL(KIND=JPRB)   , POINTER ::  GALMAX
REAL(KIND=JPRB)    , POINTER ::  RKDN
REAL(KIND=JPRB)    , POINTER ::  RKDX
REAL(KIND=JPRB)    , POINTER ::  FNEBC
REAL(KIND=JPRB) , POINTER ::  SPNBCO
REAL(KIND=JPRB) , POINTER ::  AERCS3
REAL(KIND=JPRB)   , POINTER ::  GFRAE
REAL(KIND=JPRB)   , POINTER ::  GCVIMPT
INTEGER(KIND=JPIM) , POINTER ::  NCVQLI
REAL(KIND=JPRB)   , POINTER ::  GCVUV
REAL(KIND=JPRB)   , POINTER ::  GCHECKMV_TMIN
REAL(KIND=JPRB)   , POINTER ::  GCHECKMV_TMAX
REAL(KIND=JPRB)   , POINTER ::  GCHECKMV_QVMIN
REAL(KIND=JPRB)   , POINTER ::  GCHECKMV_QVMAX
REAL(KIND=JPRB) , POINTER ::  RRGAMMA
LOGICAL , POINTER ::  LGVVEX
REAL(KIND=JPRB) , POINTER ::  C3TKEFREE
REAL(KIND=JPRB) , POINTER ::  UHDIFV
REAL(KIND=JPRB) , POINTER ::  AGRERICR
REAL(KIND=JPRB) , POINTER ::  UTILGUST
REAL(KIND=JPRB) , POINTER ::  USURICE
REAL(KIND=JPRB)   , POINTER ::  GCVENTRX
REAL(KIND=JPRB) , POINTER ::  ENT_LAMBDA
REAL(KIND=JPRB) , POINTER ::  RRSCALE
REAL(KIND=JPRB) , POINTER ::  ADJTAU
REAL(KIND=JPRB) , POINTER ::  SENSL
LOGICAL , POINTER ::  LSBUO
REAL(KIND=JPRB) , POINTER ::  ALMAVX
REAL(KIND=JPRB) , POINTER ::  FSPRAIN
LOGICAL , POINTER ::  LCVCONTAU
REAL(KIND=JPRB) , POINTER ::  GCCSV
REAL(KIND=JPRB) , POINTER ::  GALP
REAL(KIND=JPRB)   , POINTER ::  GCVRE
INTEGER(KIND=JPIM) , POINTER ::  NPCLO1
REAL(KIND=JPRB)   , POINTER ::  GCVADET
REAL(KIND=JPRB) , POINTER ::  ECTMIN
REAL(KIND=JPRB)   , POINTER ::  ADOE
REAL(KIND=JPRB) , POINTER ::  A0ML_AT
REAL(KIND=JPRB)   , POINTER ::  RLMLH1
INTEGER (KIND=JPIM) , POINTER ::  NSMTPB
REAL(KIND=JPRB) , POINTER ::  RRIMEF
REAL(KIND=JPRB) , POINTER ::  ECMNP
REAL(KIND=JPRB) , POINTER ::  GCVBETA
REAL (KIND=JPRB) , POINTER ::  GCVACHI
REAL(KIND=JPRB) , POINTER ::  QXRR
REAL (KIND=JPRB) , POINTER ::  TENTRD
REAL(KIND=JPRB) , POINTER ::  RNEGAT
REAL(KIND=JPRB) , POINTER ::  GWDAMP
REAL(KIND=JPRB) , POINTER ::  GCVOMGE
REAL(KIND=JPRB) , POINTER ::  GCVOMDPS
REAL(KIND=JPRB) , POINTER ::  GCVOMGSX
REAL(KIND=JPRB) , POINTER ::  GCVRHMIN
REAL(KIND=JPRB) , POINTER ::  GCVRHMAX
REAL(KIND=JPRB) , POINTER ::  GCVOMCA
REAL(KIND=JPRB) , POINTER ::  GCVOMCC
REAL(KIND=JPRB) , POINTER ::  TENTR
REAL(KIND=JPRB) , POINTER ::  USURIC
REAL(KIND=JPRB) , POINTER ::  QSNEBC
REAL(KIND=JPRB) , POINTER ::  RICRLM
REAL(KIND=JPRB) , POINTER ::  TURB
REAL(KIND=JPRB)    , POINTER ::  VVX
REAL(KIND=JPRB) , POINTER ::  SCLESPS
REAL(KIND=JPRB)   , POINTER ::  GCVPNH
REAL(KIND=JPRB)   , POINTER ::  RFRAC_ENTR_X
REAL(KIND=JPRB)   , POINTER ::  GCVTURB
REAL(KIND=JPRB) , POINTER ::  RSMDTX
REAL(KIND=JPRB)    , POINTER ::  GAMAP1
REAL(KIND=JPRB) , POINTER ::  RHCRIT1
REAL(KIND=JPRB) , POINTER ::  SXNBCO
REAL(KIND=JPRB) , POINTER ::  ARSB2
REAL(KIND=JPRB) , POINTER ::  USURIDE
REAL(KIND=JPRB) , POINTER ::  AERCS5
REAL(KIND=JPRB)   , POINTER ::  THPCMT
REAL(KIND=JPRB) , POINTER ::  GRCVPP
REAL(KIND=JPRB) , POINTER ::  RFACNSM
REAL(KIND=JPRB) , POINTER ::  QSSUSV
REAL(KIND=JPRB) , POINTER ::  TCW
REAL(KIND=JPRB) , POINTER ::  UCWSTAR
REAL(KIND=JPRB) , POINTER ::  TFVS
REAL(KIND=JPRB) , POINTER ::  REVAPN
REAL(KIND=JPRB) , POINTER ::  REFLKUO
REAL(KIND=JPRB) , POINTER ::  NUPTKE
REAL(KIND=JPRB) , POINTER ::  ALPHAE
REAL (KIND=JPRB) , POINTER ::  GRRMINA
REAL(KIND=JPRB)   , POINTER ::  GREDDI
REAL(KIND=JPRB)   , POINTER ::  GREDDL
REAL(KIND=JPRB)   , POINTER ::  GREDDR
REAL(KIND=JPRB)   , POINTER ::  GREDDS
REAL(KIND=JPRB) , POINTER ::  QSNEBS
REAL(KIND=JPRB) , POINTER ::  STTBMIN
REAL(KIND=JPRB) , POINTER ::  GCVALFA
REAL(KIND=JPRB)   , POINTER ::  GCVFEVV
REAL(KIND=JPRB) , POINTER ::  TUDGP
REAL(KIND=JPRB) , POINTER ::  USUPRC
REAL(KIND=JPRB) , POINTER ::  RQICRT1
LOGICAL , POINTER ::  LADVLIM
REAL(KIND=JPRB) , POINTER ::  ETKE_KLM
REAL(KIND=JPRB) , POINTER ::  RNLCURV
REAL(KIND=JPRB) , POINTER ::  GEVAVF
REAL(KIND=JPRB) , POINTER ::  ETKE_OLAM
REAL(KIND=JPRB) , POINTER ::  GDDSDE
REAL(KIND=JPRB) , POINTER ::  RAUTEFR
REAL(KIND=JPRB) , POINTER ::  TENTRX
REAL(KIND=JPRB) , POINTER ::  GWDPROF
REAL(KIND=JPRB) , POINTER ::  QXRAL_ADJ
REAL(KIND=JPRB)    , POINTER ::  FEVAPC
REAL(KIND=JPRB) , POINTER ::  VCHRNK
REAL(KIND=JPRB) , POINTER ::  ADISE
REAL(KIND=JPRB) , POINTER ::  QXRTGH
REAL(KIND=JPRB) , POINTER ::  RMULACVG
REAL(KIND=JPRB) , POINTER ::  RAUTSBET
REAL(KIND=JPRB) , POINTER ::  UDECT
REAL (KIND=JPRB) , POINTER ::  GCVALMX
REAL(KIND=JPRB) , POINTER ::  TENTRVL
REAL(KIND=JPRB) , POINTER ::  GCVGAMMA
LOGICAL , POINTER ::  LKESC
REAL(KIND=JPRB) , POINTER ::  TYM(:)
REAL(KIND=JPRB) , POINTER ::  TDDGP
REAL(KIND=JPRB) , POINTER ::  TCA
REAL(KIND=JPRB)   , POINTER ::  GSDMIN
REAL(KIND=JPRB)   , POINTER ::  GCLOEA
REAL(KIND=JPRB) , POINTER ::  RGELSFON
REAL(KIND=JPRB)   , POINTER ::  AJ1PEPS
REAL(KIND=JPRB) , POINTER ::  ETKE_CG02
REAL(KIND=JPRB) , POINTER ::  HUCRED
REAL(KIND=JPRB) , POINTER ::  HUCREDRA
REAL(KIND=JPRB) , POINTER ::  RQICRMIN
REAL(KIND=JPRB) , POINTER ::  QXRDEL
REAL(KIND=JPRB) , POINTER ::  RETAMIN
REAL(KIND=JPRB) , POINTER ::  RDTFAC
REAL(KIND=JPRB) , POINTER ::  RSMDNEBX
REAL(KIND=JPRB) , POINTER ::  QSSUSS
REAL(KIND=JPRB) , POINTER ::  ETACUT
REAL(KIND=JPRB) , POINTER ::  ALD
REAL (KIND=JPRB) , POINTER ::  ECMNPI
REAL(KIND=JPRB) , POINTER ::  RAGGEF
REAL(KIND=JPRB)   , POINTER ::  GAEPS
REAL(KIND=JPRB)   , POINTER ::  GNHDSMOT
REAL(KIND=JPRB) , POINTER ::  FONT
LOGICAL , POINTER ::  LCVIMPT
LOGICAL , POINTER ::  LGDDD
REAL(KIND=JPRB)   , POINTER ::  GCVTRMIN
REAL(KIND=JPRB)   , POINTER ::  GCVTSMO
REAL(KIND=JPRB) , POINTER ::  ETKE_TALPH
REAL(KIND=JPRB)   , POINTER ::  GCVCINC
REAL(KIND=JPRB) , POINTER ::  EDB
REAL(KIND=JPRB)    , POINTER ::  FQLIC
REAL(KIND=JPRB) , POINTER ::  RAUTEFS
REAL(KIND=JPRB) , POINTER ::  RQICRT2
REAL(KIND=JPRB) , POINTER ::  RQICRMAX
REAL(KIND=JPRB)   , POINTER ::  GCVFRR
REAL(KIND=JPRB) , POINTER ::  ETKE_TAULM
REAL(KIND=JPRB) , POINTER ::  ETKE_C0SHEAR
REAL(KIND=JPRB) , POINTER ::  ETKE_R1SIM
REAL(KIND=JPRB) , POINTER ::  ETKE_R2SIM
REAL(KIND=JPRB) , POINTER ::  ETKE_GB08A
REAL(KIND=JPRB) , POINTER ::  ETKE_GB08B
REAL(KIND=JPRB) , POINTER ::  ETKE_MIN
REAL(KIND=JPRB) , POINTER ::  ETKE_CRIT
REAL(KIND=JPRB) , POINTER ::  ETKE_DELTA
REAL(KIND=JPRB) , POINTER ::  USURID
REAL(KIND=JPRB) , POINTER ::  HUCOE
REAL(KIND=JPRB) , POINTER ::  ALPHAT
REAL(KIND=JPRB)   , POINTER ::  GTDCL
LOGICAL , POINTER ::  LCVNHD
LOGICAL , POINTER ::  LCVRESDYN
LOGICAL , POINTER ::  LCVDS
REAL(KIND=JPRB) , POINTER ::  WMXOV
REAL(KIND=JPRB) , POINTER ::  RFLCHCE
REAL(KIND=JPRB) , POINTER ::  RWBF1
REAL(KIND=JPRB) , POINTER ::  ARSCH
REAL(KIND=JPRB) , POINTER ::  AECLS3
REAL(KIND=JPRB) , POINTER ::  UPRETMIN
INTEGER(KIND=JPIM) , POINTER ::  NPCLO2
REAL(KIND=JPRB) , POINTER ::  ETKE_GAMMA_EPS
REAL(KIND=JPRB)   , POINTER ::  GCLOEB
REAL(KIND=JPRB) , POINTER ::  VZIUSTAR0
REAL(KIND=JPRB) , POINTER ::  TFVL
REAL(KIND=JPRB) , POINTER ::  REVASX
REAL(KIND=JPRB) , POINTER ::  HUTIL1
REAL(KIND=JPRB)   , POINTER ::  GSHELL
REAL(KIND=JPRB) , POINTER ::  GWDLT
REAL (KIND=JPRB) , POINTER :: TUDBU, TDDBU
REAL(KIND=JPRB)   , POINTER ::  GMUKEDD
REAL(KIND=JPRB) , POINTER ::  REFLCAPE
REAL(KIND=JPRB)   , POINTER ::  RFRAC_ENTR_N
REAL(KIND=JPRB)   , POINTER ::  GCVEZ
REAL(KIND=JPRB)    , POINTER ::  VVN
REAL(KIND=JPRB) , POINTER ::  GWDCCO
REAL(KIND=JPRB) , POINTER ::  RHCEXPDX
REAL(KIND=JPRB) , POINTER ::  RACCEF
REAL(KIND=JPRB) , POINTER ::  VZ0CM
REAL(KIND=JPRB) , POINTER ::  ECTMAX
REAL(KIND=JPRB) , POINTER ::  RNINTS
REAL(KIND=JPRB) , POINTER ::  EDC
REAL(KIND=JPRB)    , POINTER ::  FENTRT
REAL(KIND=JPRB) , POINTER ::  C_EPSILON
REAL (KIND=JPRB) , POINTER :: GCVBEE,GCVEEX
REAL (KIND=JPRB) , POINTER :: GDDBETA,GDDDP,GDDFXM,GDDWPF,GDDEVF
REAL(KIND=JPRB) , POINTER   :: GREMIN,GREMAX,GCHI0,GFSURF
REAL(KIND=JPRB)  , POINTER  :: GFRIC,GUDDD,GSIGA,GNHDSMOW,GDEPTH,GALTAU,GKEDDRE,GNHACC
REAL(KIND=JPRB) , POINTER   :: GSINHD,GSINHR
REAL(KIND=JPRB) , POINTER  :: GCVFNER,GCVFNEO,GCVFNEP1,GCVFNEP2,GRBCC
REAL(KIND=JPRB) , POINTER  :: GRSO,GRTH,GRFCS
REAL(KIND=JPRB) , POINTER  :: GTOPDEPTH
REAL(KIND=JPRB) , POINTER :: GCVALBU, GCVENDY1 ,GCVENDY2 ,GCVENDYMX,GCVIDPBAS,&
                           & GCVKSKV, GCVTAUSIG
REAL(KIND=JPRB) , POINTER :: GCVCATAU, GCATHRCAP, GCATHRMOC, GCATHRCND, GCAOMCND
REAL(KIND=JPRB) , POINTER ::  GTRGDPMIX,GTRGDPHIMN,GTRGPUSLMN,GTRGKCK9,&
                            & GTRGAIN ,GTRTHRS ,GTRTHCK ,GTRBRC,&
                            & GTRKGAIN,GTRKTHRS,GTRKTHCK
REAL(KIND=JPRB) , POINTER :: GDDALBU ,GDDENDYMX,GDDFP(:),GDDFRAC, GDDFREVS,&
                           & GDDINHOM ,GDDTAUSIG
REAL(KIND=JPRB) , POINTER :: QXRCDIL
LOGICAL , POINTER ::  LCAPCIN
LOGICAL , POINTER ::  LCORSEDIM
REAL(KIND=JPRB) :: ZDELTA
INTEGER(KIND=JPIM) :: JLEV

#include "namphy0.nam.h"

! ------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUPHY0',0,ZHOOK_HANDLE)

ASSOCIATE(YDGEM => YDGEOMETRY%YRGEM, YDSTA=>YDGEOMETRY%YRSTA)

ASSOCIATE(TEQK=>YDML_PHY_MF%YRPHY0%TEQK, ETKE_KA3=>YDML_PHY_MF%YRPHY0%ETKE_KA3, &
 & ETKE_CTHETA=>YDML_PHY_MF%YRPHY0%ETKE_CTHETA, TEQH=>YDML_PHY_MF%YRPHY0%TEQH, REFB_1=>YDML_PHY_MF%YRPHY0%REFB_1, &
 & ETKE_KA2=>YDML_PHY_MF%YRPHY0%ETKE_KA2, XWSALM=>YDML_PHY_MF%YRPHY0%XWSALM, EPS=>YDML_PHY_MF%YRPHY0%EPS, &
 & ETKE_R=>YDML_PHY_MF%YRPHY0%ETKE_R, ETKE_KA1=>YDML_PHY_MF%YRPHY0%ETKE_KA1, EFB_AZ0=>YDML_PHY_MF%YRPHY0%EFB_AZ0, &
 & ETKE_LAM4=>YDML_PHY_MF%YRPHY0%ETKE_LAM4, REFB_2=>YDML_PHY_MF%YRPHY0%REFB_2, REFB_3=>YDML_PHY_MF%YRPHY0%REFB_3, &
 & ETKE_LAM1=>YDML_PHY_MF%YRPHY0%ETKE_LAM1, ETKE_RIFC=>YDML_PHY_MF%YRPHY0%ETKE_RIFC, &
 & ETKE_LAM3=>YDML_PHY_MF%YRPHY0%ETKE_LAM3, ETKE_LAM2=>YDML_PHY_MF%YRPHY0%ETKE_LAM2, &
 & TEQC=>YDML_PHY_MF%YRPHY0%TEQC, EFB_UR=>YDML_PHY_MF%YRPHY0%EFB_UR, &
 & RDELXN=>YDGEM%RDELXN, LHUCN=>YDML_PHY_MF%YRPHY%LHUCN, &
 & RLOUIS_S0=>YDML_PHY_MF%YRLOUIS%RLOUIS_S0, &
 & LSMOOTHA=>YDML_PHY_MF%YRSIMPHL%LSMOOTHA, LSMOOTHD=>YDML_PHY_MF%YRSIMPHL%LSMOOTHD, &
 & LSIMPH=>YDML_PHY_MF%YRSIMPHL%LSIMPH, &
 & LNEBNXR=>YDML_PHY_MF%YRPHY%LNEBNXR, LNEBCO=>YDML_PHY_MF%YRPHY%LNEBCO, L3MT=>YDML_PHY_MF%YRPHY%L3MT, &
 & LNEBR=>YDML_PHY_MF%YRPHY%LNEBR, LMPHYS=>YDML_PHY_MF%YRPHY%LMPHYS, LNEBGR=>YDML_PHY_MF%YRPHY%LNEBGR, &
 & LPROCLD=>YDML_PHY_MF%YRPHY%LPROCLD, LCONDWT=>YDML_PHY_MF%YRPHY%LCONDWT, LCVRAV3=>YDML_PHY_MF%YRPHY%LCVRAV3, &
 & LCVLIS=>YDML_PHY_MF%YRPHY%LCVLIS, LCVCAS=>YDML_PHY_MF%YRPHY%LCVCAS, LCOEFKTKE=>YDML_PHY_MF%YRPHY%LCOEFKTKE, &
 & LECT=>YDML_PHY_MF%YRPHY%LECT, CGTURS=>YDML_PHY_MF%YRPHY%CGTURS, LCVRA=>YDML_PHY_MF%YRPHY%LCVRA, &
 & YDPHY0=>YDML_PHY_MF%YRPHY0)
GFRAE => YDPHY0%GFRAE
RKFBNBX => YDPHY0%RKFBNBX
RNEBCX => YDPHY0%RNEBCX
ETKE_ALPH0 => YDPHY0%ETKE_ALPH0
XMINLM => YDPHY0%XMINLM
REFLRHC => YDPHY0%REFLRHC
RCIN => YDPHY0%RCIN
RNINTS => YDPHY0%RNINTS
GCVPSI => YDPHY0%GCVPSI
RNINTR => YDPHY0%RNINTR
GPEFDC => YDPHY0%GPEFDC
ARSB2 => YDPHY0%ARSB2
AGRE2 => YDPHY0%AGRE2
VKARMN => YDPHY0%VKARMN
ETKE_KLM => YDPHY0%ETKE_KLM
GUDDD => YDPHY0%GUDDD
QXRDEL => YDPHY0%QXRDEL
ADJTAU => YDPHY0%ADJTAU
A0ML_BT => YDPHY0%A0ML_BT
A0ML_BU => YDPHY0%A0ML_BU
GCVFRR => YDPHY0%GCVFRR
QXRAL => YDPHY0%QXRAL
ENT_LAMBDA => YDPHY0%ENT_LAMBDA
GCCSV => YDPHY0%GCCSV
ARSCH => YDPHY0%ARSCH
ETKE_BETA_EPS => YDPHY0%ETKE_BETA_EPS
VVX => YDPHY0%VVX
TENTRD => YDPHY0%TENTRD
USURIDE => YDPHY0%USURIDE
RMULACVG => YDPHY0%RMULACVG
XBLM => YDPHY0%XBLM
VVN => YDPHY0%VVN
BEDIFV => YDPHY0%BEDIFV
TKEMULT => YDPHY0%TKEMULT
TENTRVL => YDPHY0%TENTRVL
TENTRX => YDPHY0%TENTRX
GCVGAMMA => YDPHY0%GCVGAMMA
LKESC => YDPHY0%LKESC
RCVEVAP => YDPHY0%RCVEVAP
ETKE_GAMMA_EPS => YDPHY0%ETKE_GAMMA_EPS
GWDBC => YDPHY0%GWDBC
ETKE_ENTRX => YDPHY0%ETKE_ENTRX
RCOFLM => YDPHY0%RCOFLM
GCVOMGS => YDPHY0%GCVOMGS
GDDWPF => YDPHY0%GDDWPF
GCVNU => YDPHY0%GCVNU
EDC => YDPHY0%EDC
GNHDTAT => YDPHY0%GNHDTAT
EVAP => YDPHY0%EVAP
ADOE => YDPHY0%ADOE
GFSURF => YDPHY0%GFSURF
GCVENTRX => YDPHY0%GCVENTRX
GRCVPP => YDPHY0%GRCVPP
RHCRIT2 => YDPHY0%RHCRIT2
FQLIC => YDPHY0%FQLIC
GPETAU => YDPHY0%GPETAU
GRHCMOD => YDPHY0%GRHCMOD
UCWSTAR => YDPHY0%UCWSTAR
AGRE1 => YDPHY0%AGRE1
GREDDI => YDPHY0%GREDDI
GREDDL => YDPHY0%GREDDL
GREDDR => YDPHY0%GREDDR
GREDDS => YDPHY0%GREDDS
GPBLHRA => YDPHY0%GPBLHRA
GWDAMP => YDPHY0%GWDAMP
RNLCURV => YDPHY0%RNLCURV
RHCRIT1 => YDPHY0%RHCRIT1
TYM => YDPHY0%TYM
TUDGP => YDPHY0%TUDGP
REFLCAPE => YDPHY0%REFLCAPE
EDD => YDPHY0%EDD
TUDFR => YDPHY0%TUDFR
TDDFR => YDPHY0%TDDFR
HUCRED => YDPHY0%HUCRED
HUCREDRA => YDPHY0%HUCREDRA
RQICRSN => YDPHY0%RQICRSN
GCVRE => YDPHY0%GCVRE
FEVAPC => YDPHY0%FEVAPC
GSINHD => YDPHY0%GSINHD
GCLOEA => YDPHY0%GCLOEA
GCVTAUREM => YDPHY0%GCVTAUREM
RFRAC_ENTR_X => YDPHY0%RFRAC_ENTR_X
TFVR => YDPHY0%TFVR
SCLESPR => YDPHY0%SCLESPR
GSDAMAX => YDPHY0%GSDAMAX
TRENTRV => YDPHY0%TRENTRV
NCVGMAX => YDPHY0%NCVGMAX
TFVS => YDPHY0%TFVS
TCTC => YDPHY0%TCTC
GCVBEE => YDPHY0%GCVBEE
LADVLIM => YDPHY0%LADVLIM
ALMAVX => YDPHY0%ALMAVX
RACCEF => YDPHY0%RACCEF
GCVALMX => YDPHY0%GCVALMX
GRTH => YDPHY0%GRTH
GCVADET => YDPHY0%GCVADET
VCHRNK => YDPHY0%VCHRNK
XWSBLM => YDPHY0%XWSBLM
GCVADS => YDPHY0%GCVADS
TDDBU => YDPHY0%TDDBU
UTILGUST => YDPHY0%UTILGUST
AGREF => YDPHY0%AGREF
GALMIN => YDPHY0%GALMIN
RAUTEFS => YDPHY0%RAUTEFS
RAUTSBET => YDPHY0%RAUTSBET
RQICRMIN => YDPHY0%RQICRMIN
RSMDNEBX => YDPHY0%RSMDNEBX
AHCLPV => YDPHY0%AHCLPV
FONT => YDPHY0%FONT
ALMAVE => YDPHY0%ALMAVE
GFRIC => YDPHY0%GFRIC
SCO => YDPHY0%SCO
RWBF1 => YDPHY0%RWBF1
ETKE_RIFC_MAF => YDPHY0%ETKE_RIFC_MAF
GSIGA => YDPHY0%GSIGA
ALPHAT => YDPHY0%ALPHAT
LCVNHD => YDPHY0%LCVNHD
LCVRESDYN => YDPHY0%LCVRESDYN
LCVDS => YDPHY0%LCVDS
TCW => YDPHY0%TCW
TCT => YDPHY0%TCT
ETKE_TALPH => YDPHY0%ETKE_TALPH
REFLKUO => YDPHY0%REFLKUO
GPEIPHI => YDPHY0%GPEIPHI
GCVACHI => YDPHY0%GCVACHI
GCVCINC => YDPHY0%GCVCINC
REVAPN => YDPHY0%REVAPN
NCVSIG => YDPHY0%NCVSIG
ETACUT => YDPHY0%ETACUT
ALPHAE => YDPHY0%ALPHAE
GCVWEXC => YDPHY0%GCVWEXC
RSMDTX => YDPHY0%RSMDTX
RRAUTCS => YDPHY0%RRAUTCS
GWDPROF => YDPHY0%GWDPROF
TCA => YDPHY0%TCA
HUTIL2 => YDPHY0%HUTIL2
GCISMIN => YDPHY0%GCISMIN
RAUTEFR => YDPHY0%RAUTEFR
HUTIL1 => YDPHY0%HUTIL1
NSMTPA => YDPHY0%NSMTPA
LGDDD => YDPHY0%LGDDD
LGVVEX => YDPHY0%LGVVEX
LCVEOD => YDPHY0%LCVEOD
LGPRONI1 => YDPHY0%LGPRONI1
NPRONI => YDPHY0%NPRONI
GPRONI => YDPHY0%GPRONI
C3TKEFREE => YDPHY0%C3TKEFREE
GWDCD => YDPHY0%GWDCD
GCVMLT => YDPHY0%GCVMLT
GREMIN => YDPHY0%GREMIN
FSPRAIN => YDPHY0%FSPRAIN
GWDVALI => YDPHY0%GWDVALI
GCVEEX => YDPHY0%GCVEEX
QXRHX => YDPHY0%QXRHX
USHEARM => YDPHY0%USHEARM
RDPHIC => YDPHY0%RDPHIC
RQICVMIN => YDPHY0%RQICVMIN
RQCRNS => YDPHY0%RQCRNS
GRFCS => YDPHY0%GRFCS
C_EPSILON => YDPHY0%C_EPSILON
QSSC => YDPHY0%QSSC
QSMODC => YDPHY0%QSMODC
ALMAV => YDPHY0%ALMAV
ETKE_CG01 => YDPHY0%ETKE_CG01
RQICRT1 => YDPHY0%RQICRT1
RQICRT2 => YDPHY0%RQICRT2
RQICVMAX => YDPHY0%RQICVMAX
HUCOE => YDPHY0%HUCOE
GAEPS => YDPHY0%GAEPS
RAGGEF => YDPHY0%RAGGEF
USDMLT => YDPHY0%USDMLT
RDECRD => YDPHY0%RDECRD
RDECRD1 => YDPHY0%RDECRD1
RDECRD2 => YDPHY0%RDECRD2
RDECRD3 => YDPHY0%RDECRD3
RDECRD4 => YDPHY0%RDECRD4
RDECRDRED => YDPHY0%RDECRDRED
UHDIFV => YDPHY0%UHDIFV
GRBCC => YDPHY0%GRBCC
GKEDDRE => YDPHY0%GKEDDRE
EFFCOLL => YDPHY0%EFFCOLL
SENSL => YDPHY0%SENSL
GWDSE => YDPHY0%GWDSE
ETKE_GAMD => YDPHY0%ETKE_GAMD
LCVMICC => YDPHY0%LCVMICC
HOBST => YDPHY0%HOBST
GAMAP1 => YDPHY0%GAMAP1
ETKE_OLAM => YDPHY0%ETKE_OLAM
GENVSRH => YDPHY0%GENVSRH
LCVTADV => YDPHY0%LCVTADV
RTCAPE => YDPHY0%RTCAPE
QXRTGH => YDPHY0%QXRTGH
RLMLH1 => YDPHY0%RLMLH1
RFACNSM => YDPHY0%RFACNSM
ECTMIN => YDPHY0%ECTMIN
GSDAMIN => YDPHY0%GSDAMIN
AKN => YDPHY0%AKN
RQICRMAX => YDPHY0%RQICRMAX
RICRLM => YDPHY0%RICRLM
RWBF2 => YDPHY0%RWBF2
GNHDSMOS => YDPHY0%GNHDSMOS
GRRMINA => YDPHY0%GRRMINA
ECTMAX => YDPHY0%ECTMAX
GSDMAX => YDPHY0%GSDMAX
RGELSFON => YDPHY0%RGELSFON
QSSUSC => YDPHY0%QSSUSC
QSMIN => YDPHY0%QSMIN
RPHIR => YDPHY0%RPHIR
ETKE_ENTRN => YDPHY0%ETKE_ENTRN
GSDMIN => YDPHY0%GSDMIN
GTDCL => YDPHY0%GTDCL
GNHDSMOT => YDPHY0%GNHDSMOT
GCVHMIN => YDPHY0%GCVHMIN
GCVORGED => YDPHY0%GCVORGED
RSPCRR => YDPHY0%RSPCRR
GWDCCO => YDPHY0%GWDCCO
RFLCHCE => YDPHY0%RFLCHCE
QSSUSS => YDPHY0%QSSUSS
GDDSDE => YDPHY0%GDDSDE
QSSUSV => YDPHY0%QSSUSV
GDDDP => YDPHY0%GDDDP
GDDFXM => YDPHY0%GDDFXM
LCVFEVV => YDPHY0%LCVFEVV
AJBUMIN => YDPHY0%AJBUMIN
GCVFNER => YDPHY0%GCVFNER
TVF => YDPHY0%TVF
XNBMAX => YDPHY0%XNBMAX
GCVBETA => YDPHY0%GCVBETA
WMXOV => YDPHY0%WMXOV
RPHI0 => YDPHY0%RPHI0
NWEIGHT => YDPHY0%NWEIGHT
NCATAU => YDPHY0%NCATAU
GALP => YDPHY0%GALP
RDTFAC => YDPHY0%RDTFAC
GCVFNEP2 => YDPHY0%GCVFNEP2
VZ0CM => YDPHY0%VZ0CM
ECMNP => YDPHY0%ECMNP
ETKE_TAULM => YDPHY0%ETKE_TAULM
ETKE_C0SHEAR => YDPHY0%ETKE_C0SHEAR
ETKE_R1SIM => YDPHY0%ETKE_R1SIM
ETKE_R2SIM => YDPHY0%ETKE_R2SIM
ETKE_GB08A => YDPHY0%ETKE_GB08A
ETKE_GB08B => YDPHY0%ETKE_GB08B
ETKE_MIN => YDPHY0%ETKE_MIN
ETKE_CRIT => YDPHY0%ETKE_CRIT
ETKE_DELTA => YDPHY0%ETKE_DELTA
GSHELL => YDPHY0%GSHELL
FNEBC => YDPHY0%FNEBC
RPRTH => YDPHY0%RPRTH
VZIUSTAR0 => YDPHY0%VZIUSTAR0
GCVTAUDE => YDPHY0%GCVTAUDE
RETAMIN => YDPHY0%RETAMIN
NAJITER => YDPHY0%NAJITER
AGRERICR => YDPHY0%AGRERICR
GCVFNEO => YDPHY0%GCVFNEO
ALFX => YDPHY0%ALFX
ALFX_LR => YDPHY0%ALFX_LR
ALFX_HR => YDPHY0%ALFX_HR
GCVRESN => YDPHY0%GCVRESN
GCVRESX => YDPHY0%GCVRESX
GMIRH => YDPHY0%GMIRH
GCVGAX => YDPHY0%GCVGAX
GCVGAW => YDPHY0%GCVGAW
EDB => YDPHY0%EDB
QSUSXS => YDPHY0%QSUSXS
AJ1PEPS => YDPHY0%AJ1PEPS
ETKE_CG03 => YDPHY0%ETKE_CG03
GCVPSIE => YDPHY0%GCVPSIE
QXRAL_ADJ => YDPHY0%QXRAL_ADJ
EDK => YDPHY0%EDK
ALD => YDPHY0%ALD
ETKE_CG02 => YDPHY0%ETKE_CG02
TUDBU => YDPHY0%TUDBU
QXRR => YDPHY0%QXRR
QSUSXC => YDPHY0%QSUSXC
GCVOMGE => YDPHY0%GCVOMGE
USURICE => YDPHY0%USURICE
TVFC => YDPHY0%TVFC
GCVFEVV => YDPHY0%GCVFEVV
USURICL => YDPHY0%USURICL
RKFBTAU => YDPHY0%RKFBTAU
ETKE_LAM0 => YDPHY0%ETKE_LAM0
UPRETMIN => YDPHY0%UPRETMIN
ACBRPHIM => YDPHY0%ACBRPHIM
LCVCONTAU => YDPHY0%LCVCONTAU
RFRAC_ENTR_N => YDPHY0%RFRAC_ENTR_N
GCVTURB => YDPHY0%GCVTURB
GCVTRMIN => YDPHY0%GCVTRMIN
GCVTSMO => YDPHY0%GCVTSMO
QSNEBC => YDPHY0%QSNEBC
GCVTEXC => YDPHY0%GCVTEXC
GDDBETA => YDPHY0%GDDBETA
GMUKEDD => YDPHY0%GMUKEDD
REVGSL => YDPHY0%REVGSL
UPRETMAX => YDPHY0%UPRETMAX
GWDLT => YDPHY0%GWDLT
THPCMT => YDPHY0%THPCMT
RNEGAT => YDPHY0%RNEGAT
GDEPTH => YDPHY0%GDEPTH
RKDN => YDPHY0%RKDN
RKDX => YDPHY0%RKDX
SNNBCO => YDPHY0%SNNBCO
QSNEBS => YDPHY0%QSNEBS
GCVFNEP1 => YDPHY0%GCVFNEP1
REVASX => YDPHY0%REVASX
TDDGP => YDPHY0%TDDGP
GCVOMGQ => YDPHY0%GCVOMGQ
GCVOMDPS => YDPHY0%GCVOMDPS
GCVOMGSX => YDPHY0%GCVOMGSX
GCVRHMIN => YDPHY0%GCVRHMIN
GCVRHMAX => YDPHY0%GCVRHMAX
GCVOMCA => YDPHY0%GCVOMCA
GCVOMCC => YDPHY0%GCVOMCC

RSMOOTHMELT => YDPHY0%RSMOOTHMELT
GTOPDEPTH => YDPHY0%GTOPDEPTH
TFVL => YDPHY0%TFVL
GNHDSMOW => YDPHY0%GNHDSMOW
GDDEVF => YDPHY0%GDDEVF
GCVALFA => YDPHY0%GCVALFA
GDDEVA => YDPHY0%GDDEVA
GALMAX => YDPHY0%GALMAX
NCVCLOS => YDPHY0%NCVCLOS
GSINHR => YDPHY0%GSINHR
ARSC1 => YDPHY0%ARSC1
GEVAVF => YDPHY0%GEVAVF
GCVENTRN => YDPHY0%GCVENTRN
GCHI0 => YDPHY0%GCHI0
NCVENTR => YDPHY0%NCVENTR
RHCEXPDX => YDPHY0%RHCEXPDX
AJ1MEPS => YDPHY0%AJ1MEPS
GCVEZ => YDPHY0%GCVEZ
SPNBCO => YDPHY0%SPNBCO
AECLS4 => YDPHY0%AECLS4
AERCS1 => YDPHY0%AERCS1
AERCS3 => YDPHY0%AERCS3
AERCS5 => YDPHY0%AERCS5
STTBMIN => YDPHY0%STTBMIN
AECLS3 => YDPHY0%AECLS3
NSMTPB => YDPHY0%NSMTPB
GCVPNH => YDPHY0%GCVPNH
XMAXLM => YDPHY0%XMAXLM
XKLM => YDPHY0%XKLM
GPBLHK0 => YDPHY0%GPBLHK0
UDECT => YDPHY0%UDECT
ARSCQ => YDPHY0%ARSCQ
FENTRT => YDPHY0%FENTRT
GNHACC => YDPHY0%GNHACC
GALTAU => YDPHY0%GALTAU
GEXPKD => YDPHY0%GEXPKD
ADISE => YDPHY0%ADISE
A0ML_AU => YDPHY0%A0ML_AU
A0ML_AT => YDPHY0%A0ML_AT
NCAPEMAX => YDPHY0%NCAPEMAX
ADISI => YDPHY0%ADISI
LCVNAUV => YDPHY0%LCVNAUV
LCVUVM => YDPHY0%LCVUVM
TURB => YDPHY0%TURB
TFVI => YDPHY0%TFVI
LCVIMPT => YDPHY0%LCVIMPT
ECMNPI => YDPHY0%ECMNPI
RICRET => YDPHY0%RICRET
TENTR => YDPHY0%TENTR
GNHDEV => YDPHY0%GNHDEV
GREMAX => YDPHY0%GREMAX
LSBUO => YDPHY0%LSBUO
RQLCV => YDPHY0%RQLCV
GNHDTAU => YDPHY0%GNHDTAU
SXNBCO => YDPHY0%SXNBCO
SCLESPS => YDPHY0%SCLESPS
RQLCR => YDPHY0%RQLCR
GRSO => YDPHY0%GRSO
GCVENTR_MIN => YDPHY0%GCVENTR_MIN
USUPRC => YDPHY0%USUPRC
RRSCALE => YDPHY0%RRSCALE
RRIMEF => YDPHY0%RRIMEF
RRGAMMA => YDPHY0%RRGAMMA
HUTIL => YDPHY0%HUTIL
GCLOEB => YDPHY0%GCLOEB
USURIC => YDPHY0%USURIC
USURID => YDPHY0%USURID
NPCLO1 => YDPHY0%NPCLO1
NPCLO2 => YDPHY0%NPCLO2
NUPTKE => YDPHY0%NUPTKE
GCVIMPT => YDPHY0%GCVIMPT
NCVQLI => YDPHY0%NCVQLI
GCVUV => YDPHY0%GCVUV
GCHECKMV_TMIN => YDPHY0%GCHECKMV_TMIN
GCHECKMV_TMAX => YDPHY0%GCHECKMV_TMAX
GCHECKMV_QVMIN => YDPHY0%GCHECKMV_QVMIN
GCHECKMV_QVMAX => YDPHY0%GCHECKMV_QVMAX
GCVALBU => YDPHY0%GCVALBU 
GCVENDY1  => YDPHY0%GCVENDY1  
GCVENDY2  => YDPHY0%GCVENDY2  
GCVENDYMX => YDPHY0%GCVENDYMX 
GCVIDPBAS => YDPHY0%GCVIDPBAS 
GCVKSKV => YDPHY0%GCVKSKV 
GCVTAUSIG => YDPHY0%GCVTAUSIG 
GCVCATAU => YDPHY0%GCVCATAU 
GCATHRCAP => YDPHY0%GCATHRCAP 
GCATHRMOC => YDPHY0%GCATHRMOC 
GCATHRCND => YDPHY0%GCATHRCND 
GCAOMCND => YDPHY0%GCAOMCND 
GTRGDPMIX => YDPHY0%GTRGDPMIX 
GTRGDPHIMN => YDPHY0%GTRGDPHIMN 
GTRGPUSLMN => YDPHY0%GTRGPUSLMN 
GTRGKCK9 => YDPHY0%GTRGKCK9 
GTRGAIN  => YDPHY0%GTRGAIN  
GTRTHRS  => YDPHY0%GTRTHRS  
GTRTHCK  => YDPHY0%GTRTHCK  
GTRBRC => YDPHY0%GTRBRC 
GTRKGAIN => YDPHY0%GTRKGAIN 
GTRKTHRS => YDPHY0%GTRKTHRS 
GTRKTHCK => YDPHY0%GTRKTHCK 
GDDALBU  => YDPHY0%GDDALBU  
GDDENDYMX => YDPHY0%GDDENDYMX 
GDDFP => YDPHY0%GDDFP 
GDDFRAC => YDPHY0%GDDFRAC 
GDDFREVS => YDPHY0%GDDFREVS 
GDDINHOM  => YDPHY0%GDDINHOM  
GDDTAUSIG => YDPHY0%GDDTAUSIG 
QXRCDIL => YDPHY0%QXRCDIL 
LCAPCIN => YDPHY0%LCAPCIN
LCORSEDIM => YDPHY0%LCORSEDIM
! ------------------------------------------------------------------------

!*       1.    Set default values.
!              -------------------

!        1.1 Set implicit default values

A0ML_AU=4.5_JPRB
A0ML_AT=5.0_JPRB
A0ML_BU=3.0_JPRB
A0ML_BT=0.8_JPRB
AERCS1=0.2726_JPRB
AERCS3=-0.4239_JPRB
AERCS5=0.3595_JPRB
ALMAV=300._JPRB
BEDIFV=0.05_JPRB
ECMNP=3000._JPRB
EDB=5._JPRB
EDC=5._JPRB
EDD=5._JPRB
EDK=1.0_JPRB
EFB_AZ0=0.2_JPRB
EFB_UR=0.4545_JPRB
ETACUT=1.0_JPRB
EVAP=4.8E+06_JPRB
FONT=2.4E+04_JPRB
GALP=0.53_JPRB
GCISMIN=6.7E-05_JPRB
GEVAVF=6.7E-05_JPRB
GCCSV=0._JPRB
GCVADS=0.8_JPRB
GCVALFA=4.5E-05_JPRB
GCVBETA=0.2_JPRB
GCVIMPT=0.0_JPRB
GCVMLT=0.00016_JPRB
GCVNU=2.5E-05_JPRB
GCVPSI=0.5_JPRB
GCVPSIE=0.0_JPRB
GDDEVA=0.25_JPRB
GDDSDE=0.5_JPRB
GPBLHK0=0.25_JPRB
GPBLHRA=4._JPRB
GRCVPP=1._JPRB
GWDAMP=0.6_JPRB
GWDBC=2._JPRB
GWDCCO=1._JPRB
GWDCD=6._JPRB
GWDLT=0._JPRB
GWDSE=3.5E-03_JPRB
GWDPROF=1._JPRB
GWDVALI=0._JPRB
HOBST=3._JPRB
HUCOE=2._JPRB
HUTIL=1.8_JPRB
HUTIL1=-0.6_JPRB
HUTIL2=1.1_JPRB
NPCLO1=1
NPCLO2=1
QSSC=1600._JPRB
QSMODC=1._JPRB
QSMIN=1.E-4_JPRB
QSNEBC=26000._JPRB
QSNEBS=0.7_JPRB
QSSUSC=1._JPRB
QSSUSS=0.25_JPRB
QSSUSV=0._JPRB
QSUSXC=3.3E-05_JPRB
QSUSXS=3.3E-05_JPRB
RDECRD=2.E+04_JPRB
RDECRD1=1.E+04_JPRB
RDECRD2=2.E+04_JPRB
RDECRD3=0.30_JPRB
RDECRD4=0.45_JPRB
RDECRDRED=1._JPRB
RGELSFON=0.0125_JPRB
REVAPN=1._JPRB
RPHI0=0._JPRB
RPHIR=1750._JPRB
QXRAL=130._JPRB
QXRAL_ADJ=130._JPRB
QXRCDIL=0.5_JPRB
QXRDEL=0._JPRB
QXRHX=1._JPRB
QXRR=0.5_JPRB
QXRTGH=3.5_JPRB
RCIN=0._JPRB
RCVEVAP=0._JPRB
REVGSL=80._JPRB
REFB_1=9.0_JPRB
REFB_2=5.0_JPRB
REFB_3=-11.0_JPRB
RFLCHCE=0._JPRB
RTCAPE=10800._JPRB
SCO=-20._JPRB
SENSL=1._JPRB
SNNBCO=0._JPRB
SPNBCO=3000._JPRB
SXNBCO=0.5_JPRB
TCA=1._JPRB
TCT=1.E-4_JPRB
TCW=8.E-4_JPRB
TENTR=2.5E-06_JPRB
TENTRX=8.E-05_JPRB
TDDGP=0.8_JPRB
TUDGP=0.8_JPRB
TURB=1._JPRB
TVF=1._JPRB
TYM(1)=0.92_JPRB
TYM(2)=0.74_JPRB
TYM(3)=16.6_JPRB
TYM(4)=10.1_JPRB
TYM(5)=0.08_JPRB
UHDIFV=8.E-04_JPRB
USDMLT=1.25E+04_JPRB
USUPRC=0.0_JPRB
USURIC=1.0_JPRB
USURID=0.035_JPRB
USURIDE=1.0_JPRB
USURICE=0.5_JPRB
USURICL=4._JPRB
UTILGUST=0.125_JPRB
VCHRNK=0.021_JPRB
VKARMN=0.4_JPRB
VZ0CM=1.5E-04_JPRB
VZIUSTAR0=0._JPRB
XNBMAX=1._JPRB
AHCLPV=1000._JPRB
RICRLM=0.5_JPRB
RRGAMMA=0.8_JPRB
RRSCALE=1.15E-4_JPRB
XBLM=6.5_JPRB
XKLM=1.0_JPRB
XMAXLM=3000._JPRB
XMINLM=500._JPRB
XWSALM=0.1_JPRB
XWSBLM=7.0_JPRB
RNEGAT = -7.E-05_JPRB
RNLCURV = 7.E+04_JPRB
WMXOV=1.0_JPRB

!     - - - - - - - - - - - - - -
!     The convective scheme :
!     - - - - - - - - - - - - - -
TRENTRV=1._JPRB
TENTRVL=-1.0_JPRB
GCVGAMMA=20._JPRB
LKESC=.FALSE.

IF ( LCONDWT.AND.LPROCLD ) THEN
  RDTFAC=0.5_JPRB
ELSE
  RDTFAC=1.0_JPRB
ENDIF

!        - - - - - - - - - -
!        Lopez Microphysics :
!        - - - - - - - - - -
RAUTEFR=1.E-03_JPRB
RRAUTCS=1.0_JPRB
RAUTEFS=1.E-03_JPRB
RAUTSBET=0.025_JPRB
RNINTR=8.E+06_JPRB
RNINTS=2.E+06_JPRB
RQLCR=2.E-04_JPRB
RSPCRR=0.0_JPRB
RQICRMAX=0.3E-04_JPRB
RQICRMIN=0.2E-06_JPRB
RQLCV=2.E-04_JPRB
RQICVMAX=0.3E-04_JPRB
RQICVMIN=0.2E-06_JPRB
RQICRT1=-80._JPRB
RQICRT2=30._JPRB
RQICRSN=0.5_JPRB
RQCRNS=0.03_JPRB
RACCEF=1._JPRB
RAGGEF=0.2_JPRB
RRIMEF=1._JPRB
REVASX=0.0_JPRB
RHCRIT1=0.5_JPRB
RHCRIT2=0.91_JPRB
RETAMIN=0.4_JPRB
RFACNSM=1.4_JPRB
TFVL=0.0_JPRB
TFVI=0.0_JPRB
TFVR=5.0_JPRB
TFVS=0.6_JPRB
GRHCMOD=0.3_JPRB
RHCEXPDX=0.3_JPRB


!--------------------------
! PIL MICROPHYSICS
!--------------------------
ADJTAU=900._JPRB
RDPHIC=10000._JPRB
RWBF1=300._JPRB
RWBF2=4._JPRB
SCLESPR=248000._JPRB
SCLESPS=15500._JPRB
HUCRED=1.0_JPRB
HUCREDRA=0.0_JPRB
FSPRAIN=13.4_JPRB
EFFCOLL=6.7E-02_JPRB
RSMDNEBX=0.2_JPRB
RSMDTX=1.0_JPRB
NSMTPA=2
NSMTPB=3
!--------------------------
! Prognostic convection physical parameters
!--------------------------
TUDBU=0.5_JPRB
TDDBU=0.5_JPRB
TUDFR=0.0012_JPRB
TDDFR=0.0006_JPRB
GCVALMX=0.95_JPRB
RMULACVG=25._JPRB
GCVACHI=1.E9_JPRB
GCVBEE=0._JPRB
GCVEEX=1._JPRB
GCVTAUDE=900._JPRB
ECMNPI=3000._JPRB
GPEIPHI=0._JPRB
GENVSRH=0._JPRB
IF (ROMEGA /= 0.0_JPRB) THEN
GPETAU=1._JPRB/ROMEGA
ELSE
GPETAU=0._JPRB
ENDIF
GPEFDC=1._JPRB
GRRMINA=1.E-5_JPRB
GDDBETA=2.0_JPRB
GDDDP=10000._JPRB
GDDFXM=1.E+5_JPRB
GDDEVF=0.5_JPRB
GDDWPF=0._JPRB
TENTRD=1.E-4_JPRB
!----------------------------
! Non saturated downdraft
!----------------------------
GDDALBU=1._JPIM
GDDFRAC=0.33_JPIM
GDDENDYMX=1.E-4_JPRB
GDDFP(1)=4.398E-2_JPRB
GDDFP(2)=0.75_JPRB
GDDFP(3)=0._JPRB
GDDTAUSIG=0._JPRB
GDDFREVS=0.5_JPRB
GDDINHOM=2.0_JPRB
!---------------------------------------------------
! Complementary subgrid updraft scheme (Alaro-1)
!---------------------------------------------------
! accsu:
GCVALBU=0.9_JPRB
GCVENDY1=1.E-8_JPRB
GCVENDY2=5.E-5_JPRB
GCVENDYMX=1.E-4_JPRB
GCVIDPBAS=3.E-3_JPRB
GCVTAUSIG=-1._JPRB
GCVKSKV=3._JPRB
! CA for accsu:
GCVCATAU=1000._JPRB
GCATHRCAP=200._JPRB
GCATHRMOC=-1._JPRB
GCATHRCND=-1._JPRB
GCAOMCND=1._JPRB
! Triggering:
GTRGKCK9=0.4_JPRB
GTRGDPMIX=6000._JPRB ! 60hPa
GTRGDPHIMN=29340._JPRB ! 3km if LCVSHCU=T
GTRGPUSLMN=30000._JPRB ! 300 hPa above the surface
GTRGAIN=2._JPRB
GTRTHRS=0.15_JPRB
GTRTHCK=5.E4_JPRB
GTRBRC=0.5_JPRB
GTRKGAIN=100._JPRB
GTRKTHRS=0.02_JPRB
GTRKTHCK=2000._JPRB

!-------------------------------------------------
! PCMT convection scheme parameters.
!-------------------------------------------------
LGDDD=.FALSE.
LCVNHD=.FALSE.
LCVRESDYN=.FALSE.
LCVDS=.FALSE.
LCVMICC=.FALSE.
GMUKEDD=0._JPRB
GNHDTAT=0.1_JPRB
GNHDSMOS=900._JPRB
GNHDSMOT=0.22_JPRB
GNHDEV=0._JPRB
GNHDTAU=0._JPRB
LCVEOD=.FALSE.
LGPRONI1=.FALSE.
NPRONI=0
GPRONI=1._JPRB
LGVVEX=.FALSE.
NCVENTR=1
NCVSIG=1
NCVCLOS=1
NCVQLI=1
GCVENTRN=1.2E-4_JPRB
GCVENTRX=6.0E-4_JPRB
GCVENTR_MIN=0._JPRB
THPCMT=-1._JPRB
GAEPS=1._JPRB
GCVEZ=1._JPRB
GCVTRMIN=10000._JPRB
LCVFEVV=.FALSE.
GCVFEVV=0._JPRB
GCVTEXC=0._JPRB
GCVWEXC=0._JPRB
GFSURF=0._JPRB
LCVNAUV=.TRUE.
GCVFRR=1._JPRB
GCVPNH=0._JPRB
GCVORGED=0._JPRB
GCVTAUREM=0._JPRB
GCLOEA=1._JPRB
GCLOEB=0._JPRB
GFRAE=0._JPRB
GCVADET=0._JPRB
GCVCINC=0.0_JPRB
GSDMIN=1.0E-3_JPRB
GCHI0=1._JPRB
GSDMAX=1.3E-3_JPRB
GALMIN=0.011_JPRB
GALMAX=0.030_JPRB
GSDAMIN=6.0E-4_JPRB
GSDAMAX=2.1E-3_JPRB
GEXPKD=2.0_JPRB
GREMIN=0.01_JPRB
GREMAX=1.0_JPRB
GSHELL=0._JPRB
GCVFNER=0._JPRB
GCVFNEO=-5.0_JPRB
GCVFNEP1=30000._JPRB
GCVFNEP2=10000._JPRB
GRBCC=1.0_JPRB
GREDDI=1.0_JPRB
GREDDL=1.0_JPRB
GREDDR=1.0_JPRB
GREDDS=1.0_JPRB
GCVUV=1.0_JPRB
GCHECKMV_TMIN=-200._JPRB
GCHECKMV_TMAX=+200._JPRB
GCHECKMV_QVMIN=-0.1_JPRB
GCHECKMV_QVMAX=+0.2_JPRB
GCVRE=1._JPRB
LSBUO=.FALSE.
LCVTADV=.FALSE.
GRSO=100.0_JPRB
GRTH=1.0_JPRB
GRFCS=1.0_JPRB
GFRIC=4.2E-3_JPRB
GUDDD=0.25_JPRB
GSIGA=0.90_JPRB
GNHDSMOW=1800._JPRB
GSINHD=1800._JPRB
GSINHR=0._JPRB
GDEPTH=800._JPRB
GALTAU=1.9E-5_JPRB
GKEDDRE=6.98E-4_JPRB
GNHACC=0._JPRB
GTDCL=1._JPRB
LCVCONTAU=.TRUE.
LCVIMPT=.TRUE.
LADVLIM=.TRUE.
LCVUVM=.FALSE.
ADOE=1.0_JPRB
RFRAC_ENTR_N=1.E-5_JPRB
RFRAC_ENTR_X=1.1E-3_JPRB
GCVTURB=5.0E-5_JPRB
RNEBCX=1._JPRB
GCVTSMO=0.5_JPRB
RKDX=300.E-06_JPRB
LCAPCIN=.FALSE.
LCORSEDIM=.FALSE.

!--------------------
! Minimal depth of convection in ACNPART for TOP
!--------------------
GTOPDEPTH=4000._JPRB

!--------------------
! For CA-scheme
!--------------------
NWEIGHT=1.0_JPRB
NCATAU=1000._JPRB
NCAPEMAX=0._JPRB
NCVGMAX=1.E-6_JPRB

!     - - - - - - - -
!     For TKE scheme :
!     - - - - - - - -
ADISE=-0.5_JPRB
ADISI=1.5_JPRB
AECLS3=3.75_JPRB
AECLS4=0.3_JPRB
AKN=0.126_JPRB
ALD=1.18_JPRB
ALPHAE=2.7_JPRB
ALPHAT=1.13_JPRB
ECTMIN=1.E-6_JPRB
ECTMAX=100._JPRB

UCWSTAR=1.0_JPRB/3._JPRB
UDECT=5._JPRB
USHEARM=1.E-04_JPRB
UPRETMIN=60000._JPRB
UPRETMAX=97500._JPRB
ARSCH=4._JPRB
ARSCQ=1.2_JPRB
ARSC1=2.0_JPRB/(3._JPRB*ARSCH*ARSCQ)
ARSB2=3._JPRB*ARSCH*ARSC1/2.0_JPRB
ACBRPHIM=2.2_JPRB
ALMAVE=10._JPRB
ALMAVX=1000._JPRB
RICRET=0.195_JPRB
GCVHMIN=0.0_JPRB
GCVOMGE=0.0_JPRB
GCVOMGQ=0.0_JPRB
GCVOMGS=0.0_JPRB
GCVOMDPS=2000.0_JPRB
GCVOMGSX=0.5_JPRB
GCVRHMIN=0.5_JPRB
GCVRHMAX=1.0_JPRB
GCVOMCA=-1.918_JPRB
GCVOMCC=1.35_JPRB

!     ---------------------------
!     For KFB CVPP d'AROME
!     ---------------------------
RKFBTAU=0._JPRB
RKFBNBX=0.3_JPRB

STTBMIN=SQRT(3._JPRB)
! A minimum value for the adimentional jump in boyancy : d(Theta)/Theta
AJBUMIN=0.005_JPRB
! The "Master Length" is equal to "RCOFLM*Z_PBL"
RCOFLM=0.085_JPRB

!     - - - - - - - - - - - - - - - -
!     For dry conv. adjustment scheme :
!     - - - - - - - - - - - - - - - -
AJ1MEPS=0.99_JPRB
AJ1PEPS=10.0_JPRB
NAJITER=30

!     - - - - - - - - - - - - - - - - - - - - - - -
!     For Grenier (2000) top-PBL entrainment scheme :
!     - - - - - - - - - - - - - - - - - - - - - - -
AGRE1=0.16_JPRB
AGRE2=100._JPRB
AGREF=1._JPRB
AGRERICR=50._JPRB

! Pseudo prognostic TKE scheme
NUPTKE=0.52_JPRB
! tuning par for TKE-related mixing length
TKEMULT=1.0_JPRB
! TOUCANS scheme
C_EPSILON =0.871_JPRB
ETKE_CTHETA =1.0_JPRB
ETKE_RIFC_MAF =0.5_JPRB
ETKE_RIFC =0.186_JPRB
ETKE_R    =0.367_JPRB
ETKE_LAM1 =0.107_JPRB
ETKE_LAM2 =0.00032_JPRB
ETKE_LAM3 =0.0864_JPRB
ETKE_LAM4 =0.1_JPRB
ETKE_OLAM =2.0_JPRB/3.0_JPRB
ETKE_LAM0 =2.0_JPRB/3.0_JPRB
!  RV, RESTT and RCPD to be used from from YOMCST
!ENT_LAMBDA=(3545._JPRB+RV*LOG(100000._JPRB/RESTT))/RCPD
ENT_LAMBDA=5.87_JPRB
ETKE_CG01 =1.0_JPRB
ETKE_CG02 =1.0_JPRB
ETKE_CG03 =1.0_JPRB
ETKE_BETA_EPS =0.02_JPRB
ETKE_GAMMA_EPS =3E-2_JPRB
ETKE_GAMD =2.0_JPRB
ETKE_TALPH =200.0_JPRB
ETKE_ALPH0 =100.0_JPRB
ETKE_ENTRX=1E-3_JPRB
ETKE_ENTRN=1E-4_JPRB
ETKE_KLM=1.0_JPRB
ETKE_TAULM=1.0_JPRB
ETKE_C0SHEAR=0.5_JPRB
ETKE_R1SIM=0.0_JPRB
ETKE_R2SIM=0.2_JPRB
ETKE_GB08A=0.537_JPRB
ETKE_GB08B=0.2685_JPRB
ETKE_MIN=1.0E-08_JPRB
ETKE_CRIT=1.0E-07_JPRB
ETKE_DELTA=0._JPRB
C3TKEFREE =1.184_JPRB

!     - - - - - - - - - - - - -
!     For ACCVIMPGY and PCMT :
!     - - - - - - - - - - - - -
ALFX=10.E-02_JPRB
ALFX_LR=0.04_JPRB
ALFX_HR=0.15_JPRB
GCVRESN=7.44E-6_JPRB
GCVRESX=6.00E-5_JPRB
GMIRH=0.98_JPRB
GCVGAW=0.7_JPRB
GCVGAX=0._JPRB
TCTC=5.0E-04_JPRB
TVFC=1._JPRB
GAMAP1=1.5_JPRB
RKDN=30.E-06_JPRB
VVN=-2.0_JPRB
VVX=-38.0_JPRB
FENTRT=2.5_JPRB
FQLIC=1.0_JPRB
FNEBC=7.0_JPRB
FEVAPC=4.0_JPRB

!     For the "Lenderink & Holtslag" mixing Length : (ACNEBR)
RLMLH1  = 0.4_JPRB

RPRTH   = 0.0_JPRB

! Smoothing of melting of snow in advprcs.F90

RSMOOTHMELT=0.6

! REFL.. for convection scheme.
REFLKUO=17558._JPRB
REFLCAPE=89558._JPRB
REFLRHC=150000._JPRB

!        1.2 Modify default values according to LECMWF

IF (LECMWF) THEN
ELSE
ENDIF

!     ------------------------------------------------------------------

!*       2.    Modify default values.
!              ----------------------

CALL POSNAM(NULNAM,'NAMPHY0')
READ(NULNAM,NAMPHY0)


IF(.NOT.(LNEBCO.AND.(LNEBR.OR.LNEBGR.OR.LECT)) .AND.LCVRAV3) THEN
  WRITE(UNIT=KULOUT,FMT='(A)') ' '
  WRITE(UNIT=KULOUT,FMT='(A)') ' !'
  WRITE(UNIT=KULOUT,FMT='(A)') ' ! TENTRVL is set to 0. in SUPHY0  !!'
  WRITE(UNIT=KULOUT,FMT='(A)') ' !'
  WRITE(UNIT=KULOUT,FMT='(A)') ' '
  TENTRVL = 0.0_JPRB
ENDIF

! Computation of constants for TOUCANS scheme (Alaro physics)

ITTYPE=0
IF(LCOEFKTKE) THEN
  IF     (TRIM(CGTURS) == 'RMC') THEN
    ITTYPE=1
  ELSEIF (TRIM(CGTURS) == 'MD1') THEN
    ITTYPE=2
  ELSEIF (TRIM(CGTURS) == 'MD2') THEN
    ITTYPE=3
  ELSEIF (TRIM(CGTURS) == 'QNSE') THEN
    ITTYPE=4
  ELSEIF (TRIM(CGTURS) == 'EFB') THEN
    ITTYPE=5
  ELSEIF (TRIM(CGTURS) == 'LOUIS') THEN
    ITTYPE=6
  ELSE
    CLERR='SUPHY0: UNEXPECTED VALUE FOR CGTURS: '//TRIM(CGTURS)
    CALL ABOR1(CLERR)
  ENDIF
ENDIF

ZNUPTKE4=NUPTKE**4
ZSM0=ZNUPTKE4/2._JPRB
ZLAMF_X=SQRT(375.0_JPRB*C3TKEFREE**2*(C3TKEFREE**2+2._JPRB*C3TKEFREE+1._JPRB)*ZSM0**2&
  & -20.0_JPRB*(C3TKEFREE**2+C3TKEFREE-1._JPRB)*ZSM0+1.0_JPRB)
ZLAMBDA=SQRT(5.0_JPRB)*3.0_JPRB/4.0_JPRB*ZLAMF_X-30.0_JPRB*C3TKEFREE&
  & *(C3TKEFREE+1._JPRB)*ZSM0+0.25_JPRB
ZSF=(10.0_JPRB-75.0_JPRB*C3TKEFREE*(C3TKEFREE+1._JPRB)*ZSM0)/(8.0_JPRB*ZLAMBDA)

ETKE_LAM1=4.0_JPRB/15.0_JPRB*ZLAMBDA
ETKE_LAM3=(14.0_JPRB*ZLAMBDA*ZSF+5.0_JPRB*ZLAMBDA)/75.0_JPRB
ETKE_LAM2=(5.0_JPRB*ZLAMBDA-6.0_JPRB*ZLAMBDA*ZSF)/25.0_JPRB

IF(ITTYPE==1) THEN
  !RMC01
  ETKE_R=1.0_JPRB
  ETKE_LAM4=0.0_JPRB
  ETKE_RIFC=0.544_JPRB
ELSEIF (ITTYPE==2) THEN
  ! Model I
  ETKE_R=1.0_JPRB-2.0_JPRB*ZLAMBDA*(44.0_JPRB*ZSF**2+160.0_JPRB*ZSF-25.0_JPRB)/375.0_JPRB
  ETKE_LAM4=0.0_JPRB
  ETKE_RIFC=(15.0_JPRB*ZSM0*C3TKEFREE**2*(C3TKEFREE+1.0_JPRB))&
  & /(6.0_JPRB*ETKE_OLAM+2.0_JPRB*C3TKEFREE)
ELSEIF ((ITTYPE==3).OR.(ITTYPE==4)) THEN
  ! Model II or QNSE
  ETKE_R=-4.0_JPRB*C3TKEFREE/75.0_JPRB*&
    &(88.0_JPRB*ZLAMBDA*ZSF**2+320.0_JPRB*ZLAMBDA*ZSF-50.0_JPRB*ZLAMBDA-375.0_JPRB)/&
    &(8.0_JPRB*ZLAMBDA*C3TKEFREE*ZSF+10.0_JPRB*ZLAMBDA*C3TKEFREE+20.0_JPRB&
    & *C3TKEFREE+15.0_JPRB)
  ETKE_LAM4=ZLAMBDA/4.0_JPRB
  ETKE_RIFC=(30_JPRB*C3TKEFREE**3*ZSM0)/&
  &(12.0_JPRB*ETKE_OLAM+(-60.0_JPRB*C3TKEFREE**2*ETKE_LAM3-20.0_JPRB*C3TKEFREE**2&
  &*ETKE_LAM2+4.0_JPRB*C3TKEFREE)*ETKE_LAM4-15.0_JPRB*C3TKEFREE**2*ETKE_LAM1&
  & +4.0_JPRB*C3TKEFREE)
ELSEIF (ITTYPE==5) THEN
  !EFB
  ETKE_R=EFB_UR
  ETKE_LAM4=0.0_JPRB
  ETKE_RIFC=0.25_JPRB
ELSEIF (ITTYPE==6) THEN
  !LOUIS
  ETKE_R=RLOUIS_S0
  ETKE_LAM4=0.0_JPRB
  ETKE_RIFC=0.91_JPRB
ENDIF

IF ((ITTYPE==1.OR.ITTYPE==2.OR.ITTYPE==3).AND.ETKE_R<ETKE_RIFC) THEN
  CLERR='SUPHY0: ETKE_R must be greater than ETKE_RIFC.&
  & Modify NUPTKE, ETKE_OLAM, C3TKEFREE'
  CALL ABOR1(CLERR)
ENDIF

ETKE_CTHETA=C_EPSILON*C3TKEFREE/ETKE_OLAM

ETKE_KA1 = ZLAMBDA/2.0_JPRB
ETKE_KA2 = ETKE_OLAM/(2.0_JPRB*C3TKEFREE)
ETKE_KA3 = 1.0_JPRB

! Constant TEQC, TEQK, TEQH used as a threshold in the physics for inhibating convection.
TEQK=REFLKUO/RDELXN
TEQC=REFLCAPE/RDELXN
TEQH=REFLRHC/RDELXN

!     HUMIDITE CRITIQUE

ALLOCATE (YDPHY0%RHUC (YDGEOMETRY%YRDIMV%NFLEVG))

YDPHY0%REPS=1.E-12_JPRB
IF(LHUCN) THEN
  DO JLEV = 1, YDGEOMETRY%YRDIMV%NFLEVG
    YDPHY0%RHUC(JLEV)=1.0_JPRB-MAX( HUCOE*YDSTA%SVETAF(JLEV)*(1.0_JPRB-YDSTA%SVETAF(JLEV))/((&
    & 1.0_JPRB+HUTIL1*(YDSTA%SVETAF(JLEV)-0.5_JPRB))*(&
    & 1.0_JPRB+HUTIL2*(YDSTA%SVETAF(JLEV)-0.5_JPRB))),YDPHY0%REPS)
  ENDDO
ELSE
  DO JLEV = 1, YDGEOMETRY%YRDIMV%NFLEVG
    YDPHY0%RHUC(JLEV)=1.0_JPRB-MAX( HUCOE*YDSTA%SVETAF(JLEV)**NPCLO1*(&
     & 1.0_JPRB-YDSTA%SVETAF(JLEV))**NPCLO2*(&
     & 1.0_JPRB+SQRT(HUTIL)*(YDSTA%SVETAF(JLEV)-0.5_JPRB)),YDPHY0%REPS)
  ENDDO
ENDIF

!

ALLOCATE (YDPHY0%RQSMOD (YDGEOMETRY%YRDIMV%NFLEVG))

DO JLEV = 1, YDGEOMETRY%YRDIMV%NFLEVG
  ZDELTA=1._JPRB-YDSTA%SVETAF(JLEV)
  YDPHY0%RQSMOD(JLEV)=QSSUSV*(1._JPRB+(QSMODC-1._JPRB)*ZDELTA)
ENDDO

!

ALLOCATE (YDPHY0%RN1D (-22:11), YDPHY0%RRC1D (-22:11), YDPHY0%RSRC1D (-22:11))

YDPHY0%RN1D = &
(/ 0.0_JPRB            ,0.0_JPRB          ,  1.7225742E-05_JPRB,  0.275373E-04_JPRB ,&
 & 4.5657158E-05_JPRB,  0.748634E-04_JPRB ,  1.2344122E-04_JPRB,  0.203788E-03_JPRB ,&
 & 3.3539534E-04_JPRB,  0.553310E-03_JPRB ,  9.1189146E-04_JPRB,  0.150353E-02_JPRB ,&
 & 2.4784803E-03_JPRB,  0.408673E-02_JPRB ,  6.7381263E-03_JPRB,  0.111092E-01_JPRB ,&
 & 1.8315554E-02_JPRB,  0.301974E-01_JPRB ,  4.9787164E-02_JPRB,  0.831191E-01_JPRB ,&
 & 0.1512039_JPRB    ,  0.286653E+00_JPRB ,  0.5000000_JPRB    ,  0.691489E+00_JPRB ,&
 & 0.8413813_JPRB    ,  0.933222E+00_JPRB ,  0.9772662_JPRB    ,  0.993797E+00_JPRB ,&
 & 0.9986521_JPRB    ,  0.999768E+00_JPRB ,  0.9999684_JPRB    ,  0.9999997_JPRB    ,&
 & 1.0000000_JPRB    ,  1.000000_JPRB     /)

YDPHY0%RRC1D = &
(/ 0.0_JPRB          ,  0.0_JPRB          ,  1.1461278E-05_JPRB,  0.275279E-04_JPRB ,&
 & 4.3084903E-05_JPRB,  0.747532E-04_JPRB ,  1.2315845E-04_JPRB,  0.201069E-03_JPRB ,&
 & 3.3593364E-04_JPRB,  0.551618E-03_JPRB ,  9.1182487E-04_JPRB,  0.150296E-02_JPRB ,&
 & 2.4801120E-03_JPRB,  0.408695E-02_JPRB ,  6.7372285E-03_JPRB,  0.111084E-01_JPRB ,&
 & 1.8315896E-02_JPRB,  0.301974E-01_JPRB ,  4.9786866E-02_JPRB,  0.721706E-01_JPRB ,&
 & 0.1165014_JPRB    ,  0.210263E+00_JPRB ,  0.3990000_JPRB    ,  0.697847E+00_JPRB ,&
 & 1.0833505_JPRB    ,  0.152933E+01_JPRB ,  2.0084987_JPRB    ,  0.250201E+01_JPRB ,&
 & 3.0003829_JPRB    ,  0.350006E+01_JPRB ,  4.0000072_JPRB    ,  0.450000E+01_JPRB ,&
 & 5.0000000_JPRB    ,  5.500000_JPRB     /)

YDPHY0%RSRC1D = &
(/ 0.0_JPRB          ,  0.0_JPRB          ,  2.0094444E-04_JPRB,   0.316670E-03_JPRB,&
 & 4.9965648E-04_JPRB,  0.785956E-03_JPRB ,  1.2341294E-03_JPRB,   0.193327E-02_JPRB,&
 & 3.0190963E-03_JPRB,  0.470144E-02_JPRB ,  7.2950651E-03_JPRB,   0.112759E-01_JPRB,&
 & 1.7350994E-02_JPRB,  0.265640E-01_JPRB ,  4.0427860E-02_JPRB,   0.610997E-01_JPRB,&
 & 9.1578111E-02_JPRB,  0.135888E+00_JPRB ,  0.1991484_JPRB    ,   0.230756E+00_JPRB,&
 & 0.2850565_JPRB    ,  0.375050E+00_JPRB ,  0.5000000_JPRB    ,   0.691489E+00_JPRB,&
 & 0.8413813_JPRB    ,  0.933222E+00_JPRB ,  0.9772662_JPRB    ,   0.993797E+00_JPRB,&
 & 0.9986521_JPRB    ,  0.999768E+00_JPRB ,  0.9999684_JPRB    ,   0.999997E+00_JPRB,&
 & 1.0000000_JPRB    ,  1.000000_JPRB     /)


!     ------------------------------------------------------------------

!*       3.    Print final values.
!              -------------------

WRITE(UNIT=KULOUT,FMT='('' COMMON YOMPHY0 '')')
WRITE(UNIT=KULOUT,FMT='('' AERCS1 = '',E11.4,'' AERCS3 = '',E11.4&
 & ,'' AERCS5 = '',E11.4,'' ALMAV = '',E11.4,'' ECMNP = '',E11.4&
 & ,'' EDB = '',E11.4,/,'' EDC = '',E11.4,'' EDD = '',E11.4&
 & ,'' EDK = '',E11.4,'' ETACUT = '',E11.4&
 & ,'' EVAP = '',E11.4,'' FONT = '',E11.4,'' GWDAMP = '',E11.4&
 & ,'' GWDSE = '',E11.4,'' GWDBC = '',E11.4,/&
 & ,'' GWDCD = '',E11.4,/&
 & ,'' GWDPROF = '',E11.4,'' GWDVALI = '',E11.4,/&
 & ,'' HUCOE = '',E11.4,'' HUTIL = '',E11.4 ,'' HUTIL1 = '',E11.4 ,'' HUTIL2 = '',E11.4&
 & ,'' VCHRNK = '',E11.4,'' VKARMN = '',E11.4&
 & ,'' SNNBCO = '',E11.4,/,'' SPNBCO = '',E11.4&
 & ,'' SXNBCO = '',E11.4,'' HOBST = '',E11.4,'' NPCLO1 = '',I4&
 & ,'' NPCLO2 = '',I4,'' RCIN = '',E11.4,'' RCVEVAP = '',E11.4&
 & ,'' REVGSL = '',E11.4,'' RFLCHCE = '',E11.4,/&
 & ,'' RTCAPE= '',E11.4,/&
 & ,'' UHDIFV = '',E11.4,'' VZ0CM = '',E11.4,'' VZIUSTAR0 = '',E11.4&
 & ,'' XNBMAX = '',E11.4,'' GALP = '',E11.4,'' SENSL = '',E11.4&
 & ,'' TCA = '',E11.4,/,'' TCT = '',E11.4,'' TCW = '',E11.4&
 & ,'' TURB = '',E11.4,'' TVF = '',E11.4,/&
 & ,'' TYM = '',5E11.4,'' QSMIN = '',E11.4,/&
 & ,'' QSSC = '',E11.4,'' RPHI0 = '',E11.4,'' RPHIR = '',E11.4&
 & ,'' BEDIFV = '',E11.4,'' SCO = '',E11.4&
 & ,'' USDMLT = '',E11.4,/&
 & ,'' GDDEVA = '',E11.4,'' GDDSDE = '',E11.4,/&
 & ,'' GDDFREVS = '',E11.4,'' GDDINHOM = '',E11.4,'' GWDCCO = '',E11.4,/&
 & ,'' TENTR = '',E11.4,'' TENTRX = '',E11.4,'' TENTRD = '',E11.4&
 & ,'' TUDGP = '',E11.4,'' TDDGP = '',E11.4&
 & ,'' GRCVPP = '',E11.4,'' GCVIMPT= '',E11.4,'' GCVHMIN= '',E11.4,/&
 & ,'' GCVOMGE = '',E11.4,'' GCVOMGQ= '',E11.4 &
 & ,'' GCVOMGS = '',E11.4,/&
 & ,'' GCVOMDPS = '',E11.4,'' GCVOMGSX = '',E11.4 &
 & ,'' GCVRHMIN = '',E11.4,'' GCVRHMAX = '',E11.4,/&
 & ,'' GCVOMCA = '',E11.4,'' GCVOMCC = '',E11.4,/&
 & ,'' RKFBTAU = '',E11.4,'' RKFBNBX = '',E11.4 &
 & )')&
 & AERCS1,AERCS3,AERCS5,ALMAV,ECMNP,EDB,EDC,EDD,EDK,ETACUT,EVAP,FONT,&
 & GWDAMP,GWDSE,GWDBC,GWDCD,GWDPROF,GWDVALI,&
 & HUCOE,HUTIL,HUTIL1,HUTIL2,VCHRNK,VKARMN,SNNBCO,SPNBCO,SXNBCO,HOBST,&
 & NPCLO1,NPCLO2,RCIN,RCVEVAP,REVGSL,RFLCHCE,RTCAPE,&
 & UHDIFV,VZ0CM,VZIUSTAR0,XNBMAX,GALP,SENSL,TCA,TCT,TCW,&
 & TURB,TVF,TYM,QSMIN,QSSC,RPHI0,RPHIR,BEDIFV,SCO,USDMLT,&
 & GDDEVA,GDDSDE,GDDFREVS, GDDINHOM, GWDCCO,&
 & TENTR,TENTRX,TENTRD,TUDGP,TDDGP,GRCVPP,GCVIMPT,GCVHMIN,&
 & GCVOMGE,GCVOMGQ,GCVOMGS,GCVOMDPS,GCVOMGSX,&
 & GCVRHMIN,GCVRHMAX,GCVOMCA,GCVOMCC,&
 & RKFBTAU,RKFBNBX

WRITE(UNIT=KULOUT,FMT='(6(A,E16.7))')&
 & ' REFLKUO= ',REFLKUO,' TEQK= ',TEQK,&
 & ' REFLCAPE= ',REFLCAPE,' TEQC= ',TEQC,&
 & ' REFLRHC= ',REFLRHC,' TEQH= ',TEQH

WRITE(UNIT=KULOUT,FMT='('' USUPRC = '',E11.4,'' USURIC = '',E11.4&
 & ,'' QSNEBC = '',E11.4,'' QSNEBS = '',E11.4,'' QSMODC = '',E11.4&
 & ,'' QSSUSC = '',E11.4,'' QSSUSS = '',E11.4,'' QSSUSV = '',E11.4&
 & ,'' QSUSXC = '',E11.4,'' QSUSXS = '',E11.4&
 & ,'' GCCSV  = '',E11.4,/&
 & ,'' QXRAL  = '',E11.4,'' QXRAL_ADJ  = '',E11.4,'' QXRDEL = '',E11.4&
 & ,'' QXRHX  = '',E11.4,'' QXRR   = '',E11.4,'' QXRTGH = '',E11.4,/&
 & ,'' QXRCDIL= '',E11.4,/&
 & ,'' GWDLT  = '',E11.4,'' AHCLPV = '',E11.4,/&
 & ,'' GCVADS = '',E11.4,'' GCVBETA= '',E11.4&
 & ,'' RICRLM = '',E11.4,'' XBLM   = '',E11.4,'' XKLM = '',E11.4&
 & ,'' XMINLM = '',E11.4,'' XMAXLM = '',E11.4&
 & ,'' WMXOV  = '',E11.4&
 & )')&
 & USUPRC,USURIC,QSNEBC,QSNEBS,QSMODC,QSSUSC,QSSUSS,QSSUSV,QSUSXC,QSUSXS,GCCSV&
 & ,QXRAL,QXRAL_ADJ,QXRDEL,QXRHX,QXRR,QXRTGH,QXRCDIL&
 & ,GWDLT,AHCLPV,GCVADS,GCVBETA,RICRLM&
 & ,XBLM,XKLM,XMINLM,XMAXLM,WMXOV
WRITE(UNIT=KULOUT,FMT='('' XWSALM = '',E11.4,'' XWSBLM = '',E11.4&
 & ,'' GCVALFA= '',E11.4,'' GCVPSI = '',E11.4,'' GCVPSIE = '',E11.4&
 & ,'' USURICL= '',E11.4,'' USURICE= '',E11.4,/&
 & ,'' USURID= '',E11.4,'' USURIDE= '',E11.4,'' GCVNU= '',E11.4&
 & ,'' GCVMLT= '',E11.4,'' GPBLHK0= '',E11.4,'' GPBLHRA = '',E11.4&
 & ,'' UTILGUST= '',E11.4,'' RRGAMMA= '',E11.4,'' RRSCALE = '',E11.4&
 & )')&
 & XWSALM,XWSBLM,GCVALFA,GCVPSI,GCVPSIE,USURICL,USURICE,USURID,USURIDE,&
 & GCVNU,GCVMLT,GPBLHK0&
 & ,GPBLHRA,UTILGUST,RRGAMMA,RRSCALE
WRITE(UNIT=KULOUT,FMT='('' RNEGAT == '',E11.4,'' RNLCURV = '',E11.4&
 & )') RNEGAT,RNLCURV
WRITE(UNIT=KULOUT,FMT='('' RDTFAC == '',E11.4,'' TRENTRV= '',E11.4&
 &,'' TENTRVL= '',E11.4 )') RDTFAC,TRENTRV,TENTRVL
WRITE(UNIT=KULOUT,FMT='(9(5(A,E11.4),/))') 'GCISMIN=',GCISMIN,' GEVAVF=',GEVAVF
WRITE(UNIT=KULOUT,FMT='('' A0ML_AU == '',E11.4,'' A0ML_AT == '',E11.4&
 &,'' A0ML_BU == '',E11.4,'' A0ML_BT == '',E11.4 )') A0ML_AU,A0ML_AT&
 &,A0ML_BU,A0ML_BT

!     - - - - - - - -
!     For TKE scheme :
!     - - - - - - - -
WRITE(UNIT=KULOUT,FMT='('' ADISE   = '',E11.4,&
 & '' ADISI   = '',E11.4,/&
 & ,'' AECLS3  = '',E11.4,'' AECLS4  = '',E11.4,'' AKN     = '',E11.4,/&
 & ,'' ALD     = '',E11.4,'' ALPHAE  = '',E11.4,'' ALPHAT  = '',E11.4,/&
 & ,'' ECTMIN  = '',E11.4,'' ECTMAX  = '',E11.4,'' UCWSTAR = '',E11.4,/&
 & ,'' UDECT   = '',E11.4,'' USHEARM = '',E11.4,/&
 & ,'' UPRETMIN= '',E11.4,'' UPRETMAX= '',E11.4,'' ARSCH   = '',E11.4,/&
 & ,'' ARSCQ   = '',E11.4,'' ARSC1   = '',E11.4,/&
 & ,'' ARSB2   = '',E11.4,'' STTBMIN = '',E11.4,/&
 & ,'' ACBRPHIM= '',E11.4,'' ALMAVE  = '',E11.4,'' ALMAVX  = '',E11.4,/&
 & ,'' RICRET  = '',E11.4,/&
 & ,'' AJBUMIN = '',E11.4,'' RCOFLM  = '',E11.4&
 & )')&
 & ADISE,ADISI,AECLS3,AECLS4,AKN,ALD,ALPHAE,ALPHAT,ECTMIN,ECTMAX,UCWSTAR,UDECT,&
 & USHEARM,UPRETMIN,UPRETMAX,ARSCH,ARSCQ,ARSC1,ARSB2,STTBMIN,&
 &ACBRPHIM,ALMAVE,ALMAVX,RICRET,AJBUMIN,RCOFLM

!       - - - - - - - - - -
!       Lopez Microphysics :
!       - - - - - - - - - -
WRITE(UNIT=KULOUT,FMT='('' - - - - - - - - - - - '')')
WRITE(UNIT=KULOUT,FMT='(''  Microphysics scheme  '')')
WRITE(UNIT=KULOUT,FMT='('' - - - - - - - - - - - '')')
WRITE(UNIT=KULOUT,FMT='( '' RAUTEFR = '',E11.4&
 &,'' RRAUTCS = '',E11.4,/&
 &,'' RAUTEFS = '',E11.4,'' RAUTSBET= '',E11.4,/&
 &,'' RNINTR  = '',E11.4,'' RNINTS  = '',E11.4,/&
 &,'' RQLCR   = '',E11.4,'' RQCRNS  = '',E11.4,/&
 &,'' RQICRMIN= '',E11.4,'' RQICRMAX= '',E11.4,/&
 &,'' RQLCV   = '',E11.4,'' RSPCRR  = '',E11.4,/&
 &,'' RQICVMIN= '',E11.4,'' RQICVMAX= '',E11.4,/&
 &,'' RQICRT1 = '',E11.4,'' RQICRT2 = '',E11.4,/&
 &,'' RQICRSN = '',E11.4,'' RACCEF  = '',E11.4,/&
 &,'' RAGGEF  = '',E11.4,'' RRIMEF  = '',E11.4,/&
 &,'' RHCRIT1 = '',E11.4,'' RHCRIT2 = '',E11.4,/&
 &,'' RETAMIN = '',E11.4,'' RFACNSM = '',E11.4,/&
 &,'' TFVL    = '',E11.4,'' TFVI    = '',E11.4,/&
 &,'' TFVR    = '',E11.4,'' TFVS    = '',E11.4,/&
 &,'' GRHCMOD = '',E11.4,'' REVASX  = '',E11.4,/&
 &,'' RHCEXPDX= '',E11.4,/&
 &)')&
 &RAUTEFR,RRAUTCS,RAUTEFS,RAUTSBET,RNINTR,RNINTS,RQLCR,RQCRNS,RQICRMIN,RQICRMAX,&
 &RQLCV,RSPCRR,RQICVMIN,RQICVMAX,RQICRT1,RQICRT2,RQICRSN,RACCEF,RAGGEF,RRIMEF,&
 &RHCRIT1,RHCRIT2,RETAMIN,RFACNSM,TFVL,TFVI,TFVR,TFVS,GRHCMOD,REVASX,RHCEXPDX

!     - - - - - - - - - - -
!     For Grenier scheme :
!     - - - - - - - - - - -
WRITE(UNIT=KULOUT,FMT='('' AGRE1   = '',E11.4,&
 & '' AGRE2   = '',E11.4,'' AGREF   = '',E11.4,&
 & '' AGRERICR= '',E11.4,'' RPRTH   = '',E11.4&
 & )')&
 & AGRE1,    AGRE2,   AGREF, AGRERICR, RPRTH

!     - - - - - - - - - - - - - - - -
!     For dry conv. adjustment scheme :                                -
!     - - - - - - - - - - - - - - - -
WRITE(UNIT=KULOUT,FMT='(&
 & '' AJ1PEPS = '',E11.4,'' AJ1MEPS = '',E11.4,'' NAJITER = '',I3,8X&
 & )')&
 & AJ1PEPS, AJ1MEPS, NAJITER

!     - - - - - - - - - - - - -
!     For ACCVIMPGY and PCMT :
!     - - - - - - - - - - - - -
WRITE(UNIT=KULOUT,FMT='( '' ALFX    = '',E11.4&
 &,'' TCTC    = '',E11.4,'' TVFC    = '',F11.6,/&
 &,'' GAMAP1  = '',F11.6,'' RKDN    = '',E11.4,'' RKDX    = '',E11.4,/&
 &,'' VVN     = '',F11.6,'' VVX     = '',F11.6,/&
 &,'' FENTRT  = '',F11.6&
 &,'' FQLIC   = '',F11.6,'' FNEBC   = '',F11.6,/&
 &,'' FEVAPC  = '',F11.6)')&
 & ALFX, TCTC, TVFC, GAMAP1, RKDN, RKDX, VVN, VVX, FENTRT, FQLIC, FNEBC, FEVAPC
WRITE(UNIT=KULOUT,FMT='(100(A,G16.7))') 'ALFX_LR=',ALFX_LR,' ALFX_HR=',ALFX_HR,&
& ' GCVRESN=',GCVRESN,' GCVRESX=',GCVRESX

WRITE(UNIT=KULOUT,FMT='(100(A,E11.4))') 'GCVGAW=',GCVGAW,' GCVGAX=',GCVGAX, &
  & ' GMIRH=',GMIRH
!     - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!     For the "Lenderink & Holtslag" mixing Length : (ACNEBR)
!     - - - - - - - - - - - - - - - - - - - - - - - - - - - -
WRITE(UNIT=KULOUT,FMT='('' RLMLH1  = '',E10.4)') RLMLH1

WRITE(UNIT=KULOUT,FMT='(''  Alaro TOUCANS/pTKE scheme '')')
WRITE(UNIT=KULOUT,FMT='( '' NUPTKE = '',E11.4&
 & ,'' TKEMULT = '',E11.4,'' C_EPSILON = '',E11.4,'' ETKE_RIFC = '',E11.4&
 & ,'' ETKE_LAM2 = '',E11.4,'' ETKE_LAM3 = '',E11.4,'' C3TKEFREE = '',E11.4,&
 & '' ETKE_R = '',E11.4,'' ETKE_LAM4 = '',E11.4 ,'' ETKE_OLAM = '',E11.4,&
 & '' ETKE_LAM0 = '',E11.4,'' ETKE_LAM1 = '',E11.4,&
 & '' ETKE_CTHETA = '',E11.4,'' ETKE_KA1 = '',E11.4,'' ETKE_KA2 = '',E11.4,&
 & '' ETKE_ETKE_KA3 = '',E11.4,'' ETKE_CG01 = '',E11.4,'' ETKE_CG02 = '',E11.4,&
 & '' ETKE_CG03='',E11.4,'' ETKE_BETA_EPS='',E11.4,'' ETKE_GAMMA_EPS = '',E11.4,&
 & '' ENT_LAMBDA = '',E11.4, '' ETKE_RIFC_MAF = '',E11.4,&
 & '' ETKE_GAMD = '',E11.4, ''  ETKE_TALPH = '',E11.4,'' ETKE_ALPH0 = '',E11.4,&
 & '' ETKE_ENTRX = '',E11.4,'' ETKE_ENTRN = '',E11.4,'' ETKE_KLM = '',E11.4,&
 & '' ETKE_TAULM = '',E11.4,'' ETKE_C0SHEAR = '',E11.4,&
 & '' ETKE_R1SIM = '',E11.4, '' ETKE_R2SIM = '',E11.4,&
 & '' ETKE_GB08A = '',E11.4, '' ETKE_GB08B = '',E11.4,&
 & '' ETKE_MIN = '',E11.4,'' ETKE_CRIT = '',E11.4,'' ETKE_DELTA = '',E11.4)')&
 & NUPTKE, TKEMULT, C_EPSILON, ETKE_RIFC, ETKE_LAM2, ETKE_LAM3, C3TKEFREE,&
 & ETKE_R,ETKE_LAM4,ETKE_OLAM,ETKE_LAM0,ETKE_LAM1,ETKE_CTHETA,ETKE_KA1,&
 & ETKE_KA2,ETKE_KA3, ETKE_CG01, ETKE_CG02,ETKE_CG03,ETKE_BETA_EPS,&
 & ETKE_GAMMA_EPS,ENT_LAMBDA,ETKE_RIFC_MAF,ETKE_GAMD,&
 & ETKE_TALPH,ETKE_ALPH0,ETKE_ENTRX,ETKE_ENTRN,ETKE_KLM,ETKE_TAULM,&
 & ETKE_C0SHEAR,ETKE_R1SIM,ETKE_R2SIM,ETKE_GB08A,ETKE_GB08B,&
 & ETKE_MIN,ETKE_CRIT,ETKE_DELTA

WRITE(UNIT=KULOUT,FMT='(''  Alaro TOUCANS/EFB constants '')')
WRITE(UNIT=KULOUT,FMT='( ''EFB_AZ0  = '',E11.4,&
 &'' EFB_UR = '',E11.4,'' REFB_1 = '',E11.4,'' REFB_2 = '',E11.4,&
 &'' REFB_3 = '',E11.4)')&
 & EFB_AZ0,EFB_UR,REFB_1,REFB_2,REFB_3
WRITE(UNIT=KULOUT,FMT='(''  Intermediate TOUCANS/pTKE constants '')')
WRITE(UNIT=KULOUT,FMT='( ''LAMBDA  = '',E11.4,&
 &'' F = '',E11.4,'' lambda_8 = '',E11.4,'' Q = '',E11.4,'' SM0 = '',E11.4,&
 &'' C_K = '',E11.4, '' C_H = '',E11.4, '' A/kappa = '',E11.4)')&
 &ZLAMBDA,ZSF**2,ETKE_OLAM/C3TKEFREE,&
 &1.0_JPRB-3.0_JPRB*ETKE_LAM3+ETKE_LAM2,&
 & ZSM0,ZNUPTKE4/C_EPSILON,ZNUPTKE4/C_EPSILON*C3TKEFREE,NUPTKE**3*C_EPSILON

WRITE(KULOUT,'(/'' PIL MICROPHYSICS : '')')
WRITE(UNIT=KULOUT,FMT='('' RDPHIC = '',F8.2&
 &,'' RWBF1 = '',F6.2,'' RWBF2 = '',F6.2,/&
 &,'' SCLESPR = '',F10.1,'' SCLESPS = '',F10.1,'' HUCRED = '',F5.2&
 &,'' HUCREDRA = '',F5.2,'' FSPRAIN = '',F9.3,'' EFFCOLL = '',F10.5&
 &,'' REVAPN = '',F5.3,'' ADJTAU = '',F6.1, '' RSMDNEBX = '',F5.2&
 &,'' RSMDTX = '',F5.2, '' RDECRD = '',F8.1, '' RDECRD1 = '',F8.1&
 &,'' RDECRD2 = '',F8.1, '' RDECRD3 = '',F6.4, '' RDECRD4 = '',F6.4&
 &,'' RDECRDRED = '',F6.4, '' RGELSFON = '',F10.6&
 &,'' NSMTPA = '',I2&
 &,'' NSMTPB = '',I2&
 &)')&
 &RDPHIC,RWBF1,RWBF2,SCLESPR,SCLESPS,HUCRED,HUCREDRA,FSPRAIN,&
 &EFFCOLL,REVAPN,ADJTAU,RSMDNEBX,RSMDTX,RDECRD,RDECRD1,&
 &RDECRD2,RDECRD3,RDECRD4,RDECRDRED,RGELSFON,NSMTPA,NSMTPB

WRITE(KULOUT,'(/'' PROGNOSTIC CONVECTION '')')
WRITE(KULOUT,&
 &'('' TUDBU='',E16.6,'' TUDFR='',E16.6,'' TDDBU='',E16.6&
 &,'' TDDFR='',E16.6,''RMULACVG= '',E16.6&
 &,'' GCVALMX='',G10.4,'' GCVACHI='',E16.6&
 &,'' GCVEEX ='',G10.4,'' GCVTAUDE='',G10.4&
 &,'' GCVBEE ='',G10.4&
 &,'' ECMNPI ='',G10.4,/&
 &,'' GPEIPHI ='',G10.4&
 &,'' GPETAU ='',G10.4&
 &,'' GENVSRH ='',G10.4&
 &,'' GPEFDC ='',G10.4&
 &)')&
 &TUDBU,TUDFR,TDDBU,TDDFR,RMULACVG,GCVALMX,GCVACHI,&
 &GCVEEX,GCVTAUDE,GCVBEE,ECMNPI,&
 &  GPEIPHI, GPETAU, GENVSRH, GPEFDC

WRITE(KULOUT,'(''GCVALBU = '',G9.3,'' GCVIDPBAS = '',G9.3,&
& '' GCVENDY1 = '',G9.3,'' GCVENDY2 = '',G9.3,&
& '' GCVENDYMX = '',G9.3,'' GCVKSKV = '',G9.3,'' GCVTAUSIG = '',G9.3)')&
& GCVALBU,GCVIDPBAS,GCVENDY1,GCVENDY2, GCVENDYMX,&
& GCVKSKV,GCVTAUSIG
WRITE(KULOUT,'(''GCVCATAU = '',G9.3,'' GCATHRCAP = '',G9.3,&
& '' GCATHRMOC = '',G9.3,'' GCATHRCND = '',G9.3,'' GCAOMCND = '',G9.3)')&
& GCVCATAU,GCATHRCAP,GCATHRMOC,GCATHRCND,GCAOMCND

WRITE(KULOUT,'(''GTRGDPMIX = '',G9.3,'' GTRGDPHIMN = '',G9.3,&
& '' GTRGPUSLMN = '',G9.3,'' GTRGKCK9 = '',G9.3,'' GTRBRC = '',G9.3,&
& '' GTRGAIN = '',G9.3,'' GTRTHRS = '',G9.3,'' GTRTHCK = '',G9.3,&
& '' GTRKGAIN = '',G9.3,'' GTRKTHRS = '',G9.3,'' GTRKTHCK = '',G9.3&
& )')&
& GTRGDPMIX,GTRGDPHIMN,GTRGPUSLMN,GTRGKCK9,GTRBRC,&
& GTRGAIN,GTRTHRS,GTRTHCK,GTRKGAIN,GTRKTHRS,GTRKTHCK

WRITE(KULOUT,&
 &'('' GDDEVF='',G10.4,'' GDDWPF='',G10.4,'' GDDBETA='',G10.4,&
 &'' GDDDP='',G10.4,'' GDDFXM='',G10.4)')&
 & GDDEVF, GDDWPF, GDDBETA, GDDDP, GDDFXM

WRITE(KULOUT,'(''GDDALBU = '',G9.3,'' GDDFRAC= '',G9.3,&
& '' GDDENDYMX ='',G9.3,'' GDDTAUSIG = '',G9.3,'' GDDFP='',3(1X,G9.3))')&
& GDDALBU,GDDFRAC,GDDENDYMX, GDDTAUSIG, GDDFP

WRITE(KULOUT,'('' GRRMINA ='',G10.4)') GRRMINA
WRITE(KULOUT,FMT=*) ' LGDDD=',LGDDD,'LGVVEX',LGVVEX&
 &, ' NCVENTR=',NCVENTR,' LCVFEVV=',LCVFEVV,' LCVCONTAU=',LCVCONTAU,' LCVIMPT=',LCVIMPT
WRITE(KULOUT,FMT='(9(A,G10.4))') ' GCVENTRN=',&
& GCVENTRN,' GCVENTRX=',GCVENTRX,' GCVENTR_MIN=',GCVENTR_MIN
WRITE(KULOUT,FMT='(19(A,G10.4))') ' ADOE=',ADOE,' RFRAC_ENTR_N=',RFRAC_ENTR_N&
 &,' RFRAC_ENTR_X=',RFRAC_ENTR_X,' THPCMT=',THPCMT,' GAEPS=',GAEPS,&
 &' GCVEZ=',GCVEZ,' GCVTRMIN=',GCVTRMIN,' GCVTSMO=',GCVTSMO&
 &,' GCVFEVV=',GCVFEVV,' GCVTEXC=',GCVTEXC,' GCVFRR=',GCVFRR,' GCVPNH=',&
 & GCVPNH,' GCVORGED=',GCVORGED
WRITE(KULOUT,FMT='(18(A,G10.4))') 'GCVTAUREM=',GCVTAUREM,' GCLOEA=',&
& GCLOEA,' GCLOEB=',GCLOEB&
& ,' GFRAE=',GFRAE,' GCVADET=',GCVADET,' GCVWEXC=',GCVWEXC,' GSDMIN=',GSDMIN&
& ,' GSDMAX=',GSDMAX,' GALMIN=',GALMIN,' GALMAX=',GALMAX,' GSDAMIN=',GSDAMIN&
 &,' GSDAMAX=',GSDAMAX,' GEXPKD=',GEXPKD

WRITE(KULOUT,FMT='(18(A,G10.4))') ' GNHDSMOS=',GNHDSMOS,' GNHDEV=',GNHDEV&
 &,' GNHDTAT=',GNHDTAT,' GNHDSMOT=',GNHDSMOT&
 &,' GMUKEDD=',GMUKEDD,' GNHDTAU=',GNHDTAU,' GCVCINC=',GCVCINC,' RNEBCX=',RNEBCX

WRITE(KULOUT,FMT='(18(A,G10.4))')&
  & 'GREMIN=',GREMIN,' GREMAX=',GREMAX,' GCHI0=',GCHI0,' GFSURF=',&
  & GFSURF,' GSHELL=',GSHELL&
  & ,' GFRIC=',GFRIC,' GUDDD=',GUDDD,' GSIGA=',GSIGA,' GNHDSMOW=',&
  & GNHDSMOW,' GDEPTH=',GDEPTH&
  & ,' GALTAU=',GALTAU,' GKEDDRE=',GKEDDRE,' GNHACC=',GNHACC,&
  & ' GTDCL=',GTDCL,' GSINHD=',GSINHD,' GSINHR=',GSINHR

WRITE(KULOUT,FMT='(20(A,G16.7))') &
  & 'GCVFNER=',GCVFNER,' GCVFNEO=',GCVFNEO,' GCVFNEP1=',GCVFNEP1,' GRBCC=',GRBCC&
  & ,' GCVFNEP2=',GCVFNEP2,' GRSO=',GRSO,' GRTH=',GRTH,' GRFCS=',GRFCS&
  & ,' GCVRE=',GCVRE,' GCVUV=',GCVUV,' GCHECKMV_TMIN=',GCHECKMV_TMIN&
  & ,' GCHECKMV_TMAX=',GCHECKMV_TMAX,' GCHECKMV_QVMIN=',GCHECKMV_QVMIN&
  & ,' GCHECKMV_QVMAX=',GCHECKMV_QVMAX,' GREDDI=',GREDDI,' GREDDL=',GREDDL&
  & ,' GREDDR=',GREDDR,' GREDDS=',GREDDS


WRITE(KULOUT,FMT='(18(A,G16.7))') &
  & ' GCVGAMMA=',GCVGAMMA

WRITE(KULOUT,FMT=*) 'LCVNAUV=',LCVNAUV,' LCVEOD=',LCVEOD,' LADVLIM=',&
& LADVLIM,' NCVCLOS=',NCVCLOS&
& ,' NCVSIG=',NCVSIG,' LCVUVM=',LCVUVM,' LCVNHD=',LCVNHD,&
& ' LCVMICC=',LCVMICC,' LSBUO=',LSBUO,' LCVTADV=',LCVTADV,&
  & ' NCVQLI=',NCVQLI,' LGPRONI1=',LGPRONI1,' NPRONI=',NPRONI, &
  & ' GPRONI=',GPRONI,' LCVRESDYN=',LCVRESDYN,' LCVDS=',LCVDS,' LCAPCIN=',LCAPCIN, &
& ' LCORSEDIM=',LCORSEDIM,' LKESC=',LKESC
WRITE(KULOUT,'(''GTOPDETH'',G16.7)') GTOPDEPTH
!     ------------------------------------------------------------------

!*       4.    Check consistency between logical and real namelist inputs.
!              -------------------

IF (LMPHYS) THEN

  IF(LCVRA.AND.((TUDGP /= 0.0_JPRB.OR.TDDGP /= 0.0_JPRB).AND..NOT.LCVCAS)) THEN
    WRITE(UNIT=KULOUT,FMT='(A)')&
     & 'INCONSISTENCY BETWEEN TUDGP, TDDGP AND LCVCAS!...'
    CALL ABOR1('TUDP<>0. OR TDDGP<>0. IMPLIES LCVCAS=T!...')
  ENDIF

  IF(.NOT.LCVLIS.AND.GCVPSI /= 0.0_JPRB) THEN
    WRITE(UNIT=KULOUT,FMT='(A)') 'INCONSISTENCY BETWEEN LCVLIS AND GCVPSI!...'
    CALL ABOR1('LCVLIS=F IMPLIES GCVPSI=0.!...')
  ENDIF

  IF(L3MT.AND.LNEBNXR.AND..NOT.(QXRDEL==0.5_JPRB.AND.QXRR==0.25_JPRB)) THEN
    WRITE(UNIT=KULOUT,FMT='(A)') 'IF L3MT IT MUST BE QXRDEL=0.5 AND QXRR=0.25!'
    CALL ABOR1('3MT && X-R settings inconsistency')
  ENDIF

ENDIF

!*  Consistency check for simplified physics keys

IF ((LMPHYS.OR.LSIMPH).AND.(LSMOOTHD.OR.LSMOOTHA)) THEN

  IF(RNLCURV == 0.0_JPRB) THEN
    WRITE(UNIT=KULOUT,FMT='(A)') 'SMOOTHING IN SIM. PH. BUT RNLCURV = ZERO'
    CALL ABOR1('PHYSICS AND SMOOTHING IMPLY RNLCURV /= ZERO')
  ENDIF

ENDIF

! ------------------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUPHY0',1,ZHOOK_HANDLE)
END SUBROUTINE SUPHY0
