SUBROUTINE SUALDYN_DDH(YDGEOMETRY,YDML_DIAG,YDML_GCONF)

!**** *SUALDYN_DDH * - Allocate additional space for Dynamical DDH tendencies,

!     Purpose.
!     --------

!**   Interface.
!     ----------
!        *CALL* *SUALDYN_DDH*

!     Author.
!     -------
!        F. Voitus * METEO-FRANCE * 
!        R. El Khatib 09-Mar-2012 allocations management
!     ------------------------------------------------------------------

USE MODEL_DIAGNOSTICS_MOD  , ONLY : MODEL_DIAGNOSTICS_TYPE
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD           , ONLY : GEOMETRY
USE PARKIND1               , ONLY : JPIM, JPRB
USE YOMHOOK                , ONLY : LHOOK, DR_HOOK
USE YOMCT0                 , ONLY : LNHDYN   ,LALLOPR
USE YOMDYNA                , ONLY : LNHX
USE YOMLUN                 , ONLY : NULOUT

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_DIAGNOSTICS_TYPE) ,INTENT(INOUT):: YDML_DIAG
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN):: YDML_GCONF
INTEGER(KIND=JPIM) :: IFLSUR, ITPEC2, IPROMA, IFLEVG  
REAL(KIND=JPRB) :: ZHOOK_HANDLE
#ifdef __INTEL_COMPILER
INTRINSIC :: SHAPE ! Fails with Intel compiler as it thinks we use ATLAS shape function
#endif


!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUALDYN_DDH',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP, &
  & YDMDDH=>YDML_DIAG%YRMDDH,YDLDDH=>YDML_DIAG%YRLDDH,YGFL=>YDML_GCONF%YGFL,YDDIMF=>YDML_GCONF%YRDIMF, &
  & YDSPDDH=>YDML_DIAG%YRSPDDH,YDGPDDH=>YDML_DIAG%YRGPDDH)
ASSOCIATE(NUMFLDS=>YGFL%NUMFLDS, NUMSPFLDS=>YGFL%NUMSPFLDS, &
 & NGPBLKS=>YDDIM%NGPBLKS, NPROMA=>YDDIM%NPROMA, NSPEC2=>YDDIM%NSPEC2, &
 & NFTHER=>YDDIMF%NFTHER, &
 & NFLEVG=>YDDIMV%NFLEVG, NFLSUR=>YDDIMV%NFLSUR, &
 & LRDDHDYN=>YDLDDH%LRDDHDYN, &
 & NDIMSIGMV=>YDMDDH%NDIMSIGMV)
!     ------------------------------------------------------------------

!*       1.    PREAMBLE.
!              ---------

IF (LRDDHDYN) THEN
  IFLSUR=NFLSUR
  ITPEC2=NSPEC2
  IPROMA=NPROMA
  IFLEVG=NFLEVG
ELSE
  IFLSUR=1
  ITPEC2=1
  IPROMA=1
  IFLEVG=1
ENDIF
IF (LALLOPR) WRITE(NULOUT,FMT='('' ALLOCATE SPACE FOR SPECTRAL AND GRIDPOINT DYNAMICAL DDH TENDENCIES '')')


!*       2.    ALLOCATION OF SPECTRAL ARRAYS.
!              -----------

!** VORTICITY
ALLOCATE(YDSPDDH%SPTNDSI_VOR(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDSI_VOR   ', SIZE(YDSPDDH%SPTNDSI_VOR), SHAPE(YDSPDDH%SPTNDSI_VOR)
!** DIVERGENCE
ALLOCATE(YDSPDDH%SPTNDSI_DIV(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDSI_DIV   ', SIZE(YDSPDDH%SPTNDSI_DIV), SHAPE(YDSPDDH%SPTNDSI_DIV)
!** TEMPERATURE
ALLOCATE(YDSPDDH%SPTNDSI_T(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDSI_T     ', SIZE(YDSPDDH%SPTNDSI_T), SHAPE(YDSPDDH%SPTNDSI_T)
!** NH PRESSURE DEPARTURE
ALLOCATE(YDSPDDH%SPTNDSI_SPD(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDSI_SPD   ', SIZE(YDSPDDH%SPTNDSI_SPD), SHAPE(YDSPDDH%SPTNDSI_SPD)
!** NH VERTICAL DIVERGENCE
ALLOCATE(YDSPDDH%SPTNDSI_SVD(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDSI_SVD   ', SIZE(YDSPDDH%SPTNDSI_SVD), SHAPE(YDSPDDH%SPTNDSI_SVD)

!** VORTICITY
ALLOCATE(YDSPDDH%SPTNDHD_VOR(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDHD_VOR   ', SIZE(YDSPDDH%SPTNDHD_VOR), SHAPE(YDSPDDH%SPTNDHD_VOR)
!** DIVERGENCE
ALLOCATE(YDSPDDH%SPTNDHD_DIV(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDHD_DIV   ', SIZE(YDSPDDH%SPTNDHD_DIV), SHAPE(YDSPDDH%SPTNDHD_DIV)
!** TEMPERATURE
ALLOCATE(YDSPDDH%SPTNDHD_T(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDHD_T     ', SIZE(YDSPDDH%SPTNDHD_T), SHAPE(YDSPDDH%SPTNDHD_T)
!** GFL (Specific Humidity)
ALLOCATE(YDSPDDH%SPTNDHD_GFL(1:IFLSUR,1:ITPEC2,MAX(1,NUMSPFLDS)))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDHD_GFL   ',SIZE(YDSPDDH%SPTNDHD_GFL), SHAPE(YDSPDDH%SPTNDHD_GFL)
!** NH PRESSURE DEPARTURE
ALLOCATE(YDSPDDH%SPTNDHD_SPD(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDHD_SPD   ', SIZE(YDSPDDH%SPTNDHD_SPD), SHAPE(YDSPDDH%SPTNDHD_SPD)
!** NH VERTICAL DIVERGENCE
ALLOCATE(YDSPDDH%SPTNDHD_SVD(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDHD_SVD   ', SIZE(YDSPDDH%SPTNDHD_SVD), SHAPE(YDSPDDH%SPTNDHD_SVD)
!** NH "X" PART OF DIVERGENCE
ALLOCATE(YDSPDDH%SPTNDHD_SNHX(IFLSUR,ITPEC2))
IF (LALLOPR) WRITE(NULOUT,999) 'SPTNDHD_SNHX  ', SIZE(YDSPDDH%SPTNDHD_SNHX), SHAPE(YDSPDDH%SPTNDHD_SNHX  )


!*       3.    ALLOCATION OF GRIDPOINT ARRAYS.
!              -----------

ALLOCATE(YDGPDDH%GMVTNDSI_DDH(IPROMA,IFLEVG,NDIMSIGMV,NGPBLKS))
IF (LALLOPR) WRITE(NULOUT,999) 'GMVTNDSI_DDH   ', SIZE(YDGPDDH%GMVTNDSI_DDH), SHAPE(YDGPDDH%GMVTNDSI_DDH)

ALLOCATE(YDGPDDH%GMVTNDHD_DDH(IPROMA,IFLEVG,2+NFTHER,NGPBLKS))
IF (LALLOPR) WRITE(NULOUT,999) 'GMVTNDHD_DDH   ', SIZE(YDGPDDH%GMVTNDHD_DDH), SHAPE(YDGPDDH%GMVTNDHD_DDH)

ALLOCATE(YDGPDDH%GFLTNDHD_DDH(IPROMA,IFLEVG,MAX(1,NUMSPFLDS),NGPBLKS))
IF (LALLOPR) WRITE(NULOUT,999) 'GFLTNDHD_DDH   ', SIZE(YDGPDDH%GFLTNDHD_DDH), SHAPE(YDGPDDH%GFLTNDHD_DDH)

ALLOCATE(YDGPDDH%GMVTNDSL_DDH(IPROMA,IFLEVG,2+NFTHER,NGPBLKS))
IF (LALLOPR) WRITE(NULOUT,999) 'GMVTNDSL_DDH   ', SIZE(YDGPDDH%GMVTNDSL_DDH), SHAPE(YDGPDDH%GMVTNDSL_DDH)

ALLOCATE(YDGPDDH%GFLTNDSL_DDH(IPROMA,IFLEVG,NUMFLDS,NGPBLKS))
IF (LALLOPR) WRITE(NULOUT,999) 'GFLTNDSL_DDH   ', SIZE(YDGPDDH%GFLTNDSL_DDH), SHAPE(YDGPDDH%GFLTNDSL_DDH)

999 FORMAT(' ARRAY ',A12,' ALLOCATED ',8I8)


!*       4.    EVERYTHING SET TO 0.
!              --------------------

YDSPDDH%SPTNDSI_VOR(:,:)= 0.0_JPRB
YDSPDDH%SPTNDSI_DIV(:,:)= 0.0_JPRB
IF (NFTHER >= 1) YDSPDDH%SPTNDSI_T(:,:)= 0.0_JPRB
IF (LNHDYN) THEN
  YDSPDDH%SPTNDSI_SPD(:,:)= 0.0_JPRB
  YDSPDDH%SPTNDSI_SVD(:,:)= 0.0_JPRB
ENDIF

YDSPDDH%SPTNDHD_VOR(:,:)= 0.0_JPRB
YDSPDDH%SPTNDHD_DIV(:,:)= 0.0_JPRB
IF (NFTHER >= 1) YDSPDDH%SPTNDHD_T(:,:)= 0.0_JPRB
YDSPDDH%SPTNDHD_GFL(:,:,1)= 0.0_JPRB
IF (LNHDYN) THEN
  YDSPDDH%SPTNDHD_SPD(:,:)= 0.0_JPRB
  YDSPDDH%SPTNDHD_SVD(:,:)= 0.0_JPRB
ENDIF
IF (LNHX) YDSPDDH%SPTNDHD_SNHX(:,:)= 0.0_JPRB

YDSPDDH%SPTNDHD_GFL(:,:,:)= 0.0_JPRB

YDGPDDH%GMVTNDSI_DDH(:,:,:,:)= 0.0_JPRB
YDGPDDH%GMVTNDHD_DDH(:,:,:,:)= 0.0_JPRB
YDGPDDH%GFLTNDHD_DDH(:,:,:,:)= 0.0_JPRB
YDGPDDH%GMVTNDSL_DDH(:,:,:,:)= 0.0_JPRB
YDGPDDH%GFLTNDSL_DDH(:,:,:,:)= 0.0_JPRB

!     ------------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUALDYN_DDH',1,ZHOOK_HANDLE)
END SUBROUTINE SUALDYN_DDH
