
MODULE APLPAR_STATE_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE CPG_TYPE_MOD, ONLY : CPG_DYN_TYPE, CPG_PHY_TYPE
USE FIELD_MODULE
IMPLICIT NONE


TYPE APLPAR_STATE_GSP_SG_TYPE
  REAL (KIND=JPRB), POINTER :: F (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FF => NULL ()
  REAL (KIND=JPRB), POINTER :: A (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FA => NULL ()
  REAL (KIND=JPRB), POINTER :: R (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FR => NULL ()
END TYPE APLPAR_STATE_GSP_SG_TYPE

TYPE APLPAR_STATE_GSP_RR_TYPE
  REAL (KIND=JPRB), POINTER :: T (:) => NULL ()
  TYPE (FIELD_2D), POINTER :: FT => NULL ()
  REAL (KIND=JPRB), POINTER :: FC (:) => NULL ()
  TYPE (FIELD_2D), POINTER :: FFC => NULL ()
  REAL (KIND=JPRB), POINTER :: W (:) => NULL ()
  TYPE (FIELD_2D), POINTER :: FW => NULL ()
  REAL (KIND=JPRB), POINTER :: IC (:) => NULL ()
  TYPE (FIELD_2D), POINTER :: FIC => NULL ()
END TYPE APLPAR_STATE_GSP_RR_TYPE

TYPE APLPAR_STATE_GSP_SB_TYPE
  REAL (KIND=JPRB), POINTER :: Q (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FQ => NULL ()
  REAL (KIND=JPRB), POINTER :: TL (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FTL => NULL ()
  REAL (KIND=JPRB), POINTER :: T (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FT => NULL ()
END TYPE APLPAR_STATE_GSP_SB_TYPE


TYPE APLPAR_STATE_TYPE
  TYPE (CPG_DYN_TYPE), POINTER :: YCPG_DYN    => NULL ()
  TYPE (CPG_PHY_TYPE), POINTER :: YCPG_PHY    => NULL ()
  REAL (KIND=JPRB), POINTER :: P1EXT  (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER :: P1CHEM (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER :: P1NOGW (:,:)   => NULL ()
  REAL (KIND=JPRB), POINTER :: P2NOGW (:,:)   => NULL ()
  
  REAL (KIND=JPRB), POINTER :: CVV (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FCVV => NULL ()
  REAL (KIND=JPRB), POINTER :: DIV (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FDIV => NULL ()
  REAL (KIND=JPRB), POINTER :: EFB1 (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FEFB1 => NULL ()
  REAL (KIND=JPRB), POINTER :: EFB2 (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FEFB2 => NULL ()
  REAL (KIND=JPRB), POINTER :: EFB3 (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FEFB3 => NULL ()
  REAL (KIND=JPRB), POINTER :: G (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FG => NULL ()
  REAL (KIND=JPRB), POINTER :: I (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FI => NULL ()
  REAL (KIND=JPRB), POINTER :: L (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FL => NULL ()
  REAL (KIND=JPRB), POINTER :: O3 (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FO3 => NULL ()
  REAL (KIND=JPRB), POINTER :: Q (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FQ => NULL ()
  REAL (KIND=JPRB), POINTER :: R (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FR => NULL ()
  REAL (KIND=JPRB), POINTER :: S (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FS => NULL ()
  REAL (KIND=JPRB), POINTER :: T (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FT => NULL ()
  REAL (KIND=JPRB), POINTER :: TKE (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FTKE => NULL ()
  REAL (KIND=JPRB), POINTER :: U (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FU => NULL ()
  REAL (KIND=JPRB), POINTER :: V (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FV => NULL ()
  REAL (KIND=JPRB), POINTER :: VOR (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FVOR => NULL ()

  TYPE (APLPAR_STATE_GSP_SG_TYPE) :: YGSP_SG
  TYPE (APLPAR_STATE_GSP_RR_TYPE) :: YGSP_RR
  TYPE (APLPAR_STATE_GSP_SB_TYPE) :: YGSP_SB

CONTAINS

  PROCEDURE :: INIT => APLPAR_STATE_TYPE_INIT

END TYPE APLPAR_STATE_TYPE

CONTAINS


SUBROUTINE APLPAR_STATE_TYPE_INIT (SELF, LDT0, YDCPG_DYN0, YDCPG_DYN9, YDCPG_PHY0, YDCPG_PHY9, YDVARS, YDMF_PHYS_SURF, &
                                 & P1EXT0, P1EXT9, P1CHEM0, P1CHEM9, P1NOGW0, P1NOGW9, P2NOGW0, P2NOGW9)

USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES

CLASS (APLPAR_STATE_TYPE)              :: SELF
TYPE (MF_PHYS_SURF_TYPE),INTENT(INOUT) :: YDMF_PHYS_SURF
LOGICAL,                INTENT (IN)    :: LDT0
TYPE (CPG_DYN_TYPE),    INTENT (INOUT), TARGET :: YDCPG_DYN0, YDCPG_DYN9
TYPE (CPG_PHY_TYPE),    INTENT (INOUT), TARGET :: YDCPG_PHY0, YDCPG_PHY9
TYPE (FIELD_VARIABLES), INTENT (INOUT) :: YDVARS
REAL (KIND=JPRB), POINTER :: P1EXT0  (:,:,:), P1EXT9  (:,:,:)
REAL (KIND=JPRB), POINTER :: P1CHEM0 (:,:,:), P1CHEM9 (:,:,:)
REAL (KIND=JPRB), POINTER :: P1NOGW0 (:,:), P1NOGW9 (:,:)
REAL (KIND=JPRB), POINTER :: P2NOGW0 (:,:), P2NOGW9 (:,:)
REAL (KIND=JPRB), TARGET, SAVE :: ZDUM2 (1, 1), ZDUM3 (1, 1, 1)

IF (LDT0) THEN
  SELF%YCPG_DYN => YDCPG_DYN0
  SELF%YCPG_PHY => YDCPG_PHY0

  SELF%P1EXT  => ZDUM3
  SELF%P1CHEM => ZDUM3
  SELF%P1NOGW => ZDUM2
  SELF%P2NOGW => ZDUM2

  IF (ASSOCIATED (P1EXT0 )) SELF%P1EXT  => P1EXT0
  IF (ASSOCIATED (P1CHEM0)) SELF%P1CHEM => P1CHEM0
  IF (ASSOCIATED (P1NOGW0)) SELF%P1NOGW => P1NOGW0
  IF (ASSOCIATED (P2NOGW0)) SELF%P2NOGW => P2NOGW0

  SELF%CVV (LBOUND (YDVARS%CVV%T0,1):, LBOUND (YDVARS%CVV%T0,2):) => YDVARS%CVV%T0
  SELF%FCVV => YDVARS%CVV%FT0
  SELF%DIV (LBOUND (YDVARS%DIV%T0,1):, LBOUND (YDVARS%DIV%T0,2):) => YDVARS%DIV%T0
  SELF%FDIV => YDVARS%DIV%FT0
  SELF%EFB1 (LBOUND (YDVARS%EFB1%T0,1):, LBOUND (YDVARS%EFB1%T0,2):) => YDVARS%EFB1%T0
  SELF%FEFB1 => YDVARS%EFB1%FT0
  SELF%EFB2 (LBOUND (YDVARS%EFB2%T0,1):, LBOUND (YDVARS%EFB2%T0,2):) => YDVARS%EFB2%T0
  SELF%FEFB2 => YDVARS%EFB2%FT0
  SELF%EFB3 (LBOUND (YDVARS%EFB3%T0,1):, LBOUND (YDVARS%EFB3%T0,2):) => YDVARS%EFB3%T0
  SELF%FEFB3 => YDVARS%EFB3%FT0
  SELF%G (LBOUND (YDVARS%G%T0,1):, LBOUND (YDVARS%G%T0,2):) => YDVARS%G%T0
  SELF%FG => YDVARS%G%FT0
  SELF%I (LBOUND (YDVARS%I%T0,1):, LBOUND (YDVARS%I%T0,2):) => YDVARS%I%T0
  SELF%FI => YDVARS%I%FT0
  SELF%L (LBOUND (YDVARS%L%T0,1):, LBOUND (YDVARS%L%T0,2):) => YDVARS%L%T0
  SELF%FL => YDVARS%L%FT0
  SELF%O3 (LBOUND (YDVARS%O3%T0,1):, LBOUND (YDVARS%O3%T0,2):) => YDVARS%O3%T0
  SELF%FO3 => YDVARS%O3%FT0
  SELF%Q (LBOUND (YDVARS%Q%T0,1):, LBOUND (YDVARS%Q%T0,2):) => YDVARS%Q%T0
  SELF%FQ => YDVARS%Q%FT0
  SELF%R (LBOUND (YDVARS%R%T0,1):, LBOUND (YDVARS%R%T0,2):) => YDVARS%R%T0
  SELF%FR => YDVARS%R%FT0
  SELF%S (LBOUND (YDVARS%S%T0,1):, LBOUND (YDVARS%S%T0,2):) => YDVARS%S%T0
  SELF%FS => YDVARS%S%FT0
  SELF%T (LBOUND (YDVARS%T%T0,1):, LBOUND (YDVARS%T%T0,2):) => YDVARS%T%T0
  SELF%FT => YDVARS%T%FT0
  SELF%TKE (LBOUND (YDVARS%TKE%T0,1):, LBOUND (YDVARS%TKE%T0,2):) => YDVARS%TKE%T0
  SELF%FTKE => YDVARS%TKE%FT0
  SELF%U (LBOUND (YDVARS%U%T0,1):, LBOUND (YDVARS%U%T0,2):) => YDVARS%U%T0
  SELF%FU => YDVARS%U%FT0
  SELF%V (LBOUND (YDVARS%V%T0,1):, LBOUND (YDVARS%V%T0,2):) => YDVARS%V%T0
  SELF%FV => YDVARS%V%FT0
  SELF%VOR (LBOUND (YDVARS%VOR%T0,1):, LBOUND (YDVARS%VOR%T0,2):) => YDVARS%VOR%T0
  SELF%FVOR => YDVARS%VOR%FT0

  SELF%YGSP_SG%F ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PF_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PF_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PF_T0
  SELF%YGSP_SG%FF => YDMF_PHYS_SURF%GSP_SG%F_F_T0

  SELF%YGSP_SG%A ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PA_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PA_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PA_T0
  SELF%YGSP_SG%FA => YDMF_PHYS_SURF%GSP_SG%F_A_T0

  SELF%YGSP_SG%R ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PR_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PR_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PR_T0
  SELF%YGSP_SG%FR => YDMF_PHYS_SURF%GSP_SG%F_R_T0

  SELF%YGSP_RR%T ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PT_T0, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PT_T0
  SELF%YGSP_RR%FT => YDMF_PHYS_SURF%GSP_RR%F_T_T0

  SELF%YGSP_RR%FC ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PFC_T0, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PFC_T0
  SELF%YGSP_RR%FFC => YDMF_PHYS_SURF%GSP_RR%F_FC_T0

  SELF%YGSP_RR%W ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PW_T0, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PW_T0
  SELF%YGSP_RR%FW => YDMF_PHYS_SURF%GSP_RR%F_W_T0

  SELF%YGSP_RR%IC ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PIC_T0, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PIC_T0
  SELF%YGSP_RR%FIC => YDMF_PHYS_SURF%GSP_RR%F_IC_T0

  SELF%YGSP_SB%Q ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PQ_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PQ_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PQ_T0
  SELF%YGSP_SB%FQ => YDMF_PHYS_SURF%GSP_SB%F_Q_T0

  SELF%YGSP_SB%TL ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PTL_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PTL_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PTL_T0
  SELF%YGSP_SB%FTL => YDMF_PHYS_SURF%GSP_SB%F_TL_T0

  SELF%YGSP_SB%T ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PT_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PT_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PT_T0
  SELF%YGSP_SB%FT => YDMF_PHYS_SURF%GSP_SB%F_T_T0


ELSE
  SELF%YCPG_DYN => YDCPG_DYN9
  SELF%YCPG_PHY => YDCPG_PHY9

  SELF%P1EXT  => ZDUM3
  SELF%P1CHEM => ZDUM3
  SELF%P1NOGW => ZDUM2
  SELF%P2NOGW => ZDUM2

  IF (ASSOCIATED (P1EXT9 )) SELF%P1EXT  => P1EXT9
  IF (ASSOCIATED (P1CHEM9)) SELF%P1CHEM => P1CHEM9
  IF (ASSOCIATED (P1NOGW9)) SELF%P1NOGW => P1NOGW9
  IF (ASSOCIATED (P2NOGW9)) SELF%P2NOGW => P2NOGW9

  SELF%CVV (LBOUND (YDVARS%CVV%T9,1):, LBOUND (YDVARS%CVV%T9,2):) => YDVARS%CVV%T9
  SELF%FCVV => YDVARS%CVV%FT9
  SELF%DIV (LBOUND (YDVARS%DIV%T9,1):, LBOUND (YDVARS%DIV%T9,2):) => YDVARS%DIV%T9
  SELF%FDIV => YDVARS%DIV%FT9
  SELF%EFB1 (LBOUND (YDVARS%EFB1%T9,1):, LBOUND (YDVARS%EFB1%T9,2):) => YDVARS%EFB1%T9
  SELF%FEFB1 => YDVARS%EFB1%FT9
  SELF%EFB2 (LBOUND (YDVARS%EFB2%T9,1):, LBOUND (YDVARS%EFB2%T9,2):) => YDVARS%EFB2%T9
  SELF%FEFB2 => YDVARS%EFB2%FT9
  SELF%EFB3 (LBOUND (YDVARS%EFB3%T9,1):, LBOUND (YDVARS%EFB3%T9,2):) => YDVARS%EFB3%T9
  SELF%FEFB3 => YDVARS%EFB3%FT9
  SELF%G (LBOUND (YDVARS%G%T9,1):, LBOUND (YDVARS%G%T9,2):) => YDVARS%G%T9
  SELF%FG => YDVARS%G%FT9
  SELF%I (LBOUND (YDVARS%I%T9,1):, LBOUND (YDVARS%I%T9,2):) => YDVARS%I%T9
  SELF%FI => YDVARS%I%FT9
  SELF%L (LBOUND (YDVARS%L%T9,1):, LBOUND (YDVARS%L%T9,2):) => YDVARS%L%T9
  SELF%FL => YDVARS%L%FT9
  SELF%O3 (LBOUND (YDVARS%O3%T9,1):, LBOUND (YDVARS%O3%T9,2):) => YDVARS%O3%T9
  SELF%FO3 => YDVARS%O3%FT9
  SELF%Q (LBOUND (YDVARS%Q%T9,1):, LBOUND (YDVARS%Q%T9,2):) => YDVARS%Q%T9
  SELF%FQ => YDVARS%Q%FT9
  SELF%R (LBOUND (YDVARS%R%T9,1):, LBOUND (YDVARS%R%T9,2):) => YDVARS%R%T9
  SELF%FR => YDVARS%R%FT9
  SELF%S (LBOUND (YDVARS%S%T9,1):, LBOUND (YDVARS%S%T9,2):) => YDVARS%S%T9
  SELF%FS => YDVARS%S%FT9
  SELF%T (LBOUND (YDVARS%T%T9,1):, LBOUND (YDVARS%T%T9,2):) => YDVARS%T%T9
  SELF%FT => YDVARS%T%FT9
  SELF%TKE (LBOUND (YDVARS%TKE%T9,1):, LBOUND (YDVARS%TKE%T9,2):) => YDVARS%TKE%T9
  SELF%FTKE => YDVARS%TKE%FT9
  SELF%U (LBOUND (YDVARS%U%T9,1):, LBOUND (YDVARS%U%T9,2):) => YDVARS%U%T9
  SELF%FU => YDVARS%U%FT9
  SELF%V (LBOUND (YDVARS%V%T9,1):, LBOUND (YDVARS%V%T9,2):) => YDVARS%V%T9
  SELF%FV => YDVARS%V%FT9
  SELF%VOR (LBOUND (YDVARS%VOR%T9,1):, LBOUND (YDVARS%VOR%T9,2):) => YDVARS%VOR%T9
  SELF%FVOR => YDVARS%VOR%FT9

  SELF%YGSP_SG%F ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PF_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PF_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PF_T9
  SELF%YGSP_SG%FF => YDMF_PHYS_SURF%GSP_SG%F_F_T9

  SELF%YGSP_SG%A ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PA_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PA_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PA_T9
  SELF%YGSP_SG%FA => YDMF_PHYS_SURF%GSP_SG%F_A_T9

  SELF%YGSP_SG%R ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PR_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PR_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PR_T9
  SELF%YGSP_SG%FR => YDMF_PHYS_SURF%GSP_SG%F_R_T9

  SELF%YGSP_RR%T ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PT_T9, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PT_T9
  SELF%YGSP_RR%FT => YDMF_PHYS_SURF%GSP_RR%F_T_T9

  SELF%YGSP_RR%FC ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PFC_T9, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PFC_T9
  SELF%YGSP_RR%FFC => YDMF_PHYS_SURF%GSP_RR%F_FC_T9

  SELF%YGSP_RR%W ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PW_T9, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PW_T9
  SELF%YGSP_RR%FW => YDMF_PHYS_SURF%GSP_RR%F_W_T9

  SELF%YGSP_RR%IC ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PIC_T9, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PIC_T9
  SELF%YGSP_RR%FIC => YDMF_PHYS_SURF%GSP_RR%F_IC_T9

  SELF%YGSP_SB%Q ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PQ_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PQ_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PQ_T9
  SELF%YGSP_SB%FQ => YDMF_PHYS_SURF%GSP_SB%F_Q_T9

  SELF%YGSP_SB%TL ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PTL_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PTL_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PTL_T9
  SELF%YGSP_SB%FTL => YDMF_PHYS_SURF%GSP_SB%F_TL_T9

  SELF%YGSP_SB%T ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PT_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PT_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PT_T9
  SELF%YGSP_SB%FT => YDMF_PHYS_SURF%GSP_SB%F_T_T9


ENDIF

END SUBROUTINE APLPAR_STATE_TYPE_INIT

END MODULE APLPAR_STATE_TYPE_MOD
