MODULE CPG_DYN_TYPE_MOD

USE FIELD_MODULE
USE FIELD_REGISTRY_MOD
USE PARKIND1, ONLY : JPRB, JPIM

IMPLICIT NONE

TYPE CPG_DYN_TYPE
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PHI (:,:) => NULL ()
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PRE (:,:) => NULL ()
  TYPE(FIELD_3D), POINTER :: F_PHI => NULL ()
  TYPE(FIELD_3D), POINTER :: F_PRE => NULL ()
CONTAINS
  PROCEDURE :: INIT => CPG_DYN_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_DYN_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_DYN_TYPE_FINAL
END TYPE

CONTAINS

SUBROUTINE CPG_DYN_TYPE_INIT (SELF, REGISTRY, NLEV, PERSISTENT)

CLASS (CPG_DYN_TYPE)                  :: SELF
TYPE (FIELD_REGISTRY), INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),   INTENT (IN)    :: NLEV
LOGICAL, OPTIONAL,     INTENT (IN)    :: PERSISTENT

SELF%F_PHI => CREATE_TEMPORARY('PHI', GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
SELF%F_PRE => CREATE_TEMPORARY('PRE', GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)

END SUBROUTINE

SUBROUTINE CPG_DYN_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_DYN_TYPE)              :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

SELF%PHI (1:, 0:) => SELF%F_PHI%GET_VIEW (BLOCK_INDEX)
SELF%PRE (1:, 0:) => SELF%F_PRE%GET_VIEW (BLOCK_INDEX)

END SUBROUTINE

SUBROUTINE CPG_DYN_TYPE_FINAL (SELF)
CLASS (CPG_DYN_TYPE)              :: SELF

CALL DELETE_TEMPORARY (SELF%F_PHI)
CALL DELETE_TEMPORARY (SELF%F_PRE)

END SUBROUTINE 

END MODULE CPG_DYN_TYPE_MOD

