MODULE CPG_DIM_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMCT3, ONLY : NSTEP
USE SURFACE_FIELDS_MIX , ONLY : TYPE_SURF_GEN

IMPLICIT NONE

TYPE CPG_DIM_VAR_TYPE
  INTEGER(KIND=JPIM) :: ILEVT1I
  INTEGER(KIND=JPIM) :: ILEVT1F
END TYPE


TYPE CPG_DIM_VARS_TYPE
  TYPE (CPG_DIM_VAR_TYPE) :: U
  TYPE (CPG_DIM_VAR_TYPE) :: V
  TYPE (CPG_DIM_VAR_TYPE) :: T
  TYPE (CPG_DIM_VAR_TYPE) :: SVD
  TYPE (CPG_DIM_VAR_TYPE) :: Q
  TYPE (CPG_DIM_VAR_TYPE) :: I
  TYPE (CPG_DIM_VAR_TYPE) :: L
  TYPE (CPG_DIM_VAR_TYPE) :: LCONV
  TYPE (CPG_DIM_VAR_TYPE) :: ICONV
  TYPE (CPG_DIM_VAR_TYPE) :: RCONV
  TYPE (CPG_DIM_VAR_TYPE) :: SCONV
  TYPE (CPG_DIM_VAR_TYPE) :: IRAD
  TYPE (CPG_DIM_VAR_TYPE) :: LRAD
  TYPE (CPG_DIM_VAR_TYPE) :: S
  TYPE (CPG_DIM_VAR_TYPE) :: R
  TYPE (CPG_DIM_VAR_TYPE) :: G
  TYPE (CPG_DIM_VAR_TYPE) :: H
  TYPE (CPG_DIM_VAR_TYPE) :: TKE
  TYPE (CPG_DIM_VAR_TYPE) :: TTE
  TYPE (CPG_DIM_VAR_TYPE) :: EFB1
  TYPE (CPG_DIM_VAR_TYPE) :: EFB2
  TYPE (CPG_DIM_VAR_TYPE) :: EFB3
  TYPE (CPG_DIM_VAR_TYPE) :: A
  TYPE (CPG_DIM_VAR_TYPE) :: O3
  TYPE (CPG_DIM_VAR_TYPE) :: SRC
  TYPE (CPG_DIM_VAR_TYPE) :: MXL
  TYPE (CPG_DIM_VAR_TYPE) :: SHTUR
  TYPE (CPG_DIM_VAR_TYPE) :: FQTUR
  TYPE (CPG_DIM_VAR_TYPE) :: FSTUR
  TYPE (CPG_DIM_VAR_TYPE) :: CPF
  TYPE (CPG_DIM_VAR_TYPE) :: SPF
  TYPE (CPG_DIM_VAR_TYPE) :: CVGQ
  TYPE (CPG_DIM_VAR_TYPE) :: QVA
  TYPE (CPG_DIM_VAR_TYPE) :: LRCH4
  TYPE (CPG_DIM_VAR_TYPE) :: PHYCTY
  TYPE (CPG_DIM_VAR_TYPE) :: RSPEC
  TYPE (CPG_DIM_VAR_TYPE) :: SDSAT
  TYPE (CPG_DIM_VAR_TYPE) :: CVV
  TYPE (CPG_DIM_VAR_TYPE) :: RKTH
  TYPE (CPG_DIM_VAR_TYPE) :: RKTQV
  TYPE (CPG_DIM_VAR_TYPE) :: RKTQC
  TYPE (CPG_DIM_VAR_TYPE) :: UOM
  TYPE (CPG_DIM_VAR_TYPE) :: UAL
  TYPE (CPG_DIM_VAR_TYPE) :: DOM
  TYPE (CPG_DIM_VAR_TYPE) :: DAL
  TYPE (CPG_DIM_VAR_TYPE) :: UEN
  TYPE (CPG_DIM_VAR_TYPE) :: UNEBH
  TYPE (CPG_DIM_VAR_TYPE) :: FSD
CONTAINS 
  PROCEDURE :: INIT => CPG_DIM_VARS_TYPE_INIT
END TYPE

TYPE CPG_DIM_SURF_TYPE
  TYPE (TYPE_SURF_GEN) :: YSP_SBD
  TYPE (TYPE_SURF_GEN) :: YSP_SGD
  TYPE (TYPE_SURF_GEN) :: YSP_SLD
  TYPE (TYPE_SURF_GEN) :: YSP_RRD
  TYPE (TYPE_SURF_GEN) :: YSP_CLD
  TYPE (TYPE_SURF_GEN) :: YSP_OMD
  TYPE (TYPE_SURF_GEN) :: YSP_EPD
  TYPE (TYPE_SURF_GEN) :: YSP_X2D
  TYPE (TYPE_SURF_GEN) :: YSP_CID
  TYPE (TYPE_SURF_GEN) :: YSD_VFD
  TYPE (TYPE_SURF_GEN) :: YSD_VHD
  TYPE (TYPE_SURF_GEN) :: YSD_VKD
  TYPE (TYPE_SURF_GEN) :: YSD_VPD
  TYPE (TYPE_SURF_GEN) :: YSD_VVD
  TYPE (TYPE_SURF_GEN) :: YSD_VAD
  TYPE (TYPE_SURF_GEN) :: YSD_VND
  TYPE (TYPE_SURF_GEN) :: YSD_V2D
  TYPE (TYPE_SURF_GEN) :: YSD_V3D
  TYPE (TYPE_SURF_GEN) :: YSD_VDD
  TYPE (TYPE_SURF_GEN) :: YSD_SMD
  TYPE (TYPE_SURF_GEN) :: YSD_WSD
  TYPE (TYPE_SURF_GEN) :: YSD_WWD
  TYPE (TYPE_SURF_GEN) :: YSD_XAD
  TYPE (TYPE_SURF_GEN) :: YSD_DID
  TYPE (TYPE_SURF_GEN) :: YSD_XPD
  TYPE (TYPE_SURF_GEN) :: YSD_XP2D
  TYPE (TYPE_SURF_GEN) :: YSD_X2D
  TYPE (TYPE_SURF_GEN) :: YSD_SFOD
  TYPE (TYPE_SURF_GEN) :: YSD_SFLD
  TYPE (TYPE_SURF_GEN) :: YSD_VCD
END TYPE

TYPE CPG_DIM_TYPE
  INTEGER(KIND=JPIM) :: KIDIA 
  INTEGER(KIND=JPIM) :: KFDIA 
  INTEGER(KIND=JPIM) :: KBL 
  INTEGER(KIND=JPIM) :: KLON 
  INTEGER(KIND=JPIM) :: KFLEVG 
  INTEGER(KIND=JPIM) :: KSTGLO 
  INTEGER(KIND=JPIM) :: KGPTOT 
  INTEGER(KIND=JPIM) :: KGPBLKS
  INTEGER(KIND=JPIM) :: KGPCOMP 
  INTEGER(KIND=JPIM) :: KFDIE 
  INTEGER(KIND=JPIM) :: KIDIE
  INTEGER(KIND=JPIM) :: KGL1
  INTEGER(KIND=JPIM) :: KGL2
  INTEGER(KIND=JPIM) :: KSTEP
  INTEGER(KIND=JPIM) :: KTDIA
  INTEGER(KIND=JPIM) :: KVCLIS
  INTEGER(KIND=JPIM) :: KDTPREC
  INTEGER(KIND=JPIM) :: KDTPREC2
  INTEGER(KIND=JPIM) :: KTSSG
  INTEGER(KIND=JPIM) :: KGRADIENTS
  INTEGER(KIND=JPIM) :: KMAXDRAFT
  INTEGER(KIND=JPIM) :: KSW
  
  TYPE (CPG_DIM_SURF_TYPE) :: YRSURF

  TYPE (CPG_DIM_VARS_TYPE) :: VARS

CONTAINS
  PROCEDURE :: INIT => CPG_DIM_TYPE_INIT
  PROCEDURE :: UPDATE => CPG_DIM_TYPE_UPDATE
END TYPE CPG_DIM_TYPE

CONTAINS

  SUBROUTINE CPG_DIM_TYPE_INIT(SELF, YDGEOMETRY, YDMODEL, YDFIELDS)
    USE TYPE_MODEL, ONLY : MODEL
    USE FIELDS_MOD, ONLY : FIELDS
    USE YOMCT0, ONLY : LSLAG, LTWOTL
    CLASS(CPG_DIM_TYPE) :: SELF
    TYPE(MODEL)   , INTENT(IN) :: YDMODEL
    TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
    TYPE(FIELDS),   INTENT(IN), TARGET :: YDFIELDS

    SELF%KBL          =  1
    SELF%KLON         =  YDGEOMETRY%YRDIM%NPROMA
    SELF%KIDIA        =  1
    SELF%KIDIE        =  1
    SELF%KFDIA        =  YDGEOMETRY%YRDIM%NPROMA
    SELF%KFDIE        =  YDGEOMETRY%YRDIM%NPROMA
    SELF%KFLEVG       =  YDGEOMETRY%YRDIMV%NFLEVG
    SELF%KGPTOT       =  YDGEOMETRY%YRGEM%NGPTOT
    SELF%KGPBLKS      =  YDGEOMETRY%YRDIM%NGPBLKS
    SELF%KGPCOMP      =  YDGEOMETRY%YRGEM%NGPTOT_CAP
    SELF%KSTEP        =  NSTEP
    SELF%KGL1         =  YDGEOMETRY%YRDIM%NDGENL
    SELF%KTDIA        =  1
    SELF%KVCLIS       =  YDMODEL%YRML_PHY_G%YRDPHY%NVCLIS
    SELF%KDTPREC      =  YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC
    SELF%KDTPREC2     =  YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC2
    SELF%KTSSG        =  YDMODEL%YRML_PHY_G%YRDPHY%NTSSG
    SELF%KGRADIENTS   =  YDMODEL%YRML_PHY_MF%YRARPHY%NGRADIENTS

    IF (YDMODEL%YRML_PHY_MF%YRARPHY%LMFSHAL .AND. YDMODEL%YRML_PHY_MF%YRPARAR%CMF_UPDRAFT=='DUAL') THEN
      SELF%KMAXDRAFT=3
    ELSE
      SELF%KMAXDRAFT=0
    ENDIF

    IF (YDMODEL%YRML_PHY_MF%YRPHY%LRAY) THEN
      SELF%KSW = 1
    ELSE
      SELF%KSW = YDMODEL%YRML_PHY_RAD%YRERAD%NSW
    ENDIF

    SELF%YRSURF%YSP_SBD = YDFIELDS%YRSURF%YSP_SBD
    SELF%YRSURF%YSP_SGD = YDFIELDS%YRSURF%YSP_SGD
    SELF%YRSURF%YSP_SLD = YDFIELDS%YRSURF%YSP_SLD
    SELF%YRSURF%YSP_RRD = YDFIELDS%YRSURF%YSP_RRD
    SELF%YRSURF%YSP_CLD = YDFIELDS%YRSURF%YSP_CLD
    SELF%YRSURF%YSP_OMD = YDFIELDS%YRSURF%YSP_OMD
    SELF%YRSURF%YSP_EPD = YDFIELDS%YRSURF%YSP_EPD
    SELF%YRSURF%YSP_X2D = YDFIELDS%YRSURF%YSP_X2D
    SELF%YRSURF%YSP_CID = YDFIELDS%YRSURF%YSP_CID
    SELF%YRSURF%YSD_VFD = YDFIELDS%YRSURF%YSD_VFD
    SELF%YRSURF%YSD_VHD = YDFIELDS%YRSURF%YSD_VHD
    SELF%YRSURF%YSD_VKD = YDFIELDS%YRSURF%YSD_VKD
    SELF%YRSURF%YSD_VPD = YDFIELDS%YRSURF%YSD_VPD
    SELF%YRSURF%YSD_VVD = YDFIELDS%YRSURF%YSD_VVD
    SELF%YRSURF%YSD_VAD = YDFIELDS%YRSURF%YSD_VAD
    SELF%YRSURF%YSD_VND = YDFIELDS%YRSURF%YSD_VND
    SELF%YRSURF%YSD_V2D = YDFIELDS%YRSURF%YSD_V2D
    SELF%YRSURF%YSD_V3D = YDFIELDS%YRSURF%YSD_V3D
    SELF%YRSURF%YSD_VDD = YDFIELDS%YRSURF%YSD_VDD
    SELF%YRSURF%YSD_SMD = YDFIELDS%YRSURF%YSD_SMD
    SELF%YRSURF%YSD_WSD = YDFIELDS%YRSURF%YSD_WSD
    SELF%YRSURF%YSD_WWD = YDFIELDS%YRSURF%YSD_WWD
    SELF%YRSURF%YSD_XAD = YDFIELDS%YRSURF%YSD_XAD
    SELF%YRSURF%YSD_DID = YDFIELDS%YRSURF%YSD_DID
    SELF%YRSURF%YSD_XPD = YDFIELDS%YRSURF%YSD_XPD
    SELF%YRSURF%YSD_XP2D = YDFIELDS%YRSURF%YSD_XP2D
    SELF%YRSURF%YSD_X2D = YDFIELDS%YRSURF%YSD_X2D
    SELF%YRSURF%YSD_SFOD = YDFIELDS%YRSURF%YSD_SFOD
    SELF%YRSURF%YSD_SFLD = YDFIELDS%YRSURF%YSD_SFLD
    SELF%YRSURF%YSD_VCD = YDFIELDS%YRSURF%YSD_VCD

    CALL SELF%VARS%INIT (YDGEOMETRY, YDMODEL, YDFIELDS%VARIABLES)

  END SUBROUTINE CPG_DIM_TYPE_INIT

  SUBROUTINE CPG_DIM_TYPE_UPDATE(SELF, IBL)
    CLASS(CPG_DIM_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: IBL

    SELF%KBL    = IBL
    SELF%KSTGLO = 1 + (IBL - 1) * SELF%KLON
    SELF%KFDIA  = MIN (SELF%KLON, SELF%KGPCOMP - SELF%KSTGLO + 1)
    SELF%KFDIE  = MIN (SELF%KLON, SELF%KGPTOT  - SELF%KSTGLO + 1)

  END SUBROUTINE CPG_DIM_TYPE_UPDATE

  SUBROUTINE CPG_DIM_VARS_TYPE_INIT (SELF, YDGEOMETRY, YDMODEL, YDVARS)
    USE TYPE_MODEL, ONLY : MODEL
    USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
    USE YOMCT0, ONLY : LSLAG, LTWOTL
    CLASS(CPG_DIM_VARS_TYPE) :: SELF
    TYPE(MODEL)   , INTENT(IN) :: YDMODEL
    TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
    TYPE (FIELD_VARIABLES), INTENT (IN) :: YDVARS

    IF (LSLAG) THEN
    
      SELF%U   = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      SELF%V   = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      SELF%T   = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      SELF%SVD = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      
      IF (YDVARS%Q%LADV) THEN
        SELF%Q = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%Q = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%I%LADV) THEN
        SELF%I = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%I = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%L%LADV) THEN
        SELF%L = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%L = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%LCONV%LADV) THEN
        SELF%LCONV = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%LCONV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%ICONV%LADV) THEN
        SELF%ICONV = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%ICONV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%RCONV%LADV) THEN
        SELF%RCONV = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%RCONV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%SCONV%LADV) THEN
        SELF%SCONV = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%SCONV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%IRAD%LADV) THEN
        SELF%IRAD = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%IRAD = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%LRAD%LADV) THEN
        SELF%LRAD = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%LRAD = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%S%LADV) THEN
        SELF%S = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%S = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%R%LADV) THEN
        SELF%R = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%R = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%G%LADV) THEN
        SELF%G = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%G = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%H%LADV) THEN
        SELF%H = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%H = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%TKE%LADV) THEN
        SELF%TKE = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%TKE = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%TTE%LADV) THEN
        SELF%TTE = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%TTE = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%EFB1%LADV) THEN
        SELF%EFB1 = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%EFB1 = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%EFB2%LADV) THEN
        SELF%EFB2 = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%EFB2 = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%EFB3%LADV) THEN
        SELF%EFB3 = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%EFB3 = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%A%LADV) THEN
        SELF%A = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%A = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%O3%LADV) THEN
        SELF%O3 = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%O3 = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%SRC%LADV) THEN
        SELF%SRC = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%SRC = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%MXL%LADV) THEN
        SELF%MXL = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%MXL = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%SHTUR%LADV) THEN
        SELF%SHTUR = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%SHTUR = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%FQTUR%LADV) THEN
        SELF%FQTUR = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%FQTUR = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%FSTUR%LADV) THEN
        SELF%FSTUR = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%FSTUR = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%CPF%LADV) THEN
        SELF%CPF = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%CPF = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%SPF%LADV) THEN
        SELF%SPF = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%SPF = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%CVGQ%LADV) THEN
        SELF%CVGQ = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%CVGQ = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%QVA%LADV) THEN
        SELF%QVA = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%QVA = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%LRCH4%LADV) THEN
        SELF%LRCH4 = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%LRCH4 = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%PHYCTY%LADV) THEN
        SELF%PHYCTY = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%PHYCTY = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%RSPEC%LADV) THEN
        SELF%RSPEC = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%RSPEC = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%SDSAT%LADV) THEN
        SELF%SDSAT = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%SDSAT = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%CVV%LADV) THEN
        SELF%CVV = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%CVV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%RKTH%LADV) THEN
        SELF%RKTH = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%RKTH = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%RKTQV%LADV) THEN
        SELF%RKTQV = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%RKTQV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%RKTQC%LADV) THEN
        SELF%RKTQC = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%RKTQC = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%UOM%LADV) THEN
        SELF%UOM = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%UOM = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%UAL%LADV) THEN
        SELF%UAL = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%UAL = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%DOM%LADV) THEN
        SELF%DOM = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%DOM = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%DAL%LADV) THEN
        SELF%DAL = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%DAL = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%UEN%LADV) THEN
        SELF%UEN = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%UEN = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%UNEBH%LADV) THEN
        SELF%UNEBH = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%UNEBH = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF
      IF (YDVARS%FSD%LADV) THEN
        SELF%FSD = CPG_DIM_VAR_TYPE (0, YDGEOMETRY%YRDIMV%NFLEVG+1)
      ELSE
        SELF%FSD = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      ENDIF

    ELSE

      SELF%U   = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%V   = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%T   = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%SVD = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      
      SELF%Q = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%I = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%L = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%LCONV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%ICONV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%RCONV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%SCONV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%IRAD = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%LRAD = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%S = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%R = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%G = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%H = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%TKE = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%TTE = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%EFB1 = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%EFB2 = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%EFB3 = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%A = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%O3 = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%SRC = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%MXL = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%SHTUR = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%FQTUR = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%FSTUR = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%CPF = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%SPF = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%CVGQ = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%QVA = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%LRCH4 = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%PHYCTY = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%RSPEC = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%SDSAT = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%CVV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%RKTH = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%RKTQV = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%RKTQC = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%UOM = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%UAL = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%DOM = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%DAL = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%UEN = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%UNEBH = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)
      SELF%FSD = CPG_DIM_VAR_TYPE (1, YDGEOMETRY%YRDIMV%NFLEVG)

    ENDIF
  END SUBROUTINE 

END MODULE CPG_DIM_TYPE_MOD
