MODULE ECPHYS_FLUX_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_MODULE, ONLY: FIELD_2D, FIELD_3D, FIELD_4D
USE FIELD_REGISTRY_MOD, ONLY: FIELD_REGISTRY, CREATE_TEMPORARY, DELETE_TEMPORARY

IMPLICIT NONE

TYPE FLUX_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFRSOC,PFRTHC ! (KLON,0:1) SHORTWAVE and LONGWAVE CLEAR SKY RADIATIVE FLUX
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PDIFCQ     ! CONVECTIVE FLUX OF SPECIFIC HUMIDITY (NOT RAIN/SNOW).
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PDIFCS     ! CONVECTIVE FLUX OF ENTHALPY (NOT RAIN/SNOW).
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PDIFTQ     ! TURBULENT FLUX (INC. Q NEGATIVE) OF SPECIFIC HUMIDITY.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PDIFTI,PDIFTL ! TURBULENT FLUX (INC. Q NEGATIVE) OF SOLID/LIQUID WATER
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PDIFTS     ! TURBULENT FLUX OF ENTHALPY (OR DRY STATIC ENERGY).
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFCQNG     ! PSEUDO-FLUX OF WATER TO CORRECT FOR Q<0.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFCQLNG,PFCQNNG  ! PSEUDO-FLUX OF LIQUID WATER/ICE TO CORRECT FOR Q<0.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFCQRNG,PFCQSNG  ! PSEUDO-FLUX OF RAIN/SNOW TO CORRECT FOR Q<0.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFPLCL     ! CONVECTIVE PRECIPITATION AS RAIN.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFPLCN     ! CONVECTIVE PRECIPITATION AS SNOW.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFPLSL     ! STRATIFORM PRECIPITATION AS RAIN.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFPLSN     ! STRATIFORM PRECIPITATION AS SNOW.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFHPCL     ! ENTHALPY FLUX OF CONVECTIVE PRECIPITATION AS RAIN
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFHPCN     ! ENTHALPY FLUX OF CONVECTIVE PRECIPITATION AS SNOW.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFHPSL     ! ENTHALPY FLUX OF STRATIFORM PRECIPITATION AS RAIN.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFHPSN     ! ENTHALPY FLUX OF STRATIFORM PRECIPITATION AS SNOW.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFRSO      ! SHORTWAVE RADIATIVE FLUX.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFRTH      ! LONGWAVE RADIATIVE FLUX.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PSTRCU,PSTRCV ! CONVECTIVE FLUX OF MOMENTUM (U and V)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PSTRDU,PSTRDV ! GRAVITY WAVE DRAG FLUX OF MOMENTUM (U and V)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PSTRTU,PSTRTV ! TURBULENT FLUX OF MOMENTUM (U and V)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFCCQL,PFCCQN ! CONVECTIVE CONDENSATION FLUX FOR LIQUID WATER/ICE.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFCSQL,PFCSQN ! STRATIFORM CONDENSATION FLUX FOR LIQUID WATER/ICE.
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFSQRF,PFSQSF ! RAIN/SNOW FLUX FROM LS CLOUD SCHEME
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFSQLTUR,PFSQITUR ! LIQUID/ICE FLUX DUE TO VDF
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFRSOD,PFRSODC  ! DOWNWARD (CLEAR-SKY) SHORTWAVE FLUX AT SURFACE
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFRTHD,PFRTHDC  ! DOWNWARD (CLEAR-SKY) LONGWAVE FLUX AT SURFACE
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PUVDF,PPARF     ! DOWNWARD UV,PAR FLUX AT SURFACE
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PPARCF          ! CLEAR-SKY DOWNWARD PAR FLUX AT SURFACE
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PTOFDU,PTOFDV   ! TOFD COMP. OF TURBULENT FLUX OF U/V-MOMEMTUM
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFTG12          ! HEAT FLUX FROM LAYER 1 TO 2  ! NOT USED
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFWG12          ! WATER FLUX FROM LAYER 1 TO 2  ! NOT USED
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFWEV           ! SURFACE WATER VAPOUR FLUX (EVAPORATION)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFWSB           ! SURFACE WATER VAPOUR FLUX (SUBLIMATION)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFWMLT          ! WATER FLUX CORRESPONDING TO SURFACE SNOW MELT.
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFWROD          ! RUN-OFF FLUX AT DEEPER LAYERS (2-4)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFWRO1          ! RUN-OFF FLUX AT LAYER 1
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFTLHEV         ! SURFACE LATENT HEAT FLUX (SNOW FREE FRACTION)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFTLHSB         ! SURFACE LATENT HEAT FLUX (SNOW COVERED FRACTION)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PENES         !  ???
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PAERODDF    ! Diagnostic array with aerosol fluxes (sources and sinks)

  ! Storage fields to provide thread-local views
  TYPE(FIELD_2D), POINTER :: F_PFRSOD, F_PFRSODC, F_PFRTHD, F_PFRTHDC, F_PUVDF, F_PPARF, F_PPARCF, F_PTOFDU, F_PTOFDV, &
   & F_PFTG12, F_PFWG12, F_PFWEV, F_PFWSB, F_PFWMLT, F_PFWROD, F_PFWRO1, F_PFTLHEV, F_PFTLHSB
  TYPE(FIELD_3D), POINTER :: F_PFRSOC, F_PFRTHC, F_PDIFCQ, F_PDIFCS, F_PDIFTQ, F_PDIFTI, F_PDIFTL, F_PDIFTS, F_PFCQNG, &
   & F_PFCQLNG, F_PFCQNNG, F_PFCQRNG, F_PFCQSNG, F_PFPLCL, F_PFPLCN, F_PFPLSL, F_PFPLSN, F_PFHPCL, F_PFHPCN, F_PFHPSL, &
   & F_PFHPSN, F_PFRSO, F_PFRTH, F_PSTRCU, F_PSTRCV, F_PSTRDU, F_PSTRDV, F_PSTRTU, F_PSTRTV, F_PFCCQL, F_PFCCQN, F_PFCSQL, &
   & F_PFCSQN, F_PFSQRF, F_PFSQSF, F_PFSQLTUR, F_PFSQITUR, F_PENES
  TYPE(FIELD_4D), POINTER :: F_PAERODDF

CONTAINS
  PROCEDURE :: INIT => FLUX_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => FLUX_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => FLUX_TYPE_FINAL
END TYPE FLUX_TYPE

CONTAINS

  SUBROUTINE FLUX_TYPE_INIT(SELF, REGISTRY, NLEV, NLEVS, NACTAERO, NPAERODIAG, PERSISTENT)
    CLASS(FLUX_TYPE) :: SELF
    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
    INTEGER(KIND=JPIM), INTENT(IN) :: NLEV, NLEVS, NACTAERO, NPAERODIAG
    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT

    SELF%F_PFRSOD => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFRSODC => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PUVDF => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PPARF => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PPARCF => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFRTHD => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFRTHDC => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PTOFDU => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PTOFDV => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFTG12 => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFWEV => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFWSB => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFWG12 => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFWMLT => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFWROD => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFWRO1 => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFTLHEV => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFTLHSB => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFRSOC => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=2, PERSISTENT=PERSISTENT)
    SELF%F_PFRTHC => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=2, PERSISTENT=PERSISTENT)
    SELF%F_PDIFCQ => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PDIFCS => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PDIFTQ => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PDIFTS => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFCQNG => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFPLCL => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFPLCN => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFPLSL => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFPLSN => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFHPCL => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFHPCN => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFHPSL => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFHPSN => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFRSO => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFRTH => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PSTRCU => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PSTRCV => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PSTRDU => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PSTRDV => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PSTRTU => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PSTRTV => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PDIFTL => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PDIFTI => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFCCQL => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFCCQN => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFCSQL => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFCSQN => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFCQLNG => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFCQNNG => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFSQRF => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFSQSF => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFCQRNG => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFCQSNG => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFSQLTUR => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PFSQITUR => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_PENES => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEVS, PERSISTENT=PERSISTENT)
    SELF%F_PAERODDF => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NACTAERO, NDIM=NPAERODIAG, PERSISTENT=PERSISTENT)
  END SUBROUTINE FLUX_TYPE_INIT

  SUBROUTINE FLUX_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(FLUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    SELF%PFRSOD => SELF%F_PFRSOD%GET_VIEW(BLOCK_INDEX)
    SELF%PFRSODC => SELF%F_PFRSODC%GET_VIEW(BLOCK_INDEX)
    SELF%PUVDF => SELF%F_PUVDF%GET_VIEW(BLOCK_INDEX)
    SELF%PPARF => SELF%F_PPARF%GET_VIEW(BLOCK_INDEX)
    SELF%PPARCF => SELF%F_PPARCF%GET_VIEW(BLOCK_INDEX)
    SELF%PFRTHD => SELF%F_PFRTHD%GET_VIEW(BLOCK_INDEX)
    SELF%PFRTHDC => SELF%F_PFRTHDC%GET_VIEW(BLOCK_INDEX)
    SELF%PTOFDU => SELF%F_PTOFDU%GET_VIEW(BLOCK_INDEX)
    SELF%PTOFDV => SELF%F_PTOFDV%GET_VIEW(BLOCK_INDEX)
    SELF%PFTG12 => SELF%F_PFTG12%GET_VIEW(BLOCK_INDEX)
    SELF%PFWEV => SELF%F_PFWEV%GET_VIEW(BLOCK_INDEX)
    SELF%PFWSB => SELF%F_PFWSB%GET_VIEW(BLOCK_INDEX)
    SELF%PFWG12 => SELF%F_PFWG12%GET_VIEW(BLOCK_INDEX)
    SELF%PFWMLT => SELF%F_PFWMLT%GET_VIEW(BLOCK_INDEX)
    SELF%PFWROD => SELF%F_PFWROD%GET_VIEW(BLOCK_INDEX)
    SELF%PFWRO1 => SELF%F_PFWRO1%GET_VIEW(BLOCK_INDEX)
    SELF%PFTLHEV => SELF%F_PFTLHEV%GET_VIEW(BLOCK_INDEX)
    SELF%PFTLHSB => SELF%F_PFTLHSB%GET_VIEW(BLOCK_INDEX)
    SELF%PFRSOC(1:,0:) => SELF%F_PFRSOC%GET_VIEW(BLOCK_INDEX)
    SELF%PFRTHC(1:,0:) => SELF%F_PFRTHC%GET_VIEW(BLOCK_INDEX)
    SELF%PDIFCQ(1:,0:) => SELF%F_PDIFCQ%GET_VIEW(BLOCK_INDEX)
    SELF%PDIFCS(1:,0:) => SELF%F_PDIFCS%GET_VIEW(BLOCK_INDEX)
    SELF%PDIFTQ(1:,0:) => SELF%F_PDIFTQ%GET_VIEW(BLOCK_INDEX)
    SELF%PDIFTS(1:,0:) => SELF%F_PDIFTS%GET_VIEW(BLOCK_INDEX)
    SELF%PFCQNG(1:,0:) => SELF%F_PFCQNG%GET_VIEW(BLOCK_INDEX)
    SELF%PFPLCL(1:,0:) => SELF%F_PFPLCL%GET_VIEW(BLOCK_INDEX)
    SELF%PFPLCN(1:,0:) => SELF%F_PFPLCN%GET_VIEW(BLOCK_INDEX)
    SELF%PFPLSL(1:,0:) => SELF%F_PFPLSL%GET_VIEW(BLOCK_INDEX)
    SELF%PFPLSN(1:,0:) => SELF%F_PFPLSN%GET_VIEW(BLOCK_INDEX)
    SELF%PFHPCL(1:,0:) => SELF%F_PFHPCL%GET_VIEW(BLOCK_INDEX)
    SELF%PFHPCN(1:,0:) => SELF%F_PFHPCN%GET_VIEW(BLOCK_INDEX)
    SELF%PFHPSL(1:,0:) => SELF%F_PFHPSL%GET_VIEW(BLOCK_INDEX)
    SELF%PFHPSN(1:,0:) => SELF%F_PFHPSN%GET_VIEW(BLOCK_INDEX)
    SELF%PFRSO(1:,0:) => SELF%F_PFRSO%GET_VIEW(BLOCK_INDEX)
    SELF%PFRTH(1:,0:) => SELF%F_PFRTH%GET_VIEW(BLOCK_INDEX)
    SELF%PSTRCU(1:,0:) => SELF%F_PSTRCU%GET_VIEW(BLOCK_INDEX)
    SELF%PSTRCV(1:,0:) => SELF%F_PSTRCV%GET_VIEW(BLOCK_INDEX)
    SELF%PSTRDU(1:,0:) => SELF%F_PSTRDU%GET_VIEW(BLOCK_INDEX)
    SELF%PSTRDV(1:,0:) => SELF%F_PSTRDV%GET_VIEW(BLOCK_INDEX)
    SELF%PSTRTU(1:,0:) => SELF%F_PSTRTU%GET_VIEW(BLOCK_INDEX)
    SELF%PSTRTV(1:,0:) => SELF%F_PSTRTV%GET_VIEW(BLOCK_INDEX)
    SELF%PDIFTL(1:,0:) => SELF%F_PDIFTL%GET_VIEW(BLOCK_INDEX)
    SELF%PDIFTI(1:,0:) => SELF%F_PDIFTI%GET_VIEW(BLOCK_INDEX)
    SELF%PFCCQL(1:,0:) => SELF%F_PFCCQL%GET_VIEW(BLOCK_INDEX)
    SELF%PFCCQN(1:,0:) => SELF%F_PFCCQN%GET_VIEW(BLOCK_INDEX)
    SELF%PFCSQL(1:,0:) => SELF%F_PFCSQL%GET_VIEW(BLOCK_INDEX)
    SELF%PFCSQN(1:,0:) => SELF%F_PFCSQN%GET_VIEW(BLOCK_INDEX)
    SELF%PFCQLNG(1:,0:) => SELF%F_PFCQLNG%GET_VIEW(BLOCK_INDEX)
    SELF%PFCQNNG(1:,0:) => SELF%F_PFCQNNG%GET_VIEW(BLOCK_INDEX)
    SELF%PFSQRF(1:,0:) => SELF%F_PFSQRF%GET_VIEW(BLOCK_INDEX)
    SELF%PFSQSF(1:,0:) => SELF%F_PFSQSF%GET_VIEW(BLOCK_INDEX)
    SELF%PFCQRNG(1:,0:) => SELF%F_PFCQRNG%GET_VIEW(BLOCK_INDEX)
    SELF%PFCQSNG(1:,0:) => SELF%F_PFCQSNG%GET_VIEW(BLOCK_INDEX)
    SELF%PFSQLTUR(1:,0:) => SELF%F_PFSQLTUR%GET_VIEW(BLOCK_INDEX)
    SELF%PFSQITUR(1:,0:) => SELF%F_PFSQITUR%GET_VIEW(BLOCK_INDEX)
    SELF%PAERODDF => SELF%F_PAERODDF%GET_VIEW(BLOCK_INDEX)
    SELF%PENES => SELF%F_PENES%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE FLUX_TYPE_UPDATE_VIEW

  SUBROUTINE FLUX_TYPE_FINAL(SELF)
    CLASS(FLUX_TYPE) :: SELF

    CALL DELETE_TEMPORARY(SELF%F_PFRSOD)
    CALL DELETE_TEMPORARY(SELF%F_PFRSODC)
    CALL DELETE_TEMPORARY(SELF%F_PUVDF)
    CALL DELETE_TEMPORARY(SELF%F_PPARF)
    CALL DELETE_TEMPORARY(SELF%F_PPARCF)
    CALL DELETE_TEMPORARY(SELF%F_PFRTHD)
    CALL DELETE_TEMPORARY(SELF%F_PFRTHDC)
    CALL DELETE_TEMPORARY(SELF%F_PTOFDU)
    CALL DELETE_TEMPORARY(SELF%F_PTOFDV)
    CALL DELETE_TEMPORARY(SELF%F_PFTG12)
    CALL DELETE_TEMPORARY(SELF%F_PFWEV)
    CALL DELETE_TEMPORARY(SELF%F_PFWSB)
    CALL DELETE_TEMPORARY(SELF%F_PFWG12)
    CALL DELETE_TEMPORARY(SELF%F_PFWMLT)
    CALL DELETE_TEMPORARY(SELF%F_PFWROD)
    CALL DELETE_TEMPORARY(SELF%F_PFWRO1)
    CALL DELETE_TEMPORARY(SELF%F_PFTLHEV)
    CALL DELETE_TEMPORARY(SELF%F_PFTLHSB)
    CALL DELETE_TEMPORARY(SELF%F_PFRSOC)
    CALL DELETE_TEMPORARY(SELF%F_PFRTHC)
    CALL DELETE_TEMPORARY(SELF%F_PDIFCQ)
    CALL DELETE_TEMPORARY(SELF%F_PDIFCS)
    CALL DELETE_TEMPORARY(SELF%F_PDIFTQ)
    CALL DELETE_TEMPORARY(SELF%F_PDIFTS)
    CALL DELETE_TEMPORARY(SELF%F_PFCQNG)
    CALL DELETE_TEMPORARY(SELF%F_PFPLCL)
    CALL DELETE_TEMPORARY(SELF%F_PFPLCN)
    CALL DELETE_TEMPORARY(SELF%F_PFPLSL)
    CALL DELETE_TEMPORARY(SELF%F_PFPLSN)
    CALL DELETE_TEMPORARY(SELF%F_PFHPCL)
    CALL DELETE_TEMPORARY(SELF%F_PFHPCN)
    CALL DELETE_TEMPORARY(SELF%F_PFHPSL)
    CALL DELETE_TEMPORARY(SELF%F_PFHPSN)
    CALL DELETE_TEMPORARY(SELF%F_PFRSO)
    CALL DELETE_TEMPORARY(SELF%F_PFRTH)
    CALL DELETE_TEMPORARY(SELF%F_PSTRCU)
    CALL DELETE_TEMPORARY(SELF%F_PSTRCV)
    CALL DELETE_TEMPORARY(SELF%F_PSTRDU)
    CALL DELETE_TEMPORARY(SELF%F_PSTRDV)
    CALL DELETE_TEMPORARY(SELF%F_PSTRTU)
    CALL DELETE_TEMPORARY(SELF%F_PSTRTV)
    CALL DELETE_TEMPORARY(SELF%F_PDIFTL)
    CALL DELETE_TEMPORARY(SELF%F_PDIFTI)
    CALL DELETE_TEMPORARY(SELF%F_PFCCQL)
    CALL DELETE_TEMPORARY(SELF%F_PFCCQN)
    CALL DELETE_TEMPORARY(SELF%F_PFCSQL)
    CALL DELETE_TEMPORARY(SELF%F_PFCSQN)
    CALL DELETE_TEMPORARY(SELF%F_PFCQLNG)
    CALL DELETE_TEMPORARY(SELF%F_PFCQNNG)
    CALL DELETE_TEMPORARY(SELF%F_PFSQRF)
    CALL DELETE_TEMPORARY(SELF%F_PFSQSF)
    CALL DELETE_TEMPORARY(SELF%F_PFCQRNG)
    CALL DELETE_TEMPORARY(SELF%F_PFCQSNG)
    CALL DELETE_TEMPORARY(SELF%F_PFSQLTUR)
    CALL DELETE_TEMPORARY(SELF%F_PFSQITUR)
    CALL DELETE_TEMPORARY(SELF%F_PENES)
    CALL DELETE_TEMPORARY(SELF%F_PAERODDF)
  END SUBROUTINE FLUX_TYPE_FINAL

END MODULE ECPHYS_FLUX_TYPE_MOD
