MODULE ECPHYS_AUX_DIAG_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_MODULE, ONLY: FIELD_2D, FIELD_3D, FIELD_4D, FIELD_INT2D
USE FIELD_REGISTRY_MOD, ONLY: FIELD_REGISTRY, CREATE_TEMPORARY, CREATE_TEMPORARY_INT2D, DELETE_TEMPORARY

IMPLICIT NONE

TYPE AUX_DIAG_TYPE
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCAPE      !  CONVECTIVE AVAILABLE POTENTIAL ENERGY (J/KG)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: ZCAPE      !  CAPE (J/KG) archive diagnostic
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCBASE     !  CLOUD BASE HEIGHT
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCBASEA    !  CLOUD BASE HEIGHT AVIATION
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCTOPC     !  CLOUD TOP  HEIGHT CONVECTIVE
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: P0DEGL     ! 0 DEGREE CELSIUS LEVEL
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PVISIH     ! HORIZONTAL VISIBILITY
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCIN       ! CIN
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PVDIS      ! TURBULENT DISSIPATION
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PVDISG     ! GRAVITY WAVE DRAG DISSIPATION
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PUSTRG     ! GRAVITY WAVE DRAG SURFACE U-STRESS
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PVSTRG     ! GRAVITY WAVE DRAG SURFACE V-STRESS
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PI10FG     ! WIND GUST AT 10 m FOR CURRENT TIME LEVEL (m/s)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PPRECTYPE  ! Precipitation type
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFZRA      ! Freezing rain rate
  !INTEGER(KIND=JPIM),dimension(:), pointer :: KTYPE    ! Convection type (0,1,2)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCONVIND ! CONVECTIVE INDICES
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PZTWETB  ! HEIGHT OF 0 1 DEG C WET BULB TEMPERATURE
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PQSAT    ! SPECIFIC HUMIDITY AT SATURATION.
  ! Stored tendencies before convection (used in 1D var)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PZTENT, PZTENQ
  !    3D DIAGNOSTICS FOR ERA40
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PMFUDE_RATE   ! UD detrainmnet rate (KG/(M3*S))
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PMFDDE_RATE   ! DD detrainmnet rate (KG/(M3*S))
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PKH_VDF       ! turbulent diffusion coefficient for heat 
  !    array for precipitation fraction
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCOVPTOT     !  PRECIPITATION FRACTION IN EACH LAYER
  ! Convection and PBL types
  INTEGER(KIND=JPIM), DIMENSION(:), POINTER, CONTIGUOUS :: ITYPE, ICBOT, ICTOP
  INTEGER(KIND=JPIM), DIMENSION(:), POINTER, CONTIGUOUS :: IPBLTYPE
  ! Convection to cloud communication
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PMFU,PMFD    !  Conv. mass flux up/down
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLUDE      ! DETRAINED TOTAL CONDENSATE
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER, CONTIGUOUS:: ZLUDELI    ! DETRAINED LIQUID, ICE, VAPOR, T
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLU        ! LIQUID WATER CONTENT IN UPDRAFTS
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLRAIN     ! RAIN+SNOW WATER CONTENT IN UPDRAFTS
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER, CONTIGUOUS:: ZSNDE      ! DETRAINED SNOW/RAIN
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER, CONTIGUOUS:: PRSUD      ! VOLUME MEAN CONVECTIVE RAIN AND SNOW CONTENT
  ! Lightning fields
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PLIGH_TOT !  Total lightning density (intra-cloud and cloud-to-ground) (flash/km2/year)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PLIGH_CTG !  Cloud-to-ground lightning density (flash/km2/year)

  ! Storage fields to provide thread-local views
  TYPE(FIELD_2D), POINTER :: F_PCAPE, F_ZCAPE, F_PCBASE, F_PCBASEA, F_PCTOPC, F_P0DEGL, F_PVISIH, F_PCIN, F_PVDIS, &
   & F_PVDISG, F_PUSTRG, F_PVSTRG, F_PI10FG, F_PPRECTYPE, F_PFZRA, F_PLIGH_TOT, F_PLIGH_CTG
  TYPE(FIELD_3D), POINTER :: F_PCONVIND, F_PZTWETB, F_PQSAT, F_PZTENT, F_PZTENQ, F_PMFUDE_RATE, F_PMFDDE_RATE, F_PKH_VDF, &
   & F_PCOVPTOT, F_PMFU, F_PMFD, F_ZLUDE, F_ZLU, F_ZLRAIN
  TYPE(FIELD_4D), POINTER :: F_ZLUDELI, F_ZSNDE, F_PRSUD
  TYPE(FIELD_INT2D), POINTER :: F_ITYPE, F_ICBOT, F_ICTOP, F_IPBLTYPE

CONTAINS
  PROCEDURE :: INIT => AUX_DIAG_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => AUX_DIAG_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => AUX_DIAG_TYPE_FINAL
END TYPE AUX_DIAG_TYPE


TYPE AUX_DIAG_LOCAL_TYPE
  INTEGER(KIND=JPIM)                                 :: IEXT3D   ! position in extra field for diagnostics
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: ZWND     ! horizontal wind in the lowest model level
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: ZCCNL, ZCCNO
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: ZRAINFRAC_TOPRFZ => NULL() ! rain fraction at top of melting layer
  INTEGER(KIND=JPIM), DIMENSION(:), POINTER, CONTIGUOUS :: ITOPC, IBASC, IBOTSC
  ! radiation scheme for convenience
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS ::  ZEMIT ! Diagnosed surface broadband longwave emissivity
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS ::  ZTRSOD, ZSUDU !  radiation working arrays
  ! Skin temperature from radiation
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: ZTSKRAD   !  Skin temperature from radiation
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS ::  ZTHT ! half level temperature
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS ::  ZCTRSO,ZCEMTR ! radiation working arrays
  !     LOCAL 3D ARRAYS TO PASS OUTPUT FROM GWD TO IMPLICIT SOLVER OF VDF
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZSOTEU    ! Explicit part of U-tendency from subgrid orography scheme
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZSOTEV    ! Explicit part of V-tendency from subgrid orography scheme
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZSOBETA   ! Implicit part of subgrid orography
  ! aerosols in microphysics
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLCRIT_AER ! critical liquid mmr for rain autoconversion process
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZICRIT_AER ! critical liquid mmr for snow autoconversion process
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZRE_LIQ    ! effective radius liquid
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZRE_ICE    ! effective radius ice
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZCCN       ! CCN (prognostic, diagnostic)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZNICE      ! ice no concentration
  !    Local arrays for new cloud scheme of the linearized model
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZPATMP     ! CLOUD COVER OF INDIVIDUAL LAYER
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZPLSMP     ! ICE WATER CONTENT
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZPLTMP     ! LIQUID WATER CONTENT
  ! liquid water loading in environment neglected in convection
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLISUM     ! Local array for sum of liquid water and ice to be available
  ! local arrays variables for lightning
  ! REAL(KIND=JPRB)    :: ZLIGH_TOT(KDIM%KLON), ZLIGH_CTG(KDIM%KLON), ZLIGH_EMI(KDIM%KLON), ZWMFU(KDIM%KLON)
  ! REAL(KIND=JPRB)    :: ZCTOPH(KDIM%KLON), ZPRECMX(KDIM%KLON), ZICETOT(KDIM%KLON), ZCDEPTH(KDIM%KLON)

  ! Storage fields to provide thread-local views
  TYPE(FIELD_2D), POINTER :: F_ZWND, F_ZCCNL, F_ZCCNO, F_ZRAINFRAC_TOPRFZ, F_ZEMIT, F_ZTRSOD, F_ZSUDU, F_ZTSKRAD
  TYPE(FIELD_3D), POINTER :: F_ZTHT, F_ZCTRSO, F_ZCEMTR, F_ZSOTEU, F_ZSOTEV, F_ZSOBETA, F_ZLCRIT_AER, F_ZICRIT_AER, &
   & F_ZRE_LIQ, F_ZRE_ICE, F_ZCCN, F_ZNICE, F_ZPATMP, F_ZPLSMP, F_ZPLTMP, F_ZLISUM
  TYPE(FIELD_INT2D), POINTER :: F_ITOPC, F_IBASC, F_IBOTSC

CONTAINS
  PROCEDURE :: INIT => AUX_DIAG_LOCAL_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => AUX_DIAG_LOCAL_TYPE_FINAL
END TYPE AUX_DIAG_LOCAL_TYPE


CONTAINS

  SUBROUTINE AUX_DIAG_TYPE_INIT(SELF, REGISTRY, NLEV, PERSISTENT)
    CLASS(AUX_DIAG_TYPE) :: SELF
    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
    INTEGER(KIND=JPIM), INTENT(IN) :: NLEV
    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT

    SELF%F_PCAPE => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ZCAPE => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PCBASE => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PCBASEA => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PCTOPC => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_P0DEGL => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PVISIH => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PCIN => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PVDIS => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PVDISG => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PUSTRG => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PVSTRG => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PI10FG => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PPRECTYPE => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PFZRA => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PCONVIND => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=2, PERSISTENT=PERSISTENT)
    SELF%F_PZTWETB => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=2, PERSISTENT=PERSISTENT)
    SELF%F_PQSAT => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_PZTENT => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_PZTENQ => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_PMFUDE_RATE => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_PMFDDE_RATE => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_PKH_VDF => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_PCOVPTOT => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_PMFU => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_PMFD => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZLUDE => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZLUDELI => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, NDIM=4, PERSISTENT=PERSISTENT)
    SELF%F_ZSNDE => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, NDIM=2, PERSISTENT=PERSISTENT)
    SELF%F_PRSUD => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV,NDIM=2, PERSISTENT=PERSISTENT)
    SELF%F_ZLU => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZLRAIN => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_PLIGH_TOT => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_PLIGH_CTG => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ITYPE => CREATE_TEMPORARY_INT2D(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ICBOT => CREATE_TEMPORARY_INT2D(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ICTOP => CREATE_TEMPORARY_INT2D(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_IPBLTYPE => CREATE_TEMPORARY_INT2D(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
  END SUBROUTINE AUX_DIAG_TYPE_INIT

  SUBROUTINE AUX_DIAG_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(AUX_DIAG_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    SELF%PCAPE => SELF%F_PCAPE%GET_VIEW(BLOCK_INDEX)
    SELF%ZCAPE => SELF%F_ZCAPE%GET_VIEW(BLOCK_INDEX)
    SELF%PCBASE => SELF%F_PCBASE%GET_VIEW(BLOCK_INDEX)
    SELF%PCBASEA => SELF%F_PCBASEA%GET_VIEW(BLOCK_INDEX)
    SELF%PCTOPC => SELF%F_PCTOPC%GET_VIEW(BLOCK_INDEX)
    SELF%P0DEGL => SELF%F_P0DEGL%GET_VIEW(BLOCK_INDEX)
    SELF%PVISIH => SELF%F_PVISIH%GET_VIEW(BLOCK_INDEX)
    SELF%PCIN => SELF%F_PCIN%GET_VIEW(BLOCK_INDEX)
    SELF%PVDIS => SELF%F_PVDIS%GET_VIEW(BLOCK_INDEX)
    SELF%PVDISG => SELF%F_PVDISG%GET_VIEW(BLOCK_INDEX)
    SELF%PUSTRG => SELF%F_PUSTRG%GET_VIEW(BLOCK_INDEX)
    SELF%PVSTRG => SELF%F_PVSTRG%GET_VIEW(BLOCK_INDEX)
    SELF%PI10FG => SELF%F_PI10FG%GET_VIEW(BLOCK_INDEX)
    SELF%PPRECTYPE => SELF%F_PPRECTYPE%GET_VIEW(BLOCK_INDEX)
    SELF%PFZRA => SELF%F_PFZRA%GET_VIEW(BLOCK_INDEX)
    SELF%PCONVIND => SELF%F_PCONVIND%GET_VIEW(BLOCK_INDEX)
    SELF%PZTWETB => SELF%F_PZTWETB%GET_VIEW(BLOCK_INDEX)
    SELF%PQSAT => SELF%F_PQSAT%GET_VIEW(BLOCK_INDEX)
    SELF%PZTENT => SELF%F_PZTENT%GET_VIEW(BLOCK_INDEX)
    SELF%PZTENQ => SELF%F_PZTENQ%GET_VIEW(BLOCK_INDEX)
    SELF%PMFUDE_RATE => SELF%F_PMFUDE_RATE%GET_VIEW(BLOCK_INDEX)
    SELF%PMFDDE_RATE => SELF%F_PMFDDE_RATE%GET_VIEW(BLOCK_INDEX)
    SELF%PKH_VDF => SELF%F_PKH_VDF%GET_VIEW(BLOCK_INDEX)
    SELF%PCOVPTOT => SELF%F_PCOVPTOT%GET_VIEW(BLOCK_INDEX)
    SELF%PMFU => SELF%F_PMFU%GET_VIEW(BLOCK_INDEX)
    SELF%PMFD => SELF%F_PMFD%GET_VIEW(BLOCK_INDEX)
    SELF%ZLUDE => SELF%F_ZLUDE%GET_VIEW(BLOCK_INDEX)
    SELF%ZLUDELI => SELF%F_ZLUDELI%GET_VIEW(BLOCK_INDEX)
    SELF%ZSNDE => SELF%F_ZSNDE%GET_VIEW(BLOCK_INDEX)
    SELF%PRSUD => SELF%F_PRSUD%GET_VIEW(BLOCK_INDEX)
    SELF%ZLU => SELF%F_ZLU%GET_VIEW(BLOCK_INDEX)
    SELF%ZLRAIN => SELF%F_ZLRAIN%GET_VIEW(BLOCK_INDEX)
    SELF%PLIGH_TOT => SELF%F_PLIGH_TOT%GET_VIEW(BLOCK_INDEX)
    SELF%PLIGH_CTG => SELF%F_PLIGH_CTG%GET_VIEW(BLOCK_INDEX)
    SELF%ITYPE => SELF%F_ITYPE%GET_VIEW(BLOCK_INDEX)
    SELF%ICBOT => SELF%F_ICBOT%GET_VIEW(BLOCK_INDEX)
    SELF%ICTOP => SELF%F_ICTOP%GET_VIEW(BLOCK_INDEX)
    SELF%IPBLTYPE => SELF%F_IPBLTYPE%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE AUX_DIAG_TYPE_UPDATE_VIEW

  SUBROUTINE AUX_DIAG_TYPE_FINAL(SELF)
    CLASS(AUX_DIAG_TYPE) :: SELF

    CALL DELETE_TEMPORARY(SELF%F_PCAPE)
    CALL DELETE_TEMPORARY(SELF%F_ZCAPE)
    CALL DELETE_TEMPORARY(SELF%F_PCBASE)
    CALL DELETE_TEMPORARY(SELF%F_PCBASEA)
    CALL DELETE_TEMPORARY(SELF%F_PCTOPC)
    CALL DELETE_TEMPORARY(SELF%F_P0DEGL)
    CALL DELETE_TEMPORARY(SELF%F_PVISIH)
    CALL DELETE_TEMPORARY(SELF%F_PCIN)
    CALL DELETE_TEMPORARY(SELF%F_PVDIS)
    CALL DELETE_TEMPORARY(SELF%F_PVDISG)
    CALL DELETE_TEMPORARY(SELF%F_PUSTRG)
    CALL DELETE_TEMPORARY(SELF%F_PVSTRG)
    CALL DELETE_TEMPORARY(SELF%F_PI10FG)
    CALL DELETE_TEMPORARY(SELF%F_PPRECTYPE)
    CALL DELETE_TEMPORARY(SELF%F_PFZRA)
    CALL DELETE_TEMPORARY(SELF%F_PCONVIND)
    CALL DELETE_TEMPORARY(SELF%F_PZTWETB)
    CALL DELETE_TEMPORARY(SELF%F_PQSAT)
    CALL DELETE_TEMPORARY(SELF%F_PZTENT)
    CALL DELETE_TEMPORARY(SELF%F_PZTENQ)
    CALL DELETE_TEMPORARY(SELF%F_PMFUDE_RATE)
    CALL DELETE_TEMPORARY(SELF%F_PMFDDE_RATE)
    CALL DELETE_TEMPORARY(SELF%F_PKH_VDF)
    CALL DELETE_TEMPORARY(SELF%F_PCOVPTOT)
    CALL DELETE_TEMPORARY(SELF%F_PMFU)
    CALL DELETE_TEMPORARY(SELF%F_PMFD)
    CALL DELETE_TEMPORARY(SELF%F_ZLUDE)
    CALL DELETE_TEMPORARY(SELF%F_ZLUDELI)
    CALL DELETE_TEMPORARY(SELF%F_ZSNDE)
    CALL DELETE_TEMPORARY(SELF%F_PRSUD)
    CALL DELETE_TEMPORARY(SELF%F_ZLU)
    CALL DELETE_TEMPORARY(SELF%F_ZLRAIN)
    CALL DELETE_TEMPORARY(SELF%F_PLIGH_TOT)
    CALL DELETE_TEMPORARY(SELF%F_PLIGH_CTG)
    CALL DELETE_TEMPORARY(SELF%F_ITYPE)
    CALL DELETE_TEMPORARY(SELF%F_ICBOT)
    CALL DELETE_TEMPORARY(SELF%F_ICTOP)
    CALL DELETE_TEMPORARY(SELF%F_IPBLTYPE)
  END SUBROUTINE AUX_DIAG_TYPE_FINAL


  SUBROUTINE AUX_DIAG_LOCAL_TYPE_INIT(SELF, REGISTRY, NLEV, PERSISTENT)
    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
    INTEGER(KIND=JPIM), INTENT(IN) :: NLEV
    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT

    SELF%F_ZWND => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ZCCNL => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ZCCNO => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ZEMIT => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ZTRSOD => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ZSUDU => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ZTSKRAD => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ZRAINFRAC_TOPRFZ => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_ZTHT => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV+1, PERSISTENT=PERSISTENT)
    SELF%F_ZSOTEU => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZSOTEV => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZSOBETA => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZLCRIT_AER => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZICRIT_AER => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZRE_LIQ => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZRE_ICE => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZCCN => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZNICE => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZPATMP => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZPLTMP => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZPLSMP => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZLISUM => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=NLEV, PERSISTENT=PERSISTENT)
    SELF%F_ZCTRSO => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=2, PERSISTENT=PERSISTENT)
    SELF%F_ZCEMTR => CREATE_TEMPORARY(GEOM=REGISTRY%GEOM, NLEV=2, PERSISTENT=PERSISTENT)
    SELF%F_ITOPC => CREATE_TEMPORARY_INT2D(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_IBASC => CREATE_TEMPORARY_INT2D(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
    SELF%F_IBOTSC => CREATE_TEMPORARY_INT2D(GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)
  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_INIT

  SUBROUTINE AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    SELF%ZWND => SELF%F_ZWND%GET_VIEW(BLOCK_INDEX)
    SELF%ZCCNL => SELF%F_ZCCNL%GET_VIEW(BLOCK_INDEX)
    SELF%ZCCNO => SELF%F_ZCCNO%GET_VIEW(BLOCK_INDEX)
    SELF%ZEMIT => SELF%F_ZEMIT%GET_VIEW(BLOCK_INDEX)
    SELF%ZTRSOD => SELF%F_ZTRSOD%GET_VIEW(BLOCK_INDEX)
    SELF%ZSUDU => SELF%F_ZSUDU%GET_VIEW(BLOCK_INDEX)
    SELF%ZTSKRAD => SELF%F_ZTSKRAD%GET_VIEW(BLOCK_INDEX)
    SELF%ZRAINFRAC_TOPRFZ => SELF%F_ZRAINFRAC_TOPRFZ%GET_VIEW(BLOCK_INDEX)
    SELF%ZTHT(1:,0:) => SELF%F_ZTHT%GET_VIEW(BLOCK_INDEX)
    SELF%ZSOTEU => SELF%F_ZSOTEU%GET_VIEW(BLOCK_INDEX)
    SELF%ZSOTEV => SELF%F_ZSOTEV%GET_VIEW(BLOCK_INDEX)
    SELF%ZSOBETA => SELF%F_ZSOBETA%GET_VIEW(BLOCK_INDEX)
    SELF%ZLCRIT_AER => SELF%F_ZLCRIT_AER%GET_VIEW(BLOCK_INDEX)
    SELF%ZICRIT_AER => SELF%F_ZICRIT_AER%GET_VIEW(BLOCK_INDEX)
    SELF%ZRE_LIQ => SELF%F_ZRE_LIQ%GET_VIEW(BLOCK_INDEX)
    SELF%ZRE_ICE => SELF%F_ZRE_ICE%GET_VIEW(BLOCK_INDEX)
    SELF%ZCCN => SELF%F_ZCCN%GET_VIEW(BLOCK_INDEX)
    SELF%ZNICE => SELF%F_ZNICE%GET_VIEW(BLOCK_INDEX)
    SELF%ZPATMP => SELF%F_ZPATMP%GET_VIEW(BLOCK_INDEX)
    SELF%ZPLTMP => SELF%F_ZPLTMP%GET_VIEW(BLOCK_INDEX)
    SELF%ZPLSMP => SELF%F_ZPLSMP%GET_VIEW(BLOCK_INDEX)
    SELF%ZLISUM => SELF%F_ZLISUM%GET_VIEW(BLOCK_INDEX)
    SELF%ZCTRSO(1:,0:) => SELF%F_ZCTRSO%GET_VIEW(BLOCK_INDEX)
    SELF%ZCEMTR(1:,0:) => SELF%F_ZCEMTR%GET_VIEW(BLOCK_INDEX)
    SELF%ITOPC => SELF%F_ITOPC%GET_VIEW(BLOCK_INDEX)
    SELF%IBASC => SELF%F_IBASC%GET_VIEW(BLOCK_INDEX)
    SELF%IBOTSC => SELF%F_IBOTSC%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW

  SUBROUTINE AUX_DIAG_LOCAL_TYPE_FINAL(SELF)
    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF

    CALL DELETE_TEMPORARY(SELF%F_ZWND)
    CALL DELETE_TEMPORARY(SELF%F_ZCCNL)
    CALL DELETE_TEMPORARY(SELF%F_ZCCNO)
    CALL DELETE_TEMPORARY(SELF%F_ZEMIT)
    CALL DELETE_TEMPORARY(SELF%F_ZTRSOD)
    CALL DELETE_TEMPORARY(SELF%F_ZSUDU)
    CALL DELETE_TEMPORARY(SELF%F_ZTSKRAD)
    CALL DELETE_TEMPORARY(SELF%F_ZRAINFRAC_TOPRFZ)
    CALL DELETE_TEMPORARY(SELF%F_ZTHT)
    CALL DELETE_TEMPORARY(SELF%F_ZSOTEU)
    CALL DELETE_TEMPORARY(SELF%F_ZSOTEV)
    CALL DELETE_TEMPORARY(SELF%F_ZSOBETA)
    CALL DELETE_TEMPORARY(SELF%F_ZLCRIT_AER)
    CALL DELETE_TEMPORARY(SELF%F_ZICRIT_AER)
    CALL DELETE_TEMPORARY(SELF%F_ZRE_LIQ)
    CALL DELETE_TEMPORARY(SELF%F_ZRE_ICE)
    CALL DELETE_TEMPORARY(SELF%F_ZCCN)
    CALL DELETE_TEMPORARY(SELF%F_ZNICE)
    CALL DELETE_TEMPORARY(SELF%F_ZPATMP)
    CALL DELETE_TEMPORARY(SELF%F_ZPLTMP)
    CALL DELETE_TEMPORARY(SELF%F_ZPLSMP)
    CALL DELETE_TEMPORARY(SELF%F_ZLISUM)
    CALL DELETE_TEMPORARY(SELF%F_ZCTRSO)
    CALL DELETE_TEMPORARY(SELF%F_ZCEMTR)
    CALL DELETE_TEMPORARY(SELF%F_ITOPC)
    CALL DELETE_TEMPORARY(SELF%F_IBASC)
    CALL DELETE_TEMPORARY(SELF%F_IBOTSC)
  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_FINAL

END MODULE ECPHYS_AUX_DIAG_TYPE_MOD
