MODULE MF_PHYS_NEXT_STATE_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_MODULE
IMPLICIT NONE

TYPE MF_PHYS_NEXT_STATE_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: U (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: V (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SVD (:, :) => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: I (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: L (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LCONV (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ICONV (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RCONV (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SCONV (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: IRAD (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LRAD (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: S (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: R (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: G (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: H (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TKE (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TTE (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB1 (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB2 (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB3 (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: A (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: O3 (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SRC (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: MXL (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SHTUR (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FQTUR (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FSTUR (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CPF (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SPF (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CVGQ (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QVA (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LRCH4 (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHYCTY (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RSPEC (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SDSAT (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CVV (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RKTH (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RKTQV (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RKTQC (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UOM (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UAL (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DOM (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DAL (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UEN (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UNEBH (:, :) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FSD (:, :) => NULL ()

CONTAINS

  PROCEDURE :: INIT => MF_PHYS_NEXT_STATE_TYPE_INIT

END TYPE MF_PHYS_NEXT_STATE_TYPE

CONTAINS

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT (SELF, YDCPG_SL1, YDVARS, YDMODEL)

USE YOMCT0, ONLY : LSLAG, LTWOTL
USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
USE CPG_TYPE_MOD, ONLY : CPG_SL1_TYPE
USE TYPE_MODEL  , ONLY : MODEL

CLASS (MF_PHYS_NEXT_STATE_TYPE)        :: SELF
TYPE (CPG_SL1_TYPE),    INTENT (INOUT), TARGET :: YDCPG_SL1
TYPE (FIELD_VARIABLES), INTENT (INOUT), TARGET :: YDVARS
TYPE(MODEL),            INTENT (IN)    :: YDMODEL

ASSOCIATE (YDDYN => YDMODEL%YRML_DYN%YRDYN)

IF (LSLAG) THEN

  ! Taken from cp_ptrslb1.F90
  
  IF (YDDYN%NWLAG == 4) THEN
    SELF%U => YDCPG_SL1%U0 
    SELF%V => YDCPG_SL1%V0 
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%U => YDCPG_SL1%UF9 
      SELF%V => YDCPG_SL1%VF9 
    ELSE
      SELF%U => YDCPG_SL1%U9 
      SELF%V => YDCPG_SL1%V9 
    ENDIF
  ENDIF
  ! * temperature
  IF (YDDYN%NTLAG == 4) THEN
    SELF%T => YDCPG_SL1%T0 
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%T => YDCPG_SL1%TF9 
    ELSE
      SELF%T => YDCPG_SL1%T9 
    ENDIF
  ENDIF
  ! * vertical divergence
  IF (YDDYN%NSVDLAG == 4) THEN
    SELF%SVD => YDCPG_SL1%VD0
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%SVD => YDCPG_SL1%VDF9
    ELSE
      SELF%SVD => YDCPG_SL1%VD9
    ENDIF
  ENDIF

  ! * GFL arrays
  IF (YDDYN%LSPLTHOIGFL.OR.(YDDYN%NSPLTHOI /= 0)) THEN
    IF (YDVARS%Q%LADV) THEN
      SELF%Q => YDCPG_SL1%Q_F
    ELSE
      SELF%Q => YDVARS%Q%T1
    ENDIF
    IF (YDVARS%I%LADV) THEN
      SELF%I => YDCPG_SL1%I_F
    ELSE
      SELF%I => YDVARS%I%T1
    ENDIF
    IF (YDVARS%L%LADV) THEN
      SELF%L => YDCPG_SL1%L_F
    ELSE
      SELF%L => YDVARS%L%T1
    ENDIF
    IF (YDVARS%LCONV%LADV) THEN
      SELF%LCONV => YDCPG_SL1%LCONV_F
    ELSE
      SELF%LCONV => YDVARS%LCONV%T1
    ENDIF
    IF (YDVARS%ICONV%LADV) THEN
      SELF%ICONV => YDCPG_SL1%ICONV_F
    ELSE
      SELF%ICONV => YDVARS%ICONV%T1
    ENDIF
    IF (YDVARS%RCONV%LADV) THEN
      SELF%RCONV => YDCPG_SL1%RCONV_F
    ELSE
      SELF%RCONV => YDVARS%RCONV%T1
    ENDIF
    IF (YDVARS%SCONV%LADV) THEN
      SELF%SCONV => YDCPG_SL1%SCONV_F
    ELSE
      SELF%SCONV => YDVARS%SCONV%T1
    ENDIF
    IF (YDVARS%IRAD%LADV) THEN
      SELF%IRAD => YDCPG_SL1%IRAD_F
    ELSE
      SELF%IRAD => YDVARS%IRAD%T1
    ENDIF
    IF (YDVARS%LRAD%LADV) THEN
      SELF%LRAD => YDCPG_SL1%LRAD_F
    ELSE
      SELF%LRAD => YDVARS%LRAD%T1
    ENDIF
    IF (YDVARS%S%LADV) THEN
      SELF%S => YDCPG_SL1%S_F
    ELSE
      SELF%S => YDVARS%S%T1
    ENDIF
    IF (YDVARS%R%LADV) THEN
      SELF%R => YDCPG_SL1%R_F
    ELSE
      SELF%R => YDVARS%R%T1
    ENDIF
    IF (YDVARS%G%LADV) THEN
      SELF%G => YDCPG_SL1%G_F
    ELSE
      SELF%G => YDVARS%G%T1
    ENDIF
    IF (YDVARS%H%LADV) THEN
      SELF%H => YDCPG_SL1%H_F
    ELSE
      SELF%H => YDVARS%H%T1
    ENDIF
    IF (YDVARS%TKE%LADV) THEN
      SELF%TKE => YDCPG_SL1%TKE_F
    ELSE
      SELF%TKE => YDVARS%TKE%T1
    ENDIF
    IF (YDVARS%TTE%LADV) THEN
      SELF%TTE => YDCPG_SL1%TTE_F
    ELSE
      SELF%TTE => YDVARS%TTE%T1
    ENDIF
    IF (YDVARS%EFB1%LADV) THEN
      SELF%EFB1 => YDCPG_SL1%EFB1_F
    ELSE
      SELF%EFB1 => YDVARS%EFB1%T1
    ENDIF
    IF (YDVARS%EFB2%LADV) THEN
      SELF%EFB2 => YDCPG_SL1%EFB2_F
    ELSE
      SELF%EFB2 => YDVARS%EFB2%T1
    ENDIF
    IF (YDVARS%EFB3%LADV) THEN
      SELF%EFB3 => YDCPG_SL1%EFB3_F
    ELSE
      SELF%EFB3 => YDVARS%EFB3%T1
    ENDIF
    IF (YDVARS%A%LADV) THEN
      SELF%A => YDCPG_SL1%A_F
    ELSE
      SELF%A => YDVARS%A%T1
    ENDIF
    IF (YDVARS%O3%LADV) THEN
      SELF%O3 => YDCPG_SL1%O3_F
    ELSE
      SELF%O3 => YDVARS%O3%T1
    ENDIF
    IF (YDVARS%SRC%LADV) THEN
      SELF%SRC => YDCPG_SL1%SRC_F
    ELSE
      SELF%SRC => YDVARS%SRC%T1
    ENDIF
    IF (YDVARS%MXL%LADV) THEN
      SELF%MXL => YDCPG_SL1%MXL_F
    ELSE
      SELF%MXL => YDVARS%MXL%T1
    ENDIF
    IF (YDVARS%SHTUR%LADV) THEN
      SELF%SHTUR => YDCPG_SL1%SHTUR_F
    ELSE
      SELF%SHTUR => YDVARS%SHTUR%T1
    ENDIF
    IF (YDVARS%FQTUR%LADV) THEN
      SELF%FQTUR => YDCPG_SL1%FQTUR_F
    ELSE
      SELF%FQTUR => YDVARS%FQTUR%T1
    ENDIF
    IF (YDVARS%FSTUR%LADV) THEN
      SELF%FSTUR => YDCPG_SL1%FSTUR_F
    ELSE
      SELF%FSTUR => YDVARS%FSTUR%T1
    ENDIF
    IF (YDVARS%CPF%LADV) THEN
      SELF%CPF => YDCPG_SL1%CPF_F
    ELSE
      SELF%CPF => YDVARS%CPF%T1
    ENDIF
    IF (YDVARS%SPF%LADV) THEN
      SELF%SPF => YDCPG_SL1%SPF_F
    ELSE
      SELF%SPF => YDVARS%SPF%T1
    ENDIF
    IF (YDVARS%CVGQ%LADV) THEN
      SELF%CVGQ => YDCPG_SL1%CVGQ_F
    ELSE
      SELF%CVGQ => YDVARS%CVGQ%T1
    ENDIF
    IF (YDVARS%QVA%LADV) THEN
      SELF%QVA => YDCPG_SL1%QVA_F
    ELSE
      SELF%QVA => YDVARS%QVA%T1
    ENDIF
    IF (YDVARS%LRCH4%LADV) THEN
      SELF%LRCH4 => YDCPG_SL1%LRCH4_F
    ELSE
      SELF%LRCH4 => YDVARS%LRCH4%T1
    ENDIF
    IF (YDVARS%PHYCTY%LADV) THEN
      SELF%PHYCTY => YDCPG_SL1%PHYCTY_F
    ELSE
      SELF%PHYCTY => YDVARS%PHYCTY%T1
    ENDIF
    IF (YDVARS%RSPEC%LADV) THEN
      SELF%RSPEC => YDCPG_SL1%RSPEC_F
    ELSE
      SELF%RSPEC => YDVARS%RSPEC%T1
    ENDIF
    IF (YDVARS%SDSAT%LADV) THEN
      SELF%SDSAT => YDCPG_SL1%SDSAT_F
    ELSE
      SELF%SDSAT => YDVARS%SDSAT%T1
    ENDIF
    IF (YDVARS%CVV%LADV) THEN
      SELF%CVV => YDCPG_SL1%CVV_F
    ELSE
      SELF%CVV => YDVARS%CVV%T1
    ENDIF
    IF (YDVARS%RKTH%LADV) THEN
      SELF%RKTH => YDCPG_SL1%RKTH_F
    ELSE
      SELF%RKTH => YDVARS%RKTH%T1
    ENDIF
    IF (YDVARS%RKTQV%LADV) THEN
      SELF%RKTQV => YDCPG_SL1%RKTQV_F
    ELSE
      SELF%RKTQV => YDVARS%RKTQV%T1
    ENDIF
    IF (YDVARS%RKTQC%LADV) THEN
      SELF%RKTQC => YDCPG_SL1%RKTQC_F
    ELSE
      SELF%RKTQC => YDVARS%RKTQC%T1
    ENDIF
    IF (YDVARS%UOM%LADV) THEN
      SELF%UOM => YDCPG_SL1%UOM_F
    ELSE
      SELF%UOM => YDVARS%UOM%T1
    ENDIF
    IF (YDVARS%UAL%LADV) THEN
      SELF%UAL => YDCPG_SL1%UAL_F
    ELSE
      SELF%UAL => YDVARS%UAL%T1
    ENDIF
    IF (YDVARS%DOM%LADV) THEN
      SELF%DOM => YDCPG_SL1%DOM_F
    ELSE
      SELF%DOM => YDVARS%DOM%T1
    ENDIF
    IF (YDVARS%DAL%LADV) THEN
      SELF%DAL => YDCPG_SL1%DAL_F
    ELSE
      SELF%DAL => YDVARS%DAL%T1
    ENDIF
    IF (YDVARS%UEN%LADV) THEN
      SELF%UEN => YDCPG_SL1%UEN_F
    ELSE
      SELF%UEN => YDVARS%UEN%T1
    ENDIF
    IF (YDVARS%UNEBH%LADV) THEN
      SELF%UNEBH => YDCPG_SL1%UNEBH_F
    ELSE
      SELF%UNEBH => YDVARS%UNEBH%T1
    ENDIF
    IF (YDVARS%FSD%LADV) THEN
      SELF%FSD => YDCPG_SL1%FSD_F
    ELSE
      SELF%FSD => YDVARS%FSD%T1
    ENDIF
  ELSE
    IF (YDVARS%Q%LADV) THEN
      SELF%Q => YDCPG_SL1%Q
    ELSE
      SELF%Q => YDVARS%Q%T1
    ENDIF
    IF (YDVARS%I%LADV) THEN
      SELF%I => YDCPG_SL1%I
    ELSE
      SELF%I => YDVARS%I%T1
    ENDIF
    IF (YDVARS%L%LADV) THEN
      SELF%L => YDCPG_SL1%L
    ELSE
      SELF%L => YDVARS%L%T1
    ENDIF
    IF (YDVARS%LCONV%LADV) THEN
      SELF%LCONV => YDCPG_SL1%LCONV
    ELSE
      SELF%LCONV => YDVARS%LCONV%T1
    ENDIF
    IF (YDVARS%ICONV%LADV) THEN
      SELF%ICONV => YDCPG_SL1%ICONV
    ELSE
      SELF%ICONV => YDVARS%ICONV%T1
    ENDIF
    IF (YDVARS%RCONV%LADV) THEN
      SELF%RCONV => YDCPG_SL1%RCONV
    ELSE
      SELF%RCONV => YDVARS%RCONV%T1
    ENDIF
    IF (YDVARS%SCONV%LADV) THEN
      SELF%SCONV => YDCPG_SL1%SCONV
    ELSE
      SELF%SCONV => YDVARS%SCONV%T1
    ENDIF
    IF (YDVARS%IRAD%LADV) THEN
      SELF%IRAD => YDCPG_SL1%IRAD
    ELSE
      SELF%IRAD => YDVARS%IRAD%T1
    ENDIF
    IF (YDVARS%LRAD%LADV) THEN
      SELF%LRAD => YDCPG_SL1%LRAD
    ELSE
      SELF%LRAD => YDVARS%LRAD%T1
    ENDIF
    IF (YDVARS%S%LADV) THEN
      SELF%S => YDCPG_SL1%S
    ELSE
      SELF%S => YDVARS%S%T1
    ENDIF
    IF (YDVARS%R%LADV) THEN
      SELF%R => YDCPG_SL1%R
    ELSE
      SELF%R => YDVARS%R%T1
    ENDIF
    IF (YDVARS%G%LADV) THEN
      SELF%G => YDCPG_SL1%G
    ELSE
      SELF%G => YDVARS%G%T1
    ENDIF
    IF (YDVARS%H%LADV) THEN
      SELF%H => YDCPG_SL1%H
    ELSE
      SELF%H => YDVARS%H%T1
    ENDIF
    IF (YDVARS%TKE%LADV) THEN
      SELF%TKE => YDCPG_SL1%TKE
    ELSE
      SELF%TKE => YDVARS%TKE%T1
    ENDIF
    IF (YDVARS%TTE%LADV) THEN
      SELF%TTE => YDCPG_SL1%TTE
    ELSE
      SELF%TTE => YDVARS%TTE%T1
    ENDIF
    IF (YDVARS%EFB1%LADV) THEN
      SELF%EFB1 => YDCPG_SL1%EFB1
    ELSE
      SELF%EFB1 => YDVARS%EFB1%T1
    ENDIF
    IF (YDVARS%EFB2%LADV) THEN
      SELF%EFB2 => YDCPG_SL1%EFB2
    ELSE
      SELF%EFB2 => YDVARS%EFB2%T1
    ENDIF
    IF (YDVARS%EFB3%LADV) THEN
      SELF%EFB3 => YDCPG_SL1%EFB3
    ELSE
      SELF%EFB3 => YDVARS%EFB3%T1
    ENDIF
    IF (YDVARS%A%LADV) THEN
      SELF%A => YDCPG_SL1%A
    ELSE
      SELF%A => YDVARS%A%T1
    ENDIF
    IF (YDVARS%O3%LADV) THEN
      SELF%O3 => YDCPG_SL1%O3
    ELSE
      SELF%O3 => YDVARS%O3%T1
    ENDIF
    IF (YDVARS%SRC%LADV) THEN
      SELF%SRC => YDCPG_SL1%SRC
    ELSE
      SELF%SRC => YDVARS%SRC%T1
    ENDIF
    IF (YDVARS%MXL%LADV) THEN
      SELF%MXL => YDCPG_SL1%MXL
    ELSE
      SELF%MXL => YDVARS%MXL%T1
    ENDIF
    IF (YDVARS%SHTUR%LADV) THEN
      SELF%SHTUR => YDCPG_SL1%SHTUR
    ELSE
      SELF%SHTUR => YDVARS%SHTUR%T1
    ENDIF
    IF (YDVARS%FQTUR%LADV) THEN
      SELF%FQTUR => YDCPG_SL1%FQTUR
    ELSE
      SELF%FQTUR => YDVARS%FQTUR%T1
    ENDIF
    IF (YDVARS%FSTUR%LADV) THEN
      SELF%FSTUR => YDCPG_SL1%FSTUR
    ELSE
      SELF%FSTUR => YDVARS%FSTUR%T1
    ENDIF
    IF (YDVARS%CPF%LADV) THEN
      SELF%CPF => YDCPG_SL1%CPF
    ELSE
      SELF%CPF => YDVARS%CPF%T1
    ENDIF
    IF (YDVARS%SPF%LADV) THEN
      SELF%SPF => YDCPG_SL1%SPF
    ELSE
      SELF%SPF => YDVARS%SPF%T1
    ENDIF
    IF (YDVARS%CVGQ%LADV) THEN
      SELF%CVGQ => YDCPG_SL1%CVGQ
    ELSE
      SELF%CVGQ => YDVARS%CVGQ%T1
    ENDIF
    IF (YDVARS%QVA%LADV) THEN
      SELF%QVA => YDCPG_SL1%QVA
    ELSE
      SELF%QVA => YDVARS%QVA%T1
    ENDIF
    IF (YDVARS%LRCH4%LADV) THEN
      SELF%LRCH4 => YDCPG_SL1%LRCH4
    ELSE
      SELF%LRCH4 => YDVARS%LRCH4%T1
    ENDIF
    IF (YDVARS%PHYCTY%LADV) THEN
      SELF%PHYCTY => YDCPG_SL1%PHYCTY
    ELSE
      SELF%PHYCTY => YDVARS%PHYCTY%T1
    ENDIF
    IF (YDVARS%RSPEC%LADV) THEN
      SELF%RSPEC => YDCPG_SL1%RSPEC
    ELSE
      SELF%RSPEC => YDVARS%RSPEC%T1
    ENDIF
    IF (YDVARS%SDSAT%LADV) THEN
      SELF%SDSAT => YDCPG_SL1%SDSAT
    ELSE
      SELF%SDSAT => YDVARS%SDSAT%T1
    ENDIF
    IF (YDVARS%CVV%LADV) THEN
      SELF%CVV => YDCPG_SL1%CVV
    ELSE
      SELF%CVV => YDVARS%CVV%T1
    ENDIF
    IF (YDVARS%RKTH%LADV) THEN
      SELF%RKTH => YDCPG_SL1%RKTH
    ELSE
      SELF%RKTH => YDVARS%RKTH%T1
    ENDIF
    IF (YDVARS%RKTQV%LADV) THEN
      SELF%RKTQV => YDCPG_SL1%RKTQV
    ELSE
      SELF%RKTQV => YDVARS%RKTQV%T1
    ENDIF
    IF (YDVARS%RKTQC%LADV) THEN
      SELF%RKTQC => YDCPG_SL1%RKTQC
    ELSE
      SELF%RKTQC => YDVARS%RKTQC%T1
    ENDIF
    IF (YDVARS%UOM%LADV) THEN
      SELF%UOM => YDCPG_SL1%UOM
    ELSE
      SELF%UOM => YDVARS%UOM%T1
    ENDIF
    IF (YDVARS%UAL%LADV) THEN
      SELF%UAL => YDCPG_SL1%UAL
    ELSE
      SELF%UAL => YDVARS%UAL%T1
    ENDIF
    IF (YDVARS%DOM%LADV) THEN
      SELF%DOM => YDCPG_SL1%DOM
    ELSE
      SELF%DOM => YDVARS%DOM%T1
    ENDIF
    IF (YDVARS%DAL%LADV) THEN
      SELF%DAL => YDCPG_SL1%DAL
    ELSE
      SELF%DAL => YDVARS%DAL%T1
    ENDIF
    IF (YDVARS%UEN%LADV) THEN
      SELF%UEN => YDCPG_SL1%UEN
    ELSE
      SELF%UEN => YDVARS%UEN%T1
    ENDIF
    IF (YDVARS%UNEBH%LADV) THEN
      SELF%UNEBH => YDCPG_SL1%UNEBH
    ELSE
      SELF%UNEBH => YDVARS%UNEBH%T1
    ENDIF
    IF (YDVARS%FSD%LADV) THEN
      SELF%FSD => YDCPG_SL1%FSD
    ELSE
      SELF%FSD => YDVARS%FSD%T1
    ENDIF
  ENDIF  

ELSE

  SELF%U   => YDVARS%U%T1
  SELF%V   => YDVARS%V%T1
  SELF%T   => YDVARS%T%T1
  SELF%SVD => YDVARS%SVD%T1

  SELF%Q => YDVARS%Q%T1
  SELF%I => YDVARS%I%T1
  SELF%L => YDVARS%L%T1
  SELF%LCONV => YDVARS%LCONV%T1
  SELF%ICONV => YDVARS%ICONV%T1
  SELF%RCONV => YDVARS%RCONV%T1
  SELF%SCONV => YDVARS%SCONV%T1
  SELF%IRAD => YDVARS%IRAD%T1
  SELF%LRAD => YDVARS%LRAD%T1
  SELF%S => YDVARS%S%T1
  SELF%R => YDVARS%R%T1
  SELF%G => YDVARS%G%T1
  SELF%H => YDVARS%H%T1
  SELF%TKE => YDVARS%TKE%T1
  SELF%TTE => YDVARS%TTE%T1
  SELF%EFB1 => YDVARS%EFB1%T1
  SELF%EFB2 => YDVARS%EFB2%T1
  SELF%EFB3 => YDVARS%EFB3%T1
  SELF%A => YDVARS%A%T1
  SELF%O3 => YDVARS%O3%T1
  SELF%SRC => YDVARS%SRC%T1
  SELF%MXL => YDVARS%MXL%T1
  SELF%SHTUR => YDVARS%SHTUR%T1
  SELF%FQTUR => YDVARS%FQTUR%T1
  SELF%FSTUR => YDVARS%FSTUR%T1
  SELF%CPF => YDVARS%CPF%T1
  SELF%SPF => YDVARS%SPF%T1
  SELF%CVGQ => YDVARS%CVGQ%T1
  SELF%QVA => YDVARS%QVA%T1
  SELF%LRCH4 => YDVARS%LRCH4%T1
  SELF%PHYCTY => YDVARS%PHYCTY%T1
  SELF%RSPEC => YDVARS%RSPEC%T1
  SELF%SDSAT => YDVARS%SDSAT%T1
  SELF%CVV => YDVARS%CVV%T1
  SELF%RKTH => YDVARS%RKTH%T1
  SELF%RKTQV => YDVARS%RKTQV%T1
  SELF%RKTQC => YDVARS%RKTQC%T1
  SELF%UOM => YDVARS%UOM%T1
  SELF%UAL => YDVARS%UAL%T1
  SELF%DOM => YDVARS%DOM%T1
  SELF%DAL => YDVARS%DAL%T1
  SELF%UEN => YDVARS%UEN%T1
  SELF%UNEBH => YDVARS%UNEBH%T1
  SELF%FSD => YDVARS%FSD%T1

ENDIF

END ASSOCIATE

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT

END MODULE MF_PHYS_NEXT_STATE_TYPE_MOD
