MODULE MF_PHYS_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_MODULE
USE FIELD_REGISTRY_MOD

IMPLICIT NONE

TYPE MF_PHYS_OUT_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIFCQ (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIFCQ (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_DIFCQ => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIFCQL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIFCQL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_DIFCQL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIFCQN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIFCQN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_DIFCQN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIFCS (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIFCS (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_DIFCS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIFTQ (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIFTQ (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_DIFTQ => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIFTQL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIFTQL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_DIFTQL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIFTQN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIFTQN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_DIFTQN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIFTS (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIFTS (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_DIFTS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EDR (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: EDR (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_EDR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCCQL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCCQL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCCQL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCCQN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCCQN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCCQN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCSQL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCSQL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCSQL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCSQN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCSQN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCSQN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCQLNG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCQLNG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCQLNG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCQNNG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCQNNG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCQNNG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCQNG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCQNG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCQNG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPLCL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPLCL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPLCL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPLCN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPLCN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPLCN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPLCG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPLCG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPLCG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPLCH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPLCH (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPLCH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPLSL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPLSL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPLSL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPLSN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPLSN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPLSN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPLSG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPLSG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPLSG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPLSH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPLSH (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPLSH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPFPSL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPFPSL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPFPSL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPFPSN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPFPSN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPFPSN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPFPSG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPFPSG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPFPSG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPFPCL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPFPCL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPFPCL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPFPCN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPFPCN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPFPCN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPEVPSL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPEVPSL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPEVPSL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPEVPSN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPEVPSN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPEVPSN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPEVPSG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPEVPSG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPEVPSG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPEVPCL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPEVPCL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPEVPCL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPEVPCN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPEVPCN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPEVPCN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FPEVPCG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FPEVPCG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FPEVPCG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRSO (:, :, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FRSO (NPROMA, 0:YDCPG_OPTS%KFLEVG, 1:YDCPG_OPTS%KTSSG+1)
  TYPE (FIELD_4D), POINTER :: F_FRSO => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRTH (:, :, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FRTH (NPROMA, 0:YDCPG_OPTS%KFLEVG, 1:YDCPG_OPTS%KTSSG+1)
  TYPE (FIELD_4D), POINTER :: F_FRTH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STRCU (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: STRCU (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_STRCU => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STRCV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: STRCV (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_STRCV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STRDU (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: STRDU (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_STRDU => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STRDV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: STRDV (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_STRDV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STRTU (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: STRTU (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_STRTU => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STRTV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: STRTV (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_STRTV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STRMU (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: STRMU (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_STRMU => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STRMV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: STRMV (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_STRMV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIFCQLC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIFCQLC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_DIFCQLC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIFCQIC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIFCQIC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_DIFCQIC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FIMCC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FIMCC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FIMCC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FEDQLC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FEDQLC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FEDQLC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FEDQIC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FEDQIC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FEDQIC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FEDQRC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FEDQRC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FEDQRC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FEDQSC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FEDQSC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FEDQSC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCNEGQLC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCNEGQLC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCNEGQLC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCNEGQIC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCNEGQIC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCNEGQIC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCNEGQRC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCNEGQRC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCNEGQRC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCNEGQSC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCNEGQSC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCNEGQSC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRMH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FRMH (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FRMH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCHOZ (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCHOZ (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCHOZ => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FDIS (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FDIS (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FDIS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHPSL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHPSL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHPSL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHPSN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHPSN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHPSN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHPSG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHPSG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHPSG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHPCL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHPCL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHPCL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHPCN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHPCN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHPCN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHSCL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHSCL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHSCL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHSCN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHSCN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHSCN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHPCG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHPCG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHPCG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHSSL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHSSL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHSSL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHSSN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHSSN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHSSN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FEPFP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FEPFP (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FEPFP => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCMPCQ (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCMPCQ (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCMPCQ => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCMPSN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCMPSN (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCMPSN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FHSSG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FHSSG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FHSSG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCMPSL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCMPSL (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCMPSL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRSOC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FRSOC (NPROMA, 0:1)
  TYPE (FIELD_3D), POINTER :: F_FRSOC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRTHC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FRTHC (NPROMA, 0:1)
  TYPE (FIELD_3D), POINTER :: F_FRTHC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCHSP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCHSP (NPROMA, 1:YDCPG_OPTS%YRSURF_DIMS%YSP_SBD%NLEVS)
  TYPE (FIELD_3D), POINTER :: F_FCHSP => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCLL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCLL (NPROMA, 1:YDCPG_OPTS%KTSSG+1)
  TYPE (FIELD_3D), POINTER :: F_FCLL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCLN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCLN (NPROMA, 1:YDCPG_OPTS%KTSSG+1)
  TYPE (FIELD_3D), POINTER :: F_FCLN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCS (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCS (NPROMA, 1:YDCPG_OPTS%KTSSG+1)
  TYPE (FIELD_3D), POINTER :: F_FCS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FEVL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FEVL (NPROMA, 1:YDCPG_OPTS%KTSSG+1)
  TYPE (FIELD_3D), POINTER :: F_FEVL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FEVN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FEVN (NPROMA, 1:YDCPG_OPTS%KTSSG+1)
  TYPE (FIELD_3D), POINTER :: F_FEVN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FEVV (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FEVV (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FEVV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FLWSP (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FLWSP (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FLWSP => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FTR (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FTR (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FTR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRSODS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FRSODS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FRSODS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRSOPS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FRSOPS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FRSOPS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRSDNI (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FRSDNI (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FRSDNI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRSGNI (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FRSGNI (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FRSGNI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRTHDS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FRTHDS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FRTHDS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FONTE (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FONTE (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FONTE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FGEL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FGEL (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FGEL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FGELS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FGELS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FGELS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALB (:) => NULL ()
!>REAL (KIND=JPRB)                      :: ALB (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_ALB => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GZ0 (:) => NULL ()
!>REAL (KIND=JPRB)                      :: GZ0 (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_GZ0 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GZ0H (:) => NULL ()
!>REAL (KIND=JPRB)                      :: GZ0H (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_GZ0H => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RUISL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: RUISL (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_RUISL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RUISP (:) => NULL ()
!>REAL (KIND=JPRB)                      :: RUISP (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_RUISP => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RUISS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: RUISS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_RUISS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRSOPT (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FRSOPT (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FRSOPT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FRSOLU (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FRSOLU (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FRSOLU => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QCLS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: QCLS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_QCLS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TCLS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: TCLS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_TCLS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UCLS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: UCLS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_UCLS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VCLS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: VCLS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_VCLS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NUCLS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: NUCLS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_NUCLS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NVCLS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: NVCLS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_NVCLS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RHCLS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: RHCLS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_RHCLS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: MRT (:) => NULL ()
!>REAL (KIND=JPRB)                      :: MRT (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_MRT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CLCH (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CLCH (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_CLCH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CLCM (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CLCM (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_CLCM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CLCL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CLCL (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_CLCL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CLCC (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CLCC (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_CLCC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CLPH (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CLPH (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_CLPH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VEIN (:) => NULL ()
!>REAL (KIND=JPRB)                      :: VEIN (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_VEIN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DRNSHF (:) => NULL ()
!>REAL (KIND=JPRB)                      :: DRNSHF (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_DRNSHF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CAPE (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CAPE (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_CAPE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CTOP (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CTOP (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_CTOP => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: MOCON (:) => NULL ()
!>REAL (KIND=JPRB)                      :: MOCON (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_MOCON => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UGST (:) => NULL ()
!>REAL (KIND=JPRB)                      :: UGST (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_UGST => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VGST (:) => NULL ()
!>REAL (KIND=JPRB)                      :: VGST (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_VGST => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CT (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CT (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_CT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TENDU (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TENDU (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_TENDU => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TENDV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TENDV (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_TENDV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCQRNG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCQRNG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCQRNG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCQSNG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCQSNG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCQSNG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FCQGNG (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FCQGNG (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_FCQGNG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIAGH (:) => NULL ()
!>REAL (KIND=JPRB)                      :: DIAGH (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_DIAGH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VISICLD (:) => NULL ()
!>REAL (KIND=JPRB)                      :: VISICLD (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_VISICLD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FLASH (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FLASH (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_FLASH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VISIHYD (:) => NULL ()
!>REAL (KIND=JPRB)                      :: VISIHYD (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_VISIHYD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: MXCLWC (:) => NULL ()
!>REAL (KIND=JPRB)                      :: MXCLWC (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_MXCLWC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TPWCLS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: TPWCLS (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_TPWCLS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CUCONVCA (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CUCONVCA (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_CUCONVCA => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NLCONVCA (:) => NULL ()
!>REAL (KIND=JPRB)                      :: NLCONVCA (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_NLCONVCA => NULL ()

CONTAINS
  PROCEDURE :: INIT => MF_PHYS_OUT_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_OUT_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => MF_PHYS_OUT_TYPE_FINAL
END TYPE MF_PHYS_OUT_TYPE
TYPE MF_PHYS_OPT_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GDEOSI (:, :, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GDEOSI (NPROMA, 1:YDCPG_OPTS%KFLEVG, 1:2)
  TYPE (FIELD_4D), POINTER :: F_GDEOSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GUEOSI (:, :, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GUEOSI (NPROMA, 1:YDCPG_OPTS%KFLEVG, 1:2)
  TYPE (FIELD_4D), POINTER :: F_GUEOSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GMU0 (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GMU0 (NPROMA, 0:YDCPG_OPTS%KSORAYFR-1)
  TYPE (FIELD_3D), POINTER :: F_GMU0 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GMU0_MIN (:) => NULL ()
!>REAL (KIND=JPRB)                      :: GMU0_MIN (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_GMU0_MIN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GMU0_MAX (:) => NULL ()
!>REAL (KIND=JPRB)                      :: GMU0_MAX (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_GMU0_MAX => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GDEOTI (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GDEOTI (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_GDEOTI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GDEOTI2 (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GDEOTI2 (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_GDEOTI2 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GUEOTI (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GUEOTI (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_GUEOTI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GUEOTI2 (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GUEOTI2 (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_GUEOTI2 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GEOLT (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GEOLT (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_GEOLT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GEOXT (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GEOXT (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_GEOXT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GRPROX (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GRPROX (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_GRPROX => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GMIXP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GMIXP (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_GMIXP => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GFLUXC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GFLUXC (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_GFLUXC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GRSURF (:) => NULL ()
!>REAL (KIND=JPRB)                      :: GRSURF (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_GRSURF => NULL ()

CONTAINS
  PROCEDURE :: INIT => MF_PHYS_OPT_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_OPT_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => MF_PHYS_OPT_TYPE_FINAL
END TYPE MF_PHYS_OPT_TYPE
TYPE MF_PHYS_FOR_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: U (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: U (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_U => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: V (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: V (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_V => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: T (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_T => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: Q (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_Q => NULL ()

CONTAINS
  PROCEDURE :: INIT => MF_PHYS_FOR_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_FOR_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => MF_PHYS_FOR_TYPE_FINAL
END TYPE MF_PHYS_FOR_TYPE
TYPE MF_PHYS_GRA_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: G (:, :, :) => NULL ()
!>REAL (KIND=JPRB)                      :: G (NPROMA, 1:YDCPG_OPTS%KGRADIENTS, 1:NLEV)
  TYPE (FIELD_4D), POINTER :: F_G => NULL ()

CONTAINS
  PROCEDURE :: INIT => MF_PHYS_GRA_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_GRA_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => MF_PHYS_GRA_TYPE_FINAL
END TYPE MF_PHYS_GRA_TYPE
TYPE MF_PHYS_RAD_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EMTD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: EMTD (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_EMTD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EMTU (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: EMTU (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_EMTU => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TRSW (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TRSW (NPROMA, 0:YDCPG_OPTS%KFLEVG)
  TYPE (FIELD_3D), POINTER :: F_TRSW => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RMOON (:) => NULL ()
!>REAL (KIND=JPRB)                      :: RMOON (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_RMOON => NULL ()

CONTAINS
  PROCEDURE :: INIT => MF_PHYS_RAD_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_RAD_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => MF_PHYS_RAD_TYPE_FINAL
END TYPE MF_PHYS_RAD_TYPE

TYPE MF_PHYS_TYPE
  TYPE (MF_PHYS_OUT_TYPE) :: OUT
  TYPE (MF_PHYS_OPT_TYPE) :: OPT
  TYPE (MF_PHYS_FOR_TYPE) :: FOR
  TYPE (MF_PHYS_GRA_TYPE) :: GRA
  TYPE (MF_PHYS_RAD_TYPE) :: RAD
CONTAINS
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => MF_PHYS_TYPE_FINAL
END TYPE MF_PHYS_TYPE

REAL(KIND=JPRB),    PRIVATE, SAVE, TARGET :: ZDUM1 (1), ZDUM2 (1, 1), ZDUM3 (1,1,1)
INTEGER(KIND=JPIM), PRIVATE, SAVE, TARGET :: IDUM1 (1), IDUM2 (1, 1), IDUM3 (1,1,1)

CONTAINS




SUBROUTINE MF_PHYS_OUT_TYPE_INIT (SELF, REGISTRY, YDCPG_OPTS, PERSISTENT  )


USE CPG_OPTS_TYPE_MOD, ONLY : CPG_OPTS_TYPE


CLASS (MF_PHYS_OUT_TYPE)                    :: SELF
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
TYPE (CPG_OPTS_TYPE),         INTENT (IN)    :: YDCPG_OPTS
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT







SELF%F_DIFCQ => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_DIFCQL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_DIFCQN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_DIFCS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_DIFTQ => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_DIFTQL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_DIFTQN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_DIFTS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_EDR => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG, NLEV0=1, PERSISTENT=PERSISTENT)

SELF%F_FCCQL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCCQN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCSQL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCSQN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCQLNG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCQNNG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCQNG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPLCL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPLCN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPLCG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPLCH => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPLSL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPLSN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPLSG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPLSH => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPFPSL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPFPSN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPFPSG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPFPCL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPFPCN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPEVPSL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPEVPSN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPEVPSG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPEVPCL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPEVPCN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FPEVPCG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FRSO => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, NDIM=YDCPG_OPTS%KTSSG+1, NDIM0=1,&
    & PERSISTENT=PERSISTENT)

SELF%F_FRTH => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, NDIM=YDCPG_OPTS%KTSSG+1, NDIM0=1,&
    & PERSISTENT=PERSISTENT)

SELF%F_STRCU => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_STRCV => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_STRDU => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_STRDV => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_STRTU => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_STRTV => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_STRMU => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_STRMV => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_DIFCQLC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_DIFCQIC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FIMCC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FEDQLC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FEDQIC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FEDQRC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FEDQSC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCNEGQLC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCNEGQIC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCNEGQRC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCNEGQSC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FRMH => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCHOZ => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FDIS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHPSL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHPSN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHPSG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHPCL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHPCN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHSCL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHSCN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHPCG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHSSL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHSSN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FEPFP => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCMPCQ => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCMPSN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FHSSG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCMPSL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FRSOC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=1+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FRTHC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=1+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCHSP => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%YRSURF_DIMS%YSP_SBD%NLEVS, NLEV0=1, PERSISTENT=PERSISTENT)

SELF%F_FCLL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KTSSG+1, NLEV0=1, PERSISTENT=PERSISTENT)

SELF%F_FCLN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KTSSG+1, NLEV0=1, PERSISTENT=PERSISTENT)

SELF%F_FCS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KTSSG+1, NLEV0=1, PERSISTENT=PERSISTENT)

SELF%F_FEVL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KTSSG+1, NLEV0=1, PERSISTENT=PERSISTENT)

SELF%F_FEVN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KTSSG+1, NLEV0=1, PERSISTENT=PERSISTENT)

SELF%F_FEVV => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FLWSP => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FTR => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FRSODS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FRSOPS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FRSDNI => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FRSGNI => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FRTHDS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FONTE => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FGEL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FGELS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_ALB => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_GZ0 => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_GZ0H => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_RUISL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_RUISP => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_RUISS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FRSOPT => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FRSOLU => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_QCLS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_TCLS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_UCLS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_VCLS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_NUCLS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_NVCLS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_RHCLS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_MRT => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_CLCH => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_CLCM => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_CLCL => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_CLCC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_CLPH => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_VEIN => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_DRNSHF => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_CAPE => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_CTOP => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_MOCON => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_UGST => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_VGST => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_CT => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_TENDU => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG, NLEV0=1, PERSISTENT=PERSISTENT)

SELF%F_TENDV => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG, NLEV0=1, PERSISTENT=PERSISTENT)

SELF%F_FCQRNG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCQSNG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_FCQGNG => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, NLEV=YDCPG_OPTS%KFLEVG+1, NLEV0=0, PERSISTENT=PERSISTENT)

SELF%F_DIAGH => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_VISICLD => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_FLASH => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_VISIHYD => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_MXCLWC => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_TPWCLS => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_CUCONVCA => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)

SELF%F_NLCONVCA => CREATE_TEMPORARY (GEOM=REGISTRY%GEOM, PERSISTENT=PERSISTENT)


END SUBROUTINE MF_PHYS_OUT_TYPE_INIT

SUBROUTINE MF_PHYS_OUT_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (MF_PHYS_OUT_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

IF (ASSOCIATED (SELF%F_DIFCQ)) THEN
  SELF%DIFCQ  => SELF%F_DIFCQ%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIFCQ  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_DIFCQL)) THEN
  SELF%DIFCQL  => SELF%F_DIFCQL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIFCQL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_DIFCQN)) THEN
  SELF%DIFCQN  => SELF%F_DIFCQN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIFCQN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_DIFCS)) THEN
  SELF%DIFCS  => SELF%F_DIFCS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIFCS  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_DIFTQ)) THEN
  SELF%DIFTQ  => SELF%F_DIFTQ%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIFTQ  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_DIFTQL)) THEN
  SELF%DIFTQL  => SELF%F_DIFTQL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIFTQL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_DIFTQN)) THEN
  SELF%DIFTQN  => SELF%F_DIFTQN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIFTQN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_DIFTS)) THEN
  SELF%DIFTS  => SELF%F_DIFTS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIFTS  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_EDR)) THEN
  SELF%EDR  => SELF%F_EDR%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%EDR  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCCQL)) THEN
  SELF%FCCQL  => SELF%F_FCCQL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCCQL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCCQN)) THEN
  SELF%FCCQN  => SELF%F_FCCQN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCCQN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCSQL)) THEN
  SELF%FCSQL  => SELF%F_FCSQL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCSQL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCSQN)) THEN
  SELF%FCSQN  => SELF%F_FCSQN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCSQN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCQLNG)) THEN
  SELF%FCQLNG  => SELF%F_FCQLNG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCQLNG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCQNNG)) THEN
  SELF%FCQNNG  => SELF%F_FCQNNG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCQNNG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCQNG)) THEN
  SELF%FCQNG  => SELF%F_FCQNG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCQNG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPLCL)) THEN
  SELF%FPLCL  => SELF%F_FPLCL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPLCL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPLCN)) THEN
  SELF%FPLCN  => SELF%F_FPLCN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPLCN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPLCG)) THEN
  SELF%FPLCG  => SELF%F_FPLCG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPLCG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPLCH)) THEN
  SELF%FPLCH  => SELF%F_FPLCH%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPLCH  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPLSL)) THEN
  SELF%FPLSL  => SELF%F_FPLSL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPLSL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPLSN)) THEN
  SELF%FPLSN  => SELF%F_FPLSN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPLSN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPLSG)) THEN
  SELF%FPLSG  => SELF%F_FPLSG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPLSG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPLSH)) THEN
  SELF%FPLSH  => SELF%F_FPLSH%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPLSH  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPFPSL)) THEN
  SELF%FPFPSL  => SELF%F_FPFPSL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPFPSL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPFPSN)) THEN
  SELF%FPFPSN  => SELF%F_FPFPSN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPFPSN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPFPSG)) THEN
  SELF%FPFPSG  => SELF%F_FPFPSG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPFPSG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPFPCL)) THEN
  SELF%FPFPCL  => SELF%F_FPFPCL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPFPCL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPFPCN)) THEN
  SELF%FPFPCN  => SELF%F_FPFPCN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPFPCN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPEVPSL)) THEN
  SELF%FPEVPSL  => SELF%F_FPEVPSL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPEVPSL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPEVPSN)) THEN
  SELF%FPEVPSN  => SELF%F_FPEVPSN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPEVPSN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPEVPSG)) THEN
  SELF%FPEVPSG  => SELF%F_FPEVPSG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPEVPSG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPEVPCL)) THEN
  SELF%FPEVPCL  => SELF%F_FPEVPCL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPEVPCL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPEVPCN)) THEN
  SELF%FPEVPCN  => SELF%F_FPEVPCN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPEVPCN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FPEVPCG)) THEN
  SELF%FPEVPCG  => SELF%F_FPEVPCG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FPEVPCG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FRSO)) THEN
  SELF%FRSO  => SELF%F_FRSO%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRSO  => ZDUM3
ENDIF
IF (ASSOCIATED (SELF%F_FRTH)) THEN
  SELF%FRTH  => SELF%F_FRTH%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRTH  => ZDUM3
ENDIF
IF (ASSOCIATED (SELF%F_STRCU)) THEN
  SELF%STRCU  => SELF%F_STRCU%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%STRCU  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_STRCV)) THEN
  SELF%STRCV  => SELF%F_STRCV%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%STRCV  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_STRDU)) THEN
  SELF%STRDU  => SELF%F_STRDU%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%STRDU  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_STRDV)) THEN
  SELF%STRDV  => SELF%F_STRDV%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%STRDV  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_STRTU)) THEN
  SELF%STRTU  => SELF%F_STRTU%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%STRTU  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_STRTV)) THEN
  SELF%STRTV  => SELF%F_STRTV%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%STRTV  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_STRMU)) THEN
  SELF%STRMU  => SELF%F_STRMU%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%STRMU  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_STRMV)) THEN
  SELF%STRMV  => SELF%F_STRMV%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%STRMV  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_DIFCQLC)) THEN
  SELF%DIFCQLC  => SELF%F_DIFCQLC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIFCQLC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_DIFCQIC)) THEN
  SELF%DIFCQIC  => SELF%F_DIFCQIC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIFCQIC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FIMCC)) THEN
  SELF%FIMCC  => SELF%F_FIMCC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FIMCC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FEDQLC)) THEN
  SELF%FEDQLC  => SELF%F_FEDQLC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FEDQLC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FEDQIC)) THEN
  SELF%FEDQIC  => SELF%F_FEDQIC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FEDQIC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FEDQRC)) THEN
  SELF%FEDQRC  => SELF%F_FEDQRC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FEDQRC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FEDQSC)) THEN
  SELF%FEDQSC  => SELF%F_FEDQSC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FEDQSC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCNEGQLC)) THEN
  SELF%FCNEGQLC  => SELF%F_FCNEGQLC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCNEGQLC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCNEGQIC)) THEN
  SELF%FCNEGQIC  => SELF%F_FCNEGQIC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCNEGQIC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCNEGQRC)) THEN
  SELF%FCNEGQRC  => SELF%F_FCNEGQRC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCNEGQRC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCNEGQSC)) THEN
  SELF%FCNEGQSC  => SELF%F_FCNEGQSC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCNEGQSC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FRMH)) THEN
  SELF%FRMH  => SELF%F_FRMH%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRMH  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCHOZ)) THEN
  SELF%FCHOZ  => SELF%F_FCHOZ%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCHOZ  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FDIS)) THEN
  SELF%FDIS  => SELF%F_FDIS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FDIS  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHPSL)) THEN
  SELF%FHPSL  => SELF%F_FHPSL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHPSL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHPSN)) THEN
  SELF%FHPSN  => SELF%F_FHPSN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHPSN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHPSG)) THEN
  SELF%FHPSG  => SELF%F_FHPSG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHPSG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHPCL)) THEN
  SELF%FHPCL  => SELF%F_FHPCL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHPCL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHPCN)) THEN
  SELF%FHPCN  => SELF%F_FHPCN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHPCN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHSCL)) THEN
  SELF%FHSCL  => SELF%F_FHSCL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHSCL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHSCN)) THEN
  SELF%FHSCN  => SELF%F_FHSCN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHSCN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHPCG)) THEN
  SELF%FHPCG  => SELF%F_FHPCG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHPCG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHSSL)) THEN
  SELF%FHSSL  => SELF%F_FHSSL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHSSL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHSSN)) THEN
  SELF%FHSSN  => SELF%F_FHSSN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHSSN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FEPFP)) THEN
  SELF%FEPFP  => SELF%F_FEPFP%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FEPFP  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCMPCQ)) THEN
  SELF%FCMPCQ  => SELF%F_FCMPCQ%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCMPCQ  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCMPSN)) THEN
  SELF%FCMPSN  => SELF%F_FCMPSN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCMPSN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FHSSG)) THEN
  SELF%FHSSG  => SELF%F_FHSSG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FHSSG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCMPSL)) THEN
  SELF%FCMPSL  => SELF%F_FCMPSL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCMPSL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FRSOC)) THEN
  SELF%FRSOC  => SELF%F_FRSOC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRSOC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FRTHC)) THEN
  SELF%FRTHC  => SELF%F_FRTHC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRTHC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCHSP)) THEN
  SELF%FCHSP  => SELF%F_FCHSP%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCHSP  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCLL)) THEN
  SELF%FCLL  => SELF%F_FCLL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCLL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCLN)) THEN
  SELF%FCLN  => SELF%F_FCLN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCLN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCS)) THEN
  SELF%FCS  => SELF%F_FCS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCS  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FEVL)) THEN
  SELF%FEVL  => SELF%F_FEVL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FEVL  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FEVN)) THEN
  SELF%FEVN  => SELF%F_FEVN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FEVN  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FEVV)) THEN
  SELF%FEVV  => SELF%F_FEVV%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FEVV  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FLWSP)) THEN
  SELF%FLWSP  => SELF%F_FLWSP%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FLWSP  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FTR)) THEN
  SELF%FTR  => SELF%F_FTR%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FTR  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FRSODS)) THEN
  SELF%FRSODS  => SELF%F_FRSODS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRSODS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FRSOPS)) THEN
  SELF%FRSOPS  => SELF%F_FRSOPS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRSOPS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FRSDNI)) THEN
  SELF%FRSDNI  => SELF%F_FRSDNI%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRSDNI  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FRSGNI)) THEN
  SELF%FRSGNI  => SELF%F_FRSGNI%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRSGNI  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FRTHDS)) THEN
  SELF%FRTHDS  => SELF%F_FRTHDS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRTHDS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FONTE)) THEN
  SELF%FONTE  => SELF%F_FONTE%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FONTE  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FGEL)) THEN
  SELF%FGEL  => SELF%F_FGEL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FGEL  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FGELS)) THEN
  SELF%FGELS  => SELF%F_FGELS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FGELS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_ALB)) THEN
  SELF%ALB  => SELF%F_ALB%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%ALB  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_GZ0)) THEN
  SELF%GZ0  => SELF%F_GZ0%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GZ0  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_GZ0H)) THEN
  SELF%GZ0H  => SELF%F_GZ0H%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GZ0H  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_RUISL)) THEN
  SELF%RUISL  => SELF%F_RUISL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%RUISL  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_RUISP)) THEN
  SELF%RUISP  => SELF%F_RUISP%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%RUISP  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_RUISS)) THEN
  SELF%RUISS  => SELF%F_RUISS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%RUISS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FRSOPT)) THEN
  SELF%FRSOPT  => SELF%F_FRSOPT%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRSOPT  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FRSOLU)) THEN
  SELF%FRSOLU  => SELF%F_FRSOLU%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FRSOLU  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_QCLS)) THEN
  SELF%QCLS  => SELF%F_QCLS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%QCLS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_TCLS)) THEN
  SELF%TCLS  => SELF%F_TCLS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%TCLS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_UCLS)) THEN
  SELF%UCLS  => SELF%F_UCLS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%UCLS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_VCLS)) THEN
  SELF%VCLS  => SELF%F_VCLS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%VCLS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_NUCLS)) THEN
  SELF%NUCLS  => SELF%F_NUCLS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%NUCLS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_NVCLS)) THEN
  SELF%NVCLS  => SELF%F_NVCLS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%NVCLS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_RHCLS)) THEN
  SELF%RHCLS  => SELF%F_RHCLS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%RHCLS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_MRT)) THEN
  SELF%MRT  => SELF%F_MRT%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%MRT  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_CLCH)) THEN
  SELF%CLCH  => SELF%F_CLCH%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%CLCH  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_CLCM)) THEN
  SELF%CLCM  => SELF%F_CLCM%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%CLCM  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_CLCL)) THEN
  SELF%CLCL  => SELF%F_CLCL%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%CLCL  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_CLCC)) THEN
  SELF%CLCC  => SELF%F_CLCC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%CLCC  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_CLPH)) THEN
  SELF%CLPH  => SELF%F_CLPH%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%CLPH  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_VEIN)) THEN
  SELF%VEIN  => SELF%F_VEIN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%VEIN  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_DRNSHF)) THEN
  SELF%DRNSHF  => SELF%F_DRNSHF%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DRNSHF  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_CAPE)) THEN
  SELF%CAPE  => SELF%F_CAPE%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%CAPE  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_CTOP)) THEN
  SELF%CTOP  => SELF%F_CTOP%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%CTOP  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_MOCON)) THEN
  SELF%MOCON  => SELF%F_MOCON%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%MOCON  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_UGST)) THEN
  SELF%UGST  => SELF%F_UGST%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%UGST  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_VGST)) THEN
  SELF%VGST  => SELF%F_VGST%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%VGST  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_CT)) THEN
  SELF%CT  => SELF%F_CT%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%CT  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_TENDU)) THEN
  SELF%TENDU  => SELF%F_TENDU%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%TENDU  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_TENDV)) THEN
  SELF%TENDV  => SELF%F_TENDV%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%TENDV  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCQRNG)) THEN
  SELF%FCQRNG  => SELF%F_FCQRNG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCQRNG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCQSNG)) THEN
  SELF%FCQSNG  => SELF%F_FCQSNG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCQSNG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_FCQGNG)) THEN
  SELF%FCQGNG  => SELF%F_FCQGNG%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FCQGNG  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_DIAGH)) THEN
  SELF%DIAGH  => SELF%F_DIAGH%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%DIAGH  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_VISICLD)) THEN
  SELF%VISICLD  => SELF%F_VISICLD%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%VISICLD  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_FLASH)) THEN
  SELF%FLASH  => SELF%F_FLASH%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%FLASH  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_VISIHYD)) THEN
  SELF%VISIHYD  => SELF%F_VISIHYD%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%VISIHYD  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_MXCLWC)) THEN
  SELF%MXCLWC  => SELF%F_MXCLWC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%MXCLWC  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_TPWCLS)) THEN
  SELF%TPWCLS  => SELF%F_TPWCLS%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%TPWCLS  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_CUCONVCA)) THEN
  SELF%CUCONVCA  => SELF%F_CUCONVCA%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%CUCONVCA  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_NLCONVCA)) THEN
  SELF%NLCONVCA  => SELF%F_NLCONVCA%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%NLCONVCA  => ZDUM1
ENDIF

END SUBROUTINE MF_PHYS_OUT_TYPE_UPDATE_VIEW

SUBROUTINE MF_PHYS_OUT_TYPE_FINAL (SELF)
CLASS (MF_PHYS_OUT_TYPE)         :: SELF

IF (ASSOCIATED (SELF%F_DIFCQ)) CALL DELETE_TEMPORARY (SELF%F_DIFCQ) 
IF (ASSOCIATED (SELF%F_DIFCQL)) CALL DELETE_TEMPORARY (SELF%F_DIFCQL) 
IF (ASSOCIATED (SELF%F_DIFCQN)) CALL DELETE_TEMPORARY (SELF%F_DIFCQN) 
IF (ASSOCIATED (SELF%F_DIFCS)) CALL DELETE_TEMPORARY (SELF%F_DIFCS) 
IF (ASSOCIATED (SELF%F_DIFTQ)) CALL DELETE_TEMPORARY (SELF%F_DIFTQ) 
IF (ASSOCIATED (SELF%F_DIFTQL)) CALL DELETE_TEMPORARY (SELF%F_DIFTQL) 
IF (ASSOCIATED (SELF%F_DIFTQN)) CALL DELETE_TEMPORARY (SELF%F_DIFTQN) 
IF (ASSOCIATED (SELF%F_DIFTS)) CALL DELETE_TEMPORARY (SELF%F_DIFTS) 
IF (ASSOCIATED (SELF%F_EDR)) CALL DELETE_TEMPORARY (SELF%F_EDR) 
IF (ASSOCIATED (SELF%F_FCCQL)) CALL DELETE_TEMPORARY (SELF%F_FCCQL) 
IF (ASSOCIATED (SELF%F_FCCQN)) CALL DELETE_TEMPORARY (SELF%F_FCCQN) 
IF (ASSOCIATED (SELF%F_FCSQL)) CALL DELETE_TEMPORARY (SELF%F_FCSQL) 
IF (ASSOCIATED (SELF%F_FCSQN)) CALL DELETE_TEMPORARY (SELF%F_FCSQN) 
IF (ASSOCIATED (SELF%F_FCQLNG)) CALL DELETE_TEMPORARY (SELF%F_FCQLNG) 
IF (ASSOCIATED (SELF%F_FCQNNG)) CALL DELETE_TEMPORARY (SELF%F_FCQNNG) 
IF (ASSOCIATED (SELF%F_FCQNG)) CALL DELETE_TEMPORARY (SELF%F_FCQNG) 
IF (ASSOCIATED (SELF%F_FPLCL)) CALL DELETE_TEMPORARY (SELF%F_FPLCL) 
IF (ASSOCIATED (SELF%F_FPLCN)) CALL DELETE_TEMPORARY (SELF%F_FPLCN) 
IF (ASSOCIATED (SELF%F_FPLCG)) CALL DELETE_TEMPORARY (SELF%F_FPLCG) 
IF (ASSOCIATED (SELF%F_FPLCH)) CALL DELETE_TEMPORARY (SELF%F_FPLCH) 
IF (ASSOCIATED (SELF%F_FPLSL)) CALL DELETE_TEMPORARY (SELF%F_FPLSL) 
IF (ASSOCIATED (SELF%F_FPLSN)) CALL DELETE_TEMPORARY (SELF%F_FPLSN) 
IF (ASSOCIATED (SELF%F_FPLSG)) CALL DELETE_TEMPORARY (SELF%F_FPLSG) 
IF (ASSOCIATED (SELF%F_FPLSH)) CALL DELETE_TEMPORARY (SELF%F_FPLSH) 
IF (ASSOCIATED (SELF%F_FPFPSL)) CALL DELETE_TEMPORARY (SELF%F_FPFPSL) 
IF (ASSOCIATED (SELF%F_FPFPSN)) CALL DELETE_TEMPORARY (SELF%F_FPFPSN) 
IF (ASSOCIATED (SELF%F_FPFPSG)) CALL DELETE_TEMPORARY (SELF%F_FPFPSG) 
IF (ASSOCIATED (SELF%F_FPFPCL)) CALL DELETE_TEMPORARY (SELF%F_FPFPCL) 
IF (ASSOCIATED (SELF%F_FPFPCN)) CALL DELETE_TEMPORARY (SELF%F_FPFPCN) 
IF (ASSOCIATED (SELF%F_FPEVPSL)) CALL DELETE_TEMPORARY (SELF%F_FPEVPSL) 
IF (ASSOCIATED (SELF%F_FPEVPSN)) CALL DELETE_TEMPORARY (SELF%F_FPEVPSN) 
IF (ASSOCIATED (SELF%F_FPEVPSG)) CALL DELETE_TEMPORARY (SELF%F_FPEVPSG) 
IF (ASSOCIATED (SELF%F_FPEVPCL)) CALL DELETE_TEMPORARY (SELF%F_FPEVPCL) 
IF (ASSOCIATED (SELF%F_FPEVPCN)) CALL DELETE_TEMPORARY (SELF%F_FPEVPCN) 
IF (ASSOCIATED (SELF%F_FPEVPCG)) CALL DELETE_TEMPORARY (SELF%F_FPEVPCG) 
IF (ASSOCIATED (SELF%F_FRSO)) CALL DELETE_TEMPORARY (SELF%F_FRSO) 
IF (ASSOCIATED (SELF%F_FRTH)) CALL DELETE_TEMPORARY (SELF%F_FRTH) 
IF (ASSOCIATED (SELF%F_STRCU)) CALL DELETE_TEMPORARY (SELF%F_STRCU) 
IF (ASSOCIATED (SELF%F_STRCV)) CALL DELETE_TEMPORARY (SELF%F_STRCV) 
IF (ASSOCIATED (SELF%F_STRDU)) CALL DELETE_TEMPORARY (SELF%F_STRDU) 
IF (ASSOCIATED (SELF%F_STRDV)) CALL DELETE_TEMPORARY (SELF%F_STRDV) 
IF (ASSOCIATED (SELF%F_STRTU)) CALL DELETE_TEMPORARY (SELF%F_STRTU) 
IF (ASSOCIATED (SELF%F_STRTV)) CALL DELETE_TEMPORARY (SELF%F_STRTV) 
IF (ASSOCIATED (SELF%F_STRMU)) CALL DELETE_TEMPORARY (SELF%F_STRMU) 
IF (ASSOCIATED (SELF%F_STRMV)) CALL DELETE_TEMPORARY (SELF%F_STRMV) 
IF (ASSOCIATED (SELF%F_DIFCQLC)) CALL DELETE_TEMPORARY (SELF%F_DIFCQLC) 
IF (ASSOCIATED (SELF%F_DIFCQIC)) CALL DELETE_TEMPORARY (SELF%F_DIFCQIC) 
IF (ASSOCIATED (SELF%F_FIMCC)) CALL DELETE_TEMPORARY (SELF%F_FIMCC) 
IF (ASSOCIATED (SELF%F_FEDQLC)) CALL DELETE_TEMPORARY (SELF%F_FEDQLC) 
IF (ASSOCIATED (SELF%F_FEDQIC)) CALL DELETE_TEMPORARY (SELF%F_FEDQIC) 
IF (ASSOCIATED (SELF%F_FEDQRC)) CALL DELETE_TEMPORARY (SELF%F_FEDQRC) 
IF (ASSOCIATED (SELF%F_FEDQSC)) CALL DELETE_TEMPORARY (SELF%F_FEDQSC) 
IF (ASSOCIATED (SELF%F_FCNEGQLC)) CALL DELETE_TEMPORARY (SELF%F_FCNEGQLC) 
IF (ASSOCIATED (SELF%F_FCNEGQIC)) CALL DELETE_TEMPORARY (SELF%F_FCNEGQIC) 
IF (ASSOCIATED (SELF%F_FCNEGQRC)) CALL DELETE_TEMPORARY (SELF%F_FCNEGQRC) 
IF (ASSOCIATED (SELF%F_FCNEGQSC)) CALL DELETE_TEMPORARY (SELF%F_FCNEGQSC) 
IF (ASSOCIATED (SELF%F_FRMH)) CALL DELETE_TEMPORARY (SELF%F_FRMH) 
IF (ASSOCIATED (SELF%F_FCHOZ)) CALL DELETE_TEMPORARY (SELF%F_FCHOZ) 
IF (ASSOCIATED (SELF%F_FDIS)) CALL DELETE_TEMPORARY (SELF%F_FDIS) 
IF (ASSOCIATED (SELF%F_FHPSL)) CALL DELETE_TEMPORARY (SELF%F_FHPSL) 
IF (ASSOCIATED (SELF%F_FHPSN)) CALL DELETE_TEMPORARY (SELF%F_FHPSN) 
IF (ASSOCIATED (SELF%F_FHPSG)) CALL DELETE_TEMPORARY (SELF%F_FHPSG) 
IF (ASSOCIATED (SELF%F_FHPCL)) CALL DELETE_TEMPORARY (SELF%F_FHPCL) 
IF (ASSOCIATED (SELF%F_FHPCN)) CALL DELETE_TEMPORARY (SELF%F_FHPCN) 
IF (ASSOCIATED (SELF%F_FHSCL)) CALL DELETE_TEMPORARY (SELF%F_FHSCL) 
IF (ASSOCIATED (SELF%F_FHSCN)) CALL DELETE_TEMPORARY (SELF%F_FHSCN) 
IF (ASSOCIATED (SELF%F_FHPCG)) CALL DELETE_TEMPORARY (SELF%F_FHPCG) 
IF (ASSOCIATED (SELF%F_FHSSL)) CALL DELETE_TEMPORARY (SELF%F_FHSSL) 
IF (ASSOCIATED (SELF%F_FHSSN)) CALL DELETE_TEMPORARY (SELF%F_FHSSN) 
IF (ASSOCIATED (SELF%F_FEPFP)) CALL DELETE_TEMPORARY (SELF%F_FEPFP) 
IF (ASSOCIATED (SELF%F_FCMPCQ)) CALL DELETE_TEMPORARY (SELF%F_FCMPCQ) 
IF (ASSOCIATED (SELF%F_FCMPSN)) CALL DELETE_TEMPORARY (SELF%F_FCMPSN) 
IF (ASSOCIATED (SELF%F_FHSSG)) CALL DELETE_TEMPORARY (SELF%F_FHSSG) 
IF (ASSOCIATED (SELF%F_FCMPSL)) CALL DELETE_TEMPORARY (SELF%F_FCMPSL) 
IF (ASSOCIATED (SELF%F_FRSOC)) CALL DELETE_TEMPORARY (SELF%F_FRSOC) 
IF (ASSOCIATED (SELF%F_FRTHC)) CALL DELETE_TEMPORARY (SELF%F_FRTHC) 
IF (ASSOCIATED (SELF%F_FCHSP)) CALL DELETE_TEMPORARY (SELF%F_FCHSP) 
IF (ASSOCIATED (SELF%F_FCLL)) CALL DELETE_TEMPORARY (SELF%F_FCLL) 
IF (ASSOCIATED (SELF%F_FCLN)) CALL DELETE_TEMPORARY (SELF%F_FCLN) 
IF (ASSOCIATED (SELF%F_FCS)) CALL DELETE_TEMPORARY (SELF%F_FCS) 
IF (ASSOCIATED (SELF%F_FEVL)) CALL DELETE_TEMPORARY (SELF%F_FEVL) 
IF (ASSOCIATED (SELF%F_FEVN)) CALL DELETE_TEMPORARY (SELF%F_FEVN) 
IF (ASSOCIATED (SELF%F_FEVV)) CALL DELETE_TEMPORARY (SELF%F_FEVV) 
IF (ASSOCIATED (SELF%F_FLWSP)) CALL DELETE_TEMPORARY (SELF%F_FLWSP) 
IF (ASSOCIATED (SELF%F_FTR)) CALL DELETE_TEMPORARY (SELF%F_FTR) 
IF (ASSOCIATED (SELF%F_FRSODS)) CALL DELETE_TEMPORARY (SELF%F_FRSODS) 
IF (ASSOCIATED (SELF%F_FRSOPS)) CALL DELETE_TEMPORARY (SELF%F_FRSOPS) 
IF (ASSOCIATED (SELF%F_FRSDNI)) CALL DELETE_TEMPORARY (SELF%F_FRSDNI) 
IF (ASSOCIATED (SELF%F_FRSGNI)) CALL DELETE_TEMPORARY (SELF%F_FRSGNI) 
IF (ASSOCIATED (SELF%F_FRTHDS)) CALL DELETE_TEMPORARY (SELF%F_FRTHDS) 
IF (ASSOCIATED (SELF%F_FONTE)) CALL DELETE_TEMPORARY (SELF%F_FONTE) 
IF (ASSOCIATED (SELF%F_FGEL)) CALL DELETE_TEMPORARY (SELF%F_FGEL) 
IF (ASSOCIATED (SELF%F_FGELS)) CALL DELETE_TEMPORARY (SELF%F_FGELS) 
IF (ASSOCIATED (SELF%F_ALB)) CALL DELETE_TEMPORARY (SELF%F_ALB) 
IF (ASSOCIATED (SELF%F_GZ0)) CALL DELETE_TEMPORARY (SELF%F_GZ0) 
IF (ASSOCIATED (SELF%F_GZ0H)) CALL DELETE_TEMPORARY (SELF%F_GZ0H) 
IF (ASSOCIATED (SELF%F_RUISL)) CALL DELETE_TEMPORARY (SELF%F_RUISL) 
IF (ASSOCIATED (SELF%F_RUISP)) CALL DELETE_TEMPORARY (SELF%F_RUISP) 
IF (ASSOCIATED (SELF%F_RUISS)) CALL DELETE_TEMPORARY (SELF%F_RUISS) 
IF (ASSOCIATED (SELF%F_FRSOPT)) CALL DELETE_TEMPORARY (SELF%F_FRSOPT) 
IF (ASSOCIATED (SELF%F_FRSOLU)) CALL DELETE_TEMPORARY (SELF%F_FRSOLU) 
IF (ASSOCIATED (SELF%F_QCLS)) CALL DELETE_TEMPORARY (SELF%F_QCLS) 
IF (ASSOCIATED (SELF%F_TCLS)) CALL DELETE_TEMPORARY (SELF%F_TCLS) 
IF (ASSOCIATED (SELF%F_UCLS)) CALL DELETE_TEMPORARY (SELF%F_UCLS) 
IF (ASSOCIATED (SELF%F_VCLS)) CALL DELETE_TEMPORARY (SELF%F_VCLS) 
IF (ASSOCIATED (SELF%F_NUCLS)) CALL DELETE_TEMPORARY (SELF%F_NUCLS) 
IF (ASSOCIATED (SELF%F_NVCLS)) CALL DELETE_TEMPORARY (SELF%F_NVCLS) 
IF (ASSOCIATED (SELF%F_RHCLS)) CALL DELETE_TEMPORARY (SELF%F_RHCLS) 
IF (ASSOCIATED (SELF%F_MRT)) CALL DELETE_TEMPORARY (SELF%F_MRT) 
IF (ASSOCIATED (SELF%F_CLCH)) CALL DELETE_TEMPORARY (SELF%F_CLCH) 
IF (ASSOCIATED (SELF%F_CLCM)) CALL DELETE_TEMPORARY (SELF%F_CLCM) 
IF (ASSOCIATED (SELF%F_CLCL)) CALL DELETE_TEMPORARY (SELF%F_CLCL) 
IF (ASSOCIATED (SELF%F_CLCC)) CALL DELETE_TEMPORARY (SELF%F_CLCC) 
IF (ASSOCIATED (SELF%F_CLPH)) CALL DELETE_TEMPORARY (SELF%F_CLPH) 
IF (ASSOCIATED (SELF%F_VEIN)) CALL DELETE_TEMPORARY (SELF%F_VEIN) 
IF (ASSOCIATED (SELF%F_DRNSHF)) CALL DELETE_TEMPORARY (SELF%F_DRNSHF) 
IF (ASSOCIATED (SELF%F_CAPE)) CALL DELETE_TEMPORARY (SELF%F_CAPE) 
IF (ASSOCIATED (SELF%F_CTOP)) CALL DELETE_TEMPORARY (SELF%F_CTOP) 
IF (ASSOCIATED (SELF%F_MOCON)) CALL DELETE_TEMPORARY (SELF%F_MOCON) 
IF (ASSOCIATED (SELF%F_UGST)) CALL DELETE_TEMPORARY (SELF%F_UGST) 
IF (ASSOCIATED (SELF%F_VGST)) CALL DELETE_TEMPORARY (SELF%F_VGST) 
IF (ASSOCIATED (SELF%F_CT)) CALL DELETE_TEMPORARY (SELF%F_CT) 
IF (ASSOCIATED (SELF%F_TENDU)) CALL DELETE_TEMPORARY (SELF%F_TENDU) 
IF (ASSOCIATED (SELF%F_TENDV)) CALL DELETE_TEMPORARY (SELF%F_TENDV) 
IF (ASSOCIATED (SELF%F_FCQRNG)) CALL DELETE_TEMPORARY (SELF%F_FCQRNG) 
IF (ASSOCIATED (SELF%F_FCQSNG)) CALL DELETE_TEMPORARY (SELF%F_FCQSNG) 
IF (ASSOCIATED (SELF%F_FCQGNG)) CALL DELETE_TEMPORARY (SELF%F_FCQGNG) 
IF (ASSOCIATED (SELF%F_DIAGH)) CALL DELETE_TEMPORARY (SELF%F_DIAGH) 
IF (ASSOCIATED (SELF%F_VISICLD)) CALL DELETE_TEMPORARY (SELF%F_VISICLD) 
IF (ASSOCIATED (SELF%F_FLASH)) CALL DELETE_TEMPORARY (SELF%F_FLASH) 
IF (ASSOCIATED (SELF%F_VISIHYD)) CALL DELETE_TEMPORARY (SELF%F_VISIHYD) 
IF (ASSOCIATED (SELF%F_MXCLWC)) CALL DELETE_TEMPORARY (SELF%F_MXCLWC) 
IF (ASSOCIATED (SELF%F_TPWCLS)) CALL DELETE_TEMPORARY (SELF%F_TPWCLS) 
IF (ASSOCIATED (SELF%F_CUCONVCA)) CALL DELETE_TEMPORARY (SELF%F_CUCONVCA) 
IF (ASSOCIATED (SELF%F_NLCONVCA)) CALL DELETE_TEMPORARY (SELF%F_NLCONVCA) 

END SUBROUTINE MF_PHYS_OUT_TYPE_FINAL




SUBROUTINE MF_PHYS_OPT_TYPE_INIT (SELF, REGISTRY, YDCPG_OPTS, PERSISTENT, LDMF_PHYS, PGDEOSI, &
& PGUEOSI, PGMU0, PGMU0_MIN, PGMU0_MAX, PGDEOTI, PGDEOTI2, PGUEOTI, PGUEOTI2, PGEOLT, PGEOXT, &
& PGRPROX, PGMIXP, PGFLUXC, PGRSURF  )


USE CPG_OPTS_TYPE_MOD, ONLY : CPG_OPTS_TYPE


CLASS (MF_PHYS_OPT_TYPE)                    :: SELF
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
TYPE (CPG_OPTS_TYPE),         INTENT (IN)    :: YDCPG_OPTS
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT
LOGICAL, OPTIONAL,            INTENT (IN)    :: LDMF_PHYS

REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGDEOSI(:, :, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGUEOSI(:, :, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGMU0(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGMU0_MIN(:, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGMU0_MAX(:, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGDEOTI(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGDEOTI2(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGUEOTI(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGUEOTI2(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGEOLT(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGEOXT(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGRPROX(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGMIXP(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGFLUXC(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PGRSURF(:, :)

LOGICAL :: LLMF_PHYS




LLMF_PHYS = .FALSE.
IF (PRESENT (LDMF_PHYS)) THEN
  LLMF_PHYS = LDMF_PHYS
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGDEOSI)) THEN
      SELF%F_GDEOSI => CREATE_FIELD_WRAP (PGDEOSI, LBOUNDS=[1, 1, 1, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGUEOSI)) THEN
      SELF%F_GUEOSI => CREATE_FIELD_WRAP (PGUEOSI, LBOUNDS=[1, 1, 1, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGMU0)) THEN
      SELF%F_GMU0 => CREATE_FIELD_WRAP (PGMU0, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGMU0_MIN)) THEN
      SELF%F_GMU0_MIN => CREATE_FIELD_WRAP (PGMU0_MIN, LBOUNDS=[1, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGMU0_MAX)) THEN
      SELF%F_GMU0_MAX => CREATE_FIELD_WRAP (PGMU0_MAX, LBOUNDS=[1, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGDEOTI)) THEN
      SELF%F_GDEOTI => CREATE_FIELD_WRAP (PGDEOTI, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGDEOTI2)) THEN
      SELF%F_GDEOTI2 => CREATE_FIELD_WRAP (PGDEOTI2, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGUEOTI)) THEN
      SELF%F_GUEOTI => CREATE_FIELD_WRAP (PGUEOTI, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGUEOTI2)) THEN
      SELF%F_GUEOTI2 => CREATE_FIELD_WRAP (PGUEOTI2, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGEOLT)) THEN
      SELF%F_GEOLT => CREATE_FIELD_WRAP (PGEOLT, LBOUNDS=[1, 1, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGEOXT)) THEN
      SELF%F_GEOXT => CREATE_FIELD_WRAP (PGEOXT, LBOUNDS=[1, 1, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGRPROX)) THEN
      SELF%F_GRPROX => CREATE_FIELD_WRAP (PGRPROX, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGMIXP)) THEN
      SELF%F_GMIXP => CREATE_FIELD_WRAP (PGMIXP, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGFLUXC)) THEN
      SELF%F_GFLUXC => CREATE_FIELD_WRAP (PGFLUXC, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PGRSURF)) THEN
      SELF%F_GRSURF => CREATE_FIELD_WRAP (PGRSURF, LBOUNDS=[1, 1])
  ENDIF
ENDIF


END SUBROUTINE MF_PHYS_OPT_TYPE_INIT

SUBROUTINE MF_PHYS_OPT_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (MF_PHYS_OPT_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

IF (ASSOCIATED (SELF%F_GDEOSI)) THEN
  SELF%GDEOSI  => SELF%F_GDEOSI%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GDEOSI  => ZDUM3
ENDIF
IF (ASSOCIATED (SELF%F_GUEOSI)) THEN
  SELF%GUEOSI  => SELF%F_GUEOSI%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GUEOSI  => ZDUM3
ENDIF
IF (ASSOCIATED (SELF%F_GMU0)) THEN
  SELF%GMU0  => SELF%F_GMU0%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GMU0  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_GMU0_MIN)) THEN
  SELF%GMU0_MIN  => SELF%F_GMU0_MIN%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GMU0_MIN  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_GMU0_MAX)) THEN
  SELF%GMU0_MAX  => SELF%F_GMU0_MAX%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GMU0_MAX  => ZDUM1
ENDIF
IF (ASSOCIATED (SELF%F_GDEOTI)) THEN
  SELF%GDEOTI  => SELF%F_GDEOTI%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GDEOTI  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_GDEOTI2)) THEN
  SELF%GDEOTI2  => SELF%F_GDEOTI2%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GDEOTI2  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_GUEOTI)) THEN
  SELF%GUEOTI  => SELF%F_GUEOTI%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GUEOTI  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_GUEOTI2)) THEN
  SELF%GUEOTI2  => SELF%F_GUEOTI2%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GUEOTI2  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_GEOLT)) THEN
  SELF%GEOLT  => SELF%F_GEOLT%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GEOLT  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_GEOXT)) THEN
  SELF%GEOXT  => SELF%F_GEOXT%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GEOXT  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_GRPROX)) THEN
  SELF%GRPROX  => SELF%F_GRPROX%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GRPROX  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_GMIXP)) THEN
  SELF%GMIXP  => SELF%F_GMIXP%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GMIXP  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_GFLUXC)) THEN
  SELF%GFLUXC  => SELF%F_GFLUXC%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GFLUXC  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_GRSURF)) THEN
  SELF%GRSURF  => SELF%F_GRSURF%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%GRSURF  => ZDUM1
ENDIF

END SUBROUTINE MF_PHYS_OPT_TYPE_UPDATE_VIEW

SUBROUTINE MF_PHYS_OPT_TYPE_FINAL (SELF)
CLASS (MF_PHYS_OPT_TYPE)         :: SELF

IF (ASSOCIATED (SELF%F_GDEOSI)) CALL DELETE_TEMPORARY (SELF%F_GDEOSI) 
IF (ASSOCIATED (SELF%F_GUEOSI)) CALL DELETE_TEMPORARY (SELF%F_GUEOSI) 
IF (ASSOCIATED (SELF%F_GMU0)) CALL DELETE_TEMPORARY (SELF%F_GMU0) 
IF (ASSOCIATED (SELF%F_GMU0_MIN)) CALL DELETE_TEMPORARY (SELF%F_GMU0_MIN) 
IF (ASSOCIATED (SELF%F_GMU0_MAX)) CALL DELETE_TEMPORARY (SELF%F_GMU0_MAX) 
IF (ASSOCIATED (SELF%F_GDEOTI)) CALL DELETE_TEMPORARY (SELF%F_GDEOTI) 
IF (ASSOCIATED (SELF%F_GDEOTI2)) CALL DELETE_TEMPORARY (SELF%F_GDEOTI2) 
IF (ASSOCIATED (SELF%F_GUEOTI)) CALL DELETE_TEMPORARY (SELF%F_GUEOTI) 
IF (ASSOCIATED (SELF%F_GUEOTI2)) CALL DELETE_TEMPORARY (SELF%F_GUEOTI2) 
IF (ASSOCIATED (SELF%F_GEOLT)) CALL DELETE_TEMPORARY (SELF%F_GEOLT) 
IF (ASSOCIATED (SELF%F_GEOXT)) CALL DELETE_TEMPORARY (SELF%F_GEOXT) 
IF (ASSOCIATED (SELF%F_GRPROX)) CALL DELETE_TEMPORARY (SELF%F_GRPROX) 
IF (ASSOCIATED (SELF%F_GMIXP)) CALL DELETE_TEMPORARY (SELF%F_GMIXP) 
IF (ASSOCIATED (SELF%F_GFLUXC)) CALL DELETE_TEMPORARY (SELF%F_GFLUXC) 
IF (ASSOCIATED (SELF%F_GRSURF)) CALL DELETE_TEMPORARY (SELF%F_GRSURF) 

END SUBROUTINE MF_PHYS_OPT_TYPE_FINAL




SUBROUTINE MF_PHYS_FOR_TYPE_INIT (SELF, REGISTRY, YDCPG_OPTS, PERSISTENT, LDMF_PHYS, PU, PV, PT, PQ&
&   )


USE CPG_OPTS_TYPE_MOD, ONLY : CPG_OPTS_TYPE


CLASS (MF_PHYS_FOR_TYPE)                    :: SELF
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
TYPE (CPG_OPTS_TYPE),         INTENT (IN)    :: YDCPG_OPTS
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT
LOGICAL, OPTIONAL,            INTENT (IN)    :: LDMF_PHYS

REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PU(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PV(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PT(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PQ(:, :, :)

LOGICAL :: LLMF_PHYS




LLMF_PHYS = .FALSE.
IF (PRESENT (LDMF_PHYS)) THEN
  LLMF_PHYS = LDMF_PHYS
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PU)) THEN
      SELF%F_U => CREATE_FIELD_WRAP (PU, LBOUNDS=[1, 1, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PV)) THEN
      SELF%F_V => CREATE_FIELD_WRAP (PV, LBOUNDS=[1, 1, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PT)) THEN
      SELF%F_T => CREATE_FIELD_WRAP (PT, LBOUNDS=[1, 1, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PQ)) THEN
      SELF%F_Q => CREATE_FIELD_WRAP (PQ, LBOUNDS=[1, 1, 1])
  ENDIF
ENDIF


END SUBROUTINE MF_PHYS_FOR_TYPE_INIT

SUBROUTINE MF_PHYS_FOR_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (MF_PHYS_FOR_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

IF (ASSOCIATED (SELF%F_U)) THEN
  SELF%U  => SELF%F_U%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%U  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_V)) THEN
  SELF%V  => SELF%F_V%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%V  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_T)) THEN
  SELF%T  => SELF%F_T%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%T  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_Q)) THEN
  SELF%Q  => SELF%F_Q%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%Q  => ZDUM2
ENDIF

END SUBROUTINE MF_PHYS_FOR_TYPE_UPDATE_VIEW

SUBROUTINE MF_PHYS_FOR_TYPE_FINAL (SELF)
CLASS (MF_PHYS_FOR_TYPE)         :: SELF

IF (ASSOCIATED (SELF%F_U)) CALL DELETE_TEMPORARY (SELF%F_U) 
IF (ASSOCIATED (SELF%F_V)) CALL DELETE_TEMPORARY (SELF%F_V) 
IF (ASSOCIATED (SELF%F_T)) CALL DELETE_TEMPORARY (SELF%F_T) 
IF (ASSOCIATED (SELF%F_Q)) CALL DELETE_TEMPORARY (SELF%F_Q) 

END SUBROUTINE MF_PHYS_FOR_TYPE_FINAL




SUBROUTINE MF_PHYS_GRA_TYPE_INIT (SELF, REGISTRY, YDCPG_OPTS, PERSISTENT, LDMF_PHYS, PG  )


USE CPG_OPTS_TYPE_MOD, ONLY : CPG_OPTS_TYPE


CLASS (MF_PHYS_GRA_TYPE)                    :: SELF
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
TYPE (CPG_OPTS_TYPE),         INTENT (IN)    :: YDCPG_OPTS
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT
LOGICAL, OPTIONAL,            INTENT (IN)    :: LDMF_PHYS

REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PG(:, :, :, :)

LOGICAL :: LLMF_PHYS




LLMF_PHYS = .FALSE.
IF (PRESENT (LDMF_PHYS)) THEN
  LLMF_PHYS = LDMF_PHYS
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PG)) THEN
      SELF%F_G => CREATE_FIELD_WRAP (PG, LBOUNDS=[1, 1, 1, 1])
  ENDIF
ENDIF


END SUBROUTINE MF_PHYS_GRA_TYPE_INIT

SUBROUTINE MF_PHYS_GRA_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (MF_PHYS_GRA_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

IF (ASSOCIATED (SELF%F_G)) THEN
  SELF%G  => SELF%F_G%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%G  => ZDUM3
ENDIF

END SUBROUTINE MF_PHYS_GRA_TYPE_UPDATE_VIEW

SUBROUTINE MF_PHYS_GRA_TYPE_FINAL (SELF)
CLASS (MF_PHYS_GRA_TYPE)         :: SELF

IF (ASSOCIATED (SELF%F_G)) CALL DELETE_TEMPORARY (SELF%F_G) 

END SUBROUTINE MF_PHYS_GRA_TYPE_FINAL




SUBROUTINE MF_PHYS_RAD_TYPE_INIT (SELF, REGISTRY, YDCPG_OPTS, PERSISTENT, LDMF_PHYS, PEMTD, PEMTU, &
& PTRSW, PRMOON  )


USE CPG_OPTS_TYPE_MOD, ONLY : CPG_OPTS_TYPE


CLASS (MF_PHYS_RAD_TYPE)                    :: SELF
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
TYPE (CPG_OPTS_TYPE),         INTENT (IN)    :: YDCPG_OPTS
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT
LOGICAL, OPTIONAL,            INTENT (IN)    :: LDMF_PHYS

REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PEMTD(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PEMTU(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PTRSW(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PRMOON(:, :)

LOGICAL :: LLMF_PHYS




LLMF_PHYS = .FALSE.
IF (PRESENT (LDMF_PHYS)) THEN
  LLMF_PHYS = LDMF_PHYS
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PEMTD)) THEN
      SELF%F_EMTD => CREATE_FIELD_WRAP (PEMTD, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PEMTU)) THEN
      SELF%F_EMTU => CREATE_FIELD_WRAP (PEMTU, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PTRSW)) THEN
      SELF%F_TRSW => CREATE_FIELD_WRAP (PTRSW, LBOUNDS=[1, 0, 1])
  ENDIF
ENDIF

IF (LLMF_PHYS) THEN
  IF (PRESENT (PRMOON)) THEN
      SELF%F_RMOON => CREATE_FIELD_WRAP (PRMOON, LBOUNDS=[1, 1])
  ENDIF
ENDIF


END SUBROUTINE MF_PHYS_RAD_TYPE_INIT

SUBROUTINE MF_PHYS_RAD_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (MF_PHYS_RAD_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

IF (ASSOCIATED (SELF%F_EMTD)) THEN
  SELF%EMTD  => SELF%F_EMTD%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%EMTD  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_EMTU)) THEN
  SELF%EMTU  => SELF%F_EMTU%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%EMTU  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_TRSW)) THEN
  SELF%TRSW  => SELF%F_TRSW%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%TRSW  => ZDUM2
ENDIF
IF (ASSOCIATED (SELF%F_RMOON)) THEN
  SELF%RMOON  => SELF%F_RMOON%GET_VIEW (BLOCK_INDEX)
ELSE
  SELF%RMOON  => ZDUM1
ENDIF

END SUBROUTINE MF_PHYS_RAD_TYPE_UPDATE_VIEW

SUBROUTINE MF_PHYS_RAD_TYPE_FINAL (SELF)
CLASS (MF_PHYS_RAD_TYPE)         :: SELF

IF (ASSOCIATED (SELF%F_EMTD)) CALL DELETE_TEMPORARY (SELF%F_EMTD) 
IF (ASSOCIATED (SELF%F_EMTU)) CALL DELETE_TEMPORARY (SELF%F_EMTU) 
IF (ASSOCIATED (SELF%F_TRSW)) CALL DELETE_TEMPORARY (SELF%F_TRSW) 
IF (ASSOCIATED (SELF%F_RMOON)) CALL DELETE_TEMPORARY (SELF%F_RMOON) 

END SUBROUTINE MF_PHYS_RAD_TYPE_FINAL

SUBROUTINE MF_PHYS_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (MF_PHYS_TYPE) :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

CALL SELF%OUT%UPDATE_VIEW (BLOCK_INDEX)
CALL SELF%OPT%UPDATE_VIEW (BLOCK_INDEX)
CALL SELF%FOR%UPDATE_VIEW (BLOCK_INDEX)
CALL SELF%GRA%UPDATE_VIEW (BLOCK_INDEX)
CALL SELF%RAD%UPDATE_VIEW (BLOCK_INDEX)

END SUBROUTINE MF_PHYS_TYPE_UPDATE_VIEW

SUBROUTINE MF_PHYS_TYPE_FINAL (SELF)

CLASS (MF_PHYS_TYPE) :: SELF

CALL SELF%OUT%FINAL ()
CALL SELF%OPT%FINAL ()
CALL SELF%FOR%FINAL ()
CALL SELF%GRA%FINAL ()
CALL SELF%RAD%FINAL ()

END SUBROUTINE MF_PHYS_TYPE_FINAL

END MODULE MF_PHYS_TYPE_MOD

