
MODULE MF_PHYS_STATE_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE CPG_TYPE_MOD, ONLY : CPG_DYN_TYPE, CPG_PHY_TYPE
USE FIELD_MODULE
IMPLICIT NONE


TYPE MF_PHYS_STATE_GSP_SG_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: F (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: A (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FA => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: R (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FR => NULL ()
END TYPE MF_PHYS_STATE_GSP_SG_TYPE

TYPE MF_PHYS_STATE_GSP_RR_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:) => NULL ()
  TYPE (FIELD_2D), POINTER :: FT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FC (:) => NULL ()
  TYPE (FIELD_2D), POINTER :: FFC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: W (:) => NULL ()
  TYPE (FIELD_2D), POINTER :: FW => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: IC (:) => NULL ()
  TYPE (FIELD_2D), POINTER :: FIC => NULL ()
END TYPE MF_PHYS_STATE_GSP_RR_TYPE

TYPE MF_PHYS_STATE_GSP_SB_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FQ => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TL (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FTL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FT => NULL ()
END TYPE MF_PHYS_STATE_GSP_SB_TYPE


TYPE MF_PHYS_STATE_TYPE
  TYPE (CPG_DYN_TYPE), POINTER :: YCPG_DYN    => NULL ()
  TYPE (CPG_PHY_TYPE), POINTER :: YCPG_PHY    => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P1EXT  (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P1CHEM (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P1NOGW (:,:)   => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P2NOGW (:,:)   => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P1LIMA (:,:,:) => NULL ()
  
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CVV (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FCVV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIV (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FDIV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB1 (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FEFB1 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB2 (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FEFB2 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB3 (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FEFB3 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: G (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FG => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: H (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: I (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: L (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: O3 (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FO3 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FQ => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: R (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: S (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SRC (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FSRC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TKE (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FTKE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: U (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FU => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: V (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VOR (:,:) => NULL ()
  TYPE (FIELD_3D), POINTER :: FVOR => NULL ()

  TYPE (MF_PHYS_STATE_GSP_SG_TYPE) :: YGSP_SG
  TYPE (MF_PHYS_STATE_GSP_RR_TYPE) :: YGSP_RR
  TYPE (MF_PHYS_STATE_GSP_SB_TYPE) :: YGSP_SB

CONTAINS

  PROCEDURE :: INIT => MF_PHYS_STATE_TYPE_INIT

END TYPE MF_PHYS_STATE_TYPE

CONTAINS


SUBROUTINE MF_PHYS_STATE_TYPE_INIT (SELF, LDT0, YDCPG_DYN0, YDCPG_DYN9, YDCPG_PHY0, YDCPG_PHY9, YDVARS, YDMF_PHYS_SURF, &
                                 & YDMODEL, PGFL, P1EXT0, P1EXT9, P1CHEM0, P1CHEM9, P1NOGW0, P1NOGW9, P2NOGW0, P2NOGW9, P1LIMA0, P1LIMA9)

USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
USE SC2PRG_MOD         , ONLY : SC2PRG
USE TYPE_MODEL         , ONLY : MODEL

CLASS (MF_PHYS_STATE_TYPE)              :: SELF
TYPE (MF_PHYS_SURF_TYPE),INTENT(INOUT) :: YDMF_PHYS_SURF
LOGICAL,                INTENT (IN)    :: LDT0
TYPE (CPG_DYN_TYPE),    INTENT (INOUT), TARGET :: YDCPG_DYN0, YDCPG_DYN9
TYPE (CPG_PHY_TYPE),    INTENT (INOUT), TARGET :: YDCPG_PHY0, YDCPG_PHY9
TYPE (FIELD_VARIABLES), INTENT (INOUT) :: YDVARS
TYPE(MODEL), OPTIONAL,  INTENT (IN)    :: YDMODEL
REAL (KIND=JPRB), TARGET,  OPTIONAL :: PGFL (:,:,:)
REAL (KIND=JPRB), POINTER, OPTIONAL :: P1EXT0  (:,:,:), P1EXT9  (:,:,:)
REAL (KIND=JPRB), POINTER, OPTIONAL :: P1CHEM0 (:,:,:), P1CHEM9 (:,:,:)
REAL (KIND=JPRB), POINTER, OPTIONAL :: P1NOGW0 (:,:),   P1NOGW9 (:,:)
REAL (KIND=JPRB), POINTER, OPTIONAL :: P2NOGW0 (:,:),   P2NOGW9 (:,:)
REAL (KIND=JPRB), POINTER, OPTIONAL :: P1LIMA0 (:,:,:), P1LIMA9 (:,:,:)
REAL (KIND=JPRB), TARGET, SAVE :: ZDUM2 (1, 1), ZDUM3 (1, 1, 1)

REAL(KIND=JPRB), POINTER :: ZP1CHEM0(:,:,:), ZP1CHEM9(:,:,:)
REAL(KIND=JPRB), POINTER :: ZP1EXT0(:,:,:), ZP1EXT9(:,:,:)
REAL(KIND=JPRB), POINTER :: ZP1LIMA0(:,:,:), ZP1LIMA9(:,:,:)
REAL(KIND=JPRB), POINTER :: ZP1NOGW0(:,:), ZP1NOGW9(:,:), ZP2NOGW0(:,:), ZP2NOGW9(:,:)


ZP1CHEM0 => ZDUM3
ZP1CHEM9 => ZDUM3
ZP1LIMA0 => ZDUM3
ZP1LIMA9 => ZDUM3
ZP1EXT0  => ZDUM3
ZP1EXT9  => ZDUM3

ZP1NOGW0 => ZDUM2
ZP1NOGW9 => ZDUM2
ZP2NOGW0 => ZDUM2
ZP2NOGW9 => ZDUM2

IF (PRESENT (PGFL) .AND. PRESENT (YDMODEL)) THEN

  CALL SC2PRG (1, YDMODEL%YRML_GCONF%YGFL%YCHEM(:)%MP , YDMODEL%YRML_GCONF%YGFL%NCHEM,    PGFL, ZP1CHEM0)    !  YDVARS%CHEM(1)%T0
  CALL SC2PRG (1, YDMODEL%YRML_GCONF%YGFL%YCHEM(:)%MP9, YDMODEL%YRML_GCONF%YGFL%NCHEM,    PGFL, ZP1CHEM9)    !  YDVARS%CHEM(1)%T9
  CALL SC2PRG (1, YDMODEL%YRML_GCONF%YGFL%YLIMA(:)%MP , YDMODEL%YRML_GCONF%YGFL%NLIMA,    PGFL, ZP1LIMA0)    !  YDVARS%LIMA(1)%T0
  CALL SC2PRG (1, YDMODEL%YRML_GCONF%YGFL%YLIMA(:)%MP9, YDMODEL%YRML_GCONF%YGFL%NLIMA,    PGFL, ZP1LIMA9)    !  YDVARS%LIMA(1)%T9
  CALL SC2PRG (1, YDMODEL%YRML_GCONF%YGFL%YEXT(:)%MP  , YDMODEL%YRML_GCONF%YGFL%NGFL_EXT, PGFL, ZP1EXT0 )    !  YDVARS%EXT(1)%T0
  CALL SC2PRG (1, YDMODEL%YRML_GCONF%YGFL%YEXT(:)%MP9 , YDMODEL%YRML_GCONF%YGFL%NGFL_EXT, PGFL, ZP1EXT9 )    !  YDVARS%EXT(1)%T9

  CALL SC2PRG (1, YDMODEL%YRML_GCONF%YGFL%YNOGW(:)%MP , PGFL ,ZP1NOGW0)    !  YDVARS%NOGW(1)%T0
  CALL SC2PRG (1, YDMODEL%YRML_GCONF%YGFL%YNOGW(:)%MP9, PGFL ,ZP1NOGW9)    !  YDVARS%NOGW(1)%T9 
  CALL SC2PRG (2, YDMODEL%YRML_GCONF%YGFL%YNOGW(:)%MP , PGFL ,ZP2NOGW0)    !  YDVARS%NOGW(2)%T0
  CALL SC2PRG (2, YDMODEL%YRML_GCONF%YGFL%YNOGW(:)%MP9, PGFL ,ZP2NOGW9)    !  YDVARS%NOGW(2)%T9 

ENDIF

IF (PRESENT (P1CHEM0))  ZP1CHEM0 => P1CHEM0
IF (PRESENT (P1CHEM9))  ZP1CHEM9 => P1CHEM9
IF (PRESENT (P1LIMA0))  ZP1LIMA0 => P1LIMA0
IF (PRESENT (P1LIMA9))  ZP1LIMA9 => P1LIMA9
IF (PRESENT (P1EXT0 ))  ZP1EXT0  => P1EXT0 
IF (PRESENT (P1EXT9 ))  ZP1EXT9  => P1EXT9 

IF (PRESENT (P1NOGW0))  ZP1NOGW0 => P1NOGW0
IF (PRESENT (P1NOGW9))  ZP1NOGW9 => P1NOGW9
IF (PRESENT (P2NOGW0))  ZP2NOGW0 => P2NOGW0
IF (PRESENT (P2NOGW9))  ZP2NOGW9 => P2NOGW9

IF (LDT0) THEN
  SELF%YCPG_DYN => YDCPG_DYN0
  SELF%YCPG_PHY => YDCPG_PHY0

  SELF%P1EXT  => ZP1EXT0
  SELF%P1CHEM => ZP1CHEM0
  SELF%P1NOGW => ZP1NOGW0
  SELF%P2NOGW => ZP2NOGW0
  SELF%P1LIMA => ZP1LIMA0

  SELF%CVV (LBOUND (YDVARS%CVV%T0,1):, LBOUND (YDVARS%CVV%T0,2):) => YDVARS%CVV%T0
  SELF%FCVV => YDVARS%CVV%FT0
  SELF%DIV (LBOUND (YDVARS%DIV%T0,1):, LBOUND (YDVARS%DIV%T0,2):) => YDVARS%DIV%T0
  SELF%FDIV => YDVARS%DIV%FT0
  SELF%EFB1 (LBOUND (YDVARS%EFB1%T0,1):, LBOUND (YDVARS%EFB1%T0,2):) => YDVARS%EFB1%T0
  SELF%FEFB1 => YDVARS%EFB1%FT0
  SELF%EFB2 (LBOUND (YDVARS%EFB2%T0,1):, LBOUND (YDVARS%EFB2%T0,2):) => YDVARS%EFB2%T0
  SELF%FEFB2 => YDVARS%EFB2%FT0
  SELF%EFB3 (LBOUND (YDVARS%EFB3%T0,1):, LBOUND (YDVARS%EFB3%T0,2):) => YDVARS%EFB3%T0
  SELF%FEFB3 => YDVARS%EFB3%FT0
  SELF%G (LBOUND (YDVARS%G%T0,1):, LBOUND (YDVARS%G%T0,2):) => YDVARS%G%T0
  SELF%FG => YDVARS%G%FT0
  SELF%H (LBOUND (YDVARS%H%T0,1):, LBOUND (YDVARS%H%T0,2):) => YDVARS%H%T0
  SELF%FH => YDVARS%H%FT0
  SELF%I (LBOUND (YDVARS%I%T0,1):, LBOUND (YDVARS%I%T0,2):) => YDVARS%I%T0
  SELF%FI => YDVARS%I%FT0
  SELF%L (LBOUND (YDVARS%L%T0,1):, LBOUND (YDVARS%L%T0,2):) => YDVARS%L%T0
  SELF%FL => YDVARS%L%FT0
  SELF%O3 (LBOUND (YDVARS%O3%T0,1):, LBOUND (YDVARS%O3%T0,2):) => YDVARS%O3%T0
  SELF%FO3 => YDVARS%O3%FT0
  SELF%Q (LBOUND (YDVARS%Q%T0,1):, LBOUND (YDVARS%Q%T0,2):) => YDVARS%Q%T0
  SELF%FQ => YDVARS%Q%FT0
  SELF%R (LBOUND (YDVARS%R%T0,1):, LBOUND (YDVARS%R%T0,2):) => YDVARS%R%T0
  SELF%FR => YDVARS%R%FT0
  SELF%S (LBOUND (YDVARS%S%T0,1):, LBOUND (YDVARS%S%T0,2):) => YDVARS%S%T0
  SELF%FS => YDVARS%S%FT0
  SELF%SRC (LBOUND (YDVARS%SRC%T0,1):, LBOUND (YDVARS%SRC%T0,2):) => YDVARS%SRC%T0
  SELF%FSRC => YDVARS%SRC%FT0
  SELF%T (LBOUND (YDVARS%T%T0,1):, LBOUND (YDVARS%T%T0,2):) => YDVARS%T%T0
  SELF%FT => YDVARS%T%FT0
  SELF%TKE (LBOUND (YDVARS%TKE%T0,1):, LBOUND (YDVARS%TKE%T0,2):) => YDVARS%TKE%T0
  SELF%FTKE => YDVARS%TKE%FT0
  SELF%U (LBOUND (YDVARS%U%T0,1):, LBOUND (YDVARS%U%T0,2):) => YDVARS%U%T0
  SELF%FU => YDVARS%U%FT0
  SELF%V (LBOUND (YDVARS%V%T0,1):, LBOUND (YDVARS%V%T0,2):) => YDVARS%V%T0
  SELF%FV => YDVARS%V%FT0
  SELF%VOR (LBOUND (YDVARS%VOR%T0,1):, LBOUND (YDVARS%VOR%T0,2):) => YDVARS%VOR%T0
  SELF%FVOR => YDVARS%VOR%FT0

  SELF%YGSP_SG%F ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PF_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PF_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PF_T0
  SELF%YGSP_SG%FF => YDMF_PHYS_SURF%GSP_SG%F_F_T0

  SELF%YGSP_SG%A ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PA_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PA_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PA_T0
  SELF%YGSP_SG%FA => YDMF_PHYS_SURF%GSP_SG%F_A_T0

  SELF%YGSP_SG%R ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PR_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PR_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PR_T0
  SELF%YGSP_SG%FR => YDMF_PHYS_SURF%GSP_SG%F_R_T0

  SELF%YGSP_RR%T ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PT_T0, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PT_T0
  SELF%YGSP_RR%FT => YDMF_PHYS_SURF%GSP_RR%F_T_T0

  SELF%YGSP_RR%FC ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PFC_T0, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PFC_T0
  SELF%YGSP_RR%FFC => YDMF_PHYS_SURF%GSP_RR%F_FC_T0

  SELF%YGSP_RR%W ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PW_T0, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PW_T0
  SELF%YGSP_RR%FW => YDMF_PHYS_SURF%GSP_RR%F_W_T0

  SELF%YGSP_RR%IC ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PIC_T0, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PIC_T0
  SELF%YGSP_RR%FIC => YDMF_PHYS_SURF%GSP_RR%F_IC_T0

  SELF%YGSP_SB%Q ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PQ_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PQ_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PQ_T0
  SELF%YGSP_SB%FQ => YDMF_PHYS_SURF%GSP_SB%F_Q_T0

  SELF%YGSP_SB%TL ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PTL_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PTL_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PTL_T0
  SELF%YGSP_SB%FTL => YDMF_PHYS_SURF%GSP_SB%F_TL_T0

  SELF%YGSP_SB%T ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PT_T0, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PT_T0, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PT_T0
  SELF%YGSP_SB%FT => YDMF_PHYS_SURF%GSP_SB%F_T_T0


ELSE
  SELF%YCPG_DYN => YDCPG_DYN9
  SELF%YCPG_PHY => YDCPG_PHY9

  SELF%P1EXT  => ZP1EXT9
  SELF%P1CHEM => ZP1CHEM9
  SELF%P1NOGW => ZP1NOGW9
  SELF%P2NOGW => ZP2NOGW9
  SELF%P1LIMA => ZP1LIMA9

  SELF%CVV (LBOUND (YDVARS%CVV%T9,1):, LBOUND (YDVARS%CVV%T9,2):) => YDVARS%CVV%T9
  SELF%FCVV => YDVARS%CVV%FT9
  SELF%DIV (LBOUND (YDVARS%DIV%T9,1):, LBOUND (YDVARS%DIV%T9,2):) => YDVARS%DIV%T9
  SELF%FDIV => YDVARS%DIV%FT9
  SELF%EFB1 (LBOUND (YDVARS%EFB1%T9,1):, LBOUND (YDVARS%EFB1%T9,2):) => YDVARS%EFB1%T9
  SELF%FEFB1 => YDVARS%EFB1%FT9
  SELF%EFB2 (LBOUND (YDVARS%EFB2%T9,1):, LBOUND (YDVARS%EFB2%T9,2):) => YDVARS%EFB2%T9
  SELF%FEFB2 => YDVARS%EFB2%FT9
  SELF%EFB3 (LBOUND (YDVARS%EFB3%T9,1):, LBOUND (YDVARS%EFB3%T9,2):) => YDVARS%EFB3%T9
  SELF%FEFB3 => YDVARS%EFB3%FT9
  SELF%G (LBOUND (YDVARS%G%T9,1):, LBOUND (YDVARS%G%T9,2):) => YDVARS%G%T9
  SELF%FG => YDVARS%G%FT9
  SELF%H (LBOUND (YDVARS%H%T9,1):, LBOUND (YDVARS%H%T9,2):) => YDVARS%H%T9
  SELF%FH => YDVARS%H%FT9
  SELF%I (LBOUND (YDVARS%I%T9,1):, LBOUND (YDVARS%I%T9,2):) => YDVARS%I%T9
  SELF%FI => YDVARS%I%FT9
  SELF%L (LBOUND (YDVARS%L%T9,1):, LBOUND (YDVARS%L%T9,2):) => YDVARS%L%T9
  SELF%FL => YDVARS%L%FT9
  SELF%O3 (LBOUND (YDVARS%O3%T9,1):, LBOUND (YDVARS%O3%T9,2):) => YDVARS%O3%T9
  SELF%FO3 => YDVARS%O3%FT9
  SELF%Q (LBOUND (YDVARS%Q%T9,1):, LBOUND (YDVARS%Q%T9,2):) => YDVARS%Q%T9
  SELF%FQ => YDVARS%Q%FT9
  SELF%R (LBOUND (YDVARS%R%T9,1):, LBOUND (YDVARS%R%T9,2):) => YDVARS%R%T9
  SELF%FR => YDVARS%R%FT9
  SELF%S (LBOUND (YDVARS%S%T9,1):, LBOUND (YDVARS%S%T9,2):) => YDVARS%S%T9
  SELF%FS => YDVARS%S%FT9
  SELF%SRC (LBOUND (YDVARS%SRC%T9,1):, LBOUND (YDVARS%SRC%T9,2):) => YDVARS%SRC%T9
  SELF%FSRC => YDVARS%SRC%FT9
  SELF%T (LBOUND (YDVARS%T%T9,1):, LBOUND (YDVARS%T%T9,2):) => YDVARS%T%T9
  SELF%FT => YDVARS%T%FT9
  SELF%TKE (LBOUND (YDVARS%TKE%T9,1):, LBOUND (YDVARS%TKE%T9,2):) => YDVARS%TKE%T9
  SELF%FTKE => YDVARS%TKE%FT9
  SELF%U (LBOUND (YDVARS%U%T9,1):, LBOUND (YDVARS%U%T9,2):) => YDVARS%U%T9
  SELF%FU => YDVARS%U%FT9
  SELF%V (LBOUND (YDVARS%V%T9,1):, LBOUND (YDVARS%V%T9,2):) => YDVARS%V%T9
  SELF%FV => YDVARS%V%FT9
  SELF%VOR (LBOUND (YDVARS%VOR%T9,1):, LBOUND (YDVARS%VOR%T9,2):) => YDVARS%VOR%T9
  SELF%FVOR => YDVARS%VOR%FT9

  SELF%YGSP_SG%F ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PF_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PF_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PF_T9
  SELF%YGSP_SG%FF => YDMF_PHYS_SURF%GSP_SG%F_F_T9

  SELF%YGSP_SG%A ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PA_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PA_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PA_T9
  SELF%YGSP_SG%FA => YDMF_PHYS_SURF%GSP_SG%F_A_T9

  SELF%YGSP_SG%R ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SG%PR_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SG%PR_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SG%PR_T9
  SELF%YGSP_SG%FR => YDMF_PHYS_SURF%GSP_SG%F_R_T9

  SELF%YGSP_RR%T ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PT_T9, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PT_T9
  SELF%YGSP_RR%FT => YDMF_PHYS_SURF%GSP_RR%F_T_T9

  SELF%YGSP_RR%FC ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PFC_T9, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PFC_T9
  SELF%YGSP_RR%FFC => YDMF_PHYS_SURF%GSP_RR%F_FC_T9

  SELF%YGSP_RR%W ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PW_T9, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PW_T9
  SELF%YGSP_RR%FW => YDMF_PHYS_SURF%GSP_RR%F_W_T9

  SELF%YGSP_RR%IC ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_RR%PIC_T9, 1):  &
                     &  ) => YDMF_PHYS_SURF%GSP_RR%PIC_T9
  SELF%YGSP_RR%FIC => YDMF_PHYS_SURF%GSP_RR%F_IC_T9

  SELF%YGSP_SB%Q ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PQ_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PQ_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PQ_T9
  SELF%YGSP_SB%FQ => YDMF_PHYS_SURF%GSP_SB%F_Q_T9

  SELF%YGSP_SB%TL ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PTL_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PTL_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PTL_T9
  SELF%YGSP_SB%FTL => YDMF_PHYS_SURF%GSP_SB%F_TL_T9

  SELF%YGSP_SB%T ( &
                     &  LBOUND (YDMF_PHYS_SURF%GSP_SB%PT_T9, 1):  &
                     & ,LBOUND (YDMF_PHYS_SURF%GSP_SB%PT_T9, 2):  &
                     &  ) => YDMF_PHYS_SURF%GSP_SB%PT_T9
  SELF%YGSP_SB%FT => YDMF_PHYS_SURF%GSP_SB%F_T_T9


ENDIF

END SUBROUTINE MF_PHYS_STATE_TYPE_INIT

END MODULE MF_PHYS_STATE_TYPE_MOD
