MODULE MF_PHYS_NEXT_STATE_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_MODULE
IMPLICIT NONE

TYPE MF_PHYS_NEXT_STATE_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: U (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_U => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: V (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_V => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_T => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SVD (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_SVD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SP (:) => NULL ()
  TYPE (FIELD_2D), POINTER :: F_SP => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_Q => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: I (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_I => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: L (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_L => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LCONV (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_LCONV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ICONV (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_ICONV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RCONV (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_RCONV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SCONV (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_SCONV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: IRAD (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_IRAD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LRAD (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_LRAD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: S (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_S => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: R (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_R => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: G (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_G => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: H (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_H => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TKE (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_TKE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TTE (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_TTE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB1 (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_EFB1 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB2 (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_EFB2 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB3 (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_EFB3 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: A (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_A => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: O3 (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_O3 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SRC (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_SRC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: MXL (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_MXL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SHTUR (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_SHTUR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FQTUR (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_FQTUR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FSTUR (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_FSTUR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CPF (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_CPF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SPF (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_SPF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CVGQ (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_CVGQ => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QVA (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_QVA => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LRCH4 (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_LRCH4 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHYCTY (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_PHYCTY => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RSPEC (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_RSPEC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SDSAT (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_SDSAT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CVV (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_CVV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RKTH (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_RKTH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RKTQV (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_RKTQV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RKTQC (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_RKTQC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UOM (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_UOM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UAL (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_UAL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DOM (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_DOM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DAL (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_DAL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UEN (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_UEN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UNEBH (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_UNEBH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FSD (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_FSD => NULL ()

CONTAINS

  PROCEDURE :: INIT => MF_PHYS_NEXT_STATE_TYPE_INIT

END TYPE MF_PHYS_NEXT_STATE_TYPE

CONTAINS

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT (SELF, YDCPG_SL1, YDVARS, YDMODEL)

USE YOMCT0, ONLY : LSLAG, LTWOTL
USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
USE CPG_TYPE_MOD, ONLY : CPG_SL1_TYPE
USE TYPE_MODEL  , ONLY : MODEL

CLASS (MF_PHYS_NEXT_STATE_TYPE)        :: SELF
TYPE (CPG_SL1_TYPE),    INTENT (INOUT), TARGET :: YDCPG_SL1
TYPE (FIELD_VARIABLES), INTENT (INOUT), TARGET :: YDVARS
TYPE(MODEL),            INTENT (IN)    :: YDMODEL

ASSOCIATE (YDDYN => YDMODEL%YRML_DYN%YRDYN)

IF (LSLAG) THEN

  ! Taken from cp_ptrslb1.F90
  
  IF (YDDYN%NWLAG == 4) THEN
    SELF%U   => YDCPG_SL1%U0 
    SELF%F_U => YDCPG_SL1%F_U0
    SELF%V   => YDCPG_SL1%V0 
    SELF%F_V => YDCPG_SL1%F_V0
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%U   => YDCPG_SL1%UF9 
      SELF%F_U => YDCPG_SL1%F_UF9 
      SELF%V   => YDCPG_SL1%VF9 
      SELF%F_V => YDCPG_SL1%F_VF9 
    ELSE
      SELF%U   => YDCPG_SL1%U9 
      SELF%F_U => YDCPG_SL1%F_U9 
      SELF%V   => YDCPG_SL1%V9 
      SELF%F_V => YDCPG_SL1%F_V9 
    ENDIF
  ENDIF
  ! * temperature
  IF (YDDYN%NTLAG == 4) THEN
    SELF%T   => YDCPG_SL1%T0 
    SELF%F_T => YDCPG_SL1%F_T0 
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%T   => YDCPG_SL1%TF9 
      SELF%F_T => YDCPG_SL1%F_TF9 
    ELSE
      SELF%T   => YDCPG_SL1%T9 
      SELF%F_T => YDCPG_SL1%F_T9 
    ENDIF
  ENDIF
  ! * vertical divergence
  IF (YDDYN%NSVDLAG == 4) THEN
    SELF%SVD   => YDCPG_SL1%VD0
    SELF%F_SVD => YDCPG_SL1%F_VD0
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%SVD   => YDCPG_SL1%VDF9
      SELF%F_SVD => YDCPG_SL1%F_VDF9
    ELSE
      SELF%SVD   => YDCPG_SL1%VD9
      SELF%F_SVD => YDCPG_SL1%F_VD9
    ENDIF
  ENDIF

  SELF%SP   => YDCPG_SL1%SP9
  SELF%F_SP => YDCPG_SL1%F_SP9

  ! * GFL arrays
  IF (YDDYN%LSPLTHOIGFL.OR.(YDDYN%NSPLTHOI /= 0)) THEN
    IF (YDVARS%Q%LADV) THEN
      SELF%Q   => YDCPG_SL1%Q_F
      SELF%F_Q => YDCPG_SL1%F_Q_F
    ELSE
      SELF%Q   => YDVARS%Q%T1
      SELF%F_Q => YDVARS%Q%FT1
    ENDIF
    IF (YDVARS%I%LADV) THEN
      SELF%I   => YDCPG_SL1%I_F
      SELF%F_I => YDCPG_SL1%F_I_F
    ELSE
      SELF%I   => YDVARS%I%T1
      SELF%F_I => YDVARS%I%FT1
    ENDIF
    IF (YDVARS%L%LADV) THEN
      SELF%L   => YDCPG_SL1%L_F
      SELF%F_L => YDCPG_SL1%F_L_F
    ELSE
      SELF%L   => YDVARS%L%T1
      SELF%F_L => YDVARS%L%FT1
    ENDIF
    IF (YDVARS%LCONV%LADV) THEN
      SELF%LCONV   => YDCPG_SL1%LCONV_F
      SELF%F_LCONV => YDCPG_SL1%F_LCONV_F
    ELSE
      SELF%LCONV   => YDVARS%LCONV%T1
      SELF%F_LCONV => YDVARS%LCONV%FT1
    ENDIF
    IF (YDVARS%ICONV%LADV) THEN
      SELF%ICONV   => YDCPG_SL1%ICONV_F
      SELF%F_ICONV => YDCPG_SL1%F_ICONV_F
    ELSE
      SELF%ICONV   => YDVARS%ICONV%T1
      SELF%F_ICONV => YDVARS%ICONV%FT1
    ENDIF
    IF (YDVARS%RCONV%LADV) THEN
      SELF%RCONV   => YDCPG_SL1%RCONV_F
      SELF%F_RCONV => YDCPG_SL1%F_RCONV_F
    ELSE
      SELF%RCONV   => YDVARS%RCONV%T1
      SELF%F_RCONV => YDVARS%RCONV%FT1
    ENDIF
    IF (YDVARS%SCONV%LADV) THEN
      SELF%SCONV   => YDCPG_SL1%SCONV_F
      SELF%F_SCONV => YDCPG_SL1%F_SCONV_F
    ELSE
      SELF%SCONV   => YDVARS%SCONV%T1
      SELF%F_SCONV => YDVARS%SCONV%FT1
    ENDIF
    IF (YDVARS%IRAD%LADV) THEN
      SELF%IRAD   => YDCPG_SL1%IRAD_F
      SELF%F_IRAD => YDCPG_SL1%F_IRAD_F
    ELSE
      SELF%IRAD   => YDVARS%IRAD%T1
      SELF%F_IRAD => YDVARS%IRAD%FT1
    ENDIF
    IF (YDVARS%LRAD%LADV) THEN
      SELF%LRAD   => YDCPG_SL1%LRAD_F
      SELF%F_LRAD => YDCPG_SL1%F_LRAD_F
    ELSE
      SELF%LRAD   => YDVARS%LRAD%T1
      SELF%F_LRAD => YDVARS%LRAD%FT1
    ENDIF
    IF (YDVARS%S%LADV) THEN
      SELF%S   => YDCPG_SL1%S_F
      SELF%F_S => YDCPG_SL1%F_S_F
    ELSE
      SELF%S   => YDVARS%S%T1
      SELF%F_S => YDVARS%S%FT1
    ENDIF
    IF (YDVARS%R%LADV) THEN
      SELF%R   => YDCPG_SL1%R_F
      SELF%F_R => YDCPG_SL1%F_R_F
    ELSE
      SELF%R   => YDVARS%R%T1
      SELF%F_R => YDVARS%R%FT1
    ENDIF
    IF (YDVARS%G%LADV) THEN
      SELF%G   => YDCPG_SL1%G_F
      SELF%F_G => YDCPG_SL1%F_G_F
    ELSE
      SELF%G   => YDVARS%G%T1
      SELF%F_G => YDVARS%G%FT1
    ENDIF
    IF (YDVARS%H%LADV) THEN
      SELF%H   => YDCPG_SL1%H_F
      SELF%F_H => YDCPG_SL1%F_H_F
    ELSE
      SELF%H   => YDVARS%H%T1
      SELF%F_H => YDVARS%H%FT1
    ENDIF
    IF (YDVARS%TKE%LADV) THEN
      SELF%TKE   => YDCPG_SL1%TKE_F
      SELF%F_TKE => YDCPG_SL1%F_TKE_F
    ELSE
      SELF%TKE   => YDVARS%TKE%T1
      SELF%F_TKE => YDVARS%TKE%FT1
    ENDIF
    IF (YDVARS%TTE%LADV) THEN
      SELF%TTE   => YDCPG_SL1%TTE_F
      SELF%F_TTE => YDCPG_SL1%F_TTE_F
    ELSE
      SELF%TTE   => YDVARS%TTE%T1
      SELF%F_TTE => YDVARS%TTE%FT1
    ENDIF
    IF (YDVARS%EFB1%LADV) THEN
      SELF%EFB1   => YDCPG_SL1%EFB1_F
      SELF%F_EFB1 => YDCPG_SL1%F_EFB1_F
    ELSE
      SELF%EFB1   => YDVARS%EFB1%T1
      SELF%F_EFB1 => YDVARS%EFB1%FT1
    ENDIF
    IF (YDVARS%EFB2%LADV) THEN
      SELF%EFB2   => YDCPG_SL1%EFB2_F
      SELF%F_EFB2 => YDCPG_SL1%F_EFB2_F
    ELSE
      SELF%EFB2   => YDVARS%EFB2%T1
      SELF%F_EFB2 => YDVARS%EFB2%FT1
    ENDIF
    IF (YDVARS%EFB3%LADV) THEN
      SELF%EFB3   => YDCPG_SL1%EFB3_F
      SELF%F_EFB3 => YDCPG_SL1%F_EFB3_F
    ELSE
      SELF%EFB3   => YDVARS%EFB3%T1
      SELF%F_EFB3 => YDVARS%EFB3%FT1
    ENDIF
    IF (YDVARS%A%LADV) THEN
      SELF%A   => YDCPG_SL1%A_F
      SELF%F_A => YDCPG_SL1%F_A_F
    ELSE
      SELF%A   => YDVARS%A%T1
      SELF%F_A => YDVARS%A%FT1
    ENDIF
    IF (YDVARS%O3%LADV) THEN
      SELF%O3   => YDCPG_SL1%O3_F
      SELF%F_O3 => YDCPG_SL1%F_O3_F
    ELSE
      SELF%O3   => YDVARS%O3%T1
      SELF%F_O3 => YDVARS%O3%FT1
    ENDIF
    IF (YDVARS%SRC%LADV) THEN
      SELF%SRC   => YDCPG_SL1%SRC_F
      SELF%F_SRC => YDCPG_SL1%F_SRC_F
    ELSE
      SELF%SRC   => YDVARS%SRC%T1
      SELF%F_SRC => YDVARS%SRC%FT1
    ENDIF
    IF (YDVARS%MXL%LADV) THEN
      SELF%MXL   => YDCPG_SL1%MXL_F
      SELF%F_MXL => YDCPG_SL1%F_MXL_F
    ELSE
      SELF%MXL   => YDVARS%MXL%T1
      SELF%F_MXL => YDVARS%MXL%FT1
    ENDIF
    IF (YDVARS%SHTUR%LADV) THEN
      SELF%SHTUR   => YDCPG_SL1%SHTUR_F
      SELF%F_SHTUR => YDCPG_SL1%F_SHTUR_F
    ELSE
      SELF%SHTUR   => YDVARS%SHTUR%T1
      SELF%F_SHTUR => YDVARS%SHTUR%FT1
    ENDIF
    IF (YDVARS%FQTUR%LADV) THEN
      SELF%FQTUR   => YDCPG_SL1%FQTUR_F
      SELF%F_FQTUR => YDCPG_SL1%F_FQTUR_F
    ELSE
      SELF%FQTUR   => YDVARS%FQTUR%T1
      SELF%F_FQTUR => YDVARS%FQTUR%FT1
    ENDIF
    IF (YDVARS%FSTUR%LADV) THEN
      SELF%FSTUR   => YDCPG_SL1%FSTUR_F
      SELF%F_FSTUR => YDCPG_SL1%F_FSTUR_F
    ELSE
      SELF%FSTUR   => YDVARS%FSTUR%T1
      SELF%F_FSTUR => YDVARS%FSTUR%FT1
    ENDIF
    IF (YDVARS%CPF%LADV) THEN
      SELF%CPF   => YDCPG_SL1%CPF_F
      SELF%F_CPF => YDCPG_SL1%F_CPF_F
    ELSE
      SELF%CPF   => YDVARS%CPF%T1
      SELF%F_CPF => YDVARS%CPF%FT1
    ENDIF
    IF (YDVARS%SPF%LADV) THEN
      SELF%SPF   => YDCPG_SL1%SPF_F
      SELF%F_SPF => YDCPG_SL1%F_SPF_F
    ELSE
      SELF%SPF   => YDVARS%SPF%T1
      SELF%F_SPF => YDVARS%SPF%FT1
    ENDIF
    IF (YDVARS%CVGQ%LADV) THEN
      SELF%CVGQ   => YDCPG_SL1%CVGQ_F
      SELF%F_CVGQ => YDCPG_SL1%F_CVGQ_F
    ELSE
      SELF%CVGQ   => YDVARS%CVGQ%T1
      SELF%F_CVGQ => YDVARS%CVGQ%FT1
    ENDIF
    IF (YDVARS%QVA%LADV) THEN
      SELF%QVA   => YDCPG_SL1%QVA_F
      SELF%F_QVA => YDCPG_SL1%F_QVA_F
    ELSE
      SELF%QVA   => YDVARS%QVA%T1
      SELF%F_QVA => YDVARS%QVA%FT1
    ENDIF
    IF (YDVARS%LRCH4%LADV) THEN
      SELF%LRCH4   => YDCPG_SL1%LRCH4_F
      SELF%F_LRCH4 => YDCPG_SL1%F_LRCH4_F
    ELSE
      SELF%LRCH4   => YDVARS%LRCH4%T1
      SELF%F_LRCH4 => YDVARS%LRCH4%FT1
    ENDIF
    IF (YDVARS%PHYCTY%LADV) THEN
      SELF%PHYCTY   => YDCPG_SL1%PHYCTY_F
      SELF%F_PHYCTY => YDCPG_SL1%F_PHYCTY_F
    ELSE
      SELF%PHYCTY   => YDVARS%PHYCTY%T1
      SELF%F_PHYCTY => YDVARS%PHYCTY%FT1
    ENDIF
    IF (YDVARS%RSPEC%LADV) THEN
      SELF%RSPEC   => YDCPG_SL1%RSPEC_F
      SELF%F_RSPEC => YDCPG_SL1%F_RSPEC_F
    ELSE
      SELF%RSPEC   => YDVARS%RSPEC%T1
      SELF%F_RSPEC => YDVARS%RSPEC%FT1
    ENDIF
    IF (YDVARS%SDSAT%LADV) THEN
      SELF%SDSAT   => YDCPG_SL1%SDSAT_F
      SELF%F_SDSAT => YDCPG_SL1%F_SDSAT_F
    ELSE
      SELF%SDSAT   => YDVARS%SDSAT%T1
      SELF%F_SDSAT => YDVARS%SDSAT%FT1
    ENDIF
    IF (YDVARS%CVV%LADV) THEN
      SELF%CVV   => YDCPG_SL1%CVV_F
      SELF%F_CVV => YDCPG_SL1%F_CVV_F
    ELSE
      SELF%CVV   => YDVARS%CVV%T1
      SELF%F_CVV => YDVARS%CVV%FT1
    ENDIF
    IF (YDVARS%RKTH%LADV) THEN
      SELF%RKTH   => YDCPG_SL1%RKTH_F
      SELF%F_RKTH => YDCPG_SL1%F_RKTH_F
    ELSE
      SELF%RKTH   => YDVARS%RKTH%T1
      SELF%F_RKTH => YDVARS%RKTH%FT1
    ENDIF
    IF (YDVARS%RKTQV%LADV) THEN
      SELF%RKTQV   => YDCPG_SL1%RKTQV_F
      SELF%F_RKTQV => YDCPG_SL1%F_RKTQV_F
    ELSE
      SELF%RKTQV   => YDVARS%RKTQV%T1
      SELF%F_RKTQV => YDVARS%RKTQV%FT1
    ENDIF
    IF (YDVARS%RKTQC%LADV) THEN
      SELF%RKTQC   => YDCPG_SL1%RKTQC_F
      SELF%F_RKTQC => YDCPG_SL1%F_RKTQC_F
    ELSE
      SELF%RKTQC   => YDVARS%RKTQC%T1
      SELF%F_RKTQC => YDVARS%RKTQC%FT1
    ENDIF
    IF (YDVARS%UOM%LADV) THEN
      SELF%UOM   => YDCPG_SL1%UOM_F
      SELF%F_UOM => YDCPG_SL1%F_UOM_F
    ELSE
      SELF%UOM   => YDVARS%UOM%T1
      SELF%F_UOM => YDVARS%UOM%FT1
    ENDIF
    IF (YDVARS%UAL%LADV) THEN
      SELF%UAL   => YDCPG_SL1%UAL_F
      SELF%F_UAL => YDCPG_SL1%F_UAL_F
    ELSE
      SELF%UAL   => YDVARS%UAL%T1
      SELF%F_UAL => YDVARS%UAL%FT1
    ENDIF
    IF (YDVARS%DOM%LADV) THEN
      SELF%DOM   => YDCPG_SL1%DOM_F
      SELF%F_DOM => YDCPG_SL1%F_DOM_F
    ELSE
      SELF%DOM   => YDVARS%DOM%T1
      SELF%F_DOM => YDVARS%DOM%FT1
    ENDIF
    IF (YDVARS%DAL%LADV) THEN
      SELF%DAL   => YDCPG_SL1%DAL_F
      SELF%F_DAL => YDCPG_SL1%F_DAL_F
    ELSE
      SELF%DAL   => YDVARS%DAL%T1
      SELF%F_DAL => YDVARS%DAL%FT1
    ENDIF
    IF (YDVARS%UEN%LADV) THEN
      SELF%UEN   => YDCPG_SL1%UEN_F
      SELF%F_UEN => YDCPG_SL1%F_UEN_F
    ELSE
      SELF%UEN   => YDVARS%UEN%T1
      SELF%F_UEN => YDVARS%UEN%FT1
    ENDIF
    IF (YDVARS%UNEBH%LADV) THEN
      SELF%UNEBH   => YDCPG_SL1%UNEBH_F
      SELF%F_UNEBH => YDCPG_SL1%F_UNEBH_F
    ELSE
      SELF%UNEBH   => YDVARS%UNEBH%T1
      SELF%F_UNEBH => YDVARS%UNEBH%FT1
    ENDIF
    IF (YDVARS%FSD%LADV) THEN
      SELF%FSD   => YDCPG_SL1%FSD_F
      SELF%F_FSD => YDCPG_SL1%F_FSD_F
    ELSE
      SELF%FSD   => YDVARS%FSD%T1
      SELF%F_FSD => YDVARS%FSD%FT1
    ENDIF
  ELSE
    IF (YDVARS%Q%LADV) THEN
      SELF%Q   => YDCPG_SL1%Q
      SELF%F_Q => YDCPG_SL1%F_Q
    ELSE
      SELF%Q   => YDVARS%Q%T1
      SELF%F_Q => YDVARS%Q%FT1
    ENDIF
    IF (YDVARS%I%LADV) THEN
      SELF%I   => YDCPG_SL1%I
      SELF%F_I => YDCPG_SL1%F_I
    ELSE
      SELF%I   => YDVARS%I%T1
      SELF%F_I => YDVARS%I%FT1
    ENDIF
    IF (YDVARS%L%LADV) THEN
      SELF%L   => YDCPG_SL1%L
      SELF%F_L => YDCPG_SL1%F_L
    ELSE
      SELF%L   => YDVARS%L%T1
      SELF%F_L => YDVARS%L%FT1
    ENDIF
    IF (YDVARS%LCONV%LADV) THEN
      SELF%LCONV   => YDCPG_SL1%LCONV
      SELF%F_LCONV => YDCPG_SL1%F_LCONV
    ELSE
      SELF%LCONV   => YDVARS%LCONV%T1
      SELF%F_LCONV => YDVARS%LCONV%FT1
    ENDIF
    IF (YDVARS%ICONV%LADV) THEN
      SELF%ICONV   => YDCPG_SL1%ICONV
      SELF%F_ICONV => YDCPG_SL1%F_ICONV
    ELSE
      SELF%ICONV   => YDVARS%ICONV%T1
      SELF%F_ICONV => YDVARS%ICONV%FT1
    ENDIF
    IF (YDVARS%RCONV%LADV) THEN
      SELF%RCONV   => YDCPG_SL1%RCONV
      SELF%F_RCONV => YDCPG_SL1%F_RCONV
    ELSE
      SELF%RCONV   => YDVARS%RCONV%T1
      SELF%F_RCONV => YDVARS%RCONV%FT1
    ENDIF
    IF (YDVARS%SCONV%LADV) THEN
      SELF%SCONV   => YDCPG_SL1%SCONV
      SELF%F_SCONV => YDCPG_SL1%F_SCONV
    ELSE
      SELF%SCONV   => YDVARS%SCONV%T1
      SELF%F_SCONV => YDVARS%SCONV%FT1
    ENDIF
    IF (YDVARS%IRAD%LADV) THEN
      SELF%IRAD   => YDCPG_SL1%IRAD
      SELF%F_IRAD => YDCPG_SL1%F_IRAD
    ELSE
      SELF%IRAD   => YDVARS%IRAD%T1
      SELF%F_IRAD => YDVARS%IRAD%FT1
    ENDIF
    IF (YDVARS%LRAD%LADV) THEN
      SELF%LRAD   => YDCPG_SL1%LRAD
      SELF%F_LRAD => YDCPG_SL1%F_LRAD
    ELSE
      SELF%LRAD   => YDVARS%LRAD%T1
      SELF%F_LRAD => YDVARS%LRAD%FT1
    ENDIF
    IF (YDVARS%S%LADV) THEN
      SELF%S   => YDCPG_SL1%S
      SELF%F_S => YDCPG_SL1%F_S
    ELSE
      SELF%S   => YDVARS%S%T1
      SELF%F_S => YDVARS%S%FT1
    ENDIF
    IF (YDVARS%R%LADV) THEN
      SELF%R   => YDCPG_SL1%R
      SELF%F_R => YDCPG_SL1%F_R
    ELSE
      SELF%R   => YDVARS%R%T1
      SELF%F_R => YDVARS%R%FT1
    ENDIF
    IF (YDVARS%G%LADV) THEN
      SELF%G   => YDCPG_SL1%G
      SELF%F_G => YDCPG_SL1%F_G
    ELSE
      SELF%G   => YDVARS%G%T1
      SELF%F_G => YDVARS%G%FT1
    ENDIF
    IF (YDVARS%H%LADV) THEN
      SELF%H   => YDCPG_SL1%H
      SELF%F_H => YDCPG_SL1%F_H
    ELSE
      SELF%H   => YDVARS%H%T1
      SELF%F_H => YDVARS%H%FT1
    ENDIF
    IF (YDVARS%TKE%LADV) THEN
      SELF%TKE   => YDCPG_SL1%TKE
      SELF%F_TKE => YDCPG_SL1%F_TKE
    ELSE
      SELF%TKE   => YDVARS%TKE%T1
      SELF%F_TKE => YDVARS%TKE%FT1
    ENDIF
    IF (YDVARS%TTE%LADV) THEN
      SELF%TTE   => YDCPG_SL1%TTE
      SELF%F_TTE => YDCPG_SL1%F_TTE
    ELSE
      SELF%TTE   => YDVARS%TTE%T1
      SELF%F_TTE => YDVARS%TTE%FT1
    ENDIF
    IF (YDVARS%EFB1%LADV) THEN
      SELF%EFB1   => YDCPG_SL1%EFB1
      SELF%F_EFB1 => YDCPG_SL1%F_EFB1
    ELSE
      SELF%EFB1   => YDVARS%EFB1%T1
      SELF%F_EFB1 => YDVARS%EFB1%FT1
    ENDIF
    IF (YDVARS%EFB2%LADV) THEN
      SELF%EFB2   => YDCPG_SL1%EFB2
      SELF%F_EFB2 => YDCPG_SL1%F_EFB2
    ELSE
      SELF%EFB2   => YDVARS%EFB2%T1
      SELF%F_EFB2 => YDVARS%EFB2%FT1
    ENDIF
    IF (YDVARS%EFB3%LADV) THEN
      SELF%EFB3   => YDCPG_SL1%EFB3
      SELF%F_EFB3 => YDCPG_SL1%F_EFB3
    ELSE
      SELF%EFB3   => YDVARS%EFB3%T1
      SELF%F_EFB3 => YDVARS%EFB3%FT1
    ENDIF
    IF (YDVARS%A%LADV) THEN
      SELF%A   => YDCPG_SL1%A
      SELF%F_A => YDCPG_SL1%F_A
    ELSE
      SELF%A   => YDVARS%A%T1
      SELF%F_A => YDVARS%A%FT1
    ENDIF
    IF (YDVARS%O3%LADV) THEN
      SELF%O3   => YDCPG_SL1%O3
      SELF%F_O3 => YDCPG_SL1%F_O3
    ELSE
      SELF%O3   => YDVARS%O3%T1
      SELF%F_O3 => YDVARS%O3%FT1
    ENDIF
    IF (YDVARS%SRC%LADV) THEN
      SELF%SRC   => YDCPG_SL1%SRC
      SELF%F_SRC => YDCPG_SL1%F_SRC
    ELSE
      SELF%SRC   => YDVARS%SRC%T1
      SELF%F_SRC => YDVARS%SRC%FT1
    ENDIF
    IF (YDVARS%MXL%LADV) THEN
      SELF%MXL   => YDCPG_SL1%MXL
      SELF%F_MXL => YDCPG_SL1%F_MXL
    ELSE
      SELF%MXL   => YDVARS%MXL%T1
      SELF%F_MXL => YDVARS%MXL%FT1
    ENDIF
    IF (YDVARS%SHTUR%LADV) THEN
      SELF%SHTUR   => YDCPG_SL1%SHTUR
      SELF%F_SHTUR => YDCPG_SL1%F_SHTUR
    ELSE
      SELF%SHTUR   => YDVARS%SHTUR%T1
      SELF%F_SHTUR => YDVARS%SHTUR%FT1
    ENDIF
    IF (YDVARS%FQTUR%LADV) THEN
      SELF%FQTUR   => YDCPG_SL1%FQTUR
      SELF%F_FQTUR => YDCPG_SL1%F_FQTUR
    ELSE
      SELF%FQTUR   => YDVARS%FQTUR%T1
      SELF%F_FQTUR => YDVARS%FQTUR%FT1
    ENDIF
    IF (YDVARS%FSTUR%LADV) THEN
      SELF%FSTUR   => YDCPG_SL1%FSTUR
      SELF%F_FSTUR => YDCPG_SL1%F_FSTUR
    ELSE
      SELF%FSTUR   => YDVARS%FSTUR%T1
      SELF%F_FSTUR => YDVARS%FSTUR%FT1
    ENDIF
    IF (YDVARS%CPF%LADV) THEN
      SELF%CPF   => YDCPG_SL1%CPF
      SELF%F_CPF => YDCPG_SL1%F_CPF
    ELSE
      SELF%CPF   => YDVARS%CPF%T1
      SELF%F_CPF => YDVARS%CPF%FT1
    ENDIF
    IF (YDVARS%SPF%LADV) THEN
      SELF%SPF   => YDCPG_SL1%SPF
      SELF%F_SPF => YDCPG_SL1%F_SPF
    ELSE
      SELF%SPF   => YDVARS%SPF%T1
      SELF%F_SPF => YDVARS%SPF%FT1
    ENDIF
    IF (YDVARS%CVGQ%LADV) THEN
      SELF%CVGQ   => YDCPG_SL1%CVGQ
      SELF%F_CVGQ => YDCPG_SL1%F_CVGQ
    ELSE
      SELF%CVGQ   => YDVARS%CVGQ%T1
      SELF%F_CVGQ => YDVARS%CVGQ%FT1
    ENDIF
    IF (YDVARS%QVA%LADV) THEN
      SELF%QVA   => YDCPG_SL1%QVA
      SELF%F_QVA => YDCPG_SL1%F_QVA
    ELSE
      SELF%QVA   => YDVARS%QVA%T1
      SELF%F_QVA => YDVARS%QVA%FT1
    ENDIF
    IF (YDVARS%LRCH4%LADV) THEN
      SELF%LRCH4   => YDCPG_SL1%LRCH4
      SELF%F_LRCH4 => YDCPG_SL1%F_LRCH4
    ELSE
      SELF%LRCH4   => YDVARS%LRCH4%T1
      SELF%F_LRCH4 => YDVARS%LRCH4%FT1
    ENDIF
    IF (YDVARS%PHYCTY%LADV) THEN
      SELF%PHYCTY   => YDCPG_SL1%PHYCTY
      SELF%F_PHYCTY => YDCPG_SL1%F_PHYCTY
    ELSE
      SELF%PHYCTY   => YDVARS%PHYCTY%T1
      SELF%F_PHYCTY => YDVARS%PHYCTY%FT1
    ENDIF
    IF (YDVARS%RSPEC%LADV) THEN
      SELF%RSPEC   => YDCPG_SL1%RSPEC
      SELF%F_RSPEC => YDCPG_SL1%F_RSPEC
    ELSE
      SELF%RSPEC   => YDVARS%RSPEC%T1
      SELF%F_RSPEC => YDVARS%RSPEC%FT1
    ENDIF
    IF (YDVARS%SDSAT%LADV) THEN
      SELF%SDSAT   => YDCPG_SL1%SDSAT
      SELF%F_SDSAT => YDCPG_SL1%F_SDSAT
    ELSE
      SELF%SDSAT   => YDVARS%SDSAT%T1
      SELF%F_SDSAT => YDVARS%SDSAT%FT1
    ENDIF
    IF (YDVARS%CVV%LADV) THEN
      SELF%CVV   => YDCPG_SL1%CVV
      SELF%F_CVV => YDCPG_SL1%F_CVV
    ELSE
      SELF%CVV   => YDVARS%CVV%T1
      SELF%F_CVV => YDVARS%CVV%FT1
    ENDIF
    IF (YDVARS%RKTH%LADV) THEN
      SELF%RKTH   => YDCPG_SL1%RKTH
      SELF%F_RKTH => YDCPG_SL1%F_RKTH
    ELSE
      SELF%RKTH   => YDVARS%RKTH%T1
      SELF%F_RKTH => YDVARS%RKTH%FT1
    ENDIF
    IF (YDVARS%RKTQV%LADV) THEN
      SELF%RKTQV   => YDCPG_SL1%RKTQV
      SELF%F_RKTQV => YDCPG_SL1%F_RKTQV
    ELSE
      SELF%RKTQV   => YDVARS%RKTQV%T1
      SELF%F_RKTQV => YDVARS%RKTQV%FT1
    ENDIF
    IF (YDVARS%RKTQC%LADV) THEN
      SELF%RKTQC   => YDCPG_SL1%RKTQC
      SELF%F_RKTQC => YDCPG_SL1%F_RKTQC
    ELSE
      SELF%RKTQC   => YDVARS%RKTQC%T1
      SELF%F_RKTQC => YDVARS%RKTQC%FT1
    ENDIF
    IF (YDVARS%UOM%LADV) THEN
      SELF%UOM   => YDCPG_SL1%UOM
      SELF%F_UOM => YDCPG_SL1%F_UOM
    ELSE
      SELF%UOM   => YDVARS%UOM%T1
      SELF%F_UOM => YDVARS%UOM%FT1
    ENDIF
    IF (YDVARS%UAL%LADV) THEN
      SELF%UAL   => YDCPG_SL1%UAL
      SELF%F_UAL => YDCPG_SL1%F_UAL
    ELSE
      SELF%UAL   => YDVARS%UAL%T1
      SELF%F_UAL => YDVARS%UAL%FT1
    ENDIF
    IF (YDVARS%DOM%LADV) THEN
      SELF%DOM   => YDCPG_SL1%DOM
      SELF%F_DOM => YDCPG_SL1%F_DOM
    ELSE
      SELF%DOM   => YDVARS%DOM%T1
      SELF%F_DOM => YDVARS%DOM%FT1
    ENDIF
    IF (YDVARS%DAL%LADV) THEN
      SELF%DAL   => YDCPG_SL1%DAL
      SELF%F_DAL => YDCPG_SL1%F_DAL
    ELSE
      SELF%DAL   => YDVARS%DAL%T1
      SELF%F_DAL => YDVARS%DAL%FT1
    ENDIF
    IF (YDVARS%UEN%LADV) THEN
      SELF%UEN   => YDCPG_SL1%UEN
      SELF%F_UEN => YDCPG_SL1%F_UEN
    ELSE
      SELF%UEN   => YDVARS%UEN%T1
      SELF%F_UEN => YDVARS%UEN%FT1
    ENDIF
    IF (YDVARS%UNEBH%LADV) THEN
      SELF%UNEBH   => YDCPG_SL1%UNEBH
      SELF%F_UNEBH => YDCPG_SL1%F_UNEBH
    ELSE
      SELF%UNEBH   => YDVARS%UNEBH%T1
      SELF%F_UNEBH => YDVARS%UNEBH%FT1
    ENDIF
    IF (YDVARS%FSD%LADV) THEN
      SELF%FSD   => YDCPG_SL1%FSD
      SELF%F_FSD => YDCPG_SL1%F_FSD
    ELSE
      SELF%FSD   => YDVARS%FSD%T1
      SELF%F_FSD => YDVARS%FSD%FT1
    ENDIF
  ENDIF  

ELSE

  SELF%U     => YDVARS%U%T1
  SELF%F_U   => YDVARS%U%FT1
  SELF%V     => YDVARS%V%T1
  SELF%F_V   => YDVARS%V%FT1
  SELF%T     => YDVARS%T%T1
  SELF%F_T   => YDVARS%T%FT1
  SELF%SVD   => YDVARS%SVD%T1
  SELF%F_SVD => YDVARS%SVD%FT1
  SELF%SP    => YDVARS%SP%T1
  SELF%F_SP  => YDVARS%SP%FT1

  SELF%Q   => YDVARS%Q%T1
  SELF%F_Q => YDVARS%Q%FT1
  SELF%I   => YDVARS%I%T1
  SELF%F_I => YDVARS%I%FT1
  SELF%L   => YDVARS%L%T1
  SELF%F_L => YDVARS%L%FT1
  SELF%LCONV   => YDVARS%LCONV%T1
  SELF%F_LCONV => YDVARS%LCONV%FT1
  SELF%ICONV   => YDVARS%ICONV%T1
  SELF%F_ICONV => YDVARS%ICONV%FT1
  SELF%RCONV   => YDVARS%RCONV%T1
  SELF%F_RCONV => YDVARS%RCONV%FT1
  SELF%SCONV   => YDVARS%SCONV%T1
  SELF%F_SCONV => YDVARS%SCONV%FT1
  SELF%IRAD   => YDVARS%IRAD%T1
  SELF%F_IRAD => YDVARS%IRAD%FT1
  SELF%LRAD   => YDVARS%LRAD%T1
  SELF%F_LRAD => YDVARS%LRAD%FT1
  SELF%S   => YDVARS%S%T1
  SELF%F_S => YDVARS%S%FT1
  SELF%R   => YDVARS%R%T1
  SELF%F_R => YDVARS%R%FT1
  SELF%G   => YDVARS%G%T1
  SELF%F_G => YDVARS%G%FT1
  SELF%H   => YDVARS%H%T1
  SELF%F_H => YDVARS%H%FT1
  SELF%TKE   => YDVARS%TKE%T1
  SELF%F_TKE => YDVARS%TKE%FT1
  SELF%TTE   => YDVARS%TTE%T1
  SELF%F_TTE => YDVARS%TTE%FT1
  SELF%EFB1   => YDVARS%EFB1%T1
  SELF%F_EFB1 => YDVARS%EFB1%FT1
  SELF%EFB2   => YDVARS%EFB2%T1
  SELF%F_EFB2 => YDVARS%EFB2%FT1
  SELF%EFB3   => YDVARS%EFB3%T1
  SELF%F_EFB3 => YDVARS%EFB3%FT1
  SELF%A   => YDVARS%A%T1
  SELF%F_A => YDVARS%A%FT1
  SELF%O3   => YDVARS%O3%T1
  SELF%F_O3 => YDVARS%O3%FT1
  SELF%SRC   => YDVARS%SRC%T1
  SELF%F_SRC => YDVARS%SRC%FT1
  SELF%MXL   => YDVARS%MXL%T1
  SELF%F_MXL => YDVARS%MXL%FT1
  SELF%SHTUR   => YDVARS%SHTUR%T1
  SELF%F_SHTUR => YDVARS%SHTUR%FT1
  SELF%FQTUR   => YDVARS%FQTUR%T1
  SELF%F_FQTUR => YDVARS%FQTUR%FT1
  SELF%FSTUR   => YDVARS%FSTUR%T1
  SELF%F_FSTUR => YDVARS%FSTUR%FT1
  SELF%CPF   => YDVARS%CPF%T1
  SELF%F_CPF => YDVARS%CPF%FT1
  SELF%SPF   => YDVARS%SPF%T1
  SELF%F_SPF => YDVARS%SPF%FT1
  SELF%CVGQ   => YDVARS%CVGQ%T1
  SELF%F_CVGQ => YDVARS%CVGQ%FT1
  SELF%QVA   => YDVARS%QVA%T1
  SELF%F_QVA => YDVARS%QVA%FT1
  SELF%LRCH4   => YDVARS%LRCH4%T1
  SELF%F_LRCH4 => YDVARS%LRCH4%FT1
  SELF%PHYCTY   => YDVARS%PHYCTY%T1
  SELF%F_PHYCTY => YDVARS%PHYCTY%FT1
  SELF%RSPEC   => YDVARS%RSPEC%T1
  SELF%F_RSPEC => YDVARS%RSPEC%FT1
  SELF%SDSAT   => YDVARS%SDSAT%T1
  SELF%F_SDSAT => YDVARS%SDSAT%FT1
  SELF%CVV   => YDVARS%CVV%T1
  SELF%F_CVV => YDVARS%CVV%FT1
  SELF%RKTH   => YDVARS%RKTH%T1
  SELF%F_RKTH => YDVARS%RKTH%FT1
  SELF%RKTQV   => YDVARS%RKTQV%T1
  SELF%F_RKTQV => YDVARS%RKTQV%FT1
  SELF%RKTQC   => YDVARS%RKTQC%T1
  SELF%F_RKTQC => YDVARS%RKTQC%FT1
  SELF%UOM   => YDVARS%UOM%T1
  SELF%F_UOM => YDVARS%UOM%FT1
  SELF%UAL   => YDVARS%UAL%T1
  SELF%F_UAL => YDVARS%UAL%FT1
  SELF%DOM   => YDVARS%DOM%T1
  SELF%F_DOM => YDVARS%DOM%FT1
  SELF%DAL   => YDVARS%DAL%T1
  SELF%F_DAL => YDVARS%DAL%FT1
  SELF%UEN   => YDVARS%UEN%T1
  SELF%F_UEN => YDVARS%UEN%FT1
  SELF%UNEBH   => YDVARS%UNEBH%T1
  SELF%F_UNEBH => YDVARS%UNEBH%FT1
  SELF%FSD   => YDVARS%FSD%T1
  SELF%F_FSD => YDVARS%FSD%FT1

ENDIF

END ASSOCIATE

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT

END MODULE MF_PHYS_NEXT_STATE_TYPE_MOD
