!
! Copyright 2011-2017 ECMWF
!
! This software was developed at ECMWF for evaluation
! and may be used for academic and research purposes only.
! The software is provided as is without any warranty.
!
! This software can be used, copied and modified but not
! redistributed or sold. This notice must be reproduced
! on each copy made.
!

!> Handle model configuration for the IFS model

MODULE MODEL_MOD

USE TYPE_MODEL  , ONLY : MODEL
USE PARKIND1    , ONLY : JPRB, JPIM
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMRIP0     , ONLY : NINDAT, NSSSSS

IMPLICIT NONE

PRIVATE

PUBLIC :: MODEL, MODEL_SET,      MODEL_UNSET,  MODEL_CREATE,    MODEL_DELETE, &
 & MODEL_INIT,   MODEL_INI_PHYS, MODEL_STEP,   MODEL_STEP_TRAJ, MODEL_FINALIZE, &
 & MODEL_INITTL, MODEL_STEPTL,   MODEL_STEPAD, MODEL_INITAD

! ------------------------------------------------------------------------------

CONTAINS

SUBROUTINE MODEL_SET(SELF)

USE YOMHOOK     , ONLY : LHOOK, DR_HOOK
!!USE YOMDIMF     , ONLY : YRDIMF
USE YOMDPHY     , ONLY : YRDPHY
!!USE YOMSLPHY    , ONLY : YRSLPHY
USE YOM_YGFL    , ONLY : YGFL
!!USE YOMDYN      , ONLY : YRDYN
!!USE YOMRIP      , ONLY : YRRIP
!!USE YOERIP      , ONLY : YRERIP
!!USE YOMOZO      , ONLY : YROZO
!!USE INTDYNSL_MOD, ONLY : YYTLSCAW, YYTLSCAWH, YYTRSCAW, YYTRSCAWH, YYTSCO, YYTCCO
!!USE YOMCHEM     , ONLY : YRCHEM
!!USE YOMCOMPO    , ONLY : YRCOMPO
!!USE YOECLD      , ONLY : YRECLD
!!USE YOECND      , ONLY : YRECND
!!USE YOECUMF     , ONLY : YRECUMF
!!USE YOECUMF2    , ONLY : YRECUMF2
!!USE YOMCUMFS    , ONLY : YRCUMFS
!!USE YOEGWD      , ONLY : YREGWD
!!USE YOEGWWMS    , ONLY : YREGWWMS
!!USE YOMRADF     , ONLY : YRRADF
USE YOERAD      , ONLY : YRERAD ! used in obs operator
!!USE RADIATION_SETUP, ONLY : YRADIATION
!!USE YOEOVLP     , ONLY : YREOVLP
!!USE YOENEUR     , ONLY : YRENEUR
!!USE YOELWRAD    , ONLY : YRELWRAD
!!USE YOEAERD     , ONLY : YREAERD
!!USE YOMAERD15   , ONLY : YRAERD15
USE YOEAERATM   , ONLY : YREAERATM ! used in obs operator
!!USE YOE_UVRAD   , ONLY : YREUVRAD
!!USE YOECLDP     , ONLY : YRECLDP
!!USE YOEWCOU     , ONLY : YREWCOU
USE YOEPHLI     , ONLY : YREPHLI !! still used in obs stuff at CY45
!!USE YOPHNC      , ONLY : YRPHNC
!!USE YOPHLC      , ONLY : YRPHLC
USE YOEAERLID   , ONLY : YREAERLID
!!USE YOEAERMAP   , ONLY : YREAERMAP
USE YOEAERSNK   , ONLY : YREAERSNK
USE YOEAERSRC   , ONLY : YREAERSRC
USE YOEAERVOL   , ONLY : YREAERVOL
!!USE YOEDBUG     , ONLY : YREDBUG
USE YOEPHY      , ONLY : YREPHY
!!USE YOMMCC      , ONLY : YRMCC
!!USE YOMCOM      , ONLY : YRCOM
!!USE YOMCOU      , ONLY : YRCOU
!!USE YOMSLREP    , ONLY : YRSLREP
!!USE YOMNCL      , ONLY : YRNCL
!!USE YOEGWDWMS   , ONLY : YREGWDWMS
!!USE YOMSRFTLAD  , ONLY : YRSRFTLAD
!!USE YOMRCOEF    , ONLY : YRRCOEF
!!USE YOMTNH      , ONLY : YRTNH
!!USE YOMCDDH     , ONLY : YRCDDH
!!USE YOMLDDH     , ONLY : YRLDDH
!!USE YOMMDDH     , ONLY : YRMDDH
!!USE YOMSDDH     , ONLY : YRSDDH
!!USE YOMTDDH     , ONLY : YRTDDH
!!USE YOMGPDDH    , ONLY : YRGPDDH
!!USE YOMPADDH    , ONLY : YRPADDH
!!USE YOMSPDDH    , ONLY : YRSPDDH
!!USE PTRGPPC     , ONLY : YRPTRGPPC
!!USE PTRSLB1     , ONLY : YRPTRSLB1
!!USE PTRSLB2     , ONLY : YRPTRSLB2
!!USE PTRSLB15    , ONLY : YRPTRSLB15
!!USE YOMPRAD     , ONLY : RADGRID, YRAD_GSGEOM
!!USE YOERDI      , ONLY : YRERDI
!!USE YOMCFU      , ONLY : YRCFU
!!USE YOMXFU      , ONLY : YRXFU
!!USE STOPH_MIX   , ONLY : YRSTOPH
!!USE YOE_CUCONVCA, ONLY : YRECUCONVCA
!!USE YOMGFUB     , ONLY : GFUBUF
!!USE YOMXFUB     , ONLY : XFUBUF
!!USE YOMGPPCB    , ONLY : GPPCBUF
!!USE YOMRANDOM_STREAMS, ONLY : YR_RANDOM_STREAMS
!!USE YOE_MCICA   , ONLY : YREMCICA
!!USE YOMTRC      , ONLY : YRTRC
!!USE YOMSPHYHIST , ONLY : GPHIST
!!USE SPNG_MOD    , ONLY : YRSPNG
! ALADIN modules and structures
!USE YEMDYN      , ONLY : YREDYN
!USE YEMGEO      , ONLY : YREGEO
!USE YEMGSL      , ONLY : YREGSL
!USE YEMMP       , ONLY : YREMP
! Physic modules and structures
!!USE YOMCVMNH    , ONLY : YRCVMNH
USE YOMPHY      , ONLY : YRPHY
USE YOMPHY0     , ONLY : YRPHY0
USE YOMPHY1     , ONLY : YRPHY1
USE YOMPHY2     , ONLY : YRPHY2
!!USE YOMPHY3     , ONLY : YRPHY3
!!USE YOMPHYDS    , ONLY : YRPHYDS
!!USE YOMTOPH     , ONLY : YRTOPH
!!USE YOMVDOZ     , ONLY : YRVDOZ
!!USE YOMSIMPHL   , ONLY : YRSIMPHL
!!USE YOMARPHY    , ONLY : YRARPHY
!!USE YOMPARAR    , ONLY : YRPARAR
!!USE YOMMSE      , ONLY : YRMSE
USE YOMLOUIS    , ONLY : YRLOUIS
USE YOMCST      , ONLY : YRCST
IMPLICIT NONE

TYPE(MODEL), TARGET, INTENT(IN) :: SELF

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_SET',0,ZHOOK_HANDLE)

!!YRDIMF            => SELF%YRML_GCONF%YRDIMF
YRDPHY            => SELF%YRML_PHY_G%YRDPHY
!!YRSLPHY           => SELF%YRML_PHY_G%YRSLPHY
YGFL              => SELF%YRML_GCONF%YGFL     !! remove after cleaning up calls to GPRCPTL in op_obs
!!YRDYN             => SELF%YRML_DYN%YRDYN
!!YREDYN            => SELF%YRML_DYN%YREDYN
!!YRRIP             => SELF%YRML_GCONF%YRRIP
!!YRERIP            => SELF%YRML_PHY_RAD%YRERIP
!!YROZO             => SELF%YRML_CHEM%YROZO
!!YYTLSCAW          => SELF%YRML_DYN%YYTLSCAW
!!YYTLSCAWH         => SELF%YRML_DYN%YYTLSCAWH
!!YYTRSCAW          => SELF%YRML_DYN%YYTRSCAW
!!YYTRSCAWH         => SELF%YRML_DYN%YYTRSCAWH
!!YYTSCO            => SELF%YRML_DYN%YYTSCO
!!YYTCCO            => SELF%YRML_DYN%YYTCCO
!!YRCHEM            => SELF%YRML_CHEM%YRCHEM
!!!YRCOMPO           => SELF%YRCOMPO
!!YRECLD            => SELF%YRML_PHY_EC%YRECLD
!!YRECND            => SELF%YRML_PHY_EC%YRECND
!!YRECUMF           => SELF%YRML_PHY_EC%YRECUMF
!!YRECUMF2          => SELF%YRML_PHY_SLIN%YRECUMF2
!!YRCUMFS           => SELF%YRML_PHY_SLIN%YRCUMFS
!!YREGWD            => SELF%YRML_PHY_EC%YREGWD
!!YREGWWMS          => SELF%YRML_PHY_EC%YREGWWMS
!!YRRADF            => SELF%YRML_PHY_RAD%YRRADF
YRERAD            => SELF%YRML_PHY_RAD%YRERAD
!!YRADIATION        => SELF%YRML_PHY_RAD%YRADIATION
!!YREOVLP           => SELF%YRML_PHY_RAD%YREOVLP
!!YRENEUR           => SELF%YRML_PHY_RAD%YRENEUR
!!YRELWRAD          => SELF%YRML_PHY_RAD%YRELWRAD
!!YREAERD           => SELF%YRML_PHY_RAD%YREAERD
!!YRAERD15          => SELF%YRML_PHY_RAD%YRAERD15
YREAERATM         => SELF%YRML_PHY_RAD%YREAERATM
!!YREUVRAD          => SELF%YRML_PHY_RAD%YREUVRAD
!!YRTILEPROP        => SELF%YRTILEPROP
!!YRECLDP           => SELF%YRML_PHY_EC%YRECLDP
!!YREWCOU           => SELF%YREWCOU
YREPHLI           => SELF%YRML_PHY_SLIN%YREPHLI
!!YRPHNC            => SELF%YRML_PHY_SLIN%YRPHNC
!!YRPHLC            => SELF%YRML_PHY_SLIN%YRPHLC
YREAERLID         => SELF%YRML_PHY_AER%YREAERLID
!!YREAERMAP         => SELF%YRML_PHY_AER%YREAERMAP
YREAERSNK         => SELF%YRML_PHY_AER%YREAERSNK
YREAERSRC         => SELF%YRML_PHY_AER%YREAERSRC
YREAERVOL         => SELF%YRML_PHY_AER%YREAERVOL
!!YREDBUG           => SELF%YRML_PHY_AER%YREDBUG
YREPHY            => SELF%YRML_PHY_EC%YREPHY
!!YRMCC             => SELF%YRML_AOC%YRMCC
!!YRCOM             => SELF%YRML_AOC%YRCOM
!!YRCOU             => SELF%YRML_AOC%YRCOU
!!YRSLREP           => SELF%YRML_DYN%YRSLREP
!!YRNCL             => SELF%YRML_PHY_SLIN%YRNCL
!!YREGWDWMS         => SELF%YRML_PHY_SLIN%YREGWDWMS
!!YRSRFTLAD         => SELF%YRML_PHY_SLIN%YRSRFTLAD
!!YRRCOEF           => SELF%YRML_PHY_RAD%YRRCOEF
!!YRTNH             => SELF%YRML_DYN%YRTNH
!!YRCDDH            => SELF%YRML_DIAG%YRCDDH
!!YRLDDH            => SELF%YRML_DIAG%YRLDDH
!!YRMDDH            => SELF%YRML_DIAG%YRMDDH
!!YRSDDH            => SELF%YRML_DIAG%YRSDDH
!!YRTDDH            => SELF%YRML_DIAG%YRTDDH
!!YRGPDDH           => SELF%YRML_DIAG%YRGPDDH
!!YRPADDH           => SELF%YRML_DIAG%YRPADDH
!!YRSPDDH           => SELF%YRML_DIAG%YRSPDDH
!!YRPTRGPPC         => SELF%YRML_DYN%YRPTRGPPC
!!YRPTRSLB1         => SELF%YRML_DYN%YRPTRSLB1
!!YRPTRSLB2         => SELF%YRML_DYN%YRPTRSLB2
!!YRPTRSLB15        => SELF%YRML_DYN%YRPTRSLB15
!!RADGRID           => SELF%YRML_PHY_RAD%RADGRID
!!YRAD_GSGEOM       => SELF%YRML_PHY_RAD%YRAD_GSGEOM
!!YRERDI            => SELF%YRML_PHY_RAD%YRERDI
!!YRCFU             => SELF%YRML_DIAG%YRCFU
!!YRXFU             => SELF%YRML_DIAG%YRXFU
!!YR_RANDOM_STREAMS => SELF%YRML_PHY_STOCH%YR_RANDOM_STREAMS
!!YRSTOPH           => SELF%YRML_PHY_STOCH%YRSTOPH
!!YRECUCONVCA       => SELF%YRML_PHY_EC%YRECUCONVCA
!!GFUBUF            => SELF%GFUBUF
!!XFUBUF            => SELF%XFUBUF
!!GPPCBUF           => SELF%GPPCBUF
!!YRCSGEOMAD        => SELF%YRCSGEOMAD     !! moved to GEOMETRY
!!YRCSGEOMAD_NB     => SELF%YRCSGEOMAD_NB
!!YRGSGEOMAD        => SELF%YRGSGEOMAD
!!YRGSGEOMAD_NB     => SELF%YRGSGEOMAD_NB
!!YREMCICA          => SELF%YRML_PHY_RAD%YREMCICA
!!YRTRC             => SELF%YRML_PHY_RAD%YRTRC
!!GPHIST            => SELF%YRML_PHY_SLIN%GPHIST
!!YRSPNG            => SELF%YRML_DYN%YRSPNG
! ALADIN modules and structures
!YREGEO            => SELF%YREGEO
!YREGSL            => SELF%YREGSL
!YREMP             => SELF%YREMP
! Physic modules and structures
!!YRCVMNH           => SELF%YRML_PHY_MF%YRCVMNH
YRPHY             => SELF%YRML_PHY_MF%YRPHY
YRPHY0            => SELF%YRML_PHY_MF%YRPHY0
YRPHY1            => SELF%YRML_PHY_MF%YRPHY1
YRPHY2            => SELF%YRML_PHY_MF%YRPHY2
!!YRPHY3            => SELF%YRML_PHY_MF%YRPHY3
!!YRPHYDS           => SELF%YRML_PHY_MF%YRPHYDS
!!YRTOPH            => SELF%YRML_PHY_MF%YRTOPH
!!YRVDOZ            => SELF%YRML_PHY_MF%YRVDOZ
!!YRSIMPHL          => SELF%YRML_PHY_MF%YRSIMPHL
!!YRARPHY           => SELF%YRML_PHY_MF%YRARPHY
!!YRPARAR           => SELF%YRML_PHY_MF%YRPARAR
!!YRMSE             => SELF%YRML_PHY_MF%YRMSE
YRLOUIS           => SELF%YRML_PHY_MF%YRLOUIS
!YRSL              => SELF%YRML_DYN%YRSL
!YRAD              => SELF%YRAD   !! decide where to put them
!YRRI              => SELF%YRRI
!YRRO              => SELF%YRRO
YRCST             => SELF%YRCST

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_SET',1,ZHOOK_HANDLE)

END SUBROUTINE MODEL_SET

! ------------------------------------------------------------------------------

SUBROUTINE MODEL_UNSET(SELF)
USE YOMHOOK,   ONLY : LHOOK, DR_HOOK
IMPLICIT NONE
TYPE(MODEL), INTENT(IN) :: SELF
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_UNSET',0,ZHOOK_HANDLE)

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_UNSET',1,ZHOOK_HANDLE)
END SUBROUTINE MODEL_UNSET

! ------------------------------------------------------------------------------

SUBROUTINE MODEL_CREATE(SELF, YDGEOMETRY, PT, CDNAMELIST,LDLINEAR,KGFLCONF)

USE YOMHOOK,      ONLY : LHOOK, DR_HOOK
USE YOMLUN,       ONLY : NULNAM, NULOUT
!!USE EINT_MOD,     ONLY : YROB
USE YOE_CUCONVCA, ONLY : INI_CUCONVCA
USE YOMTRAJ,      ONLY : LTRAJALLOC
USE SPNG_MOD,     ONLY : SUSPNG
USE YOMCT0,       ONLY : NCONF, CNMEXP  ! TOWIL NAMARG HACK
USE YOMARG,       ONLY : LELAM, LECMWF, LSLAG, NSUPERSEDE, NFPSERVER  ! TOWIL NAMARG HACK
USE YOMSPSDT   ,  ONLY : YSPPT_CONFIG, YSPPT
USE SPP_MOD    ,  ONLY : YSPP_CONFIG, YSPP
USE GFL_SUBS_MOD, ONLY : DEACT_CLOUD_GFL

IMPLICIT NONE

TYPE(MODEL),            INTENT(INOUT) :: SELF
TYPE(GEOMETRY), TARGET, INTENT(INOUT) :: YDGEOMETRY
REAL(KIND=JPRB),        INTENT(IN)    :: PT
CHARACTER(LEN=*),       INTENT(IN)    :: CDNAMELIST
LOGICAL,                INTENT(IN)    :: LDLINEAR
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KGFLCONF

INTEGER(KIND=JPIM) :: IOS
CHARACTER (LEN=35) :: CLINE = '----------------------------------'
LOGICAL :: LLOPENED

REAL(KIND=JPRB) :: ZHOOK_HANDLE

#include "abor1.intfb.h"
#include "allocate_empty_trajectory.intfb.h"
#include "chem_init.intfb.h"
#include "ddhoff.intfb.h"
! #include "slcset.intfb.h"
#include "su0phy.intfb.h"
#include "suallo.intfb.h"
!!#include "sucfu.intfb.h"
#include "sudimf1.intfb.h"
#include "sudimf2.intfb.h"
#include "sudyn.intfb.h"
#include "sugfl.intfb.h"
#include "sugrib.intfb.h"
#include "sumcc.intfb.h"
#include "sumcclag.intfb.h"
#include "suphy.intfb.h"
#include "surand1.intfb.h"
#include "surip.intfb.h"
#include "suoph.intfb.h"
#include "sufa.intfb.h"
#include "susavtend.intfb.h"
#include "susc2b.intfb.h"
#include "suspvariables.intfb.h"
#include "suvareps.intfb.h"
! #include "suxfu.intfb.h"
#include "suspsdt.intfb.h"
#include "get_spp_conf.intfb.h"
#include "ini_spp.intfb.h"
#include "suclopn.intfb.h"
#include "suswn.intfb.h"
#include "suaersn.intfb.h"

! TOWIL NAMARG HACK
#include "namarg.nam.h"

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_CREATE',0,ZHOOK_HANDLE)

SELF%YRML_GCONF%GEOM => YDGEOMETRY
CALL MODEL_SET(SELF)

SELF%LINEAR_MODEL = LDLINEAR
WRITE(NULOUT,*) '---- MODEL_CREATE ----------- LINEAR MODEL = ',SELF%LINEAR_MODEL
!* Open namelist
INQUIRE(NULNAM,OPENED=LLOPENED)
IF (LLOPENED) CLOSE(NULNAM)
OPEN(NULNAM,FILE=CDNAMELIST,ACTION='READ',IOSTAT=IOS)
IF (IOS /= 0)&
  & CALL ABOR1("MODEL_MOD:MODEL_SETUP failed to open namelist "//TRIM(CDNAMELIST))

!*    Initialize special keys for the climate version
WRITE(NULOUT,*) '---- Set up MCC climate model keys --',CLINE
CALL SUMCC(SELF%YRML_AOC%YRMCC,SELF%YRML_PHY_EC%YREPHY,NULOUT)

!*    Initialize YOMRIP variables
WRITE(NULOUT,*) '------ Set up YOMRIP variables ',CLINE
CALL SURIP(YDGEOMETRY%YRDIM,SELF%YRML_GCONF%YRRIP)

!*    Initialize control of physical parameterizations
WRITE(NULOUT,*) '-- Set up physical parameterizations ',CLINE
CALL SU0PHY(SELF,NULOUT)

!! ky: maybe that too (formerly in SUDYN)?
!! !*    Initialize some dimensions for trajectory and background.
!! WRITE(NULOUT,*) '------ Set up some dimensions for trajectory and background ------',CLINE
!! CALL SUDIM_TRAJ

!*    Initialize file handling
WRITE(NULOUT,*) '---- Set up files handling, FA --',CLINE
CALL SUOPH(YDGEOMETRY)

!*    Initialize Arpege field names and GRIB packing options
WRITE(NULOUT,*) '--- Set up GRIB packing options ---',CLINE
CALL SUFA

!*    Initialize number of fields dimensions (part 2)
WRITE(NULOUT,*) '------ Set up number of fields dimensions, part 1  ------',CLINE
CALL SUDIMF1(SELF)

!*    Initialize pointers to save ECMWF physical tendencies
WRITE(NULOUT,*) '------ Set up pointers to save ECMWF physical tendencies ------',CLINE
CALL SUSAVTEND(SELF%YRML_PHY_EC%YREPHY%LSLPHY,SELF%YRML_PHY_G%YRSLPHY)

!*    Set up unified_treatment grid-point fields, from su0yoma:284
WRITE(NULOUT,*) '---- Set up unified_treatment grid-point fields -',CLINE
CALL SUGFL(YDGEOMETRY%YRDIMV,SELF,KGFLCONF)

!*    Initialize number of fields dimensions (part 2)
WRITE(NULOUT,*) '------ Set up number of fields dimensions, part 2  ------',CLINE
CALL SUDIMF2(SELF%YRML_GCONF)

CALL SUSPVARIABLES(SELF%YRML_GCONF)

!*    Allocate grid point and spectral arrays, from su0yoma:347
WRITE(NULOUT,*) '------ Set up : array allocations ------',CLINE
CALL SUALLO(YDGEOMETRY,SELF)

!*    Initialize DDH (Horizontal domains diagnostics)
WRITE(NULOUT,*) '------ Turn off DDH diagnostics --------',CLINE
CALL DDHOFF(YDGEOMETRY,SELF%YRML_GCONF,SELF%YRML_DIAG)

!! ky: maybe that too (formerly in SUDYN)?
!! !*    Setup TESTVAR.
!! WRITE(NULOUT,*) '---- Set up TESTVAR ----------',CLINE
!! CALL SETUP_TESTVAR

!*    Initialize Dynamics, from su0yomb:569 (necessary for susc2b)
WRITE(NULOUT,*) '---- Set up model dynamics ----------',CLINE
CALL SUDYN(YDGEOMETRY,SELF,NULOUT)

!*    Initialize new sponge
WRITE(NULOUT,*) '---- Set up new sponge ----------',CLINE
CALL SUSPNG(SELF%YRML_DYN%YRSPNG,SELF%YRML_GCONF%YRRIP,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRSTA%STZ)

!*    Initialize Physics
WRITE(NULOUT,*) '---- Set up model physics -----------',CLINE
CALL SUPHY(YDGEOMETRY,SELF,NULOUT)
!*    Initialize special keys for the climate version 2nd part

WRITE(NULOUT,*) '---- Set up MCC climate model keys (lagged part) --',CLINE
CALL SUMCCLAG(YDGEOMETRY%YRGEM,SELF%YRML_GCONF,SELF%YRML_AOC,SELF%YRML_CHEM%YRCOMPO, &
     &  SELF%YRML_CHEM%YRCHEM, SELF%YRML_PHY_EC%YREPHY, NULOUT)

!*    Initialize cumulated fluxes requests
!!WRITE(NULOUT,*) '------ Set up cumulated fluxes diags ---',CLINE
!!CALL SUCFU(YDGEOMETRY,SELF%YRML_DIAG%YRCFU,SELF%YRML_GCONF%YRRIP,SELF%YRML_PHY_RAD%YRERAD,SELF%YRML_PHY_MF%YRPHY,NULOUT)

!*    Initialize instantaneous fluxes requests
!!WRITE(NULOUT,*) '------ Set up instantaneous fluxes diags ',CLINE
!!CALL SUXFU(YDGEOMETRY,SELF%YRML_DIAG%YRXFU,SELF%YRML_GCONF%YRRIP,SELF%YRML_PHY_MF%YRPHY,NULOUT)

!*    Initialize buffers for gridpoint scanning, part2, from su0yomb:624
WRITE(NULOUT,*) '---- Set up gridpoint scanning, part B ----',CLINE
IF (NCONF /= 901 .AND. NCONF /= 903) CALL SUSC2B(YDGEOMETRY,SELF)

!!** OLIVIER addition, to fill in NGRIB_HANDLE_XX variables
CALL SUVAREPS(SELF%YRML_GCONF%YRRIP)
CALL SUGRIB(YDGEOMETRY%YRDIM,SELF%YRML_PHY_EC%YREPHY,SELF%YRML_PHY_G%YRDPHY,SELF%YRML_PHY_MF%YRPHY)

!    If required allocate empty skeleton of trajectory structure
IF (.NOT. LTRAJALLOC .AND. (NCONF /= 401) .AND. (NCONF /= 501) .AND.&
                         & (NCONF /= 601) .AND. (NCONF /= 801)) THEN
  CALL ALLOCATE_EMPTY_TRAJECTORY(YDGEOMETRY%YRDIM,SELF%YRML_GCONF%YRRIP)
ENDIF

!*    Set up Stochastic Physics
WRITE(NULOUT,*) '--- Set up stochastic physics, SPBS, CABS ',CLINE
CALL INI_CUCONVCA(YDGEOMETRY,SELF%YRML_PHY_EC%YRECUCONVCA, SELF%YRML_DYN%YRSL)
CALL SURAND1(YDGEOMETRY,SELF%YRML_PHY_STOCH,SELF%YRML_DYN%YRDYN,SELF%YRML_GCONF%YRRIP,SELF%YRML_PHY_EC%YRECUCONVCA)

!     Set up spectral stochastic diabatic tendencies
WRITE(NULOUT,'(A72)') '--- Set up stochastically perturbed parametrization tendencies '//CLINE
WRITE(NULOUT,*)       '      SPPT a.k.a. stochastic physics with spectral pattern'
CALL SUSPSDT(YDGEOMETRY, SELF%YRML_GCONF%YRRIP, YSPPT_CONFIG, YSPPT)

!     Set up stochastically perturbed parameterisation scheme

WRITE(NULOUT,*) '--- Set up stochastically perturbed parametrization scheme (SPP)  ',CLINE
CALL GET_SPP_CONF(SELF%YRML_GCONF%YRRIP, YSPP_CONFIG)
CALL INI_SPP(YDGEOMETRY, SELF%YRML_GCONF%YRRIP, YSPP_CONFIG, YSPP)

!antje Chemistry not called in minimization
IF (SELF%YRML_GCONF%YGFL%NCHEM > 0 .AND. .NOT. SELF%LINEAR_MODEL ) THEN
  CALL CHEM_INIT(YDGEOMETRY,SELF%YRML_GCONF,SELF%YRML_CHEM)
ENDIF

CLOSE(NULNAM)
! This should be a temporary fudge
OPEN(NULNAM,FILE='fort.4',ACTION='READ',IOSTAT=IOS)

!Modify some settings if it is an OOPS linear model being set up
IF(SELF%LINEAR_MODEL) THEN
  WRITE(NULOUT,*) '---- Mode for linear model -----------',CLINE
  IF(SELF%YRML_PHY_SLIN%YRPHNC%LENCLD2) CALL DEACT_CLOUD_GFL(YDGEOMETRY%YRDIMV,SELF)
  SELF%YRML_PHY_SLIN%YREPHLI%LPHYLIN = .TRUE.
  IF(SELF%YRML_PHY_SLIN%YRPHNC%LERADSW2 .AND. SELF%YRML_PHY_RAD%YRERAD%NSW > 2) THEN
    SELF%YRML_PHY_RAD%YRERAD%NSW=2
    CALL SUSWN(SELF%YRML_PHY_RAD%YRERAD,SELF%YRML_PHY_RAD%YRERAD%NTSW,SELF%YRML_PHY_RAD%YRERAD%NSW)
    CALL SUCLOPN(SELF%YRML_PHY_RAD%YRERAD,SELF%YRML_PHY_RAD%YRERAD%NTSW,&
     & SELF%YRML_PHY_RAD%YRERAD%NSW,YDGEOMETRY%YRDIMV%NFLEVG)
    CALL SUAERSN (SELF%YRML_PHY_RAD%YRERAD%NTSW, SELF%YRML_PHY_RAD%YRERAD%NSW)
  ENDIF
  SELF%YRML_PHY_RAD%YRERAD%NRADFR=1
ENDIF

CLOSE(NULNAM)

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_CREATE',1,ZHOOK_HANDLE)

END SUBROUTINE MODEL_CREATE

! ------------------------------------------------------------------------------

SUBROUTINE MODEL_DELETE(SELF)

USE YOMHOOK  , ONLY : LHOOK, DR_HOOK
IMPLICIT NONE

TYPE(MODEL), INTENT(INOUT) :: SELF

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_DELETE',0,ZHOOK_HANDLE)

CALL MODEL_UNSET(SELF)

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_DELETE',1,ZHOOK_HANDLE)

END SUBROUTINE MODEL_DELETE

! ------------------------------------------------------------------------------

SUBROUTINE MODEL_INIT(SELF, YDFIELDS, YDTIME)
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE FIELDS_MOD   , ONLY : FIELDS
USE YOMCT0       , ONLY : LSPRT
USE YOMCT3       , ONLY : NSTEP
USE DATETIME_TMP_MOD
USE YOMLUN      , ONLY : NULOUT
USE YOMTRAJ_OOPS, ONLY : LTRAJSAVE_OOPS
USE YOMTRAJ     , ONLY : LTRAJSAVE
USE YOMARG      , ONLY : LELAM
IMPLICIT NONE
TYPE(MODEL)       , INTENT(INOUT) :: SELF
TYPE(FIELDS)      , INTENT(INOUT) :: YDFIELDS
TYPE(DATETIME_TMP), INTENT(IN)    :: YDTIME
INTEGER(KIND=JPIM) :: II, JKGLO,  ICEND,  IBL
CHARACTER(LEN=9) :: CL="AAAA00AAA"

REAL(KIND=JPRB) :: ZHOOK_HANDLE

#include "ctvtot.intfb.h"
#include "specrt.intfb.h"
#include "especrt.intfb.h"
#include "transdirh_from_t0.intfb.h"
#include "transinvh.intfb.h"
#include "etransdirh_from_t0.intfb.h"
#include "etransinvh.intfb.h"
#include "spnorm.intfb.h"
#include "aro_surf_restart.h"
#include "gpnorm_gmv.intfb.h"
#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_INIT',0,ZHOOK_HANDLE)

CALL MODEL_SET(SELF)
LTRAJSAVE_OOPS = .FALSE.
LTRAJSAVE = .FALSE.
IF(.NOT.ALLOCATED(YDFIELDS%YRGMV%GMVT1))  ALLOCATE(YDFIELDS%YRGMV%GMVT1(YDFIELDS%GEOM%YRDIM%NPROMA, YDFIELDS%GEOM%YRDIMV%NFLEVG,&
 &                                                 YDFIELDS%YRGMV%YT1%NDIM,YDFIELDS%GEOM%YRDIM%NGPBLKS))
IF(.NOT.ALLOCATED(YDFIELDS%YRGMV%GMVT1S)) ALLOCATE(YDFIELDS%YRGMV%GMVT1S(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%YRGMV%YT1%NDIMS, &
 &                                                 YDFIELDS%GEOM%YRDIM%NGPBLKS))
IF(.NOT.ALLOCATED(YDFIELDS%YRGFL%GFLT1))  ALLOCATE(YDFIELDS%YRGFL%GFLT1(YDFIELDS%GEOM%YRDIM%NPROMA, YDFIELDS%GEOM%YRDIMV%NFLEVG, &
 &                                                 SELF%YRML_GCONF%YGFL%NDIM1,YDFIELDS%GEOM%YRDIM%NGPBLKS))

YDFIELDS%YRGMV%GMVT1  = 0._JPRB
YDFIELDS%YRGMV%GMVT1S = 0._JPRB
YDFIELDS%YRGFL%GFLT1  = 0._JPRB

NSTEP=0
CALL SETRIP0(YDTIME)

WRITE(NULOUT,*)'MODEL_INIT:BEFORE TRANSDIRH_FROM_T0'
CALL SPNORM(YDFIELDS%GEOM,SELF%YRML_GCONF,YDFIELDS%YRSPEC)
CALL GPNORM_GMV(YDFIELDS%GEOM,YDFIELDS%YRGMV)

IF (LELAM) THEN
   CALL ETRANSDIRH_FROM_T0(YDFIELDS%GEOM,YDFIELDS%YRGFL,YDFIELDS%YRGMV,CL, &
      &   SELF%YRML_GCONF%YRDIMF%NFTHER,YDFIELDS%YRSPEC)
   IF (LSPRT) THEN
     CALL ESPECRT(YDFIELDS%GEOM,YDFIELDS%YRGFL,SELF%YRML_GCONF%YGFL,0,YDFIELDS%YRSPEC)
   ENDIF

   WRITE(NULOUT,*)'MODEL_INIT:AFTER ETRANSDIRH_FROM_T0'
   CALL SPNORM(YDFIELDS%GEOM,SELF%YRML_GCONF,YDFIELDS%YRSPEC)

   CALL ETRANSINVH(YDFIELDS%GEOM,YDFIELDS%YRGFL,YDFIELDS%YRGMV,SELF%YRML_DIAG,SELF%YRML_GCONF, &
      &   CL,YDFIELDS%YRSPEC)
ELSE
   CALL TRANSDIRH_FROM_T0(YDFIELDS%GEOM,YDFIELDS%YRGFL,YDFIELDS%YRGMV,CL,SELF%YRML_GCONF%YRDIMF%NFTHER,YDFIELDS%YRSPEC)

   IF (LSPRT) THEN
     CALL SPECRT(YDFIELDS%GEOM,YDFIELDS%YRGFL,SELF%YRML_GCONF%YGFL,0,YDFIELDS%YRSPEC)
   ENDIF

   WRITE(NULOUT,*)'MODEL_INIT:AFTER TRANSDIRH_FROM_T0'
   CALL SPNORM(YDFIELDS%GEOM,SELF%YRML_GCONF,YDFIELDS%YRSPEC)

   CALL TRANSINVH(YDFIELDS%GEOM,YDFIELDS%YRGFL,YDFIELDS%YRGMV,SELF%YRML_DIAG,SELF%YRML_GCONF, &
    &               SELF%YRML_DYN%YRDYN%LRFRIC,SELF%YRML_DYN%YRDYN%RKRF,CL,YDFIELDS%YRSPEC)

   IF (LSPRT) THEN

     WRITE(NULOUT,*)'MODEL_INIT:AFTER TRANSINVH'
     DO JKGLO=1,YDFIELDS%GEOM%YRGEM%NGPTOT,YDFIELDS%GEOM%YRDIM%NPROMA
       ICEND=MIN(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRGEM%NGPTOT-JKGLO+1)
       IBL=(JKGLO-1)/YDFIELDS%GEOM%YRDIM%NPROMA+1
       CALL CTVTOT(YDFIELDS%GEOM,SELF%YRML_GCONF%YGFL,1,ICEND, &
        & YDFIELDS%YRGMV%GMV(1,1,YDFIELDS%YRGMV%YT0%MT,IBL),YDFIELDS%YRGFL%GFL(1,1,1,IBL))
     ENDDO
   ENDIF
ENDIF
CALL GPNORM_GMV(YDFIELDS%GEOM,YDFIELDS%YRGMV)

! Force the wave model to start from the first guess
SELF%YREWCOU%LWFRSTIME = .TRUE.

! Restart SURFEX
IF (SELF%YRML_PHY_MF%YRARPHY%LMSE) CALL ARO_SURF_RESTART(YDFIELDS%GEOM,SELF,NULOUT,'C',YDFIELDS%GEOM%YRDIM%NPROMA)

CALL MODEL_UNSET(SELF)

!CALL REACT_CLOUD_GFL(YDFIELDS%GEOM%YRDIMV)

!IF( MYPROC == 1 ) CALL SELF%PRINT('  configuration of model at the end of MODEL_INIT', 111)

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_INIT',1,ZHOOK_HANDLE)

END SUBROUTINE MODEL_INIT
! ------------------------------------------------------------------------------

SUBROUTINE MODEL_INI_PHYS(SELF, YDFIELDS, YDTIME)


!**** *MODEL_INI_PHYS*  - Initialize physical diagnostics (OOPS interface to STEPX)

!     Purpose.
!     --------
!        Initialize physical diagnostics

!**   Interface.
!     ----------
!        *CALL* *MODEL_INI_PHYS*

!        Explicit arguments :
!        --------------------

!        Implicit arguments :
!        --------------------
!        None

!     Method.
!     -------
!        See documentation

!     Externals.    see includes below.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Ryad El Khatib *Meteo-FRance*
!      Original : 09-Jul-2018 from CNT4

! Modifications
! -------------
! End Modifications
!------------------------------------------------------------------------------

USE PARKIND1     , ONLY : JPRB,JPIM
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE GEOMETRY_MOD , ONLY : GEOMETRY, GEOMETRY_SAME
USE FIELDS_MOD   , ONLY : FIELDS
USE YOMGFL       , ONLY : COPY_YOMGFL
USE YOMGMV       , ONLY : COPY_YOMGMV
USE MTRAJ_MOD    , ONLY : MTRAJ
USE DATETIME_TMP_MOD

IMPLICIT NONE

TYPE(MODEL)       , INTENT(INOUT) :: SELF
TYPE(FIELDS)      , INTENT(INOUT) :: YDFIELDS
TYPE(DATETIME_TMP), INTENT(IN)    :: YDTIME

TYPE(MTRAJ) :: YLMTRAJ
INTEGER(KIND=JPIM) :: JBL
REAL(KIND=JPRB), ALLOCATABLE :: ZGFL(:,:,:,:), ZGMV(:,:,:,:), ZGMVS(:,:,:)

REAL(KIND=JPRB) :: ZHOOK_HANDLE

#include "stepx.intfb.h"

!      -----------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_INI_PHYS',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDFIELDS%GEOM%YRDIM,YDDIMV=>YDFIELDS%GEOM%YRDIMV,YGFL=>YDFIELDS%STATE_MODEL%YRML_GCONF%YGFL, &
 & YDGMV=>YDFIELDS%YRGMV)
ASSOCIATE(NDIM=>YGFL%NDIM, NGPBLKS=>YDDIM%NGPBLKS, NPROMA=>YDDIM%NPROMA, NFLEVG=>YDDIMV%NFLEVG, &
 & NDIMGMV=>YDGMV%NDIMGMV, NDIMGMVS=>YDGMV%NDIMGMVS)

CALL MODEL_SET(SELF)

IF (.NOT.GEOMETRY_SAME(SELF%YRML_GCONF%GEOM,YDFIELDS%GEOM)) THEN
  CALL ABOR1('MODEL_MOD:MODEL_STEP - GEOMETRIES DIFFERENT')
ENDIF

IF (YDFIELDS%YRXFU%LXFU) THEN
  CALL SETRIP0(YDTIME)
ENDIF

! Work on copies of GMV/GFL because they will be modified by gridpoint computation
ALLOCATE(ZGMV(NPROMA,NFLEVG,NDIMGMV,NGPBLKS))
ALLOCATE(ZGMVS(NPROMA,NDIMGMVS,NGPBLKS))
ALLOCATE(ZGFL(NPROMA,NFLEVG,NDIM,NGPBLKS))
!$OMP PARALLEL DO PRIVATE(JBL)
  DO JBL = 1,NGPBLKS
    ZGMV(:,:,:,JBL) = YDFIELDS%YRGMV%GMV(:,:,:,JBL)
    ZGMVS (:,:,JBL) = YDFIELDS%YRGMV%GMVS (:,:,JBL)
    ZGFL(:,:,:,JBL) = YDFIELDS%YRGFL%GFL(:,:,:,JBL)
  ENDDO
!$OMP END PARALLEL DO

CALL STEPX(YDFIELDS%GEOM,YDFIELDS,YLMTRAJ,SELF)

! Recover GMV/GFL
!$OMP PARALLEL DO PRIVATE(JBL)
  DO JBL = 1,NGPBLKS
    YDFIELDS%YRGMV%GMV(:,:,:,JBL) = ZGMV(:,:,:,JBL)
    YDFIELDS%YRGMV%GMVS (:,:,JBL) = ZGMVS (:,:,JBL)
    YDFIELDS%YRGFL%GFL(:,:,:,JBL) = ZGFL(:,:,:,JBL)
  ENDDO
!$OMP END PARALLEL DO

CALL MODEL_UNSET(SELF)

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_INI_PHYS',1,ZHOOK_HANDLE)

END SUBROUTINE MODEL_INI_PHYS
! ------------------------------------------------------------------------------

SUBROUTINE MODEL_STEP(SELF, YDFIELDS, YDTIME, KSECS)

USE YOMHOOK     , ONLY : LHOOK, DR_HOOK
USE YOMCT0      , ONLY : NCONF
USE YOMCT3      , ONLY : NSTEP
USE FIELDS_MOD  , ONLY : FIELDS
USE MTRAJ_MOD   , ONLY : MTRAJ
USE GMV_SUBS_MOD, ONLY : SETUP_GMV5
USE YOMTRAJ_OOPS, ONLY : TRAJ_TYPE_OOPS,LTRAJSAVE_OOPS,LTRAJSLAG_OOPS
USE YOMTRAJ     , ONLY : LTRAJSAVE,LTRAJSLAG
USE YOMLUN      , ONLY : NULOUT, NULERR
USE GEOMETRY_MOD, ONLY : GEOMETRY,GEOMETRY_SAME
USE DATETIME_TMP_MOD


IMPLICIT NONE

#include "updtim.intfb.h"
#include "suecaec.intfb.h"
#include "spmcuf.intfb.h"
#include "stepo_oops.intfb.h"
#include "abor1.intfb.h"

TYPE(MODEL)       , INTENT(INOUT) :: SELF
TYPE(FIELDS)      , INTENT(INOUT) :: YDFIELDS
TYPE(DATETIME_TMP), INTENT(INOUT) :: YDTIME
INTEGER(KIND=JPIM), INTENT(INOUT) :: KSECS

TYPE(MTRAJ) :: YLMTRAJ
CHARACTER(LEN=9) :: CL="AAAA00AAA"
TYPE(TRAJ_TYPE_oops) :: YLOOPSTRAJ

CHARACTER (LEN = 10) ::  CLTIMEOD,CLDAT(3)
INTEGER(KIND=JPIM) :: IVALUES(8)

REAL(KIND=JPRB) :: ZHOOK_HANDLE
LOGICAL :: LLFIRSTCALL = .TRUE.
INTEGER(KIND=JPIM) :: IMINUT

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_STEP',0,ZHOOK_HANDLE)

CALL MODEL_SET(SELF)
IF(.NOT.GEOMETRY_SAME(SELF%YRML_GCONF%GEOM,YDFIELDS%GEOM)) CALL ABOR1('MODEL_MOD:MODEL_STEP - GEOMETRIES DIFFERENT')

!! 3D-Var case
IF ( SELF%YRML_GCONF%YRRIP%NSTOP == 0 ) RETURN

!! this should not be necessary here!
CALL SETUP_GMV5(YDFIELDS%GEOM, YLMTRAJ%YRGMV5, SELF%YRML_GCONF%YRDIMF)


LTRAJSLAG_oops=.FALSE.
LTRAJSAVE_oops=.FALSE.
LTRAJSLAG=.FALSE.
LTRAJSAVE=.FALSE.

CALL SETRIPSTEP(SELF%YRML_GCONF%YRRIP%TSTEP, YDTIME, KSECS)
CALL UPDTIM(YDFIELDS%GEOM,YDFIELDS%YRSURF,SELF,NSTEP,SELF%YRML_GCONF%YRRIP%TDT,SELF%YRML_GCONF%YRRIP%TSTEP,.TRUE.)

       IF(LLFIRSTCALL)THEN
         IMINUT=NINT(1.0_JPRB+(REAL(NSSSSS,JPRB))/60._JPRB)
         CALL SUECAEC(SELF%YRML_GCONF%GEOM,SELF%YRML_PHY_RAD%YRERAD,NINDAT,IMINUT)
         LLFIRSTCALL=.FALSE.
       ENDIF

CALL DATE_AND_TIME(CLDAT(1),CLTIMEOD,CLDAT(3),IVALUES)

CALL STEPO_OOPS(YDFIELDS%GEOM,YDFIELDS,YLMTRAJ,SELF,YLOOPSTRAJ,CL)

NSTEP=NSTEP+1
CALL GETRIPSTEP(SELF%YRML_GCONF%YRRIP%TSTEP, YDTIME, KSECS)

IF (YDFIELDS%YMCUF%LMCUF) CALL SPMCUF(YDFIELDS%GEOM,YDFIELDS%YRSPEC,YDFIELDS%YMCUF)

CALL MODEL_UNSET(SELF)

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_STEP',1,ZHOOK_HANDLE)

END SUBROUTINE MODEL_STEP
! ------------------------------------------------------------------------------

SUBROUTINE MODEL_FINALIZE(SELF, YDFIELDS, YDTIME, KSECS)

USE YOMHOOK     , ONLY : LHOOK, DR_HOOK
USE YOMCT0      , ONLY : NCONF
USE YOMCT3      , ONLY : NSTEP
USE FIELDS_MOD  , ONLY : FIELDS
USE MTRAJ_MOD   , ONLY : MTRAJ
USE GMV_SUBS_MOD, ONLY : SETUP_GMV5
USE YOMTRAJ_OOPS, ONLY : TRAJ_TYPE_oops
USE YOMLUN      , ONLY : NULOUT
USE GEOMETRY_MOD, ONLY : GEOMETRY,GEOMETRY_SAME
USE DATETIME_TMP_MOD


IMPLICIT NONE

#include "updtim.intfb.h"
#include "suecaec.intfb.h"
#include "stepo_oops.intfb.h"
#include "abor1.intfb.h"
#include "spnorm.intfb.h"

TYPE(MODEL)       , INTENT(INOUT) :: SELF
TYPE(FIELDS)      , INTENT(INOUT) :: YDFIELDS
TYPE(DATETIME_TMP), INTENT(INOUT) :: YDTIME
INTEGER(KIND=JPIM), INTENT(INOUT) :: KSECS

TYPE(MTRAJ) :: YLMTRAJ
CHARACTER(LEN=9) :: CL="0AAA00000"
TYPE(TRAJ_TYPE_oops) :: YLOOPSTRAJ


REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_FINALIZE',0,ZHOOK_HANDLE)

CALL MODEL_SET(SELF)
IF(.NOT.GEOMETRY_SAME(SELF%YRML_GCONF%GEOM,YDFIELDS%GEOM)) CALL ABOR1('MODEL_MOD:MODEL_FINALIZE - GEOMETRIES DIFFERENT')


CALL SETRIPSTEP(SELF%YRML_GCONF%YRRIP%TSTEP, YDTIME, KSECS)
CALL UPDTIM(YDFIELDS%GEOM,YDFIELDS%YRSURF,SELF,NSTEP,SELF%YRML_GCONF%YRRIP%TDT,SELF%YRML_GCONF%YRRIP%TSTEP,.TRUE.)

CALL STEPO_OOPS(YDFIELDS%GEOM,YDFIELDS,YLMTRAJ,SELF,YLOOPSTRAJ,CL)

NSTEP=NSTEP+1
CALL GETRIPSTEP(SELF%YRML_GCONF%YRRIP%TSTEP, YDTIME, KSECS)

WRITE(NULOUT,*) 'Norms at end of forecast :'
CALL SPNORM(YDFIELDS%GEOM,SELF%YRML_GCONF,YDFIELDS%YRSPEC)

CALL MODEL_UNSET(SELF)

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_FINALIZE',1,ZHOOK_HANDLE)

END SUBROUTINE MODEL_FINALIZE

! ------------------------------------------------------------------------------

SUBROUTINE MODEL_STEP_TRAJ(SELF, LINMODEL, YDFIELDS, YDOOPSTRAJ, YDTIME, KSECS)
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE FIELDS_MOD   , ONLY : FIELDS, FIELDS_ZEROS, FIELDS_CREATE, FIELDS_DELETE
USE VARIABLES_MOD, ONLY : VARIABLES, VARIABLES_CREATE, VARIABLES_DELETE
USE MTRAJ_MOD    , ONLY : MTRAJ
USE YOMCT3       , ONLY : NSTEP
USE YOMLUN       , ONLY : NULOUT, NULERR

USE TRAJ_GLOBAL_MOD    , ONLY : ALLOCATE_TRAJECTORY_EMPTY
USE YOMTRAJ_OOPS       , ONLY : TRAJ_TYPE_oops, LTRAJSAVE_oops
USE TRAJECTORY_MOD_OOPS, ONLY : ALLOCATE_TRAJECTORY_oops,STORE_TRAJECTORY_oops
USE GMV_SUBS_MOD       , ONLY : SETUP_GMV5
USE GEOMETRY_MOD       , ONLY : GEOMETRY,GEOMETRY_SAME
USE DATETIME_TMP_MOD
USE YOMTRAJ     , ONLY : LTRAJSAVE
USE YOMTRAJ_OOPS, ONLY : LTRAJSAVE_oops
USE YOE_PHYS_MWAVE     , ONLY : TEPHYSMWAVE
IMPLICIT NONE

TYPE(MODEL)         , INTENT(INOUT) :: SELF
TYPE(MODEL)         , INTENT(INOUT) :: LINMODEL
TYPE(FIELDS)        , INTENT(INOUT) :: YDFIELDS
TYPE(TRAJ_TYPE_OOPS), INTENT(INOUT) :: YDOOPSTRAJ
TYPE(DATETIME_TMP)  , INTENT(INOUT) :: YDTIME
INTEGER(KIND=JPIM)  , INTENT(INOUT) :: KSECS

CHARACTER (LEN = 10) ::  CLTIMEOD,CLDAT(3)
INTEGER(KIND=JPIM) :: IVALUES(8)

REAL(KIND=JPRB)    :: ZHOOK_HANDLE
INTEGER(KIND=JPIM) :: INSERT_POS
INTEGER(KIND=JPIM) :: JKGLO,  ICEND,  IBL
CHARACTER(LEN=9)   :: CL="TAAA00000"
LOGICAL :: LLFIRSTCALL = .TRUE.
LOGICAL :: LLFIRSTCALL_LIN = .TRUE.
INTEGER(KIND=JPIM) :: IMINUT

integer(kind=jpim) :: t_nstep
integer(kind=jpim),save :: l_nstep=0

TYPE(MTRAJ) :: YLMTRAJ !! local trajectory argument for STEPO_OOPS
TYPE(FIELDS) :: PERT_FIELDS
TYPE(VARIABLES) :: YL_VARS
TYPE(TEPHYSMWAVE) :: YRPHYSMWAVE5

#include "updtim.intfb.h"
#include "stepo_oops_traj.intfb.h"
#include "stepotl_traj_oops.intfb.h"
#include "gpnorm_gmv.intfb.h"
#include "suecaec.intfb.h"
#include "su_surf_flds.intfb.h"
#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_STEP_TRAJ',0,ZHOOK_HANDLE)

!! 3D-Var case
IF ( SELF%YRML_GCONF%YRRIP%NSTOP == 0 ) RETURN

!check that SELF is nonlinear model, and that LINMODEL is linear
IF(SELF%LINEAR_MODEL .OR. .NOT.(LINMODEL%LINEAR_MODEL)) THEN
  CALL ABOR1('Aborting in MODEL_STEP_TRAJ with wrong combination of models passed down from OOPS')
ENDIF
CALL SETRIPSTEP(SELF%YRML_GCONF%YRRIP%TSTEP, YDTIME, KSECS)
CALL MODEL_SET(SELF)
IF(.NOT.GEOMETRY_SAME(SELF%YRML_GCONF%GEOM,YDFIELDS%GEOM)) CALL ABOR1('MODEL_MOD:MODEL_STEP_TRAJ - GEOMETRIES DIFFERENT')
LTRAJSAVE_oops=.TRUE.
LTRAJSAVE=.TRUE.

!! this might not be best place for it!
CALL SETUP_GMV5(YDFIELDS%GEOM, YLMTRAJ%YRGMV5, SELF%YRML_GCONF%YRDIMF)

CALL UPDTIM(YDFIELDS%GEOM,YDFIELDS%YRSURF,SELF,NSTEP,SELF%YRML_GCONF%YRRIP%TDT,SELF%YRML_GCONF%YRRIP%TSTEP,.TRUE.)

       IF(LLFIRSTCALL)THEN
         IMINUT=NINT(1.0_JPRB+(REAL(NSSSSS,JPRB))/60._JPRB)
         CALL SUECAEC(SELF%YRML_GCONF%GEOM,SELF%YRML_PHY_RAD%YRERAD,NINDAT,IMINUT)
         LLFIRSTCALL=.FALSE.
       ENDIF


!! *NEW* trajectory code ...
CALL ALLOCATE_TRAJECTORY_EMPTY(SELF%YRML_GCONF%YRRIP)
CALL ALLOCATE_TRAJECTORY_OOPS(YDOOPSTRAJ,YDFIELDS%GEOM, YDFIELDS%YRGMV%NDIMGMV, YDFIELDS%YRGMV%NDIMGMVS, YDFIELDS%YRSURF, SELF )

!!!!!! CCCCARRRRRREEEFFUUULLLLLL!!!!
if (nstep==0) l_nstep = 0
t_nstep = nstep
nstep = l_nstep

CALL DATE_AND_TIME(CLDAT(1),CLTIMEOD,CLDAT(3),IVALUES)

CALL STEPO_OOPS_TRAJ(YDFIELDS%GEOM,YDFIELDS,YLMTRAJ,SELF,YDOOPSTRAJ,CL)
INSERT_POS=1
CALL STORE_TRAJECTORY_OOPS(YDOOPSTRAJ, SELF%YRML_GCONF, INSERT_POS, YDFIELDS%YRSPEC, YDFIELDS%YRGMV%GMV, YDFIELDS%YRGMV%GMVS, &
 &                        YDFIELDS%YRGFL%GFL, YDFIELDS, YLMTRAJ)

! Have in trajectory the right meta-data for surface fields
CALL SU_SURF_FLDS(YDFIELDS%GEOM%YRDIMV,YDOOPSTRAJ%SURFACE%Y_SURF,SELF)

CALL MODEL_UNSET(SELF)

!! STEPO_OOPS call should update TRAJ_SLAG and TRAJ_PHYS in YDOOPSTRAJ

IF(LINMODEL%YRML_PHY_SLIN%YRPHNC%LETRAJP)THEN
  CALL MODEL_SET(LINMODEL)
  CALL VARIABLES_CREATE(YL_VARS, .false.)
  CALL FIELDS_CREATE(PERT_FIELDS,YDFIELDS%GEOM,LINMODEL,YL_VARS) !! replaced SELF by LINMODEL
  CALL FIELDS_ZEROS(PERT_FIELDS)

!! this might not be the right place to do it
  CALL SETUP_GMV5(YDFIELDS%GEOM, YLMTRAJ%YRGMV5, LINMODEL%YRML_GCONF%YRDIMF)

  IF (.NOT.ALLOCATED(YLMTRAJ%YRGMV5%GMV5))  ALLOCATE (YLMTRAJ%YRGMV5%GMV5(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRDIMV%NFLEVG, &
                                                    & YLMTRAJ%YRGMV5%YT5%NDIM,YDFIELDS%GEOM%YRDIM%NGPBLKS))
  IF (.NOT.ALLOCATED(YLMTRAJ%YRGMV5%GMV5S)) ALLOCATE (YLMTRAJ%YRGMV5%GMV5S(YDFIELDS%GEOM%YRDIM%NPROMA,YLMTRAJ%YRGMV5%YT5%NDIMS, &
                                                    & YDFIELDS%GEOM%YRDIM%NGPBLKS))
  IF (.NOT.ALLOCATED(YLMTRAJ%YRGFL5%GFL5))  ALLOCATE (YLMTRAJ%YRGFL5%GFL5(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRDIMV%NFLEVG, &
                                                    & LINMODEL%YRML_GCONF%YGFL%NDIM5,YDFIELDS%GEOM%YRDIM%NGPBLKS))

  ASSOCIATE(YT5=>YLMTRAJ%YRGMV5%YT5,NDIM5=>LINMODEL%YRML_GCONF%YGFL%NDIM5)
!! copy trajectory stuff into MTRAJ argument

  IF(.NOT.ASSOCIATED(YDOOPSTRAJ%MAIN%GMV))&
    & CALL ABOR1('READING OOPSTRAJ%MAIN: OOPSTRAJ%MAIN%GMV NOT ALLOCATED')

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO,ICEND,IBL)
  DO JKGLO=1,YDFIELDS%GEOM%YRGEM%NGPTOT,YDFIELDS%GEOM%YRDIM%NPROMA
    ICEND=MIN(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRGEM%NGPTOT-JKGLO+1)
    IBL=(JKGLO-1)/YDFIELDS%GEOM%YRDIM%NPROMA+1
    YLMTRAJ%YRGMV5%GMV5(1:ICEND,:,1:YT5%NDIM,IBL)=YDOOPSTRAJ%MAIN%GMV(1:ICEND,:,1:YT5%NDIM,IBL)
    YLMTRAJ%YRGMV5%GMV5S(1:ICEND,1:YT5%NDIMS,IBL)=YDOOPSTRAJ%MAIN%GMVS(1:ICEND,1:YT5%NDIMS,IBL)
    YLMTRAJ%YRGFL5%GFL5(1:ICEND,:,1:NDIM5,IBL)   =YDOOPSTRAJ%MAIN%GFL(1:ICEND,:,1:NDIM5,IBL)
  ENDDO
!$OMP END PARALLEL DO

  END ASSOCIATE

  CALL UPDTIM(YDFIELDS%GEOM,YDFIELDS%YRSURF,LINMODEL,NSTEP,LINMODEL%YRML_GCONF%YRRIP%TDT,LINMODEL%YRML_GCONF%YRRIP%TSTEP,.TRUE.)
       IF(LLFIRSTCALL_LIN)THEN
         IMINUT=NINT(1.0_JPRB+(REAL(NSSSSS,JPRB))/60._JPRB)
         CALL SUECAEC(LINMODEL%YRML_GCONF%GEOM,LINMODEL%YRML_PHY_RAD%YRERAD,NINDAT,IMINUT)
         LLFIRSTCALL_LIN=.FALSE.
       ENDIF

  CALL YRPHYSMWAVE5%CREATE(YDFIELDS%GEOM)

  CALL DATE_AND_TIME(CLDAT(1),CLTIMEOD,CLDAT(3),IVALUES)

  CALL STEPOTL_TRAJ_OOPS(YDFIELDS%GEOM,PERT_FIELDS,YLMTRAJ,LINMODEL,YDOOPSTRAJ,CL,YRPHYSMWAVE5)  !! replaced SELF by LINMODEL

  YDFIELDS%YEC_PHYS_FIELDS%YRPHYSMWAVE=YRPHYSMWAVE5
  CALL YRPHYSMWAVE5%DESTROY

  CALL VARIABLES_DELETE(YL_VARS)
  CALL FIELDS_DELETE(PERT_FIELDS)

CALL MODEL_UNSET(LINMODEL)

ENDIF
NSTEP=NSTEP+1

LTRAJSAVE_OOPS=.FALSE.
LTRAJSAVE=.FALSE.


!!!!!! CCCCARRRRRREEEFFUUULLLLLL!!!!   DO NOT DELETE, AUTHOR IS VERY PROUD OF IT
l_nstep = l_nstep+1
nstep = t_nstep


IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_STEP_TRAJ',1,ZHOOK_HANDLE)


END SUBROUTINE MODEL_STEP_TRAJ

! ------------------------------------------------------------------------------

SUBROUTINE MODEL_INITTL(SELF, DX, YDTIME)
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE FIELDS_MOD   , ONLY : FIELDS
USE YOMCT3       , ONLY : NSTEP
USE YOMLUN       , ONLY : NULOUT
USE GEOMETRY_MOD , ONLY : GEOMETRY,GEOMETRY_SAME
USE DATETIME_TMP_MOD
IMPLICIT NONE
TYPE(MODEL)       , INTENT(INOUT) :: SELF
TYPE(FIELDS)      , INTENT(INOUT) :: DX
TYPE(DATETIME_TMP), INTENT(IN)    :: YDTIME
CHARACTER(LEN=9)   :: CL="AAAA00AAA"
REAL(KIND=JPRB) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_INITTL',0,ZHOOK_HANDLE)

IF(.NOT.GEOMETRY_SAME(SELF%YRML_GCONF%GEOM,DX%GEOM)) CALL ABOR1('MODEL_MOD:MODEL_INITTL - GEOMETRIES DIFFERENT')
IF(.NOT.ALLOCATED(DX%YRGMV%GMVT1))  ALLOCATE(DX%YRGMV%GMVT1(DX%GEOM%YRDIM%NPROMA, DX%GEOM%YRDIMV%NFLEVG,&
 &                                                          DX%YRGMV%YT1%NDIM,DX%GEOM%YRDIM%NGPBLKS))
IF(.NOT.ALLOCATED(DX%YRGMV%GMVT1S)) ALLOCATE(DX%YRGMV%GMVT1S(DX%GEOM%YRDIM%NPROMA,DX%YRGMV%YT1%NDIMS, DX%GEOM%YRDIM%NGPBLKS))
IF(.NOT.ALLOCATED(DX%YRGFL%GFLT1))  ALLOCATE(DX%YRGFL%GFLT1(DX%GEOM%YRDIM%NPROMA, DX%GEOM%YRDIMV%NFLEVG, &
 &                                           SELF%YRML_GCONF%YGFL%NDIM1,DX%GEOM%YRDIM%NGPBLKS))

DX%YRGMV%GMVT1  = 0._JPRB
DX%YRGMV%GMVT1S = 0._JPRB
DX%YRGFL%GFLT1  = 0._JPRB

!! got to be careful with NSTEP initialisation
!! they could squash each other
NSTEP = 0
CALL SETRIP0(YDTIME)

!IF( MYPROC == 1 ) CALL SELF%PRINT('  configuration of model at the end of MODEL_INITTL', 111)

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_INITTL',1,ZHOOK_HANDLE)
END SUBROUTINE MODEL_INITTL

! ------------------------------------------------------------------------------

SUBROUTINE MODEL_STEPTL(SELF, YDFIELDS, YDOOPSTRAJ,YDTIME,KSECS)
USE YOMHOOK     , ONLY : LHOOK, DR_HOOK
USE FIELDS_MOD  , ONLY : FIELDS
USE MTRAJ_MOD   , ONLY : MTRAJ
USE YOMCT3      , ONLY : NSTEP
USE YOMCT0      , ONLY : LSPRT
USE YOMTRAJ_OOPS, ONLY : TRAJ_TYPE_oops
USE GMV_SUBS_MOD, ONLY : SETUP_GMV5
USE YOMLUN      , ONLY : NULOUT, NULERR
USE GEOMETRY_MOD, ONLY : GEOMETRY,GEOMETRY_SAME
USE DATETIME_TMP_MOD
USE YOE_PHYS_MWAVE     , ONLY : TEPHYSMWAVE
IMPLICIT NONE
TYPE(MODEL)         , INTENT(INOUT) :: SELF
TYPE(FIELDS)        , INTENT(INOUT) :: YDFIELDS
TYPE(TRAJ_TYPE_oops), INTENT(INOUT) :: YDOOPSTRAJ
TYPE(DATETIME_TMP)  , INTENT(INOUT) :: YDTIME
INTEGER(KIND=JPIM)  , INTENT(INOUT) :: KSECS

TYPE(MTRAJ)     :: YLMTRAJ
TYPE(TEPHYSMWAVE) :: YRPHYSMWAVE5

CHARACTER (LEN = 10) ::  CLTIMEOD,CLDAT(3)
INTEGER(KIND=JPIM) :: IVALUES(8)

REAL(KIND=JPRB) :: ZHOOK_HANDLE
INTEGER(KIND=JPIM) :: II, JKGLO,  ICEND,  IBL
CHARACTER(LEN=9) :: CL="0AAA00AAA"  !! 6th character is a 0 because obs comparisons are not done from stepoad
LOGICAL :: LLFIRSTCALL = .TRUE.
INTEGER(KIND=JPIM) :: IMINUT

#include "stepotl_oops.intfb.h"
#include "updtim.intfb.h"
#include "suecaec.intfb.h"
#include "transdirh_from_t0.intfb.h"
#include "transinvh.intfb.h"
#include "spnorm.intfb.h"
#include "gpnorm_gmv.intfb.h"
#include "ctvtottl.intfb.h"
#include "cttotvtl.intfb.h"
#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_STEPTL',0,ZHOOK_HANDLE)

IF(.NOT.GEOMETRY_SAME(SELF%YRML_GCONF%GEOM,YDFIELDS%GEOM)) CALL ABOR1('MODEL_MOD:MODEL_STEPTL - GEOMETRIES DIFFERENT')
!! this might not be the right place to do it
CALL SETUP_GMV5(YDFIELDS%GEOM, YLMTRAJ%YRGMV5, SELF%YRML_GCONF%YRDIMF)

IF (.NOT.ALLOCATED(YLMTRAJ%YRGMV5%GMV5))  ALLOCATE (YLMTRAJ%YRGMV5%GMV5(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRDIMV%NFLEVG, &
 &                                                  YLMTRAJ%YRGMV5%YT5%NDIM,YDFIELDS%GEOM%YRDIM%NGPBLKS))
IF (.NOT.ALLOCATED(YLMTRAJ%YRGMV5%GMV5S)) ALLOCATE (YLMTRAJ%YRGMV5%GMV5S(YDFIELDS%GEOM%YRDIM%NPROMA,YLMTRAJ%YRGMV5%YT5%NDIMS, &
 &                                                  YDFIELDS%GEOM%YRDIM%NGPBLKS))
IF (.NOT.ALLOCATED(YLMTRAJ%YRGFL5%GFL5))  ALLOCATE (YLMTRAJ%YRGFL5%GFL5(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRDIMV%NFLEVG, &
 &                                                  SELF%YRML_GCONF%YGFL%NDIM5,YDFIELDS%GEOM%YRDIM%NGPBLKS))


ASSOCIATE(YT5=>YLMTRAJ%YRGMV5%YT5,NDIM5=>SELF%YRML_GCONF%YGFL%NDIM5)
!! copy trajectory stuff into MTRAJ argument

  IF(.NOT.ASSOCIATED(YDOOPSTRAJ%MAIN%GMV))&
    & CALL ABOR1('READING OOPSTRAJ%MAIN: OOPSTRAJ%MAIN%GMV NOT ALLOCATED')

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO,ICEND,IBL)
    DO JKGLO=1,YDFIELDS%GEOM%YRGEM%NGPTOT,YDFIELDS%GEOM%YRDIM%NPROMA
      ICEND=MIN(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRGEM%NGPTOT-JKGLO+1)
      IBL=(JKGLO-1)/YDFIELDS%GEOM%YRDIM%NPROMA+1
      YLMTRAJ%YRGMV5%GMV5(1:ICEND,:,1:YT5%NDIM,IBL)=YDOOPSTRAJ%MAIN%GMV(1:ICEND,:,1:YT5%NDIM,IBL)
      YLMTRAJ%YRGMV5%GMV5S(1:ICEND,1:YT5%NDIMS,IBL)=YDOOPSTRAJ%MAIN%GMVS(1:ICEND,1:YT5%NDIMS,IBL)
      YLMTRAJ%YRGFL5%GFL5(1:ICEND,:,1:NDIM5,IBL)   =YDOOPSTRAJ%MAIN%GFL(1:ICEND,:,1:NDIM5,IBL)
    ENDDO
!$OMP END PARALLEL DO

IF(NSTEP == 0)THEN

  WRITE(NULOUT,*)'BEFORE TRANSDIRH_FROM_T0'
  CALL GPNORM_GMV(YDFIELDS%GEOM,YDFIELDS%YRGMV)

  IF (LSPRT) THEN
    DO JKGLO=1,YDFIELDS%GEOM%YRGEM%NGPTOT,YDFIELDS%GEOM%YRDIM%NPROMA
      ICEND=MIN(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRGEM%NGPTOT-JKGLO+1)
      IBL=(JKGLO-1)/YDFIELDS%GEOM%YRDIM%NPROMA+1
      CALL CTTOTVTL(YDFIELDS%GEOM,SELF%YRML_DYN%YRDYN, &
       & 1,ICEND,&
       & YDFIELDS%YRGMV%GMV(:,:,YDFIELDS%YRGMV%YT0%MT,IBL),YDFIELDS%YRGFL%GFL(:,:,SELF%YRML_GCONF%YGFL%YQ%MP,IBL),&
       & YLMTRAJ%YRGMV5%GMV5(:,:,YLMTRAJ%YRGMV5%YT5%MT,IBL),YLMTRAJ%YRGFL5%GFL5(:,:,SELF%YRML_GCONF%YGFL%YQ%MP5,IBL))
    ENDDO
  ENDIF

  CALL TRANSDIRH_FROM_T0(YDFIELDS%GEOM,YDFIELDS%YRGFL,YDFIELDS%YRGMV,CL,SELF%YRML_GCONF%YRDIMF%NFTHER,YDFIELDS%YRSPEC)

  WRITE(NULOUT,*)'AFTER TRANSDIRH_FROM_T0'
  CALL SPNORM(YDFIELDS%GEOM,SELF%YRML_GCONF,YDFIELDS%YRSPEC)

  CALL TRANSINVH(YDFIELDS%GEOM,YDFIELDS%YRGFL,YDFIELDS%YRGMV,SELF%YRML_DIAG,SELF%YRML_GCONF, &
 &               SELF%YRML_DYN%YRDYN%LRFRIC,SELF%YRML_DYN%YRDYN%RKRF,CL,YDFIELDS%YRSPEC)

  IF (LSPRT) THEN
    DO JKGLO=1,YDFIELDS%GEOM%YRGEM%NGPTOT,YDFIELDS%GEOM%YRDIM%NPROMA
      ICEND=MIN(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRGEM%NGPTOT-JKGLO+1)
      IBL=(JKGLO-1)/YDFIELDS%GEOM%YRDIM%NPROMA+1
      CALL CTVTOTTL(YDFIELDS%GEOM,SELF%YRML_DYN%YRDYN, &
       & 1,ICEND,&
       & YDFIELDS%YRGMV%GMV(:,:,YDFIELDS%YRGMV%YT0%MT,IBL),YDFIELDS%YRGFL%GFL(:,:,SELF%YRML_GCONF%YGFL%YQ%MP,IBL),&
       & YLMTRAJ%YRGMV5%GMV5(:,:,YLMTRAJ%YRGMV5%YT5%MT,IBL),YLMTRAJ%YRGFL5%GFL5(:,:,SELF%YRML_GCONF%YGFL%YQ%MP5,IBL))
    ENDDO
  ENDIF

  WRITE(NULOUT,*)'AFTER TRANSINVH'
  CALL GPNORM_GMV(YDFIELDS%GEOM,YDFIELDS%YRGMV)

ENDIF

END ASSOCIATE

!CALL SETRIPSTEP(SELF%YRML_GCONF%YRRIP%TSTEP,YDTIME, KSECS)
CALL UPDTIM(YDFIELDS%GEOM,YDFIELDS%YRSURF,SELF,NSTEP,SELF%YRML_GCONF%YRRIP%TDT,SELF%YRML_GCONF%YRRIP%TSTEP,.TRUE.)

       IF(LLFIRSTCALL)THEN
         IMINUT=NINT(1.0_JPRB+(REAL(NSSSSS,JPRB))/60._JPRB)
         CALL SUECAEC(SELF%YRML_GCONF%GEOM,SELF%YRML_PHY_RAD%YRERAD,NINDAT,IMINUT)
         LLFIRSTCALL=.FALSE.
       ENDIF

CALL YRPHYSMWAVE5%CREATE(YDFIELDS%GEOM)

CALL DATE_AND_TIME(CLDAT(1),CLTIMEOD,CLDAT(3),IVALUES)

CALL STEPOTL_OOPS(YDFIELDS%GEOM,YDFIELDS,YLMTRAJ,SELF,YDOOPSTRAJ,CL,YRPHYSMWAVE5)
CALL YRPHYSMWAVE5%DESTROY

NSTEP=NSTEP+1
CALL GETRIPSTEP(SELF%YRML_GCONF%YRRIP%TSTEP, YDTIME, KSECS)


IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_STEPTL',1,ZHOOK_HANDLE)
END SUBROUTINE MODEL_STEPTL

! ------------------------------------------------------------------------------

SUBROUTINE MODEL_INITAD(SELF, DX, YDTIME,KSECS)
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE FIELDS_MOD   , ONLY : FIELDS
USE YOMCT3       , ONLY : NSTEP
USE YOMLUN       , ONLY : NULOUT
USE GEOMETRY_MOD , ONLY : GEOMETRY,GEOMETRY_SAME
USE DATETIME_TMP_MOD
IMPLICIT NONE
TYPE(MODEL)       , INTENT(INOUT) :: SELF
TYPE(FIELDS)      , INTENT(INOUT) :: DX
TYPE(DATETIME_TMP), INTENT(INOUT) :: YDTIME
INTEGER(KIND=JPIM), INTENT(INOUT) :: KSECS
REAL(KIND=JPRB) :: ZHOOK_HANDLE

#include "spnorm.intfb.h"
#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_INITAD',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>DX%GEOM%YRDIM,YDDIMV=>DX%GEOM%YRDIMV,NSTOP=>SELF%YRML_GCONF%YRRIP%NSTOP)
IF(.NOT.GEOMETRY_SAME(SELF%YRML_GCONF%GEOM,DX%GEOM)) CALL ABOR1('MODEL_MOD:MODEL_INITAD - GEOMETRIES DIFFERENT')

IF(.NOT.ALLOCATED(DX%YRGMV%GMVT1)) THEN
   ALLOCATE(DX%YRGMV%GMVT1(YDDIM%NPROMA,YDDIMV%NFLEVG,DX%YRGMV%YT1%NDIM,YDDIM%NGPBLKS))
ENDIF
DX%YRGMV%GMVT1  = 0._JPRB
IF(.NOT.ALLOCATED(DX%YRGMV%GMVT1S)) THEN
   ALLOCATE(DX%YRGMV%GMVT1S(YDDIM%NPROMA,DX%YRGMV%YT1%NDIMS,YDDIM%NGPBLKS))
ENDIF
DX%YRGMV%GMVT1S = 0._JPRB
IF(.NOT.ALLOCATED(DX%YRGFL%GFLT1)) THEN
   ALLOCATE(DX%YRGFL%GFLT1(YDDIM%NPROMA,YDDIMV%NFLEVG,SELF%YRML_GCONF%YGFL%NDIM1,YDDIM%NGPBLKS))
ENDIF
DX%YRGFL%GFLT1  = 0._JPRB

IF ( SELF%YRML_GCONF%YRRIP%NSTOP == 0 ) RETURN

CALL SETRIP0(YDTIME)
NSTEP = NSTOP
WRITE(NULOUT,*) 'END OF MODEL_MOD:MODEL_INITAD'
CALL SPNORM(DX%GEOM,SELF%YRML_GCONF,DX%YRSPEC)
CALL GETRIPSTEP(SELF%YRML_GCONF%YRRIP%TSTEP, YDTIME,KSECS)

!IF( MYPROC == 1 ) CALL SELF%PRINT('  configuration of model at the end of MODEL_INITAD', 111)

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_INITAD',1,ZHOOK_HANDLE)
END ASSOCIATE

END SUBROUTINE MODEL_INITAD

! ------------------------------------------------------------------------------

SUBROUTINE MODEL_STEPAD(SELF, YDFIELDS, YDOOPSTRAJ,YDTIME,KSECS)
USE YOMHOOK                 , ONLY : LHOOK, DR_HOOK
USE FIELDS_MOD              , ONLY : FIELDS
USE MTRAJ_MOD               , ONLY : MTRAJ
USE YOMCT3                  , ONLY : NSTEP
USE YOMTRAJ_OOPS            , ONLY : TRAJ_TYPE_oops
USE GMV_SUBS_MOD            , ONLY : SETUP_GMV5
USE VARBC_CLASS             , ONLY : CLASS_VARBC
USE YOMCT0                  , ONLY : LSPRT
USE YOMLUN                  , ONLY : NULOUT, NULERR
USE GEOMETRY_MOD            , ONLY : GEOMETRY,GEOMETRY_SAME
USE DATETIME_TMP_MOD

IMPLICIT NONE

TYPE(MODEL)         , INTENT(INOUT) :: SELF
TYPE(FIELDS)        , INTENT(INOUT) :: YDFIELDS
TYPE(TRAJ_TYPE_oops), INTENT(INOUT) :: YDOOPSTRAJ
TYPE(DATETIME_TMP)  , INTENT(INOUT) :: YDTIME
INTEGER(KIND=JPIM)  , INTENT(INOUT) :: KSECS

INTEGER(KIND=JPIM) :: II, JKGLO,  ICEND,  IBL

TYPE(MTRAJ)       :: YLMTRAJ !! dummy argument
TYPE(CLASS_VARBC) :: ZVARBC  !! dummy argument

CHARACTER (LEN = 10) ::  CLTIMEOD,CLDAT(3)
INTEGER(KIND=JPIM) :: IVALUES(8)

REAL(KIND=JPRB) :: ZHOOK_HANDLE
!!CHARACTER(LEN=9) :: CL="0AA00V000"
CHARACTER(LEN=9) :: CL="0AAA00AAA"  !! 6th character is a 0 because obs comparisons are not done from stepoad
LOGICAL :: LLFIRSTCALL = .TRUE.
INTEGER(KIND=JPIM) :: IMINUT


#include "stepoad_oops.intfb.h"
#include "updtim.intfb.h"
#include "suecaec.intfb.h"
#include "ctvtotad.intfb.h"
#include "cttotvad.intfb.h"
#include "transinvhad.intfb.h"
#include "transdirh_from_t0_ad.intfb.h"
#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_STEPAD',0,ZHOOK_HANDLE)
IF(.NOT.GEOMETRY_SAME(SELF%YRML_GCONF%GEOM,YDFIELDS%GEOM)) CALL ABOR1('MODEL_MOD:MODEL_STEPAD - GEOMETRIES DIFFERENT')


!! this should not be necessary here!
CALL SETUP_GMV5(YDFIELDS%GEOM, YLMTRAJ%YRGMV5, SELF%YRML_GCONF%YRDIMF)

IF (.NOT.ALLOCATED(YLMTRAJ%YRGMV5%GMV5))  ALLOCATE (YLMTRAJ%YRGMV5%GMV5(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRDIMV%NFLEVG, &
 &                                                  YLMTRAJ%YRGMV5%YT5%NDIM,YDFIELDS%GEOM%YRDIM%NGPBLKS))
IF (.NOT.ALLOCATED(YLMTRAJ%YRGMV5%GMV5S)) ALLOCATE (YLMTRAJ%YRGMV5%GMV5S(YDFIELDS%GEOM%YRDIM%NPROMA,YLMTRAJ%YRGMV5%YT5%NDIMS, &
 &                                                  YDFIELDS%GEOM%YRDIM%NGPBLKS))
IF (.NOT.ALLOCATED(YLMTRAJ%YRGFL5%GFL5))  ALLOCATE (YLMTRAJ%YRGFL5%GFL5(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRDIMV%NFLEVG, &
 &                                                  SELF%YRML_GCONF%YGFL%NDIM5,YDFIELDS%GEOM%YRDIM%NGPBLKS))

ASSOCIATE(YT5=>YLMTRAJ%YRGMV5%YT5,NDIM5=>SELF%YRML_GCONF%YGFL%NDIM5)
!! copy trajectory stuff into MTRAJ argument

  IF(.NOT.ASSOCIATED(YDOOPSTRAJ%MAIN%GMV))&
    & CALL ABOR1('READING OOPSTRAJ%MAIN: OOPSTRAJ%MAIN%GMV NOT ALLOCATED')

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO,ICEND,IBL)
    DO JKGLO=1,YDFIELDS%GEOM%YRGEM%NGPTOT,YDFIELDS%GEOM%YRDIM%NPROMA
      ICEND=MIN(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRGEM%NGPTOT-JKGLO+1)
      IBL=(JKGLO-1)/YDFIELDS%GEOM%YRDIM%NPROMA+1
      YLMTRAJ%YRGMV5%GMV5(1:ICEND,:,1:YT5%NDIM,IBL)=YDOOPSTRAJ%MAIN%GMV(1:ICEND,:,1:YT5%NDIM,IBL)
      YLMTRAJ%YRGMV5%GMV5S(1:ICEND,1:YT5%NDIMS,IBL)=YDOOPSTRAJ%MAIN%GMVS(1:ICEND,1:YT5%NDIMS,IBL)
      YLMTRAJ%YRGFL5%GFL5(1:ICEND,:,1:NDIM5,IBL)   =YDOOPSTRAJ%MAIN%GFL(1:ICEND,:,1:NDIM5,IBL)
    ENDDO
!$OMP END PARALLEL DO

END ASSOCIATE

NSTEP=NSTEP-1

CALL UPDTIM(YDFIELDS%GEOM,YDFIELDS%YRSURF,SELF,NSTEP,SELF%YRML_GCONF%YRRIP%TDT,SELF%YRML_GCONF%YRRIP%TSTEP, .TRUE.)

       IF(LLFIRSTCALL)THEN
         IMINUT=NINT(1.0_JPRB+(REAL(NSSSSS,JPRB))/60._JPRB)
         CALL SUECAEC(SELF%YRML_GCONF%GEOM,SELF%YRML_PHY_RAD%YRERAD,NINDAT,IMINUT)
         LLFIRSTCALL=.FALSE.
       ENDIF


CALL DATE_AND_TIME(CLDAT(1),CLTIMEOD,CLDAT(3),IVALUES)

CALL STEPOAD_OOPS(YDFIELDS%GEOM,YDFIELDS,YLMTRAJ,SELF,YDOOPSTRAJ,CL,ZVARBC)

IF(NSTEP == 0)THEN

  WRITE(NULOUT,*)'MODEL_STEPADBEFORE TRANSDIRH_FROM_T0'
  CALL GPNORM_GMV(YDFIELDS%GEOM,YDFIELDS%YRGMV)

  IF (LSPRT) THEN
    DO JKGLO=1,YDFIELDS%GEOM%YRGEM%NGPTOT,YDFIELDS%GEOM%YRDIM%NPROMA
      ICEND=MIN(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRGEM%NGPTOT-JKGLO+1)
      IBL=(JKGLO-1)/YDFIELDS%GEOM%YRDIM%NPROMA+1
      CALL CTVTOTAD(YDFIELDS%GEOM,SELF%YRML_DYN%YRDYN, &
       & 1,ICEND,&
       & YDFIELDS%YRGMV%GMV(:,:,YDFIELDS%YRGMV%YT0%MT,IBL),YDFIELDS%YRGFL%GFL(:,:,SELF%YRML_GCONF%YGFL%YQ%MP,IBL),&
       & YLMTRAJ%YRGMV5%GMV5(:,:,YLMTRAJ%YRGMV5%YT5%MT,IBL),YLMTRAJ%YRGFL5%GFL5(:,:,SELF%YRML_GCONF%YGFL%YQ%MP5,IBL))
    ENDDO
  ENDIF

  CALL TRANSINVHAD(YDFIELDS%GEOM,YDFIELDS%YRGFL,YDFIELDS%YRGMV,SELF%YRML_GCONF,CL,YDFIELDS%YRSPEC)

  CALL TRANSDIRH_FROM_T0_AD(YDFIELDS%GEOM,YDFIELDS%YRGFL,YDFIELDS%YRGMV,CL,SELF%YRML_GCONF%YRDIMF%NFTHER,YDFIELDS%YRSPEC)

  IF (LSPRT) THEN
    DO JKGLO=1,YDFIELDS%GEOM%YRGEM%NGPTOT,YDFIELDS%GEOM%YRDIM%NPROMA
      ICEND=MIN(YDFIELDS%GEOM%YRDIM%NPROMA,YDFIELDS%GEOM%YRGEM%NGPTOT-JKGLO+1)
      IBL=(JKGLO-1)/YDFIELDS%GEOM%YRDIM%NPROMA+1
      CALL CTTOTVAD(YDFIELDS%GEOM,SELF%YRML_DYN%YRDYN, &
       & 1,ICEND,&
       & YDFIELDS%YRGMV%GMV(:,:,YDFIELDS%YRGMV%YT0%MT,IBL),YDFIELDS%YRGFL%GFL(:,:,SELF%YRML_GCONF%YGFL%YQ%MP,IBL),&
       & YLMTRAJ%YRGMV5%GMV5(:,:,YLMTRAJ%YRGMV5%YT5%MT,IBL),YLMTRAJ%YRGFL5%GFL5(:,:,SELF%YRML_GCONF%YGFL%YQ%MP5,IBL))
    ENDDO
  ENDIF
!-------------


  CALL SPNORM(YDFIELDS%GEOM,SELF%YRML_GCONF,YDFIELDS%YRSPEC)

  CALL GPNORM_GMV(YDFIELDS%GEOM,YDFIELDS%YRGMV)

ENDIF

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_STEPAD',1,ZHOOK_HANDLE)
END SUBROUTINE MODEL_STEPAD

! ------------------------------------------------------------------------------

END MODULE MODEL_MOD
