
MODULE SURFACE_VIEWS_PROGNOSTIC_MODULE
  ! The SURFACE_VIEWS type contains namespaced access to groups of
  ! array pointers according to individual surface variable groups.
  !
  !
  ! Variable naming conventions
  ! ---------------------------
  ! The top-level type `SURFACE_VIEWS_TYPE` holds multiple group
  ! types, each prefixed with `GSP_` for prognostic and `GSD_` for
  ! diagnostic variable groups.
  !
  ! Each group type holds a list of array views (pointers to
  ! sub-sections of the gobal array), each prefixed with `P` to
  ! indicate a thread-local view pointer. Data views of prognostic
  ! variables have an additional suffix that indicates the time index
  ! (eg.  `_T0`, `_T1` or `_T9`). The backend storage for each of
  ! these view pointers is provided by `FIELD_2D/FIELD_3D` objects, a
  ! reference to which is also stored on the group types and prefixed
  ! with `F_`.

USE PARKIND1, ONLY: JPIM, JPRB
USE FIELD_MODULE, ONLY: FIELD_2D, FIELD_3D, FIELD_4D, FIELD_2D_PTR, &
 &                      FIELD_3D_PTR, FIELD_2D_VIEW, FIELD_3D_VIEW
! Using global imports here, since fypp notation breaks cmake's dependency analysis
USE SURFACE_VARIABLES_MOD
USE YOMDYN, ONLY : TDYN

IMPLICIT NONE

TYPE SURFACE_VIEW_GROUP_SOILB
  REAL(KIND=JPRB), POINTER :: PT_T0(:,:)   ! temperature
  REAL(KIND=JPRB), POINTER :: PT_T1(:,:)   ! temperature
  REAL(KIND=JPRB), POINTER :: PT_T9(:,:)   ! temperature
!>REAL(KIND=JPRB)          :: PT_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SBD%NLEVS)
!>REAL(KIND=JPRB)          :: PT_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SBD%NLEVS)
!>REAL(KIND=JPRB)          :: PT_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SBD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PQ_T0(:,:)   ! liquid water content
  REAL(KIND=JPRB), POINTER :: PQ_T1(:,:)   ! liquid water content
  REAL(KIND=JPRB), POINTER :: PQ_T9(:,:)   ! liquid water content
!>REAL(KIND=JPRB)          :: PQ_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SBD%NLEVS)
!>REAL(KIND=JPRB)          :: PQ_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SBD%NLEVS)
!>REAL(KIND=JPRB)          :: PQ_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SBD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PTL_T0(:,:)   ! ice water content (for MF)
  REAL(KIND=JPRB), POINTER :: PTL_T1(:,:)   ! ice water content (for MF)
  REAL(KIND=JPRB), POINTER :: PTL_T9(:,:)   ! ice water content (for MF)
!>REAL(KIND=JPRB)          :: PTL_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SBD%NLEVS)
!>REAL(KIND=JPRB)          :: PTL_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SBD%NLEVS)
!>REAL(KIND=JPRB)          :: PTL_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SBD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_SOILB), POINTER :: VARIABLE_GROUP
  TYPE(FIELD_3D), POINTER :: F_T_T0=>NULL(), F_T_T1=>NULL(), F_T_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_Q_T0=>NULL(), F_Q_T1=>NULL(), F_Q_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_TL_T0=>NULL(), F_TL_T1=>NULL(), F_TL_T9=>NULL()
  TYPE(FIELD_4D), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_SOILB_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_SOILB_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_SOILB_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_SOILB_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_SOILB_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_SOILB_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_SOILB_PHTFILT
END TYPE SURFACE_VIEW_GROUP_SOILB

TYPE SURFACE_VIEW_GROUP_SNOWG
  REAL(KIND=JPRB), POINTER :: PF_T0(:,:)   ! content of surface snow
  REAL(KIND=JPRB), POINTER :: PF_T1(:,:)   ! content of surface snow
  REAL(KIND=JPRB), POINTER :: PF_T9(:,:)   ! content of surface snow
!>REAL(KIND=JPRB)          :: PF_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
!>REAL(KIND=JPRB)          :: PF_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
!>REAL(KIND=JPRB)          :: PF_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PA_T0(:,:)   ! snow albedo
  REAL(KIND=JPRB), POINTER :: PA_T1(:,:)   ! snow albedo
  REAL(KIND=JPRB), POINTER :: PA_T9(:,:)   ! snow albedo
!>REAL(KIND=JPRB)          :: PA_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
!>REAL(KIND=JPRB)          :: PA_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
!>REAL(KIND=JPRB)          :: PA_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PR_T0(:,:)   ! snow density
  REAL(KIND=JPRB), POINTER :: PR_T1(:,:)   ! snow density
  REAL(KIND=JPRB), POINTER :: PR_T9(:,:)   ! snow density
!>REAL(KIND=JPRB)          :: PR_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
!>REAL(KIND=JPRB)          :: PR_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
!>REAL(KIND=JPRB)          :: PR_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PT_T0(:,:)   ! total albedo (diagnostic for MF for LVGSN)
  REAL(KIND=JPRB), POINTER :: PT_T1(:,:)   ! total albedo (diagnostic for MF for LVGSN)
  REAL(KIND=JPRB), POINTER :: PT_T9(:,:)   ! total albedo (diagnostic for MF for LVGSN)
!>REAL(KIND=JPRB)          :: PT_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
!>REAL(KIND=JPRB)          :: PT_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
!>REAL(KIND=JPRB)          :: PT_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PW_T0(:,:)   ! Liquid water content
  REAL(KIND=JPRB), POINTER :: PW_T1(:,:)   ! Liquid water content
  REAL(KIND=JPRB), POINTER :: PW_T9(:,:)   ! Liquid water content
!>REAL(KIND=JPRB)          :: PW_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
!>REAL(KIND=JPRB)          :: PW_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
!>REAL(KIND=JPRB)          :: PW_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_SGD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_SNOWG), POINTER :: VARIABLE_GROUP
  TYPE(FIELD_3D), POINTER :: F_F_T0=>NULL(), F_F_T1=>NULL(), F_F_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_A_T0=>NULL(), F_A_T1=>NULL(), F_A_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_R_T0=>NULL(), F_R_T1=>NULL(), F_R_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_T_T0=>NULL(), F_T_T1=>NULL(), F_T_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_W_T0=>NULL(), F_W_T1=>NULL(), F_W_T9=>NULL()
  TYPE(FIELD_4D), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_SNOWG_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_SNOWG_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_SNOWG_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_SNOWG_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_SNOWG_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_SNOWG_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_SNOWG_PHTFILT
END TYPE SURFACE_VIEW_GROUP_SNOWG

TYPE SURFACE_VIEW_GROUP_LAKEB
  REAL(KIND=JPRB), POINTER :: PLICT_T0(:)   ! lake ice temperature
  REAL(KIND=JPRB), POINTER :: PLICT_T1(:)   ! lake ice temperature
  REAL(KIND=JPRB), POINTER :: PLICT_T9(:)   ! lake ice temperature
!>REAL(KIND=JPRB)          :: PLICT_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLICT_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLICT_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PLMLT_T0(:)   ! lake mixed-layer temperature
  REAL(KIND=JPRB), POINTER :: PLMLT_T1(:)   ! lake mixed-layer temperature
  REAL(KIND=JPRB), POINTER :: PLMLT_T9(:)   ! lake mixed-layer temperature
!>REAL(KIND=JPRB)          :: PLMLT_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLMLT_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLMLT_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PLTLT_T0(:)   ! lake total layer temperature
  REAL(KIND=JPRB), POINTER :: PLTLT_T1(:)   ! lake total layer temperature
  REAL(KIND=JPRB), POINTER :: PLTLT_T9(:)   ! lake total layer temperature
!>REAL(KIND=JPRB)          :: PLTLT_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLTLT_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLTLT_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PLBLT_T0(:)   ! lake bottom layer temperature
  REAL(KIND=JPRB), POINTER :: PLBLT_T1(:)   ! lake bottom layer temperature
  REAL(KIND=JPRB), POINTER :: PLBLT_T9(:)   ! lake bottom layer temperature
!>REAL(KIND=JPRB)          :: PLBLT_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLBLT_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLBLT_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PLSHF_T0(:)   ! lake shape factor
  REAL(KIND=JPRB), POINTER :: PLSHF_T1(:)   ! lake shape factor
  REAL(KIND=JPRB), POINTER :: PLSHF_T9(:)   ! lake shape factor
!>REAL(KIND=JPRB)          :: PLSHF_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLSHF_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLSHF_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PLICD_T0(:)   ! lake ice depth
  REAL(KIND=JPRB), POINTER :: PLICD_T1(:)   ! lake ice depth
  REAL(KIND=JPRB), POINTER :: PLICD_T9(:)   ! lake ice depth
!>REAL(KIND=JPRB)          :: PLICD_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLICD_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLICD_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PLMLD_T0(:)   ! lake mixed-layer depth
  REAL(KIND=JPRB), POINTER :: PLMLD_T1(:)   ! lake mixed-layer depth
  REAL(KIND=JPRB), POINTER :: PLMLD_T9(:)   ! lake mixed-layer depth
!>REAL(KIND=JPRB)          :: PLMLD_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLMLD_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PLMLD_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_LAKEB), POINTER :: VARIABLE_GROUP
  TYPE(FIELD_2D), POINTER :: F_LICT_T0=>NULL(), F_LICT_T1=>NULL(), F_LICT_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_LMLT_T0=>NULL(), F_LMLT_T1=>NULL(), F_LMLT_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_LTLT_T0=>NULL(), F_LTLT_T1=>NULL(), F_LTLT_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_LBLT_T0=>NULL(), F_LBLT_T1=>NULL(), F_LBLT_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_LSHF_T0=>NULL(), F_LSHF_T1=>NULL(), F_LSHF_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_LICD_T0=>NULL(), F_LICD_T1=>NULL(), F_LICD_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_LMLD_T0=>NULL(), F_LMLD_T1=>NULL(), F_LMLD_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_LAKEB_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_LAKEB_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_LAKEB_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_LAKEB_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_LAKEB_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_LAKEB_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_LAKEB_PHTFILT
END TYPE SURFACE_VIEW_GROUP_LAKEB

TYPE SURFACE_VIEW_GROUP_RESVR
  REAL(KIND=JPRB), POINTER :: PT_T0(:)   ! skin temperature (Ts)
  REAL(KIND=JPRB), POINTER :: PT_T1(:)   ! skin temperature (Ts)
  REAL(KIND=JPRB), POINTER :: PT_T9(:)   ! skin temperature (Ts)
!>REAL(KIND=JPRB)          :: PT_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PT_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PT_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PW_T0(:)   ! skin water content (Wskin) at ECMWF superficial reservoir water content (Ws) at MF
  REAL(KIND=JPRB), POINTER :: PW_T1(:)   ! skin water content (Wskin) at ECMWF superficial reservoir water content (Ws) at MF
  REAL(KIND=JPRB), POINTER :: PW_T9(:)   ! skin water content (Wskin) at ECMWF superficial reservoir water content (Ws) at MF
!>REAL(KIND=JPRB)          :: PW_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PW_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PW_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PFC_T0(:)   ! skin water content (Wl) at MF
  REAL(KIND=JPRB), POINTER :: PFC_T1(:)   ! skin water content (Wl) at MF
  REAL(KIND=JPRB), POINTER :: PFC_T9(:)   ! skin water content (Wl) at MF
!>REAL(KIND=JPRB)          :: PFC_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PFC_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PFC_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PIC_T0(:)   ! superficial reservoir ice
  REAL(KIND=JPRB), POINTER :: PIC_T1(:)   ! superficial reservoir ice
  REAL(KIND=JPRB), POINTER :: PIC_T9(:)   ! superficial reservoir ice
!>REAL(KIND=JPRB)          :: PIC_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PIC_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PIC_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PFP1_T0(:)   ! interpolated Ts for 2nd part of 927-FULLPOS
  REAL(KIND=JPRB), POINTER :: PFP1_T1(:)   ! interpolated Ts for 2nd part of 927-FULLPOS
  REAL(KIND=JPRB), POINTER :: PFP1_T9(:)   ! interpolated Ts for 2nd part of 927-FULLPOS
!>REAL(KIND=JPRB)          :: PFP1_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PFP1_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PFP1_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_RESVR), POINTER :: VARIABLE_GROUP
  TYPE(FIELD_2D), POINTER :: F_T_T0=>NULL(), F_T_T1=>NULL(), F_T_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_W_T0=>NULL(), F_W_T1=>NULL(), F_W_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_FC_T0=>NULL(), F_FC_T1=>NULL(), F_FC_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_IC_T0=>NULL(), F_IC_T1=>NULL(), F_IC_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_FP1_T0=>NULL(), F_FP1_T1=>NULL(), F_FP1_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_RESVR_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_RESVR_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_RESVR_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_RESVR_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_RESVR_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_RESVR_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_RESVR_PHTFILT
END TYPE SURFACE_VIEW_GROUP_RESVR

TYPE SURFACE_VIEW_GROUP_CLS
  REAL(KIND=JPRB), POINTER :: PTCLS_T0(:)   ! 2m temperature
  REAL(KIND=JPRB), POINTER :: PTCLS_T1(:)   ! 2m temperature
  REAL(KIND=JPRB), POINTER :: PTCLS_T9(:)   ! 2m temperature
!>REAL(KIND=JPRB)          :: PTCLS_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PTCLS_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PTCLS_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PHUCLS_T0(:)   ! 2m humidity
  REAL(KIND=JPRB), POINTER :: PHUCLS_T1(:)   ! 2m humidity
  REAL(KIND=JPRB), POINTER :: PHUCLS_T9(:)   ! 2m humidity
!>REAL(KIND=JPRB)          :: PHUCLS_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PHUCLS_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PHUCLS_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PUCLS_T0(:)   ! 10m U-wind
  REAL(KIND=JPRB), POINTER :: PUCLS_T1(:)   ! 10m U-wind
  REAL(KIND=JPRB), POINTER :: PUCLS_T9(:)   ! 10m U-wind
!>REAL(KIND=JPRB)          :: PUCLS_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PUCLS_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PUCLS_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PVCLS_T0(:)   ! 10m V-wind
  REAL(KIND=JPRB), POINTER :: PVCLS_T1(:)   ! 10m V-wind
  REAL(KIND=JPRB), POINTER :: PVCLS_T9(:)   ! 10m V-wind
!>REAL(KIND=JPRB)          :: PVCLS_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PVCLS_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PVCLS_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PNUCLS_T0(:)   ! 10m neutral U-wind
  REAL(KIND=JPRB), POINTER :: PNUCLS_T1(:)   ! 10m neutral U-wind
  REAL(KIND=JPRB), POINTER :: PNUCLS_T9(:)   ! 10m neutral U-wind
!>REAL(KIND=JPRB)          :: PNUCLS_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PNUCLS_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PNUCLS_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PNVCLS_T0(:)   ! 10m neutral V-wind
  REAL(KIND=JPRB), POINTER :: PNVCLS_T1(:)   ! 10m neutral V-wind
  REAL(KIND=JPRB), POINTER :: PNVCLS_T9(:)   ! 10m neutral V-wind
!>REAL(KIND=JPRB)          :: PNVCLS_T0 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PNVCLS_T1 (YDCPG_DIM%KLON)
!>REAL(KIND=JPRB)          :: PNVCLS_T9 (YDCPG_DIM%KLON)
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_CLS), POINTER :: VARIABLE_GROUP
  TYPE(FIELD_2D), POINTER :: F_TCLS_T0=>NULL(), F_TCLS_T1=>NULL(), F_TCLS_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_HUCLS_T0=>NULL(), F_HUCLS_T1=>NULL(), F_HUCLS_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_UCLS_T0=>NULL(), F_UCLS_T1=>NULL(), F_UCLS_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_VCLS_T0=>NULL(), F_VCLS_T1=>NULL(), F_VCLS_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_NUCLS_T0=>NULL(), F_NUCLS_T1=>NULL(), F_NUCLS_T9=>NULL()
  TYPE(FIELD_2D), POINTER :: F_NVCLS_T0=>NULL(), F_NVCLS_T1=>NULL(), F_NVCLS_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_CLS_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_CLS_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_CLS_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_CLS_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_CLS_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_CLS_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_CLS_PHTFILT
END TYPE SURFACE_VIEW_GROUP_CLS

TYPE SURFACE_VIEW_GROUP_OML
  REAL(KIND=JPRB), POINTER :: PTO_T0(:,:)   ! temperature
  REAL(KIND=JPRB), POINTER :: PTO_T1(:,:)   ! temperature
  REAL(KIND=JPRB), POINTER :: PTO_T9(:,:)   ! temperature
!>REAL(KIND=JPRB)          :: PTO_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
!>REAL(KIND=JPRB)          :: PTO_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
!>REAL(KIND=JPRB)          :: PTO_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PSO_T0(:,:)   ! salinity
  REAL(KIND=JPRB), POINTER :: PSO_T1(:,:)   ! salinity
  REAL(KIND=JPRB), POINTER :: PSO_T9(:,:)   ! salinity
!>REAL(KIND=JPRB)          :: PSO_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
!>REAL(KIND=JPRB)          :: PSO_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
!>REAL(KIND=JPRB)          :: PSO_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PUO_T0(:,:)   ! U velocity
  REAL(KIND=JPRB), POINTER :: PUO_T1(:,:)   ! U velocity
  REAL(KIND=JPRB), POINTER :: PUO_T9(:,:)   ! U velocity
!>REAL(KIND=JPRB)          :: PUO_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
!>REAL(KIND=JPRB)          :: PUO_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
!>REAL(KIND=JPRB)          :: PUO_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PVO_T0(:,:)   ! V velocity
  REAL(KIND=JPRB), POINTER :: PVO_T1(:,:)   ! V velocity
  REAL(KIND=JPRB), POINTER :: PVO_T9(:,:)   ! V velocity
!>REAL(KIND=JPRB)          :: PVO_T0 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
!>REAL(KIND=JPRB)          :: PVO_T1 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
!>REAL(KIND=JPRB)          :: PVO_T9 (YDCPG_DIM%KLON, YDCPG_DIM%YRSURF%YSP_OMD%NLEVS)
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_OML), POINTER :: VARIABLE_GROUP
  TYPE(FIELD_3D), POINTER :: F_TO_T0=>NULL(), F_TO_T1=>NULL(), F_TO_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_SO_T0=>NULL(), F_SO_T1=>NULL(), F_SO_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_UO_T0=>NULL(), F_UO_T1=>NULL(), F_UO_T9=>NULL()
  TYPE(FIELD_3D), POINTER :: F_VO_T0=>NULL(), F_VO_T1=>NULL(), F_VO_T9=>NULL()
  TYPE(FIELD_4D), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_OML_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_OML_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_OML_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_OML_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_OML_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_OML_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_OML_PHTFILT
END TYPE SURFACE_VIEW_GROUP_OML

TYPE SURFACE_VIEW_GROUP_EXTRP
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_EXTRP), POINTER :: VARIABLE_GROUP
  TYPE(FIELD_4D), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_EXTRP_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_EXTRP_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_EXTRP_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_EXTRP_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_EXTRP_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_EXTRP_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_EXTRP_PHTFILT
END TYPE SURFACE_VIEW_GROUP_EXTRP

TYPE SURFACE_VIEW_GROUP_XTRP2
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_XTRP2), POINTER :: VARIABLE_GROUP
  TYPE(FIELD_3D), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_XTRP2_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_XTRP2_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_XTRP2_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_XTRP2_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_XTRP2_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_XTRP2_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_XTRP2_PHTFILT
END TYPE SURFACE_VIEW_GROUP_XTRP2

TYPE SURFACE_VIEW_GROUP_CANRI
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_CANRI), POINTER :: VARIABLE_GROUP
  TYPE(FIELD_3D), POINTER :: F_GROUP

CONTAINS
  PROCEDURE :: INIT => SURFACE_VIEW_GROUP_CANRI_INIT
  PROCEDURE :: UPDATE_VIEW => SURFACE_VIEW_GROUP_CANRI_UPDATE_VIEW
  PROCEDURE :: SET9TO0 => SURFACE_VIEW_GROUP_CANRI_SET9TO0
  PROCEDURE :: SET1TO9 => SURFACE_VIEW_GROUP_CANRI_SET1TO9
  PROCEDURE :: SET1TO0 => SURFACE_VIEW_GROUP_CANRI_SET1TO0
  PROCEDURE :: SET0TO1 => SURFACE_VIEW_GROUP_CANRI_SET0TO1
  PROCEDURE :: PHTFILT => SURFACE_VIEW_GROUP_CANRI_PHTFILT
END TYPE SURFACE_VIEW_GROUP_CANRI


CONTAINS

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_INIT(SELF, VARIABLE_GROUP)
    ! Constructor of the array view type for a surface variable group
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_SOILB), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    ! Create a view per timestep field for each prognostic variable
    SELF%F_T_T0 => VARIABLE_GROUP%VT%FT0
    SELF%F_T_T1 => VARIABLE_GROUP%VT%FT1
    SELF%F_T_T9 => VARIABLE_GROUP%VT%FT9
    SELF%F_Q_T0 => VARIABLE_GROUP%VQ%FT0
    SELF%F_Q_T1 => VARIABLE_GROUP%VQ%FT1
    SELF%F_Q_T9 => VARIABLE_GROUP%VQ%FT9
    SELF%F_TL_T0 => VARIABLE_GROUP%VTL%FT0
    SELF%F_TL_T1 => VARIABLE_GROUP%VTL%FT1
    SELF%F_TL_T9 => VARIABLE_GROUP%VTL%FT9
    SELF%VARIABLE_GROUP => VARIABLE_GROUP
    SELF%F_GROUP => VARIABLE_GROUP%F_GROUP
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_UPDATE_VIEW(SELF, BLOCK_INDEX)
    ! Extract local array views from field objects
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    ! Set up the view pointer for each timestep field
    SELF%PT_T0 => SELF%F_T_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PT_T1 => SELF%F_T_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PT_T9 => SELF%F_T_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PQ_T0 => SELF%F_Q_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PQ_T1 => SELF%F_Q_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PQ_T9 => SELF%F_Q_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PTL_T0 => SELF%F_TL_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PTL_T1 => SELF%F_TL_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PTL_T9 => SELF%F_TL_T9%GET_VIEW(BLOCK_INDEX)

    IF (ASSOCIATED(SELF%F_GROUP))  SELF%PGROUP => SELF%F_GROUP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_INIT(SELF, VARIABLE_GROUP)
    ! Constructor of the array view type for a surface variable group
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_SNOWG), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    ! Create a view per timestep field for each prognostic variable
    SELF%F_F_T0 => VARIABLE_GROUP%VF%FT0
    SELF%F_F_T1 => VARIABLE_GROUP%VF%FT1
    SELF%F_F_T9 => VARIABLE_GROUP%VF%FT9
    SELF%F_A_T0 => VARIABLE_GROUP%VA%FT0
    SELF%F_A_T1 => VARIABLE_GROUP%VA%FT1
    SELF%F_A_T9 => VARIABLE_GROUP%VA%FT9
    SELF%F_R_T0 => VARIABLE_GROUP%VR%FT0
    SELF%F_R_T1 => VARIABLE_GROUP%VR%FT1
    SELF%F_R_T9 => VARIABLE_GROUP%VR%FT9
    SELF%F_T_T0 => VARIABLE_GROUP%VT%FT0
    SELF%F_T_T1 => VARIABLE_GROUP%VT%FT1
    SELF%F_T_T9 => VARIABLE_GROUP%VT%FT9
    SELF%F_W_T0 => VARIABLE_GROUP%VW%FT0
    SELF%F_W_T1 => VARIABLE_GROUP%VW%FT1
    SELF%F_W_T9 => VARIABLE_GROUP%VW%FT9
    SELF%VARIABLE_GROUP => VARIABLE_GROUP
    SELF%F_GROUP => VARIABLE_GROUP%F_GROUP
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_UPDATE_VIEW(SELF, BLOCK_INDEX)
    ! Extract local array views from field objects
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    ! Set up the view pointer for each timestep field
    SELF%PF_T0 => SELF%F_F_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PF_T1 => SELF%F_F_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PF_T9 => SELF%F_F_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PA_T0 => SELF%F_A_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PA_T1 => SELF%F_A_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PA_T9 => SELF%F_A_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PR_T0 => SELF%F_R_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PR_T1 => SELF%F_R_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PR_T9 => SELF%F_R_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PT_T0 => SELF%F_T_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PT_T1 => SELF%F_T_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PT_T9 => SELF%F_T_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PW_T0 => SELF%F_W_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PW_T1 => SELF%F_W_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PW_T9 => SELF%F_W_T9%GET_VIEW(BLOCK_INDEX)

    IF (ASSOCIATED(SELF%F_GROUP))  SELF%PGROUP => SELF%F_GROUP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_INIT(SELF, VARIABLE_GROUP)
    ! Constructor of the array view type for a surface variable group
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_LAKEB), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    ! Create a view per timestep field for each prognostic variable
    SELF%F_LICT_T0 => VARIABLE_GROUP%VLICT%FT0
    SELF%F_LICT_T1 => VARIABLE_GROUP%VLICT%FT1
    SELF%F_LICT_T9 => VARIABLE_GROUP%VLICT%FT9
    SELF%F_LMLT_T0 => VARIABLE_GROUP%VLMLT%FT0
    SELF%F_LMLT_T1 => VARIABLE_GROUP%VLMLT%FT1
    SELF%F_LMLT_T9 => VARIABLE_GROUP%VLMLT%FT9
    SELF%F_LTLT_T0 => VARIABLE_GROUP%VLTLT%FT0
    SELF%F_LTLT_T1 => VARIABLE_GROUP%VLTLT%FT1
    SELF%F_LTLT_T9 => VARIABLE_GROUP%VLTLT%FT9
    SELF%F_LBLT_T0 => VARIABLE_GROUP%VLBLT%FT0
    SELF%F_LBLT_T1 => VARIABLE_GROUP%VLBLT%FT1
    SELF%F_LBLT_T9 => VARIABLE_GROUP%VLBLT%FT9
    SELF%F_LSHF_T0 => VARIABLE_GROUP%VLSHF%FT0
    SELF%F_LSHF_T1 => VARIABLE_GROUP%VLSHF%FT1
    SELF%F_LSHF_T9 => VARIABLE_GROUP%VLSHF%FT9
    SELF%F_LICD_T0 => VARIABLE_GROUP%VLICD%FT0
    SELF%F_LICD_T1 => VARIABLE_GROUP%VLICD%FT1
    SELF%F_LICD_T9 => VARIABLE_GROUP%VLICD%FT9
    SELF%F_LMLD_T0 => VARIABLE_GROUP%VLMLD%FT0
    SELF%F_LMLD_T1 => VARIABLE_GROUP%VLMLD%FT1
    SELF%F_LMLD_T9 => VARIABLE_GROUP%VLMLD%FT9
    SELF%VARIABLE_GROUP => VARIABLE_GROUP
    SELF%F_GROUP => VARIABLE_GROUP%F_GROUP
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_UPDATE_VIEW(SELF, BLOCK_INDEX)
    ! Extract local array views from field objects
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    ! Set up the view pointer for each timestep field
    SELF%PLICT_T0 => SELF%F_LICT_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PLICT_T1 => SELF%F_LICT_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PLICT_T9 => SELF%F_LICT_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PLMLT_T0 => SELF%F_LMLT_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PLMLT_T1 => SELF%F_LMLT_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PLMLT_T9 => SELF%F_LMLT_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PLTLT_T0 => SELF%F_LTLT_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PLTLT_T1 => SELF%F_LTLT_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PLTLT_T9 => SELF%F_LTLT_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PLBLT_T0 => SELF%F_LBLT_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PLBLT_T1 => SELF%F_LBLT_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PLBLT_T9 => SELF%F_LBLT_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PLSHF_T0 => SELF%F_LSHF_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PLSHF_T1 => SELF%F_LSHF_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PLSHF_T9 => SELF%F_LSHF_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PLICD_T0 => SELF%F_LICD_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PLICD_T1 => SELF%F_LICD_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PLICD_T9 => SELF%F_LICD_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PLMLD_T0 => SELF%F_LMLD_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PLMLD_T1 => SELF%F_LMLD_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PLMLD_T9 => SELF%F_LMLD_T9%GET_VIEW(BLOCK_INDEX)

    IF (ASSOCIATED(SELF%F_GROUP))  SELF%PGROUP => SELF%F_GROUP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_INIT(SELF, VARIABLE_GROUP)
    ! Constructor of the array view type for a surface variable group
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_RESVR), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    ! Create a view per timestep field for each prognostic variable
    SELF%F_T_T0 => VARIABLE_GROUP%VT%FT0
    SELF%F_T_T1 => VARIABLE_GROUP%VT%FT1
    SELF%F_T_T9 => VARIABLE_GROUP%VT%FT9
    SELF%F_W_T0 => VARIABLE_GROUP%VW%FT0
    SELF%F_W_T1 => VARIABLE_GROUP%VW%FT1
    SELF%F_W_T9 => VARIABLE_GROUP%VW%FT9
    SELF%F_FC_T0 => VARIABLE_GROUP%VFC%FT0
    SELF%F_FC_T1 => VARIABLE_GROUP%VFC%FT1
    SELF%F_FC_T9 => VARIABLE_GROUP%VFC%FT9
    SELF%F_IC_T0 => VARIABLE_GROUP%VIC%FT0
    SELF%F_IC_T1 => VARIABLE_GROUP%VIC%FT1
    SELF%F_IC_T9 => VARIABLE_GROUP%VIC%FT9
    SELF%F_FP1_T0 => VARIABLE_GROUP%VFP1%FT0
    SELF%F_FP1_T1 => VARIABLE_GROUP%VFP1%FT1
    SELF%F_FP1_T9 => VARIABLE_GROUP%VFP1%FT9
    SELF%VARIABLE_GROUP => VARIABLE_GROUP
    SELF%F_GROUP => VARIABLE_GROUP%F_GROUP
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_UPDATE_VIEW(SELF, BLOCK_INDEX)
    ! Extract local array views from field objects
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    ! Set up the view pointer for each timestep field
    SELF%PT_T0 => SELF%F_T_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PT_T1 => SELF%F_T_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PT_T9 => SELF%F_T_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PW_T0 => SELF%F_W_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PW_T1 => SELF%F_W_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PW_T9 => SELF%F_W_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PFC_T0 => SELF%F_FC_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PFC_T1 => SELF%F_FC_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PFC_T9 => SELF%F_FC_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PIC_T0 => SELF%F_IC_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PIC_T1 => SELF%F_IC_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PIC_T9 => SELF%F_IC_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PFP1_T0 => SELF%F_FP1_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PFP1_T1 => SELF%F_FP1_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PFP1_T9 => SELF%F_FP1_T9%GET_VIEW(BLOCK_INDEX)

    IF (ASSOCIATED(SELF%F_GROUP))  SELF%PGROUP => SELF%F_GROUP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_INIT(SELF, VARIABLE_GROUP)
    ! Constructor of the array view type for a surface variable group
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_CLS), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    ! Create a view per timestep field for each prognostic variable
    SELF%F_TCLS_T0 => VARIABLE_GROUP%VTCLS%FT0
    SELF%F_TCLS_T1 => VARIABLE_GROUP%VTCLS%FT1
    SELF%F_TCLS_T9 => VARIABLE_GROUP%VTCLS%FT9
    SELF%F_HUCLS_T0 => VARIABLE_GROUP%VHUCLS%FT0
    SELF%F_HUCLS_T1 => VARIABLE_GROUP%VHUCLS%FT1
    SELF%F_HUCLS_T9 => VARIABLE_GROUP%VHUCLS%FT9
    SELF%F_UCLS_T0 => VARIABLE_GROUP%VUCLS%FT0
    SELF%F_UCLS_T1 => VARIABLE_GROUP%VUCLS%FT1
    SELF%F_UCLS_T9 => VARIABLE_GROUP%VUCLS%FT9
    SELF%F_VCLS_T0 => VARIABLE_GROUP%VVCLS%FT0
    SELF%F_VCLS_T1 => VARIABLE_GROUP%VVCLS%FT1
    SELF%F_VCLS_T9 => VARIABLE_GROUP%VVCLS%FT9
    SELF%F_NUCLS_T0 => VARIABLE_GROUP%VNUCLS%FT0
    SELF%F_NUCLS_T1 => VARIABLE_GROUP%VNUCLS%FT1
    SELF%F_NUCLS_T9 => VARIABLE_GROUP%VNUCLS%FT9
    SELF%F_NVCLS_T0 => VARIABLE_GROUP%VNVCLS%FT0
    SELF%F_NVCLS_T1 => VARIABLE_GROUP%VNVCLS%FT1
    SELF%F_NVCLS_T9 => VARIABLE_GROUP%VNVCLS%FT9
    SELF%VARIABLE_GROUP => VARIABLE_GROUP
    SELF%F_GROUP => VARIABLE_GROUP%F_GROUP
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_UPDATE_VIEW(SELF, BLOCK_INDEX)
    ! Extract local array views from field objects
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    ! Set up the view pointer for each timestep field
    SELF%PTCLS_T0 => SELF%F_TCLS_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PTCLS_T1 => SELF%F_TCLS_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PTCLS_T9 => SELF%F_TCLS_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PHUCLS_T0 => SELF%F_HUCLS_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PHUCLS_T1 => SELF%F_HUCLS_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PHUCLS_T9 => SELF%F_HUCLS_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PUCLS_T0 => SELF%F_UCLS_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PUCLS_T1 => SELF%F_UCLS_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PUCLS_T9 => SELF%F_UCLS_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PVCLS_T0 => SELF%F_VCLS_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PVCLS_T1 => SELF%F_VCLS_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PVCLS_T9 => SELF%F_VCLS_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PNUCLS_T0 => SELF%F_NUCLS_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PNUCLS_T1 => SELF%F_NUCLS_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PNUCLS_T9 => SELF%F_NUCLS_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PNVCLS_T0 => SELF%F_NVCLS_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PNVCLS_T1 => SELF%F_NVCLS_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PNVCLS_T9 => SELF%F_NVCLS_T9%GET_VIEW(BLOCK_INDEX)

    IF (ASSOCIATED(SELF%F_GROUP))  SELF%PGROUP => SELF%F_GROUP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_OML_INIT(SELF, VARIABLE_GROUP)
    ! Constructor of the array view type for a surface variable group
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_OML), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    ! Create a view per timestep field for each prognostic variable
    SELF%F_TO_T0 => VARIABLE_GROUP%VTO%FT0
    SELF%F_TO_T1 => VARIABLE_GROUP%VTO%FT1
    SELF%F_TO_T9 => VARIABLE_GROUP%VTO%FT9
    SELF%F_SO_T0 => VARIABLE_GROUP%VSO%FT0
    SELF%F_SO_T1 => VARIABLE_GROUP%VSO%FT1
    SELF%F_SO_T9 => VARIABLE_GROUP%VSO%FT9
    SELF%F_UO_T0 => VARIABLE_GROUP%VUO%FT0
    SELF%F_UO_T1 => VARIABLE_GROUP%VUO%FT1
    SELF%F_UO_T9 => VARIABLE_GROUP%VUO%FT9
    SELF%F_VO_T0 => VARIABLE_GROUP%VVO%FT0
    SELF%F_VO_T1 => VARIABLE_GROUP%VVO%FT1
    SELF%F_VO_T9 => VARIABLE_GROUP%VVO%FT9
    SELF%VARIABLE_GROUP => VARIABLE_GROUP
    SELF%F_GROUP => VARIABLE_GROUP%F_GROUP
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_OML_UPDATE_VIEW(SELF, BLOCK_INDEX)
    ! Extract local array views from field objects
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    ! Set up the view pointer for each timestep field
    SELF%PTO_T0 => SELF%F_TO_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PTO_T1 => SELF%F_TO_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PTO_T9 => SELF%F_TO_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PSO_T0 => SELF%F_SO_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PSO_T1 => SELF%F_SO_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PSO_T9 => SELF%F_SO_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PUO_T0 => SELF%F_UO_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PUO_T1 => SELF%F_UO_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PUO_T9 => SELF%F_UO_T9%GET_VIEW(BLOCK_INDEX)
    SELF%PVO_T0 => SELF%F_VO_T0%GET_VIEW(BLOCK_INDEX)
    SELF%PVO_T1 => SELF%F_VO_T1%GET_VIEW(BLOCK_INDEX)
    SELF%PVO_T9 => SELF%F_VO_T9%GET_VIEW(BLOCK_INDEX)

    IF (ASSOCIATED(SELF%F_GROUP))  SELF%PGROUP => SELF%F_GROUP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_INIT(SELF, VARIABLE_GROUP)
    ! Constructor of the array view type for a surface variable group
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_EXTRP), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    ! Create a view per timestep field for each prognostic variable
    SELF%VARIABLE_GROUP => VARIABLE_GROUP
    SELF%F_GROUP => VARIABLE_GROUP%F_GROUP
  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_UPDATE_VIEW(SELF, BLOCK_INDEX)
    ! Extract local array views from field objects
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    ! Set up the view pointer for each timestep field

    IF (ASSOCIATED(SELF%F_GROUP))  SELF%PGROUP => SELF%F_GROUP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_INIT(SELF, VARIABLE_GROUP)
    ! Constructor of the array view type for a surface variable group
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_XTRP2), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    ! Create a view per timestep field for each prognostic variable
    SELF%VARIABLE_GROUP => VARIABLE_GROUP
    SELF%F_GROUP => VARIABLE_GROUP%F_GROUP
  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_UPDATE_VIEW(SELF, BLOCK_INDEX)
    ! Extract local array views from field objects
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    ! Set up the view pointer for each timestep field

    IF (ASSOCIATED(SELF%F_GROUP))  SELF%PGROUP => SELF%F_GROUP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_UPDATE_VIEW

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_INIT(SELF, VARIABLE_GROUP)
    ! Constructor of the array view type for a surface variable group
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF
    TYPE(SURFACE_VARIABLE_GROUP_CANRI), TARGET, INTENT(INOUT) :: VARIABLE_GROUP

    ! Create a view per timestep field for each prognostic variable
    SELF%VARIABLE_GROUP => VARIABLE_GROUP
    SELF%F_GROUP => VARIABLE_GROUP%F_GROUP
  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_INIT

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_UPDATE_VIEW(SELF, BLOCK_INDEX)
    ! Extract local array views from field objects
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    ! Set up the view pointer for each timestep field

    IF (ASSOCIATED(SELF%F_GROUP))  SELF%PGROUP => SELF%F_GROUP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_UPDATE_VIEW



  ! Timestepping utility subroutines for prognostics variables
  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET9TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF

    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T9(:,:) = SELF%PT_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VQ%LACTIVE) THEN
      SELF%PQ_T9(:,:) = SELF%PQ_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VTL%LACTIVE) THEN
      SELF%PTL_T9(:,:) = SELF%PTL_T0(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET1TO9(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF

    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T1(:,:) = SELF%PT_T9(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VQ%LACTIVE) THEN
      SELF%PQ_T1(:,:) = SELF%PQ_T9(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VTL%LACTIVE) THEN
      SELF%PTL_T1(:,:) = SELF%PTL_T9(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET1TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF

    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T1(:,:) = SELF%PT_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VQ%LACTIVE) THEN
      SELF%PQ_T1(:,:) = SELF%PQ_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VTL%LACTIVE) THEN
      SELF%PTL_T1(:,:) = SELF%PTL_T0(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET0TO1(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF

    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T0(:,:) = SELF%PT_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VQ%LACTIVE) THEN
      SELF%PQ_T0(:,:) = SELF%PQ_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VTL%LACTIVE) THEN
      SELF%PTL_T0(:,:) = SELF%PTL_T1(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_SOILB_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_SOILB) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    REPSP1 = YDDYN%REPSP1
    ZZPHY = 1.0_JPRB - REPSP1

    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T9(:,:) = REPSP1*SELF%PT_T1(:,:) &
       &                                      + ZZPHY*SELF%PT_T0(:,:)
      SELF%PT_T0(:,:) = SELF%PT_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VQ%LACTIVE) THEN
      SELF%PQ_T9(:,:) = REPSP1*SELF%PQ_T1(:,:) &
       &                                      + ZZPHY*SELF%PQ_T0(:,:)
      SELF%PQ_T0(:,:) = SELF%PQ_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VTL%LACTIVE) THEN
      SELF%PTL_T9(:,:) = REPSP1*SELF%PTL_T1(:,:) &
       &                                      + ZZPHY*SELF%PTL_T0(:,:)
      SELF%PTL_T0(:,:) = SELF%PTL_T1(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_SOILB_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET9TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF

    IF (SELF%VARIABLE_GROUP%VF%LACTIVE) THEN
      SELF%PF_T9(:,:) = SELF%PF_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VA%LACTIVE) THEN
      SELF%PA_T9(:,:) = SELF%PA_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VR%LACTIVE) THEN
      SELF%PR_T9(:,:) = SELF%PR_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T9(:,:) = SELF%PT_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VW%LACTIVE) THEN
      SELF%PW_T9(:,:) = SELF%PW_T0(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET1TO9(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF

    IF (SELF%VARIABLE_GROUP%VF%LACTIVE) THEN
      SELF%PF_T1(:,:) = SELF%PF_T9(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VA%LACTIVE) THEN
      SELF%PA_T1(:,:) = SELF%PA_T9(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VR%LACTIVE) THEN
      SELF%PR_T1(:,:) = SELF%PR_T9(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T1(:,:) = SELF%PT_T9(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VW%LACTIVE) THEN
      SELF%PW_T1(:,:) = SELF%PW_T9(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET1TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF

    IF (SELF%VARIABLE_GROUP%VF%LACTIVE) THEN
      SELF%PF_T1(:,:) = SELF%PF_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VA%LACTIVE) THEN
      SELF%PA_T1(:,:) = SELF%PA_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VR%LACTIVE) THEN
      SELF%PR_T1(:,:) = SELF%PR_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T1(:,:) = SELF%PT_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VW%LACTIVE) THEN
      SELF%PW_T1(:,:) = SELF%PW_T0(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET0TO1(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF

    IF (SELF%VARIABLE_GROUP%VF%LACTIVE) THEN
      SELF%PF_T0(:,:) = SELF%PF_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VA%LACTIVE) THEN
      SELF%PA_T0(:,:) = SELF%PA_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VR%LACTIVE) THEN
      SELF%PR_T0(:,:) = SELF%PR_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T0(:,:) = SELF%PT_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VW%LACTIVE) THEN
      SELF%PW_T0(:,:) = SELF%PW_T1(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_SNOWG) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    REPSP1 = YDDYN%REPSP1
    ZZPHY = 1.0_JPRB - REPSP1

    IF (SELF%VARIABLE_GROUP%VF%LACTIVE) THEN
      SELF%PF_T9(:,:) = REPSP1*SELF%PF_T1(:,:) &
       &                                      + ZZPHY*SELF%PF_T0(:,:)
      SELF%PF_T0(:,:) = SELF%PF_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VA%LACTIVE) THEN
      SELF%PA_T9(:,:) = REPSP1*SELF%PA_T1(:,:) &
       &                                      + ZZPHY*SELF%PA_T0(:,:)
      SELF%PA_T0(:,:) = SELF%PA_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VR%LACTIVE) THEN
      SELF%PR_T9(:,:) = REPSP1*SELF%PR_T1(:,:) &
       &                                      + ZZPHY*SELF%PR_T0(:,:)
      SELF%PR_T0(:,:) = SELF%PR_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T9(:,:) = REPSP1*SELF%PT_T1(:,:) &
       &                                      + ZZPHY*SELF%PT_T0(:,:)
      SELF%PT_T0(:,:) = SELF%PT_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VW%LACTIVE) THEN
      SELF%PW_T9(:,:) = REPSP1*SELF%PW_T1(:,:) &
       &                                      + ZZPHY*SELF%PW_T0(:,:)
      SELF%PW_T0(:,:) = SELF%PW_T1(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_SNOWG_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET9TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF

    IF (SELF%VARIABLE_GROUP%VLICT%LACTIVE) THEN
      SELF%PLICT_T9(:) = SELF%PLICT_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLMLT%LACTIVE) THEN
      SELF%PLMLT_T9(:) = SELF%PLMLT_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLTLT%LACTIVE) THEN
      SELF%PLTLT_T9(:) = SELF%PLTLT_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLBLT%LACTIVE) THEN
      SELF%PLBLT_T9(:) = SELF%PLBLT_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLSHF%LACTIVE) THEN
      SELF%PLSHF_T9(:) = SELF%PLSHF_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLICD%LACTIVE) THEN
      SELF%PLICD_T9(:) = SELF%PLICD_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLMLD%LACTIVE) THEN
      SELF%PLMLD_T9(:) = SELF%PLMLD_T0(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET1TO9(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF

    IF (SELF%VARIABLE_GROUP%VLICT%LACTIVE) THEN
      SELF%PLICT_T1(:) = SELF%PLICT_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLMLT%LACTIVE) THEN
      SELF%PLMLT_T1(:) = SELF%PLMLT_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLTLT%LACTIVE) THEN
      SELF%PLTLT_T1(:) = SELF%PLTLT_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLBLT%LACTIVE) THEN
      SELF%PLBLT_T1(:) = SELF%PLBLT_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLSHF%LACTIVE) THEN
      SELF%PLSHF_T1(:) = SELF%PLSHF_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLICD%LACTIVE) THEN
      SELF%PLICD_T1(:) = SELF%PLICD_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLMLD%LACTIVE) THEN
      SELF%PLMLD_T1(:) = SELF%PLMLD_T9(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET1TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF

    IF (SELF%VARIABLE_GROUP%VLICT%LACTIVE) THEN
      SELF%PLICT_T1(:) = SELF%PLICT_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLMLT%LACTIVE) THEN
      SELF%PLMLT_T1(:) = SELF%PLMLT_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLTLT%LACTIVE) THEN
      SELF%PLTLT_T1(:) = SELF%PLTLT_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLBLT%LACTIVE) THEN
      SELF%PLBLT_T1(:) = SELF%PLBLT_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLSHF%LACTIVE) THEN
      SELF%PLSHF_T1(:) = SELF%PLSHF_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLICD%LACTIVE) THEN
      SELF%PLICD_T1(:) = SELF%PLICD_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLMLD%LACTIVE) THEN
      SELF%PLMLD_T1(:) = SELF%PLMLD_T0(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET0TO1(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF

    IF (SELF%VARIABLE_GROUP%VLICT%LACTIVE) THEN
      SELF%PLICT_T0(:) = SELF%PLICT_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLMLT%LACTIVE) THEN
      SELF%PLMLT_T0(:) = SELF%PLMLT_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLTLT%LACTIVE) THEN
      SELF%PLTLT_T0(:) = SELF%PLTLT_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLBLT%LACTIVE) THEN
      SELF%PLBLT_T0(:) = SELF%PLBLT_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLSHF%LACTIVE) THEN
      SELF%PLSHF_T0(:) = SELF%PLSHF_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLICD%LACTIVE) THEN
      SELF%PLICD_T0(:) = SELF%PLICD_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLMLD%LACTIVE) THEN
      SELF%PLMLD_T0(:) = SELF%PLMLD_T1(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_LAKEB) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    REPSP1 = YDDYN%REPSP1
    ZZPHY = 1.0_JPRB - REPSP1

    IF (SELF%VARIABLE_GROUP%VLICT%LACTIVE) THEN
      SELF%PLICT_T9(:) = REPSP1*SELF%PLICT_T1(:) &
       &                                      + ZZPHY*SELF%PLICT_T0(:)
      SELF%PLICT_T0(:) = SELF%PLICT_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLMLT%LACTIVE) THEN
      SELF%PLMLT_T9(:) = REPSP1*SELF%PLMLT_T1(:) &
       &                                      + ZZPHY*SELF%PLMLT_T0(:)
      SELF%PLMLT_T0(:) = SELF%PLMLT_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLTLT%LACTIVE) THEN
      SELF%PLTLT_T9(:) = REPSP1*SELF%PLTLT_T1(:) &
       &                                      + ZZPHY*SELF%PLTLT_T0(:)
      SELF%PLTLT_T0(:) = SELF%PLTLT_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLBLT%LACTIVE) THEN
      SELF%PLBLT_T9(:) = REPSP1*SELF%PLBLT_T1(:) &
       &                                      + ZZPHY*SELF%PLBLT_T0(:)
      SELF%PLBLT_T0(:) = SELF%PLBLT_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLSHF%LACTIVE) THEN
      SELF%PLSHF_T9(:) = REPSP1*SELF%PLSHF_T1(:) &
       &                                      + ZZPHY*SELF%PLSHF_T0(:)
      SELF%PLSHF_T0(:) = SELF%PLSHF_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLICD%LACTIVE) THEN
      SELF%PLICD_T9(:) = REPSP1*SELF%PLICD_T1(:) &
       &                                      + ZZPHY*SELF%PLICD_T0(:)
      SELF%PLICD_T0(:) = SELF%PLICD_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VLMLD%LACTIVE) THEN
      SELF%PLMLD_T9(:) = REPSP1*SELF%PLMLD_T1(:) &
       &                                      + ZZPHY*SELF%PLMLD_T0(:)
      SELF%PLMLD_T0(:) = SELF%PLMLD_T1(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_LAKEB_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET9TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF

    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T9(:) = SELF%PT_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VW%LACTIVE) THEN
      SELF%PW_T9(:) = SELF%PW_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VFC%LACTIVE) THEN
      SELF%PFC_T9(:) = SELF%PFC_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VIC%LACTIVE) THEN
      SELF%PIC_T9(:) = SELF%PIC_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VFP1%LACTIVE) THEN
      SELF%PFP1_T9(:) = SELF%PFP1_T0(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET1TO9(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF

    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T1(:) = SELF%PT_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VW%LACTIVE) THEN
      SELF%PW_T1(:) = SELF%PW_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VFC%LACTIVE) THEN
      SELF%PFC_T1(:) = SELF%PFC_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VIC%LACTIVE) THEN
      SELF%PIC_T1(:) = SELF%PIC_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VFP1%LACTIVE) THEN
      SELF%PFP1_T1(:) = SELF%PFP1_T9(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET1TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF

    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T1(:) = SELF%PT_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VW%LACTIVE) THEN
      SELF%PW_T1(:) = SELF%PW_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VFC%LACTIVE) THEN
      SELF%PFC_T1(:) = SELF%PFC_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VIC%LACTIVE) THEN
      SELF%PIC_T1(:) = SELF%PIC_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VFP1%LACTIVE) THEN
      SELF%PFP1_T1(:) = SELF%PFP1_T0(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET0TO1(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF

    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T0(:) = SELF%PT_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VW%LACTIVE) THEN
      SELF%PW_T0(:) = SELF%PW_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VFC%LACTIVE) THEN
      SELF%PFC_T0(:) = SELF%PFC_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VIC%LACTIVE) THEN
      SELF%PIC_T0(:) = SELF%PIC_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VFP1%LACTIVE) THEN
      SELF%PFP1_T0(:) = SELF%PFP1_T1(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_RESVR_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_RESVR) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    REPSP1 = YDDYN%REPSP1
    ZZPHY = 1.0_JPRB - REPSP1

    IF (SELF%VARIABLE_GROUP%VT%LACTIVE) THEN
      SELF%PT_T9(:) = REPSP1*SELF%PT_T1(:) &
       &                                      + ZZPHY*SELF%PT_T0(:)
      SELF%PT_T0(:) = SELF%PT_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VW%LACTIVE) THEN
      SELF%PW_T9(:) = REPSP1*SELF%PW_T1(:) &
       &                                      + ZZPHY*SELF%PW_T0(:)
      SELF%PW_T0(:) = SELF%PW_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VFC%LACTIVE) THEN
      SELF%PFC_T9(:) = REPSP1*SELF%PFC_T1(:) &
       &                                      + ZZPHY*SELF%PFC_T0(:)
      SELF%PFC_T0(:) = SELF%PFC_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VIC%LACTIVE) THEN
      SELF%PIC_T9(:) = REPSP1*SELF%PIC_T1(:) &
       &                                      + ZZPHY*SELF%PIC_T0(:)
      SELF%PIC_T0(:) = SELF%PIC_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VFP1%LACTIVE) THEN
      SELF%PFP1_T9(:) = REPSP1*SELF%PFP1_T1(:) &
       &                                      + ZZPHY*SELF%PFP1_T0(:)
      SELF%PFP1_T0(:) = SELF%PFP1_T1(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_RESVR_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET9TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF

    IF (SELF%VARIABLE_GROUP%VTCLS%LACTIVE) THEN
      SELF%PTCLS_T9(:) = SELF%PTCLS_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VHUCLS%LACTIVE) THEN
      SELF%PHUCLS_T9(:) = SELF%PHUCLS_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VUCLS%LACTIVE) THEN
      SELF%PUCLS_T9(:) = SELF%PUCLS_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VVCLS%LACTIVE) THEN
      SELF%PVCLS_T9(:) = SELF%PVCLS_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VNUCLS%LACTIVE) THEN
      SELF%PNUCLS_T9(:) = SELF%PNUCLS_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VNVCLS%LACTIVE) THEN
      SELF%PNVCLS_T9(:) = SELF%PNVCLS_T0(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET1TO9(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF

    IF (SELF%VARIABLE_GROUP%VTCLS%LACTIVE) THEN
      SELF%PTCLS_T1(:) = SELF%PTCLS_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VHUCLS%LACTIVE) THEN
      SELF%PHUCLS_T1(:) = SELF%PHUCLS_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VUCLS%LACTIVE) THEN
      SELF%PUCLS_T1(:) = SELF%PUCLS_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VVCLS%LACTIVE) THEN
      SELF%PVCLS_T1(:) = SELF%PVCLS_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VNUCLS%LACTIVE) THEN
      SELF%PNUCLS_T1(:) = SELF%PNUCLS_T9(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VNVCLS%LACTIVE) THEN
      SELF%PNVCLS_T1(:) = SELF%PNVCLS_T9(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET1TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF

    IF (SELF%VARIABLE_GROUP%VTCLS%LACTIVE) THEN
      SELF%PTCLS_T1(:) = SELF%PTCLS_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VHUCLS%LACTIVE) THEN
      SELF%PHUCLS_T1(:) = SELF%PHUCLS_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VUCLS%LACTIVE) THEN
      SELF%PUCLS_T1(:) = SELF%PUCLS_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VVCLS%LACTIVE) THEN
      SELF%PVCLS_T1(:) = SELF%PVCLS_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VNUCLS%LACTIVE) THEN
      SELF%PNUCLS_T1(:) = SELF%PNUCLS_T0(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VNVCLS%LACTIVE) THEN
      SELF%PNVCLS_T1(:) = SELF%PNVCLS_T0(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET0TO1(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF

    IF (SELF%VARIABLE_GROUP%VTCLS%LACTIVE) THEN
      SELF%PTCLS_T0(:) = SELF%PTCLS_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VHUCLS%LACTIVE) THEN
      SELF%PHUCLS_T0(:) = SELF%PHUCLS_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VUCLS%LACTIVE) THEN
      SELF%PUCLS_T0(:) = SELF%PUCLS_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VVCLS%LACTIVE) THEN
      SELF%PVCLS_T0(:) = SELF%PVCLS_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VNUCLS%LACTIVE) THEN
      SELF%PNUCLS_T0(:) = SELF%PNUCLS_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VNVCLS%LACTIVE) THEN
      SELF%PNVCLS_T0(:) = SELF%PNVCLS_T1(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_CLS_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_CLS) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    REPSP1 = YDDYN%REPSP1
    ZZPHY = 1.0_JPRB - REPSP1

    IF (SELF%VARIABLE_GROUP%VTCLS%LACTIVE) THEN
      SELF%PTCLS_T9(:) = REPSP1*SELF%PTCLS_T1(:) &
       &                                      + ZZPHY*SELF%PTCLS_T0(:)
      SELF%PTCLS_T0(:) = SELF%PTCLS_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VHUCLS%LACTIVE) THEN
      SELF%PHUCLS_T9(:) = REPSP1*SELF%PHUCLS_T1(:) &
       &                                      + ZZPHY*SELF%PHUCLS_T0(:)
      SELF%PHUCLS_T0(:) = SELF%PHUCLS_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VUCLS%LACTIVE) THEN
      SELF%PUCLS_T9(:) = REPSP1*SELF%PUCLS_T1(:) &
       &                                      + ZZPHY*SELF%PUCLS_T0(:)
      SELF%PUCLS_T0(:) = SELF%PUCLS_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VVCLS%LACTIVE) THEN
      SELF%PVCLS_T9(:) = REPSP1*SELF%PVCLS_T1(:) &
       &                                      + ZZPHY*SELF%PVCLS_T0(:)
      SELF%PVCLS_T0(:) = SELF%PVCLS_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VNUCLS%LACTIVE) THEN
      SELF%PNUCLS_T9(:) = REPSP1*SELF%PNUCLS_T1(:) &
       &                                      + ZZPHY*SELF%PNUCLS_T0(:)
      SELF%PNUCLS_T0(:) = SELF%PNUCLS_T1(:)
    END IF
    IF (SELF%VARIABLE_GROUP%VNVCLS%LACTIVE) THEN
      SELF%PNVCLS_T9(:) = REPSP1*SELF%PNVCLS_T1(:) &
       &                                      + ZZPHY*SELF%PNVCLS_T0(:)
      SELF%PNVCLS_T0(:) = SELF%PNVCLS_T1(:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_CLS_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_OML_SET9TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF

    IF (SELF%VARIABLE_GROUP%VTO%LACTIVE) THEN
      SELF%PTO_T9(:,:) = SELF%PTO_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VSO%LACTIVE) THEN
      SELF%PSO_T9(:,:) = SELF%PSO_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VUO%LACTIVE) THEN
      SELF%PUO_T9(:,:) = SELF%PUO_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VVO%LACTIVE) THEN
      SELF%PVO_T9(:,:) = SELF%PVO_T0(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_OML_SET1TO9(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF

    IF (SELF%VARIABLE_GROUP%VTO%LACTIVE) THEN
      SELF%PTO_T1(:,:) = SELF%PTO_T9(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VSO%LACTIVE) THEN
      SELF%PSO_T1(:,:) = SELF%PSO_T9(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VUO%LACTIVE) THEN
      SELF%PUO_T1(:,:) = SELF%PUO_T9(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VVO%LACTIVE) THEN
      SELF%PVO_T1(:,:) = SELF%PVO_T9(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_OML_SET1TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF

    IF (SELF%VARIABLE_GROUP%VTO%LACTIVE) THEN
      SELF%PTO_T1(:,:) = SELF%PTO_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VSO%LACTIVE) THEN
      SELF%PSO_T1(:,:) = SELF%PSO_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VUO%LACTIVE) THEN
      SELF%PUO_T1(:,:) = SELF%PUO_T0(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VVO%LACTIVE) THEN
      SELF%PVO_T1(:,:) = SELF%PVO_T0(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_OML_SET0TO1(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF

    IF (SELF%VARIABLE_GROUP%VTO%LACTIVE) THEN
      SELF%PTO_T0(:,:) = SELF%PTO_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VSO%LACTIVE) THEN
      SELF%PSO_T0(:,:) = SELF%PSO_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VUO%LACTIVE) THEN
      SELF%PUO_T0(:,:) = SELF%PUO_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VVO%LACTIVE) THEN
      SELF%PVO_T0(:,:) = SELF%PVO_T1(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_OML_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_OML) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    REPSP1 = YDDYN%REPSP1
    ZZPHY = 1.0_JPRB - REPSP1

    IF (SELF%VARIABLE_GROUP%VTO%LACTIVE) THEN
      SELF%PTO_T9(:,:) = REPSP1*SELF%PTO_T1(:,:) &
       &                                      + ZZPHY*SELF%PTO_T0(:,:)
      SELF%PTO_T0(:,:) = SELF%PTO_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VSO%LACTIVE) THEN
      SELF%PSO_T9(:,:) = REPSP1*SELF%PSO_T1(:,:) &
       &                                      + ZZPHY*SELF%PSO_T0(:,:)
      SELF%PSO_T0(:,:) = SELF%PSO_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VUO%LACTIVE) THEN
      SELF%PUO_T9(:,:) = REPSP1*SELF%PUO_T1(:,:) &
       &                                      + ZZPHY*SELF%PUO_T0(:,:)
      SELF%PUO_T0(:,:) = SELF%PUO_T1(:,:)
    END IF
    IF (SELF%VARIABLE_GROUP%VVO%LACTIVE) THEN
      SELF%PVO_T9(:,:) = REPSP1*SELF%PVO_T1(:,:) &
       &                                      + ZZPHY*SELF%PVO_T0(:,:)
      SELF%PVO_T0(:,:) = SELF%PVO_T1(:,:)
    END IF
  END SUBROUTINE SURFACE_VIEW_GROUP_OML_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET9TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET1TO9(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET1TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET0TO1(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_EXTRP) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    REPSP1 = YDDYN%REPSP1
    ZZPHY = 1.0_JPRB - REPSP1

  END SUBROUTINE SURFACE_VIEW_GROUP_EXTRP_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET9TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET1TO9(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET1TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET0TO1(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_XTRP2) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    REPSP1 = YDDYN%REPSP1
    ZZPHY = 1.0_JPRB - REPSP1

  END SUBROUTINE SURFACE_VIEW_GROUP_XTRP2_PHTFILT

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET9TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET9TO0

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET1TO9(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET1TO9

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET1TO0(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET1TO0

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET0TO1(SELF)
    ! Field update operation for timestepping schemes
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_SET0TO1

  SUBROUTINE SURFACE_VIEW_GROUP_CANRI_PHTFILT(SELF, YDDYN)
    CLASS(SURFACE_VIEW_GROUP_CANRI) :: SELF
    TYPE(TDYN), INTENT(IN) :: YDDYN
    REAL(KIND=JPRB) :: REPSP1, ZZPHY

    REPSP1 = YDDYN%REPSP1
    ZZPHY = 1.0_JPRB - REPSP1

  END SUBROUTINE SURFACE_VIEW_GROUP_CANRI_PHTFILT


END MODULE SURFACE_VIEWS_PROGNOSTIC_MODULE
