MODULE TRAJ_SEMILAG_MOD

!     Purpose.
!     --------
!       Manage semi-lagrangian trajectory

!     Author.
!     -------
!        Y. Tremolet *ECMWF*
!        Original : 28-03-02

!     Modifications.
!     --------------
!        Modified by C. Temperton 02-01-08 Case LSPRT=.TRUE.
!        K. YESSAD 04-JAN-2002: pruning (rm obsolete NVLAG=1, PCL05, PX05)
!        Modified by C. Temperton 02-04-24 : allow TSTEP=0 (for testing).
!        Modified by C. Temperton 03-04-08 : bugfix for case LSPRT=.TRUE.
!        M.Hamrud      01-Oct-2003 CY28 Cleaning
!        K. YESSAD (Jan 2004): correct dimension of PGFLL95.
!        Y.Tremolet    18-Mar-2004 Add lprttraj option for diagnostics
!        F. Vana    13-Jan-2009 : LSLHD = .T.
!        F. Vana  19-03-2012: t+dt values for T -> Tv conversion added
!                              when available (using add_traj_slag)
!        F. Vana  28-Nov-2013 : Redesigned trajectory handling
!        K. Yessad (July 2014): Move some variables.
!        F. Vana  25-Sep-2013 : Split KAPPA to KAPPA and KAPPAT
!        F. Vana  24-Feb-2014 : LSETTLSVF option
!        F. Vana  21-Nov-2017 : Option LSLDP_CURV
!        F. Vana   July 2018: RK4 scheme for trajectory research.

!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK
USE YOMLUN   , ONLY : NULOUT
USE YOMDIM   , ONLY : TDIM
USE YOMDYNA  , ONLY : YRDYNA
USE YOMVWRK  , ONLY : NTRSLTYPE
USE YOMCT0   , ONLY : LIFSTRAJ, LSPRT, LR2D
USE YOMTRAJ  , ONLY : TRAJEC

IMPLICIT NONE

PRIVATE
PUBLIC ALLOCATE_TRAJ_SLAG, DEALLOCATE_TRAJ_SLAG

#include "abor1.intfb.h"

!-----------------------------------------------------------------------
CONTAINS
!-----------------------------------------------------------------------

SUBROUTINE ALLOCATE_TRAJ_SLAG(YDGEOMETRY,YDML_GCONF,YDDYN)

USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMDYN                 , ONLY : TDYN
USE GEOMETRY_MOD           , ONLY : GEOMETRY
TYPE(GEOMETRY)               , INTENT(IN)   :: YDGEOMETRY
TYPE(TDYN)                   , INTENT(IN)   :: YDDYN
TYPE(MODEL_GENERAL_CONF_TYPE), INTENT(IN)   :: YDML_GCONF
INTEGER(KIND=JPIM) :: IGFLADV,JGFL,J1,J2
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD:ALLOCATE_TRAJ_SLAG',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV, &
  & YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP, YGFL=>YDML_GCONF%YGFL,YDRIP=>YDML_GCONF%YRRIP)
ASSOCIATE(NUMFLDS=>YGFL%NUMFLDS, YCOMP=>YGFL%YCOMP, &
 & NGPBLKS=>YDDIM%NGPBLKS, NPROMA=>YDDIM%NPROMA, &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & LADVF=>YDDYN%LADVF, LSETTLSVF=>YDDYN%LSETTLSVF, LSLHDHEAT=>YDDYN%LSLHDHEAT, &
 & L2TLFF=>YDDYN%L2TLFF, LSLDP_CURV=>YDDYN%LSLDP_CURV, LSLDP_RK=>YDDYN%LSLDP_RK, &
 & NSTART=>YDRIP%NSTART, NSTOP=>YDRIP%NSTOP)
! NOTE: It should be used also for Eulerian scheme when LSPRT=true

IF (LIFSTRAJ) CALL ABOR1('Cannot interpolate SL trajectory')

! Computation of size for SL traj (to use only appropriate amount of memory)
IGFLADV=0
DO JGFL=1,NUMFLDS
  IF(YCOMP(JGFL)%LADV) IGFLADV=IGFLADV+1
ENDDO
    
IF (LR2D) THEN ! Clive's code for shallow water model

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(J1,J2)
  DO J2=0,NSTOP
    ALLOCATE(TRAJEC(J2)%SLAG(NGPBLKS))
    DO J1=1,NGPBLKS
      IF (NTRSLTYPE == 1) THEN
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PUT95(NPROMA)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVT95(NPROMA)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PSPNLT95(NPROMA)) 
      ELSEIF(NTRSLTYPE == 2) THEN
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PUL95(NPROMA,1)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVL95(NPROMA,1)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PUL05(NPROMA,1)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVL05(NPROMA,1)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PURL05(NPROMA,1)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVRL05(NPROMA,1)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PURL5(NPROMA,1)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVRL5(NPROMA,1)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PUSI5(NPROMA)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVSI5(NPROMA)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PUT15(NPROMA,1)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVT15(NPROMA,1)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PSPL95(NPROMA)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PSPL05(NPROMA)) 
        ! LSLDP_CURV to be completed
      ENDIF
      TRAJEC(J2)%SLAG(J1)%LASTCHUNK=.FALSE.
    ENDDO
    TRAJEC(J2)%SLAG(NGPBLKS)%LASTCHUNK=.TRUE.
  ENDDO
!$OMP END PARALLEL DO

ELSE  ! full 3D model

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(J1,J2)
  DO J2=0,NSTOP
    ALLOCATE(TRAJEC(J2)%SLAG(NGPBLKS))
    DO J1=1,NGPBLKS
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PUL95(NPROMA,NFLEVG)) 
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVL95(NPROMA,NFLEVG)) 
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PTL95(NPROMA,NFLEVG)) 
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PCL95(NPROMA,NFLEVG)) 
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PUL05(NPROMA,NFLEVG)) 
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVL05(NPROMA,NFLEVG)) 
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PTL05(NPROMA,NFLEVG)) 
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PURL05(NPROMA,NFLEVG)) 
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVRL05(NPROMA,NFLEVG)) 
      IF (LSLDP_CURV) THEN
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PZRL05(NPROMA,NFLEVG)) 
      ENDIF
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PWRL05(NPROMA,NFLEVG)) 
      IF (LSLDP_RK) THEN
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PURL005(NPROMA,NFLEVG)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVRL005(NPROMA,NFLEVG)) 
        IF (LSLDP_CURV) THEN
          ALLOCATE (TRAJEC(J2)%SLAG(J1)%PZRL005(NPROMA,NFLEVG)) 
        ENDIF
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PWRL005(NPROMA,NFLEVG)) 
      ENDIF
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PURL5(NPROMA,NFLEVG)) 
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVRL5(NPROMA,NFLEVG)) 
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PWRL5(NPROMA,NFLEVG)) 
      IF (LADVF.AND.L2TLFF) THEN
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PUT15(NPROMA,NFLEVG)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PVT15(NPROMA,NFLEVG)) 
      ENDIF
      IF (LSPRT) THEN
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PTT15(NPROMA,NFLEVG)) 
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PQT15(NPROMA,NFLEVG))
      ENDIF
      IF (YRDYNA%LSLHD.AND.(.NOT.YRDYNA%LSLHD_STATIC)) THEN
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PKAPPA5(NPROMA,NFLEVG)) 
        IF (LSLHDHEAT) ALLOCATE (TRAJEC(J2)%SLAG(J1)%PKAPPAT5(NPROMA,NFLEVG))
      ENDIF
      IF (LSETTLSVF) THEN
        ALLOCATE (TRAJEC(J2)%SLAG(J1)%PWRL95(NPROMA,NFLEVG)) 
      ENDIF
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PX95(NPROMA))
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%PGFLL95(NPROMA,NFLEVG,IGFLADV))
      ALLOCATE (TRAJEC(J2)%SLAG(J1)%IGFLL95(IGFLADV))
      TRAJEC(J2)%SLAG(J1)%LASTCHUNK=.FALSE.
    ENDDO
    TRAJEC(J2)%SLAG(NGPBLKS)%LASTCHUNK=.TRUE.
  ENDDO
!$OMP END PARALLEL DO

ENDIF

WRITE(NULOUT,*)'GREPTRAJ ARRAY TRAJEC%SLAG ALLOCATED '

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD:ALLOCATE_TRAJ_SLAG',1,ZHOOK_HANDLE)
END SUBROUTINE ALLOCATE_TRAJ_SLAG

!-----------------------------------------------------------------------

SUBROUTINE DEALLOCATE_TRAJ_SLAG(YDDIM,YDRIP,YDDYN)

USE YOMDYN , ONLY : TDYN
USE YOMRIP , ONLY : TRIP
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TDYN)  ,INTENT(IN) :: YDDYN
TYPE(TRIP)  ,INTENT(IN) :: YDRIP

INTEGER(KIND=JPIM) :: J1,J2
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD:DEALLOCATE_TRAJ_SLAG',0,ZHOOK_HANDLE)
ASSOCIATE(NGPBLKS=>YDDIM%NGPBLKS, &
 & LADVF=>YDDYN%LADVF, LSETTLSVF=>YDDYN%LSETTLSVF, LSLHDHEAT=>YDDYN%LSLHDHEAT, &
 & L2TLFF=>YDDYN%L2TLFF, LSLDP_CURV=>YDDYN%LSLDP_CURV, LSLDP_RK=>YDDYN%LSLDP_RK,  &
 & NSTOP=>YDRIP%NSTOP)
IF (LR2D) THEN ! Clive's code for shallow water model
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(J1,J2)
  DO J2=0,NSTOP
    DO J1=1,NGPBLKS
      IF (NTRSLTYPE == 1) THEN
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PUT95))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PUT95)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVT95))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVT95)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PSPNLT95))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PSPNLT95)
      ELSEIF(NTRSLTYPE == 2) THEN
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PUL95))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PUL95)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVL95))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVL95)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PUL05))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PUL05)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVL05))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVL05)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PURL05)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PURL05)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVRL05)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVRL05)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PURL5))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PURL5)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVRL5))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVRL5)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PUSI5))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PUSI5)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVSI5))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVSI5)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PUT15))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PUT15)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVT15))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVT15)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PSPL95)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PSPL95)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PSPL05)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PSPL05)
      ENDIF
    ENDDO
    IF (ASSOCIATED(TRAJEC(J2)%SLAG)) DEALLOCATE(TRAJEC(J2)%SLAG)
  ENDDO
!$OMP END PARALLEL DO

ELSE

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(J1,J2)
  DO J2=0,NSTOP
    DO J1=1,NGPBLKS
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PUL95))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PUL95)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVL95))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVL95)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PTL95))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PTL95)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PCL95))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PCL95)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PUL05))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PUL05)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVL05))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVL05)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PTL05))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PTL05)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PURL05)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PURL05)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVRL05)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVRL05)
      IF (LSLDP_CURV) THEN
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PZRL05)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PZRL05)
      ENDIF
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PWRL05)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PWRL05)
      IF (LSLDP_RK) THEN
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PURL005)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PURL005)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVRL005)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVRL005)
        IF (LSLDP_CURV) THEN
          IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PZRL005)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PZRL005)
        ENDIF
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PWRL005)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PWRL005)
      ENDIF
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PURL5))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PURL5)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVRL5))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVRL5)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PWRL5))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PWRL5)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PX95))   DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PX95)
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PGFLL95)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PGFLL95) 
      IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%IGFLL95)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%IGFLL95)
      IF (LADVF.AND.L2TLFF) THEN
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PUT15))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PUT15)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PVT15))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PVT15)
      ENDIF
      IF (LSPRT) THEN
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PTT15))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PTT15)
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PQT15))  DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PQT15)
      ENDIF
      IF (YRDYNA%LSLHD.AND.(.NOT.YRDYNA%LSLHD_STATIC)) THEN
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PKAPPA5)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PKAPPA5)
        IF (LSLHDHEAT) THEN
          IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PKAPPAT5)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PKAPPAT5)
        ENDIF
      ENDIF
      IF (LSETTLSVF) THEN
        IF (ASSOCIATED (TRAJEC(J2)%SLAG(J1)%PWRL95)) DEALLOCATE (TRAJEC(J2)%SLAG(J1)%PWRL95)
      ENDIF
    ENDDO
    IF (ASSOCIATED(TRAJEC(J2)%SLAG)) DEALLOCATE(TRAJEC(J2)%SLAG)
  ENDDO
!$OMP END PARALLEL DO
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD:DEALLOCATE_TRAJ_SLAG',1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_TRAJ_SLAG

!-----------------------------------------------------------------------
END MODULE TRAJ_SEMILAG_MOD
