MODULE TRAJ_SEMILAG_MOD_OOPS

!     Purpose.
!     --------
!       Manage semi-lagrangian trajectory

!     Author.
!     -------
!        Y. Tremolet *ECMWF*
!        Original : 28-03-02

!     Modifications.
!     --------------
!        Modified by C. Temperton 02-01-08 Case LSPRT=.TRUE.
!        K. YESSAD 04-JAN-2002: pruning (rm obsolete NVLAG=1, PCL05, PX05)
!        Modified by C. Temperton 02-04-24 : allow TSTEP=0 (for testing).
!        Modified by C. Temperton 03-04-08 : bugfix for case LSPRT=.TRUE.
!        M.Hamrud      01-Oct-2003 CY28 Cleaning
!        K. YESSAD (Jan 2004): correct dimension of PGFLL95.
!        Y.Tremolet    18-Mar-2004 Add lprttraj option for diagnostics
!        F. Vana    13-Jan-2009 : LSLHD = .T.
!        F. Vana  19-03-2012: t+dt values for T -> Tv conversion added
!                              when available (using add_traj_slag)
!        F. Vana  28-Nov-2013 : Redesigned trajectory handling
!        K. Yessad (July 2014): Move some variables.
!        F. Vana  25-Sep-2013 : Split KAPPA to KAPPA and KAPPAT
!        F. Vana  24-Feb-2014 : LSETTLSVF option
!     ------------------------------------------------------------------

USE PARKIND1      , ONLY : JPIM, JPRB
USE YOMHOOK       , ONLY : LHOOK, DR_HOOK
USE YOMLUN        , ONLY : NULOUT
USE YOMDYNA       , ONLY : LSLHD, LSLHD_STATIC
USE YOMVWRK       , ONLY : NTRSLTYPE
USE YOMCT0        , ONLY : LSPRT, LR2D
USE YOMTRAJ       , ONLY : TRAJ_SLAG_TYPE
!!$USE YOMTRAJ_OOPS  , ONLY : MKINDTRAJ

IMPLICIT NONE

PRIVATE
PUBLIC TRAJ_SLAG_TYPE, ALLOCATE_TRAJ_SLAG_OOPS, DEALLOCATE_TRAJ_SLAG_OOPS, CHECK_TRAJ_SLAG_OOPS, CH_ALLOC_TRAJ_SLAG_OOPS

!-----------------------------------------------------------------------

!!$TYPE TRAJ_SLAG_TYPE
!!$  REAL(KIND=MKINDTRAJ), pointer :: PUL95(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PVL95(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PTL95(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PCL95(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PUL05(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PVL05(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PTL05(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PUT15(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PVT15(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PURL05(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PVRL05(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PWRL05(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PURL5(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PVRL5(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PWRL5(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PKAPPA5(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PKAPPAT5(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PTT15(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PQT15(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PWRL95(:,:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PGFLL95(:,:,:)
!!$  INTEGER(KIND=JPIM), pointer :: IGFLL95(:) ! flag identifying trajectory content
!!$  REAL(KIND=MKINDTRAJ), pointer :: PX95(:)
!!$  ! quantities required by 2D model only
!!$  REAL(KIND=MKINDTRAJ), pointer :: PUT95(:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PVT95(:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PSPNLT95(:)  ! NTRSLTYPE=1
!!$  REAL(KIND=MKINDTRAJ), pointer :: PUSI5(:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PVSI5(:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PSPL95(:)
!!$  REAL(KIND=MKINDTRAJ), pointer :: PSPL05(:) ! NTRSLTYPE=2
!!$  LOGICAL :: LASTCHUNK
!!$END TYPE TRAJ_SLAG_TYPE

!-----------------------------------------------------------------------
CONTAINS
!-----------------------------------------------------------------------

SUBROUTINE ALLOCATE_TRAJ_SLAG_OOPS(SELF,KPROMA,KFLEVG,KGPBLKS,YGFL,YDDYN)
USE YOMDYN   , ONLY : TDYN
USE YOM_YGFL , ONLY : TYPE_GFLD
IMPLICIT NONE
INTEGER(KIND=JPIM)  , INTENT(IN)    :: KPROMA, KFLEVG,KGPBLKS
TYPE(TRAJ_SLAG_TYPE), INTENT(INOUT) :: SELF(:)
TYPE(TDYN)          , INTENT(INOUT) :: YDDYN
TYPE(TYPE_GFLD)     , INTENT(INOUT) :: YGFL

INTEGER(KIND=JPIM) :: IGFLADV,JGFL,JBLK
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD_OOPS:ALLOCATE_TRAJ_SLAG_OOPS',0,ZHOOK_HANDLE)


! NOTE: It should be used also for Eulerian scheme when LSPRT=true

!   Computation of size for SL traj (to use only appropriate amount of memory)
IGFLADV=0
DO JGFL=1,YGFL%NUMFLDS
  IF(YGFL%YCOMP(JGFL)%LADV) IGFLADV=IGFLADV+1
ENDDO

DO JBLK=1,KGPBLKS

  IF (LR2D) THEN ! Clive's code for shallow water model
  
    IF (NTRSLTYPE == 1) THEN
      ALLOCATE(SELF(JBLK)%PUT95(KPROMA)) 
      ALLOCATE(SELF(JBLK)%PVT95(KPROMA)) 
      ALLOCATE(SELF(JBLK)%PSPNLT95(KPROMA)) 
    ELSEIF(NTRSLTYPE == 2) THEN
      ALLOCATE(SELF(JBLK)%PUL95(KPROMA,1)) 
      ALLOCATE(SELF(JBLK)%PVL95(KPROMA,1)) 
      ALLOCATE(SELF(JBLK)%PUL05(KPROMA,1)) 
      ALLOCATE(SELF(JBLK)%PVL05(KPROMA,1)) 
      ALLOCATE(SELF(JBLK)%PURL05(KPROMA,1)) 
      ALLOCATE(SELF(JBLK)%PVRL05(KPROMA,1)) 
      ALLOCATE(SELF(JBLK)%PURL5(KPROMA,1)) 
      ALLOCATE(SELF(JBLK)%PVRL5(KPROMA,1)) 
      ALLOCATE(SELF(JBLK)%PUSI5(KPROMA)) 
      ALLOCATE(SELF(JBLK)%PVSI5(KPROMA)) 
      ALLOCATE(SELF(JBLK)%PUT15(KPROMA,1)) 
      ALLOCATE(SELF(JBLK)%PVT15(KPROMA,1)) 
      ALLOCATE(SELF(JBLK)%PSPL95(KPROMA)) 
      ALLOCATE(SELF(JBLK)%PSPL05(KPROMA)) 
    ENDIF
  
  ELSE  ! full 3D model
  
    ALLOCATE(SELF(JBLK)%PUL95(KPROMA,KFLEVG)) 
    SELF(JBLK)%PUL95 = 0.
    ALLOCATE(SELF(JBLK)%PVL95(KPROMA,KFLEVG)) 
    SELF(JBLK)%PVL95 = 0.
    ALLOCATE(SELF(JBLK)%PTL95(KPROMA,KFLEVG)) 
    SELF(JBLK)%PTL95 = 0.
    ALLOCATE(SELF(JBLK)%PCL95(KPROMA,KFLEVG)) 
    SELF(JBLK)%PCL95 = 0.
    ALLOCATE(SELF(JBLK)%PUL05(KPROMA,KFLEVG)) 
    SELF(JBLK)%PUL05 = 0.
    ALLOCATE(SELF(JBLK)%PVL05(KPROMA,KFLEVG)) 
    SELF(JBLK)%PVL05 = 0.
    ALLOCATE(SELF(JBLK)%PTL05(KPROMA,KFLEVG)) 
    SELF(JBLK)%PTL05 = 0.
    ALLOCATE(SELF(JBLK)%PURL05(KPROMA,KFLEVG)) 
    SELF(JBLK)%PURL05 = 0.
    ALLOCATE(SELF(JBLK)%PVRL05(KPROMA,KFLEVG)) 
    SELF(JBLK)%PVRL05 = 0.
    ALLOCATE(SELF(JBLK)%PWRL05(KPROMA,KFLEVG)) 
    SELF(JBLK)%PWRL05 = 0.
    ALLOCATE(SELF(JBLK)%PURL5(KPROMA,KFLEVG)) 
    SELF(JBLK)%PURL5 = 0.
    ALLOCATE(SELF(JBLK)%PVRL5(KPROMA,KFLEVG)) 
    SELF(JBLK)%PVRL5 = 0.
    ALLOCATE(SELF(JBLK)%PWRL5(KPROMA,KFLEVG)) 
    SELF(JBLK)%PWRL5 = 0.
    IF (YDDYN%LADVF.AND.YDDYN%L2TLFF) THEN
      ALLOCATE(SELF(JBLK)%PUT15(KPROMA,KFLEVG)) 
      SELF(JBLK)%PUT15 = 0.
      ALLOCATE(SELF(JBLK)%PVT15(KPROMA,KFLEVG)) 
      SELF(JBLK)%PVT15 = 0.
    ENDIF
    IF (LSPRT) THEN
      ALLOCATE(SELF(JBLK)%PTT15(KPROMA,KFLEVG)) 
      SELF(JBLK)%PTT15 = 0.
      ALLOCATE(SELF(JBLK)%PQT15(KPROMA,KFLEVG))
      SELF(JBLK)%PQT15 = 0.
    ENDIF
    IF (LSLHD.AND.(.NOT.LSLHD_STATIC)) THEN
      ALLOCATE(SELF(JBLK)%PKAPPA5(KPROMA,KFLEVG)) 
      SELF(JBLK)%PKAPPA5 = 0.
      IF (YDDYN%LSLHDHEAT) THEN
         ALLOCATE(SELF(JBLK)%PKAPPAT5(KPROMA,KFLEVG))
         SELF(JBLK)%PKAPPAT5 = 0.
      ENDIF
    ENDIF
    IF (YDDYN%LSETTLSVF) THEN
      ALLOCATE(SELF(JBLK)%PWRL95(KPROMA,KFLEVG)) 
      SELF(JBLK)%PWRL95 = 0.
    ENDIF
    ALLOCATE(SELF(JBLK)%PX95(KPROMA))
    SELF(JBLK)%PX95 = 0.

    ALLOCATE(SELF(JBLK)%PGFLL95(KPROMA,KFLEVG,IGFLADV))
    SELF(JBLK)%PGFLL95 = 0.
    ALLOCATE(SELF(JBLK)%IGFLL95(IGFLADV))
    
  ENDIF
  SELF(JBLK)%LASTCHUNK=.FALSE.
ENDDO
SELF(KGPBLKS)%LASTCHUNK=.TRUE.

WRITE(NULOUT,*)'OOPS_TRAJ TRAJ SEMILAG ALLOCATED '


IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD_OOPS:ALLOCATE_TRAJ_SLAG_OOPS',1,ZHOOK_HANDLE)
END SUBROUTINE ALLOCATE_TRAJ_SLAG_OOPS

!-----------------------------------------------------------------------

SUBROUTINE DEALLOCATE_TRAJ_SLAG_OOPS(SELF)
IMPLICIT NONE
TYPE(TRAJ_SLAG_TYPE), INTENT(INOUT) :: SELF(:)
INTEGER(KIND=JPIM) :: JBLK, IBLKS
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD_OOPS:DEALLOCATE_TRAJ_SLAG_OOPS',0,ZHOOK_HANDLE)

! IBLKS should be the same as that in the geometry used to create the trajectory
IBLKS = SIZE(SELF,1)

DO JBLK=1,IBLKS
  IF (ASSOCIATED(SELF(JBLK)%PUL95   )) DEALLOCATE(SELF(JBLK)%PUL95)
  IF (ASSOCIATED(SELF(JBLK)%PVL95   )) DEALLOCATE(SELF(JBLK)%PVL95)
  IF (ASSOCIATED(SELF(JBLK)%PTL95   )) DEALLOCATE(SELF(JBLK)%PTL95)
  IF (ASSOCIATED(SELF(JBLK)%PCL95   )) DEALLOCATE(SELF(JBLK)%PCL95)
  IF (ASSOCIATED(SELF(JBLK)%PUL05   )) DEALLOCATE(SELF(JBLK)%PUL05)
  IF (ASSOCIATED(SELF(JBLK)%PVL05   )) DEALLOCATE(SELF(JBLK)%PVL05)
  IF (ASSOCIATED(SELF(JBLK)%PTL05   )) DEALLOCATE(SELF(JBLK)%PTL05)
  IF (ASSOCIATED(SELF(JBLK)%PUT15   )) DEALLOCATE(SELF(JBLK)%PUT15)
  IF (ASSOCIATED(SELF(JBLK)%PVT15   )) DEALLOCATE(SELF(JBLK)%PVT15)
  IF (ASSOCIATED(SELF(JBLK)%PURL05  )) DEALLOCATE(SELF(JBLK)%PURL05)
  IF (ASSOCIATED(SELF(JBLK)%PVRL05  )) DEALLOCATE(SELF(JBLK)%PVRL05)
  IF (ASSOCIATED(SELF(JBLK)%PWRL05  )) DEALLOCATE(SELF(JBLK)%PWRL05)
  IF (ASSOCIATED(SELF(JBLK)%PURL5   )) DEALLOCATE(SELF(JBLK)%PURL5)
  IF (ASSOCIATED(SELF(JBLK)%PVRL5   )) DEALLOCATE(SELF(JBLK)%PVRL5)
  IF (ASSOCIATED(SELF(JBLK)%PWRL5   )) DEALLOCATE(SELF(JBLK)%PWRL5)
  IF (ASSOCIATED(SELF(JBLK)%PKAPPA5 )) DEALLOCATE(SELF(JBLK)%PKAPPA5)
  IF (ASSOCIATED(SELF(JBLK)%PKAPPAT5)) DEALLOCATE(SELF(JBLK)%PKAPPAT5)
  IF (ASSOCIATED(SELF(JBLK)%PTT15   )) DEALLOCATE(SELF(JBLK)%PTT15)
  IF (ASSOCIATED(SELF(JBLK)%PQT15   )) DEALLOCATE(SELF(JBLK)%PQT15)
  IF (ASSOCIATED(SELF(JBLK)%PWRL95  )) DEALLOCATE(SELF(JBLK)%PWRL95)
  IF (ASSOCIATED(SELF(JBLK)%PGFLL95 )) DEALLOCATE(SELF(JBLK)%PGFLL95)
  IF (ASSOCIATED(SELF(JBLK)%IGFLL95 )) DEALLOCATE(SELF(JBLK)%IGFLL95)
  IF (ASSOCIATED(SELF(JBLK)%PX95    )) DEALLOCATE(SELF(JBLK)%PX95)
  IF (ASSOCIATED(SELF(JBLK)%PUT95   )) DEALLOCATE(SELF(JBLK)%PUT95)
  IF (ASSOCIATED(SELF(JBLK)%PVT95   )) DEALLOCATE(SELF(JBLK)%PVT95)
  IF (ASSOCIATED(SELF(JBLK)%PSPNLT95)) DEALLOCATE(SELF(JBLK)%PSPNLT95)
  IF (ASSOCIATED(SELF(JBLK)%PUSI5   )) DEALLOCATE(SELF(JBLK)%PUSI5)
  IF (ASSOCIATED(SELF(JBLK)%PVSI5   )) DEALLOCATE(SELF(JBLK)%PVSI5)
  IF (ASSOCIATED(SELF(JBLK)%PSPL95  )) DEALLOCATE(SELF(JBLK)%PSPL95)
  IF (ASSOCIATED(SELF(JBLK)%PSPL05  )) DEALLOCATE(SELF(JBLK)%PSPL05)
ENDDO

IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD_OOPS:DEALLOCATE_TRAJ_SLAG_OOPS',1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_TRAJ_SLAG_OOPS

!-----------------------------------------------------------------------

SUBROUTINE CHECK_TRAJ_SLAG_OOPS(SELF, KBLKNUM)

USE,intrinsic :: IEEE_ARITHMETIC ! only in f2003 (and later); here to replace ISNAN (GNU-ext) ==> IEEE_IS_NAN

IMPLICIT NONE
TYPE(TRAJ_SLAG_TYPE), INTENT(IN) :: SELF
INTEGER(KIND=JPIM)  , INTENT(IN) :: KBLKNUM
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD_OOPS:CHECK_TRAJ_SLAG_OOPS',0,ZHOOK_HANDLE)

!!WRITE(0,*) 'checking for NaNs in semilag trajectory :'
IF (ANY(IEEE_IS_NAN(SELF%PUL95   ))) WRITE(0,*) 'semilag traj NaN in PUL95    in blk ',KBLKNUM 
IF (ANY(IEEE_IS_NAN(SELF%PVL95   ))) WRITE(0,*) 'semilag traj NaN in PVL95    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PTL95   ))) WRITE(0,*) 'semilag traj NaN in PTL95    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PCL95   ))) WRITE(0,*) 'semilag traj NaN in PCL95    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PUL05   ))) WRITE(0,*) 'semilag traj NaN in PUL05    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PVL05   ))) WRITE(0,*) 'semilag traj NaN in PVL05    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PTL05   ))) WRITE(0,*) 'semilag traj NaN in PTL05    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PUT15   ))) WRITE(0,*) 'semilag traj NaN in PUT15    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PVT15   ))) WRITE(0,*) 'semilag traj NaN in PVT15    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PURL05  ))) WRITE(0,*) 'semilag traj NaN in PURL05   in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PVRL05  ))) WRITE(0,*) 'semilag traj NaN in PVRL05   in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PWRL05  ))) WRITE(0,*) 'semilag traj NaN in PWRL05   in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PURL5   ))) WRITE(0,*) 'semilag traj NaN in PURL5    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PVRL5   ))) WRITE(0,*) 'semilag traj NaN in PVRL5    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PWRL5   ))) WRITE(0,*) 'semilag traj NaN in PWRL5    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PKAPPA5 ))) WRITE(0,*) 'semilag traj NaN in PKAPPA5) in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PKAPPAT5))) WRITE(0,*) 'semilag traj NaN in PKAPPAT5 in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PTT15   ))) WRITE(0,*) 'semilag traj NaN in PTT15    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PQT15   ))) WRITE(0,*) 'semilag traj NaN in PQT15    in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PWRL95  ))) WRITE(0,*) 'semilag traj NaN in PWRL95   in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PGFLL95 ))) WRITE(0,*) 'semilag traj NaN in PGFLL95  in blk ',KBLKNUM
IF (ANY(IEEE_IS_NAN(SELF%PX95    ))) WRITE(0,*) 'semilag traj NaN in PX95     in blk ',KBLKNUM
!!IF (ANY(ISNAN(SELF%PUT95   ))) WRITE(0,*) 'semilag traj NaN in PUT95'   !! these are all 2D traj arrays
!!IF (ANY(ISNAN(SELF%PVT95   ))) WRITE(0,*) 'semilag traj NaN in PVT95'
!!IF (ANY(ISNAN(SELF%PSPNLT95))) WRITE(0,*) 'semilag traj NaN in PSPNLT95'
!!IF (ANY(ISNAN(SELF%PUSI5   ))) WRITE(0,*) 'semilag traj NaN in PUSI5'
!!IF (ANY(ISNAN(SELF%PVSI5   ))) WRITE(0,*) 'semilag traj NaN in PVSI5'
!!IF (ANY(ISNAN(SELF%PSPL95  ))) WRITE(0,*) 'semilag traj NaN in PSPL95'
!!IF (ANY(ISNAN(SELF%PSPL05  ))) WRITE(0,*) 'semilag traj NaN in PSPL05'

IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD_OOPS:CHECK_TRAJ_SLAG_OOPS',1,ZHOOK_HANDLE)
END SUBROUTINE CHECK_TRAJ_SLAG_OOPS

!-----------------------------------------------------------------------

SUBROUTINE CH_ALLOC_TRAJ_SLAG_OOPS(SELF,YDDYN,KBLKNUM)
USE YOMDYN , ONLY : TDYN
IMPLICIT NONE
TYPE(TRAJ_SLAG_TYPE), INTENT(IN) :: SELF
TYPE(TDYN)          , INTENT(INOUT):: YDDYN
INTEGER(KIND=JPIM)  , INTENT(IN) :: KBLKNUM
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD_OOPS:CH_ALLOC_TRAJ_SLAG_OOPS',0,ZHOOK_HANDLE)

!!WRITE(0,*) 'checking for NaNs in semilag trajectory :'
IF ( .NOT. (ASSOCIATED(SELF%PUL95   ))) WRITE(0,*) 'Why isnt semilag traj PUL95    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PVL95   ))) WRITE(0,*) 'Why isnt semilag traj PVL95    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PTL95   ))) WRITE(0,*) 'Why isnt semilag traj PTL95    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PCL95   ))) WRITE(0,*) 'Why isnt semilag traj PCL95    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PUL05   ))) WRITE(0,*) 'Why isnt semilag traj PUL05    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PVL05   ))) WRITE(0,*) 'Why isnt semilag traj PVL05    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PTL05   ))) WRITE(0,*) 'Why isnt semilag traj PTL05    allocated in blk ',KBLKNUM
IF (YDDYN%LADVF.AND.YDDYN%L2TLFF .AND.  .NOT. (ASSOCIATED(SELF%PUT15   ))) &
     &  WRITE(0,*) 'WTF isnt semilag traj PUT15    allocated in blk ',KBLKNUM
IF (YDDYN%LADVF.AND.YDDYN%L2TLFF .AND. .NOT. (ASSOCIATED(SELF%PVT15   ))) &
     & WRITE(0,*) 'WTF isnt semilag traj PVT15    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PURL05  ))) WRITE(0,*) 'Why isnt semilag traj PURL05   allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PVRL05  ))) WRITE(0,*) 'Why isnt semilag traj PVRL05   allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PWRL05  ))) WRITE(0,*) 'Why isnt semilag traj PWRL05   allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PURL5   ))) WRITE(0,*) 'Why isnt semilag traj PURL5    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PVRL5   ))) WRITE(0,*) 'Why isnt semilag traj PVRL5    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PWRL5   ))) WRITE(0,*) 'Why isnt semilag traj PWRL5    allocated in blk ',KBLKNUM
IF (LSLHD.AND.(.NOT.LSLHD_STATIC) .AND.  .NOT. (ASSOCIATED(SELF%PKAPPA5 )))&
     & WRITE(0,*) 'WTF isnt semilag traj PKAPPA5) allocated in blk ',KBLKNUM
IF (LSLHD.AND.(.NOT.LSLHD_STATIC) .AND. YDDYN%LSLHDHEAT .AND.  .NOT. (ASSOCIATED(SELF%PKAPPAT5))) &
     & WRITE(0,*) 'WTF isnt semilag traj PKAPPAT5 allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PTT15   ))) WRITE(0,*) 'WTF isnt semilag traj PTT15    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PQT15   ))) WRITE(0,*) 'WTF isnt semilag traj PQT15    allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PWRL95  ))) WRITE(0,*) 'WTF isnt semilag traj PWRL95   allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PGFLL95 ))) WRITE(0,*) 'WTF isnt semilag traj PGFLL95  allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%IGFLL95 ))) WRITE(0,*) 'WTF isnt semilag traj IGFLL95  allocated in blk ',KBLKNUM
IF ( .NOT. (ASSOCIATED(SELF%PX95    ))) WRITE(0,*) 'WTF isnt semilag traj PX95     allocated in blk ',KBLKNUM

IF (LHOOK) CALL DR_HOOK('TRAJ_SEMILAG_MOD_OOPS:CH_ALLOC_TRAJ_SLAG_OOPS',1,ZHOOK_HANDLE)
END SUBROUTINE CH_ALLOC_TRAJ_SLAG_OOPS

!-----------------------------------------------------------------------

END MODULE TRAJ_SEMILAG_MOD_OOPS
