SUBROUTINE CPG_END_TRA (YDMF_PHYS_SURF, YDCPG_MISC, YDCPG_BNDS, PTRAJ_PHYS)


USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE CPG_TYPE_MOD, ONLY : CPG_MISC_TYPE
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE
USE YOMTRAJ  , ONLY : TRAJ_PHYS_TYPE


IMPLICIT NONE

TYPE(MF_PHYS_SURF_TYPE),INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(CPG_MISC_TYPE),    INTENT(INOUT) :: YDCPG_MISC
TYPE(CPG_BNDS_TYPE),    INTENT(IN)    :: YDCPG_BNDS
TYPE (TRAJ_PHYS_TYPE)  ,INTENT(INOUT) :: PTRAJ_PHYS




  PTRAJ_PHYS%PQSS1MF(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDCPG_MISC%QS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  PTRAJ_PHYS%PTS1MF(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_SURF%GSP_RR%PT_T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)



END SUBROUTINE
