SUBROUTINE CPG_GP_TENC (YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDVARS, YDMODEL, YDFIELDS)

USE PARKIND1, ONLY : JPIM, JPRB

USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE TYPE_MODEL         , ONLY : MODEL
USE FIELDS_MOD   ,ONLY : FIELDS


IMPLICIT NONE

TYPE(GEOMETRY)               ,INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE)          ,INTENT(IN)    :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE)          ,INTENT(IN)    :: YDCPG_OPTS
TYPE(FIELD_VARIABLES)        ,INTENT(INOUT) :: YDVARS
TYPE(MODEL)                  ,INTENT(INOUT) :: YDMODEL
TYPE(FIELDS)                 ,INTENT(INOUT) :: YDFIELDS

#include "abor1.intfb.h"
#include "etenc.intfb.h"


!*     1.1  TENDENCY COUPLING FOR SURFACE PRESSURE.
  
IF (.NOT.YDCPG_OPTS%LTWOTL) THEN
  CALL ABOR1('CPG_GP: ABOR1 CALLED: LTENC.AND..NOT.LTWOTL')
ENDIF

IF (YDCPG_OPTS%NSTEP > 0) THEN
  CALL ETENC(YDGEOMETRY, YDMODEL%YRML_GCONF%YRRIP, YDMODEL%YRML_LBC, YDFIELDS%YRELBC_FIELDS, YDCPG_OPTS%L_DFISTEP, &
  & YDCPG_BNDS%KFDIE, YDCPG_BNDS%KSTGLO, YDVARS%SP%T0, YDVARS%SP%DL, YDVARS%SP%DM, YDVARS%SP%T9, YDVARS%SP%DL9, YDVARS%SP%DM9)
ENDIF

END SUBROUTINE
