SUBROUTINE CPG_GP_TNDDDH (YDGEOMETRY, YDCPG_BNDS, YDCPG_DYN0, YDCPG_DYN9, YDVARS, YDMODEL, PGFL, PGMVTNDSL, PGFLTNDSL)

USE PARKIND1, ONLY : JPIM, JPRB

USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD   , ONLY : CPG_DYN_TYPE, CPG_MISC_TYPE, &
                          & CPG_TND_TYPE, CPG_GPAR_TYPE
USE CPG_TYPE_MOD   , ONLY : CPG_DYN_TYPE, CPG_MISC_TYPE, &
                          & CPG_TND_TYPE, CPG_GPAR_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE TYPE_MODEL         , ONLY : MODEL
USE YOMCT0, ONLY : LTWOTL, LNHDYN, LNHQE
USE YOMDYNA, ONLY : YRDYNA


IMPLICIT NONE

TYPE(GEOMETRY)               ,INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE)          ,INTENT(IN)    :: YDCPG_BNDS
TYPE(CPG_DYN_TYPE)           ,INTENT(INOUT) :: YDCPG_DYN0
TYPE(CPG_DYN_TYPE)           ,INTENT(INOUT) :: YDCPG_DYN9
TYPE(FIELD_VARIABLES)        ,INTENT(INOUT) :: YDVARS
TYPE(MODEL)                  ,INTENT(INOUT) :: YDMODEL
REAL(KIND=JPRB)              ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB)              ,INTENT(INOUT) :: PGMVTNDSL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,2+YDMODEL%YRML_GCONF%YRDIMF%NFTHER)
REAL(KIND=JPRB)              ,INTENT(INOUT) :: PGFLTNDSL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NUMFLDS)


INTEGER (KIND=JPIM) :: JGFL


!     ------------------------------------------------------------------

!*       7.    INITIALZE SL DDH TENDENCY ARRAYS.
!              ----------------------------------


IF (LTWOTL) THEN
  PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_U)=-YDVARS%U%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
  PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_V)=-YDVARS%V%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
  IF (YDMODEL%YRML_GCONF%YRDIMF%NFTHER > 0) PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_T)=-YDVARS%T%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
  IF (LNHDYN)THEN !!! ?????? ky: LNHDYN or LNHEE there?
    PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_PD)=-YDVARS%SPD%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
  ENDIF
  IF (LNHDYN)THEN
    PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_VD)=-YDVARS%SVD%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
    IF (YRDYNA%LNHX) PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_NHX)=-YDCPG_DYN0%NHX(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
  ENDIF
  DO JGFL=1,YDMODEL%YRML_GCONF%YGFL%NUMFLDS
    IF (YDMODEL%YRML_GCONF%YGFL%YCOMP(JGFL)%LADV) THEN
      PGFLTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,JGFL)=-PGFL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%YCOMP(JGFL)%MP)
    ENDIF
  ENDDO
ELSE
  PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_U)=-YDVARS%U%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
  PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_V)=-YDVARS%V%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
  IF (YDMODEL%YRML_GCONF%YRDIMF%NFTHER > 0) PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_T)=-YDVARS%T%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
  IF (LNHDYN)THEN !!! ?????? ky: LNHDYN or LNHEE there?
    PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_PD)=-YDVARS%SPD%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
  ENDIF
  IF (LNHDYN)THEN
    PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_VD)=-YDVARS%SVD%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
    IF (YRDYNA%LNHX) PGMVTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DIAG%YRMDDH%MSLDDH_NHX)=-YDCPG_DYN9%NHX(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG)
  ENDIF
  DO JGFL=1,YDMODEL%YRML_GCONF%YGFL%NUMFLDS
    IF (YDMODEL%YRML_GCONF%YGFL%YCOMP(JGFL)%LADV) THEN
      PGFLTNDSL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,JGFL)=-PGFL(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDIF
  ENDDO
ENDIF


END SUBROUTINE
