SUBROUTINE CPG_DIA_FLU (YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF, &
                      & YDVARS, YDCFU, YDXFU, YDMODEL)

USE PARKIND1, ONLY : JPIM, JPRB

USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_DYN_TYPE, CPG_MISC_TYPE, CPG_TND_TYPE, CPG_GPAR_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_DYN_TYPE, CPG_MISC_TYPE, CPG_TND_TYPE, CPG_GPAR_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE YOMCFU             , ONLY : TCFU
USE YOMXFU             , ONLY : TXFU
USE TYPE_MODEL         , ONLY : MODEL
USE YOMCT0             , ONLY : LAROME
USE YOMINI             , ONLY : LINITER
USE YOMLUN             , ONLY : NULOUT


IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE),INTENT(IN)   :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE),INTENT(INOUT):: YDCPG_MISC
TYPE(MF_PHYS_TYPE),INTENT(INOUT) :: YDMF_PHYS
TYPE(CPG_DYN_TYPE),INTENT(INOUT) :: YDCPG_DYN0
TYPE(MF_PHYS_SURF_TYPE),INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
TYPE(TCFU)        ,INTENT(INOUT) :: YDCFU
TYPE(TXFU)        ,INTENT(INOUT) :: YDXFU
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL

#include "abor1.intfb.h"
#include "cpcfu.intfb.h"
#include "cpxfu.intfb.h"
#include "cumcpl.intfb.h"
#include "cpcls_assim.intfb.h"

INTEGER(KIND=JPIM) :: ILEVCO
LOGICAL :: LLCALL_CPCFU
LOGICAL :: LLCALL_CPXFU
LOGICAL :: LLCALL_CUMCPLDM
REAL(KIND=JPRB) :: ZDPRECIPS(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC)
REAL(KIND=JPRB) :: ZDPRECIPS2(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC2)
REAL(KIND=JPRB) :: ZSTRCU(YDGEOMETRY%YRDIM%NPROMM,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZSTRCV(YDGEOMETRY%YRDIM%NPROMM,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZSTRDU(YDGEOMETRY%YRDIM%NPROMM,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZSTRDV(YDGEOMETRY%YRDIM%NPROMM,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZSTRTU(YDGEOMETRY%YRDIM%NPROMM,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZSTRTV(YDGEOMETRY%YRDIM%NPROMM,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZUGST(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) :: ZVGST(YDGEOMETRY%YRDIM%NPROMM)

REAL(KIND=JPRB) :: ZUCLS(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) :: ZNUCLS(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) :: ZVCLS(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) :: ZNVCLS(YDGEOMETRY%YRDIM%NPROMM)

INTEGER (KIND=JPIM) :: JLEV


!     ------------------------------------------------------------------

!*       2.    CFU AND XFU:
!              ------------

!*    2.1   DEFINE THE CONDITIONS OF CALLING SOME ROUTINES.

LLCALL_CPCFU=&
 & YDCFU%LCUMFU.AND.(.NOT.LINITER).AND.(.NOT.YDCPG_OPTS%LCONFX).AND.(.NOT.YDMODEL%YRML_PHY_EC%YREPHY%LAGPHY)
LLCALL_CPXFU=YDXFU%LXFU.AND.YDCPG_OPTS%LDIAB.AND.(.NOT.LINITER).AND..NOT.YDCPG_OPTS%L_DFISTEP
LLCALL_CUMCPLDM= (&
 & YDMODEL%YRML_AOC%YRMCC%NFRCPL /= 0).AND.(YDMODEL%YRML_AOC%YRMCC%NFRCPL <= YDMODEL%YRML_GCONF%YRRIP%NSTOP).AND.(.NOT.YDCPG_OPTS%LCONFX).AND.(.NOT.YDMODEL%YRML_PHY_EC%YREPHY%LAGPHY).AND.(.NOT.LAROME)
! Check that if NPROMM /= NPROMA, all these LLCALL... keys are .F.:
IF ((LLCALL_CPCFU.OR.LLCALL_CPXFU.OR.LLCALL_CUMCPLDM)&
 & .AND.(YDGEOMETRY%YRDIM%NPROMM /= YDGEOMETRY%YRDIM%NPROMA)) THEN
  WRITE(NULOUT,*) ' CPG_DIA part 2: if NPROMM /= NPROMA,'
  WRITE(NULOUT,*) '  all the LLCALL_... keys must be equal to .F.'
  WRITE(NULOUT,*) '  Check the calculation of these keys.'
  WRITE(NULOUT,*) '  In particular, in adiabatic runs, CFU, XFU'
  WRITE(NULOUT,*) '  and cumul of coupled fields MUST NOT be called.'
  CALL ABOR1(' CPG_DIA: ABOR1 CALLED')
ENDIF

!*    2.2   DIVIDE SOME QUANTITIES LINKED TO (U,V) BY THE MAPPING FACTOR.

! * ZSTR.. arrays are used for CFU, XFU and in CUMCPL.
IF (LLCALL_CPCFU.OR.LLCALL_CPXFU.OR.LLCALL_CUMCPLDM) THEN
  DO JLEV=0,YDGEOMETRY%YRDIMV%NFLEVG
    ZSTRCU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS%OUT%STRCU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
    ZSTRCV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS%OUT%STRCV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
    ZSTRDU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS%OUT%STRDU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
    ZSTRDV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS%OUT%STRDV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
    ZSTRTU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS%OUT%STRTU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
    ZSTRTV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=YDMF_PHYS%OUT%STRTV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)
  ENDDO
ENDIF

! * Z(U,V)CLS and Z(U,V)GST are used for XFU.
IF (LLCALL_CPXFU .OR. YDMODEL%YRML_PHY_G%YRDPHY%LDIRCLSMOD) THEN
  ZUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS%OUT%UCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ZVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS%OUT%VCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ZNUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS%OUT%NUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ZNVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS%OUT%NVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ZUGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS%OUT%UGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ZVGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS%OUT%VGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF

! * Divide the arrays by the mapping factor for the cases
!   where the quantities to diagnose are the reduced ones.
!!! -- Test to be checked, seems suspicious -- !!!
IF (YDCPG_OPTS%LDIAB.OR.(YDMODEL%YRML_PHY_MF%YRSIMPHL%LSIMPH.AND.(.NOT.YDMODEL%YRML_PHY_MF%YRSIMPHL%LTRAJPS))) THEN  
  IF (LLCALL_CPCFU.OR.LLCALL_CPXFU.OR.LLCALL_CUMCPLDM) THEN
    DO JLEV=0,YDGEOMETRY%YRDIMV%NFLEVG
      ZSTRCU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRCU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
      ZSTRCV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRCV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
      ZSTRDU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRDU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
      ZSTRDV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRDV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
      ZSTRTU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRTU(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
      ZSTRTV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)=ZSTRTV(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ENDDO
  ENDIF
  IF (LLCALL_CPXFU .OR. YDMODEL%YRML_PHY_G%YRDPHY%LDIRCLSMOD) THEN
    ZUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ZVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ZNUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZNUCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ZNVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZNVCLS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ZUGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZUGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
    ZVGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=ZVGST(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)/YDGEOMETRY%YRGSGEOM(YDCPG_BNDS%KBL)%GM(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ENDIF
ENDIF

!*    2.3   CUMUL OF FLUX DIAGNOSTICS

IF(LLCALL_CPCFU)THEN  
  CALL CPCFU(YDGEOMETRY, YDCFU, YDMODEL%YRML_GCONF%YRRIP, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_BNDS%KIDIE, YDCPG_BNDS%KFDIE,                &
  & YDCPG_BNDS%KSTGLO, YDCPG_OPTS%LFSTEP, YDMF_PHYS%OUT%DIFCQ, YDMF_PHYS%OUT%DIFCS, YDMF_PHYS%OUT%DIFTQ, YDMF_PHYS%OUT%DIFTS,          &
  & YDMF_PHYS%OUT%FCCQL, YDMF_PHYS%OUT%FCCQN, YDMF_PHYS%OUT%FCSQL, YDMF_PHYS%OUT%FCSQN, YDMF_PHYS%OUT%FPLCL,                  &
  & YDMF_PHYS%OUT%FPLCN, YDMF_PHYS%OUT%FPLCG, YDMF_PHYS%OUT%FPLCH, YDMF_PHYS%OUT%FPLSL, YDMF_PHYS%OUT%FPLSN,                  &
  & YDMF_PHYS%OUT%FPLSG, YDMF_PHYS%OUT%FPLSH, YDMF_PHYS%OUT%FRMH, YDMF_PHYS%OUT%FRSO, YDMF_PHYS%OUT%FRSOC,                    &
  & YDMF_PHYS%OUT%FRTH, YDMF_PHYS%OUT%FRTHC, YDMF_PHYS%OUT%FDIS(:, YDGEOMETRY%YRDIMV%NFLEVG), ZSTRCU, ZSTRCV, ZSTRDU,                           &
  & ZSTRDV, ZSTRTU, ZSTRTV, YDCPG_DYN0%XYB%DELP, YDCPG_MISC%NEB, YDCPG_MISC%QICE, YDCPG_MISC%QLI, YDCPG_DYN0%PRE(1:, YDGEOMETRY%YRDIMV%NFLEVG), &
  & YDMF_PHYS_SURF%GSP_SG%PF_T0, YDVARS%O3%T0, YDVARS%Q%T0, YDMF_PHYS_SURF%GSP_RR%PW_T0, YDMF_PHYS%OUT%FEVL,                  &
  & YDMF_PHYS%OUT%FEVN, YDCPG_MISC%CLCT, YDMF_PHYS%OUT%CLCH, YDMF_PHYS%OUT%CLCM, YDMF_PHYS%OUT%CLCL,                          &
  & YDMF_PHYS%OUT%CLCC, YDMF_PHYS%OUT%FCLL, YDMF_PHYS%OUT%FCLN, YDMF_PHYS%OUT%FCS, YDMF_PHYS%OUT%FONTE,                       &
  & YDMF_PHYS%OUT%FCHSP, YDMF_PHYS%OUT%FLWSP, YDMF_PHYS%OUT%RUISS, YDMF_PHYS%OUT%RUISP, YDMF_PHYS%OUT%FEVV,                   &
  & YDMF_PHYS%OUT%FTR, YDMF_PHYS%OUT%RUISL, YDMF_PHYS%OUT%FGEL, YDMF_PHYS%OUT%FGELS, YDMF_PHYS%OUT%FRSODS,                    &
  & YDMF_PHYS%OUT%FRSOPS, YDMF_PHYS%OUT%FRSOPT, YDMF_PHYS%OUT%FRSOLU, YDMF_PHYS%OUT%FRTHDS, YDMF_PHYS%OUT%FRSDNI,             &
  & YDMF_PHYS%OUT%FRSGNI, YDMF_PHYS%OUT%FLASH)
ENDIF

IF(LLCALL_CUMCPLDM) THEN  
  ILEVCO=YDGEOMETRY%YRDIMV%NFLEVG
  CALL CUMCPL(YDGEOMETRY%YRDIM, YDMODEL%YRML_GCONF%YRRIP, YDMODEL%YRML_PHY_MF%YRPHY, ILEVCO, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_BNDS%KSTGLO,             &
  & YDMODEL%YRML_PHY_G%YRDPHY%NTSSG, ZSTRTU(1, YDGEOMETRY%YRDIMV%NFLEVG), ZSTRTV(1, YDGEOMETRY%YRDIMV%NFLEVG), YDMF_PHYS%OUT%FRTH, YDMF_PHYS%OUT%FRSO, YDMF_PHYS%OUT%FCLL,             &
  & YDMF_PHYS%OUT%FCLN, YDMF_PHYS%OUT%FCS, YDMF_PHYS%OUT%FEVL, YDMF_PHYS%OUT%FEVN, YDMF_PHYS%OUT%FPLCL(:, YDGEOMETRY%YRDIMV%NFLEVG),       &
  & YDMF_PHYS%OUT%FPLCN(:, YDGEOMETRY%YRDIMV%NFLEVG), YDMF_PHYS%OUT%FPLSL(:, YDGEOMETRY%YRDIMV%NFLEVG), YDMF_PHYS%OUT%FPLSN(:, YDGEOMETRY%YRDIMV%NFLEVG), YDMF_PHYS%OUT%RUISS, &
  & YDMF_PHYS%OUT%RUISP, YDMF_PHYS_SURF%GSP_RR%PT_T0, YDMF_PHYS%OUT%DRNSHF, YDMF_PHYS%OUT%ALB, ZUCLS,                    &
  & ZVCLS)
ENDIF

!*    2.5   INTERFACE FOR INSTANTANEOUS FLUXES

IF (LLCALL_CPXFU) THEN
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS) THEN
    ZDPRECIPS(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC)=YDMF_PHYS_SURF%GSD_XP%PPRECIP(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC)
  ENDIF
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LDPRECIPS2) THEN
    ZDPRECIPS2(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC2)=YDMF_PHYS_SURF%GSD_XP2%PPRECIP2(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS%NDTPREC2)
  ENDIF
  CALL CPXFU(YDGEOMETRY, YDXFU, YDMODEL%YRML_PHY_MF%YRPHY%YRDPRECIPS, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_BNDS%KIDIE,               &
  & YDCPG_BNDS%KFDIE, YDCPG_BNDS%KSTGLO, YDMF_PHYS%OUT%DIFCQ, YDMF_PHYS%OUT%DIFCS, YDMF_PHYS%OUT%DIFTQ,               &
  & YDMF_PHYS%OUT%DIFTS, YDMF_PHYS%OUT%FPLCL, YDMF_PHYS%OUT%FPLCN, YDMF_PHYS%OUT%FPLCG, YDMF_PHYS%OUT%FPLCH,          &
  & YDMF_PHYS%OUT%FPLSL, YDMF_PHYS%OUT%FPLSN, YDMF_PHYS%OUT%FPLSG, YDMF_PHYS%OUT%FPLSH, YDMF_PHYS%OUT%FRSO,           &
  & YDMF_PHYS%OUT%FRTH, YDCPG_MISC%CLCT, ZSTRCU, ZSTRCV, ZSTRDU, ZSTRDV, ZSTRTU, ZSTRTV, YDCPG_MISC%NEB,              &
  & YDCPG_MISC%QICE, YDCPG_MISC%QLI, ZUCLS, ZVCLS, ZNUCLS, ZNVCLS, YDMF_PHYS%OUT%TCLS, YDMF_PHYS%OUT%QCLS,            &
  & YDMF_PHYS%OUT%RHCLS, YDMF_PHYS%OUT%CLCH, YDMF_PHYS%OUT%CLCM, YDMF_PHYS%OUT%CLCL, YDMF_PHYS%OUT%CLCC,              &
  & YDMF_PHYS%OUT%FCS, YDMF_PHYS%OUT%FONTE, YDMF_PHYS%OUT%FCHSP, YDMF_PHYS%OUT%FLWSP, YDMF_PHYS%OUT%FEVL,             &
  & YDMF_PHYS%OUT%RUISP, YDMF_PHYS%OUT%RUISS, YDMF_PHYS%OUT%CAPE, YDMF_PHYS%OUT%CTOP, YDMF_PHYS%OUT%MOCON,            &
  & YDMF_PHYS%OUT%CLPH, YDMF_PHYS%OUT%VEIN, ZUGST, ZVGST, YDMF_PHYS%OUT%FEVV, YDMF_PHYS%OUT%FTR, YDMF_PHYS%OUT%RUISL, &
  & YDMF_PHYS%OUT%DIAGH, YDMF_PHYS%OUT%MRT, YDMF_PHYS%OUT%VISICLD, YDMF_PHYS%OUT%VISIHYD, YDMF_PHYS%OUT%MXCLWC,       &
  & YDMF_PHYS%OUT%TPWCLS, ZDPRECIPS, ZDPRECIPS2)
ENDIF

!*    2.6   INTERFACE FOR CLS FIELDS FOR ASSIMILATION

IF (YDMODEL%YRML_PHY_G%YRDPHY%LDIRCLSMOD) THEN
  CALL CPCLS_ASSIM(YDGEOMETRY, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDMF_PHYS_SURF%GSP_CL%PUCLS_T1,             &
  & YDMF_PHYS_SURF%GSP_CL%PVCLS_T1, YDMF_PHYS_SURF%GSP_CL%PNUCLS_T1, YDMF_PHYS_SURF%GSP_CL%PNVCLS_T1,                  &
  & YDMF_PHYS_SURF%GSP_CL%PTCLS_T1, YDMF_PHYS_SURF%GSP_CL%PHUCLS_T1, ZUCLS, ZVCLS, ZNUCLS, ZNVCLS, YDMF_PHYS%OUT%TCLS, &
  & YDMF_PHYS%OUT%RHCLS)
ENDIF

END SUBROUTINE
