SUBROUTINE CPG_END_SPR (YDVARS, YDCPG_BNDS, YDCPG_OPTS)


USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE


IMPLICIT NONE

TYPE(FIELD_VARIABLES)  ,INTENT(INOUT) :: YDVARS
TYPE(CPG_BNDS_TYPE),    INTENT(IN)    :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),    INTENT(IN)    :: YDCPG_OPTS


!*    4.    SURFACE PRESSURE AND ITS DERIVATIVES.
!           -------------------------------------

IF (YDCPG_OPTS%LTWOTL) THEN
  YDVARS%SP%T9  (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA) = YDVARS%SP%T0 (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  YDVARS%SP%DL9 (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA) = YDVARS%SP%DL (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  YDVARS%SP%DM9 (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA) = YDVARS%SP%DM (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF

END SUBROUTINE
