SUBROUTINE CPUTQY_AROME_EXPL(YDMF_PHYS_NEXT_STATE, YDVARS, YDMODEL, YDDIMV, &
 & YDCPG_DIM, PDT, &
 & PTENDQ, PTENDL, PTENDR, PTENDI, PTENDS, PTENDG, PTENDH, PTENDTKE, &
 !  Variables 2D Input
 & PTENDT, PTENDU, PTENDV, PTENDD)
 !  Variables 2D In/Out

!     --------------------------------------------
!**** *CPUTQY_AROME_EXPL*  EVOLUTION DE T,  et des  QI et de la TKE
!     --------------------------------------------

!     ARGUMENTS D'ENTREE
!     ------------------
!       KPROMA : DIMENSION HORIZONTALE
!       KSTART : DEBUT DE LA BOUCLE HORIZONTALE
!       KPROF : BORNE HORIZONTALE DES CALCULS
!       KFLEV : DIMENSION ET BORNE VERTICALE
!       KFLDN, KFLDX : SECONDE DIMENSION de PEXT1 (/= selon SL ou pas)
!       PDT : PAS DE TEMPS EFFECTIF

!       PTTS (KPROMA,KFLEV) : TENDANCE DE TEMPERATURE 
!       PRS ( KPROMA,KFLEV,NRR ) : TENDANCE DES Qi

!     ARGUMENTS IMPLICITES
!     --------------------

!     SORTIES
!     -------
!       PTT1(NPROMA,KFLEV): VARIABLES A FAIRE EVOLUER
!       PNEBH (NVCLIN_AROME): tableau contenant les Qi a faire evoluer
!       PQV1 : Qv au temps 1
!       PQL1 : Ql au temps 1
!       PQI1 : Qi au temps 1

!     Modifications
!     -------------
!   03/03/03 Creation par Y. Seity et S. Malardel
!   04/07/27 Modif par G. Hello (to run Hydrostatic case)
!   05/09/28 Modif par Y. Seity (Add PTENDEXT)
!   25-Jan-08 K. Yessad: bug correction for EXT.
!   N. Wedi and K. Yessad (Jan 2008): different dev for NH model and PC scheme
!      07/12/18 Modif par Y. Seity (Add Hail PQH1)
!   26-Apr-2010 Modif par Y.Bouteloup (Only one call to cputqy_arome in mf_phys)
!   29-Apr-2019 R. El Khatib Use PTENDGFLR + pointer adresses KPTR to avoid a big array copy
!   18-Feb-2020 Y. Seity bf for non advected prognostic GFL (IF ordering)
! ----------------------------------------------------------------------------

USE YOMDIMV   , ONLY : TDIMV
USE YOMGMV    , ONLY : TGMV
USE PARKIND1  , ONLY : JPIM, JPRB
USE YOMHOOK   , ONLY : LHOOK, DR_HOOK
USE YOMCT0    , ONLY : LNHDYN, LSLAG
USE TYPE_MODEL, ONLY : MODEL
USE CPG_DIM_TYPE_MOD, ONLY : CPG_DIM_TYPE
USE MF_PHYS_NEXT_STATE_TYPE_MOD &
               , ONLY : MF_PHYS_NEXT_STATE_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES

! ----------------------------------------------------------------------------

IMPLICIT NONE

TYPE (MF_PHYS_NEXT_STATE_TYPE), INTENT(INOUT) :: YDMF_PHYS_NEXT_STATE
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL
TYPE(TDIMV)       ,INTENT(IN)    :: YDDIMV
TYPE(CPG_DIM_TYPE),INTENT(IN)    :: YDCPG_DIM
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDT 
REAL(KIND=JPRB),   INTENT(IN)    :: PTENDQ (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)  
REAL(KIND=JPRB),   INTENT(IN)    :: PTENDL (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)  
REAL(KIND=JPRB),   INTENT(IN)    :: PTENDR (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)  
REAL(KIND=JPRB),   INTENT(IN)    :: PTENDI (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)  
REAL(KIND=JPRB),   INTENT(IN)    :: PTENDS (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)  
REAL(KIND=JPRB),   INTENT(IN)    :: PTENDG (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)  
REAL(KIND=JPRB),   INTENT(IN)    :: PTENDTKE (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)  
REAL(KIND=JPRB),   INTENT(IN)    :: PTENDH (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)  
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTENDT(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTENDU(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTENDV(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTENDD(YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG) 

#include "cputqy0.intfb.h"

REAL(KIND=JPRB) :: ZHOOK_HANDLE

! ----------------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('CPUTQY_AROME_EXPL',0,ZHOOK_HANDLE)

CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%U, PDT, YDMF_PHYS_NEXT_STATE%U, PTENDU)
CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%V, PDT, YDMF_PHYS_NEXT_STATE%V, PTENDV)
CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%T, PDT, YDMF_PHYS_NEXT_STATE%T, PTENDT)

IF (LNHDYN) THEN
  CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%SVD, PDT, YDMF_PHYS_NEXT_STATE%SVD, PTENDD)
ENDIF

IF (YDVARS%L%LT1)     CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%L,   PDT, YDMF_PHYS_NEXT_STATE%L,     PTENDL)
IF (YDVARS%I%LT1)     CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%I,   PDT, YDMF_PHYS_NEXT_STATE%I,     PTENDI)
IF (YDVARS%S%LT1)     CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%S,   PDT, YDMF_PHYS_NEXT_STATE%S,     PTENDS)
IF (YDVARS%R%LT1)     CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%R,   PDT, YDMF_PHYS_NEXT_STATE%R,     PTENDR)
IF (YDVARS%G%LT1)     CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%G,   PDT, YDMF_PHYS_NEXT_STATE%G,     PTENDG)
IF (YDVARS%H%LT1)     CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%H,   PDT, YDMF_PHYS_NEXT_STATE%H,     PTENDH)
IF (YDVARS%TKE%LT1)   CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%TKE, PDT, YDMF_PHYS_NEXT_STATE%TKE,   PTENDTKE)
IF (YDVARS%Q%LT1)     CALL CPUTQY0 (YDCPG_DIM, YDCPG_DIM%VARS%Q,   PDT, YDMF_PHYS_NEXT_STATE%Q,     PTENDQ)

! ----------------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('CPUTQY_AROME_EXPL',1,ZHOOK_HANDLE)
END SUBROUTINE CPUTQY_AROME_EXPL
