SUBROUTINE CPUTQY0 (LDT1, YDCPG_BNDS, YDCPG_OPTS, YDCPG_DIMS_VAR, PDT, PVAR, PTND)

!**** *CPUTQY0*  

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 28-04-2021

USE YOMHOOK, ONLY : LHOOK, DR_HOOK

USE PARKIND1, ONLY : JPRB, JPIM
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_DIM_VAR_TYPE, CPG_OPTS_TYPE

IMPLICIT NONE

LOGICAL,                 INTENT (IN)    :: LDT1
TYPE (CPG_BNDS_TYPE),    INTENT (IN)    :: YDCPG_BNDS
TYPE (CPG_OPTS_TYPE),    INTENT (IN)    :: YDCPG_OPTS
TYPE (CPG_DIM_VAR_TYPE), INTENT (IN)    :: YDCPG_DIMS_VAR
REAL (KIND=JPRB),        INTENT (IN)    :: PDT
REAL (KIND=JPRB),        INTENT (INOUT) :: PVAR (YDCPG_OPTS%KLON,YDCPG_DIMS_VAR%ILEVT1I:YDCPG_DIMS_VAR%ILEVT1F)
REAL (KIND=JPRB),        INTENT (IN)    :: PTND (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)

INTEGER (KIND=JPIM) :: JLEV, JLON

REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPUTQY0', 0, ZHOOK_HANDLE) 

IF (LDT1) THEN

!=PARALLEL

  DO JLEV = 1, YDCPG_OPTS%KFLEVG
    DO JLON = YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
      PVAR (JLON, JLEV) = PVAR (JLON, JLEV) + PDT * PTND (JLON, JLEV)
    ENDDO
  ENDDO

!=END PARALLEL

ENDIF

IF (LHOOK) CALL DR_HOOK ('CPUTQY0', 1, ZHOOK_HANDLE) 

END SUBROUTINE


