SUBROUTINE CPUTQY0 (YDCPG_DIM, YDCPG_OPTS, YDCPG_DIM_VAR, PDT, PVAR, PTND)

USE PARKIND1, ONLY : JPRB, JPIM
USE CPG_DIM_TYPE_MOD, ONLY : CPG_DIM_TYPE, CPG_DIM_VAR_TYPE, CPG_OPTS_TYPE

IMPLICIT NONE

TYPE (CPG_DIM_TYPE),     INTENT(IN)     :: YDCPG_DIM
TYPE (CPG_OPTS_TYPE),    INTENT(IN)     :: YDCPG_OPTS
TYPE (CPG_DIM_VAR_TYPE), INTENT(IN)     :: YDCPG_DIM_VAR
REAL (KIND=JPRB),        INTENT (IN)    :: PDT
REAL (KIND=JPRB),        INTENT (INOUT) :: PVAR (YDCPG_DIM%KLON,YDCPG_DIM_VAR%ILEVT1I:YDCPG_DIM_VAR%ILEVT1F)
REAL (KIND=JPRB),        INTENT (IN)    :: PTND (YDCPG_DIM%KLON,YDCPG_DIM%KFLEVG)

INTEGER (KIND=JPIM) :: JLEV, JROF

DO JLEV = 1, YDCPG_DIM%KFLEVG
  DO JROF = YDCPG_DIM%KIDIA, YDCPG_DIM%KFDIA
    PVAR (JROF, JLEV) = PVAR (JROF, JLEV) + PDT * PTND (JROF, JLEV)
  ENDDO
ENDDO

END SUBROUTINE


