!OCL  NOEVAL
SUBROUTINE GPGRGEO(&
 ! --- INPUT -----------------------------------------------------------------
 & YDGEOMETRY,KPROMA,KD,KF,KFLEV,&
 & PRT,PRTL,PRTM,&
 & PLNPR,PALPH,PXYBDER,&
 & POROGL,POROGM,&
 ! --- OUTPUT ----------------------------------------------------------------
 & PHIFL,PHIFM,PHIHL,PHIHM,&
 ! --- OPTIONAL INPUT --------------------------------------------------------
 & LDNHEE,PRNHPPI,PQCHAL,PQCHAM,&
 ! --- OPTIONAL OUTPUT -------------------------------------------------------
 & PNH1L,PNH1M)

!**** *GPGRGEO* - Computes half and full level gradient of geopotential height "gz".

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE YOMCVER      , ONLY : LVERTFE
USE INTDYN_MOD   , ONLY : YYTXYBDER

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY),    INTENT(IN)    :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROMA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KD 
INTEGER(KIND=JPIM),INTENT(IN)    :: KF 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRT(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRTL(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRTM(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLNPR(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PALPH(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXYBDER(KPROMA,KFLEV,YYTXYBDER%NDIM)
REAL(KIND=JPRB)   ,INTENT(IN)    :: POROGL(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: POROGM(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PHIFL(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PHIFM(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PHIHL(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PHIHM(KPROMA,0:KFLEV) 
LOGICAL,OPTIONAL,INTENT(IN)          :: LDNHEE
REAL(KIND=JPRB),OPTIONAL,INTENT(IN)  :: PRNHPPI(KPROMA,KFLEV) 
REAL(KIND=JPRB),OPTIONAL,INTENT(IN)  :: PQCHAL(KPROMA,KFLEV) 
REAL(KIND=JPRB),OPTIONAL,INTENT(IN)  :: PQCHAM(KPROMA,KFLEV) 
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PNH1L(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PNH1M(KPROMA,KFLEV)

!     ------------------------------------------------------------------

#include "gpgrgeo_expl.intfb.h"

REAL (KIND=JPRB) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('GPGRGEO',0,ZHOOK_HANDLE)

CALL GPGRGEO_EXPL(&
 & YDGEOMETRY,KPROMA,KD,KF,KFLEV,&
 & PRT,PRTL,PRTM,&
 & PLNPR,PALPH,&
 & POROGL,POROGM,&
 & PHIFL,PHIFM,PHIHL,PHIHM,&
 & LDNHEE,PRNHPPI,PQCHAL,PQCHAM,&
 & PNH1L,PNH1M,&
 & PXYBDER(:,:,YYTXYBDER%M_LNPRL), PXYBDER(:,:,YYTXYBDER%M_LNPRM), &
 & PXYBDER(:,:,YYTXYBDER%M_ALPHL), PXYBDER(:,:,YYTXYBDER%M_ALPHM))


!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('GPGRGEO',1,ZHOOK_HANDLE)

END SUBROUTINE GPGRGEO
