
SUBROUTINE GPMPFC_EXPL_PART2 (YDVARS, YDML_GCONF, KPROMA, KFLEV, KST, KEN, PGM, PGFL)

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK,  ONLY: LHOOK, DR_HOOK

USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE FIELD_VARIABLES_MOD    , ONLY : FIELD_VARIABLES

IMPLICIT NONE

TYPE(FIELD_VARIABLES)        ,INTENT(INOUT) :: YDVARS
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN):: YDML_GCONF
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KEN
REAL(KIND=JPRB),INTENT(IN) :: PGM(KPROMA)
REAL(KIND=JPRB),INTENT(INOUT) :: PGFL(KPROMA,KFLEV,YDML_GCONF%YGFL%NDIM)

INTEGER (KIND=JPIM) :: JGFL
INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF

REAL(KIND=JPRB) :: ZHOOK

IF (LHOOK) CALL DR_HOOK("GPMPFC_EXPL_PART2",0,ZHOOK)

IF (YDVARS%Q%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%Q%DM (JROF,JLEV) = YDVARS%Q%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%Q%DL (JROF,JLEV) = YDVARS%Q%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%I%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%I%DM (JROF,JLEV) = YDVARS%I%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%I%DL (JROF,JLEV) = YDVARS%I%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%L%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%L%DM (JROF,JLEV) = YDVARS%L%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%L%DL (JROF,JLEV) = YDVARS%L%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%LCONV%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%LCONV%DM (JROF,JLEV) = YDVARS%LCONV%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%LCONV%DL (JROF,JLEV) = YDVARS%LCONV%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%ICONV%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%ICONV%DM (JROF,JLEV) = YDVARS%ICONV%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%ICONV%DL (JROF,JLEV) = YDVARS%ICONV%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%RCONV%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%RCONV%DM (JROF,JLEV) = YDVARS%RCONV%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%RCONV%DL (JROF,JLEV) = YDVARS%RCONV%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%SCONV%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%SCONV%DM (JROF,JLEV) = YDVARS%SCONV%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%SCONV%DL (JROF,JLEV) = YDVARS%SCONV%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%IRAD%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%IRAD%DM (JROF,JLEV) = YDVARS%IRAD%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%IRAD%DL (JROF,JLEV) = YDVARS%IRAD%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%LRAD%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%LRAD%DM (JROF,JLEV) = YDVARS%LRAD%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%LRAD%DL (JROF,JLEV) = YDVARS%LRAD%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%S%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%S%DM (JROF,JLEV) = YDVARS%S%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%S%DL (JROF,JLEV) = YDVARS%S%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%R%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%R%DM (JROF,JLEV) = YDVARS%R%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%R%DL (JROF,JLEV) = YDVARS%R%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%G%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%G%DM (JROF,JLEV) = YDVARS%G%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%G%DL (JROF,JLEV) = YDVARS%G%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%H%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%H%DM (JROF,JLEV) = YDVARS%H%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%H%DL (JROF,JLEV) = YDVARS%H%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%TKE%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%TKE%DM (JROF,JLEV) = YDVARS%TKE%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%TKE%DL (JROF,JLEV) = YDVARS%TKE%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%TTE%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%TTE%DM (JROF,JLEV) = YDVARS%TTE%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%TTE%DL (JROF,JLEV) = YDVARS%TTE%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%EFB1%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%EFB1%DM (JROF,JLEV) = YDVARS%EFB1%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%EFB1%DL (JROF,JLEV) = YDVARS%EFB1%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%EFB2%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%EFB2%DM (JROF,JLEV) = YDVARS%EFB2%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%EFB2%DL (JROF,JLEV) = YDVARS%EFB2%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%EFB3%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%EFB3%DM (JROF,JLEV) = YDVARS%EFB3%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%EFB3%DL (JROF,JLEV) = YDVARS%EFB3%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%A%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%A%DM (JROF,JLEV) = YDVARS%A%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%A%DL (JROF,JLEV) = YDVARS%A%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%O3%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%O3%DM (JROF,JLEV) = YDVARS%O3%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%O3%DL (JROF,JLEV) = YDVARS%O3%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%SRC%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%SRC%DM (JROF,JLEV) = YDVARS%SRC%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%SRC%DL (JROF,JLEV) = YDVARS%SRC%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%MXL%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%MXL%DM (JROF,JLEV) = YDVARS%MXL%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%MXL%DL (JROF,JLEV) = YDVARS%MXL%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%SHTUR%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%SHTUR%DM (JROF,JLEV) = YDVARS%SHTUR%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%SHTUR%DL (JROF,JLEV) = YDVARS%SHTUR%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%FQTUR%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%FQTUR%DM (JROF,JLEV) = YDVARS%FQTUR%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%FQTUR%DL (JROF,JLEV) = YDVARS%FQTUR%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%FSTUR%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%FSTUR%DM (JROF,JLEV) = YDVARS%FSTUR%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%FSTUR%DL (JROF,JLEV) = YDVARS%FSTUR%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%CPF%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%CPF%DM (JROF,JLEV) = YDVARS%CPF%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%CPF%DL (JROF,JLEV) = YDVARS%CPF%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%SPF%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%SPF%DM (JROF,JLEV) = YDVARS%SPF%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%SPF%DL (JROF,JLEV) = YDVARS%SPF%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%CVGQ%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%CVGQ%DM (JROF,JLEV) = YDVARS%CVGQ%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%CVGQ%DL (JROF,JLEV) = YDVARS%CVGQ%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%QVA%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%QVA%DM (JROF,JLEV) = YDVARS%QVA%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%QVA%DL (JROF,JLEV) = YDVARS%QVA%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%LRCH4%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%LRCH4%DM (JROF,JLEV) = YDVARS%LRCH4%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%LRCH4%DL (JROF,JLEV) = YDVARS%LRCH4%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%PHYCTY%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%PHYCTY%DM (JROF,JLEV) = YDVARS%PHYCTY%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%PHYCTY%DL (JROF,JLEV) = YDVARS%PHYCTY%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%RSPEC%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%RSPEC%DM (JROF,JLEV) = YDVARS%RSPEC%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%RSPEC%DL (JROF,JLEV) = YDVARS%RSPEC%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%SDSAT%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%SDSAT%DM (JROF,JLEV) = YDVARS%SDSAT%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%SDSAT%DL (JROF,JLEV) = YDVARS%SDSAT%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%CVV%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%CVV%DM (JROF,JLEV) = YDVARS%CVV%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%CVV%DL (JROF,JLEV) = YDVARS%CVV%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%RKTH%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%RKTH%DM (JROF,JLEV) = YDVARS%RKTH%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%RKTH%DL (JROF,JLEV) = YDVARS%RKTH%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%RKTQV%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%RKTQV%DM (JROF,JLEV) = YDVARS%RKTQV%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%RKTQV%DL (JROF,JLEV) = YDVARS%RKTQV%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%RKTQC%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%RKTQC%DM (JROF,JLEV) = YDVARS%RKTQC%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%RKTQC%DL (JROF,JLEV) = YDVARS%RKTQC%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%UOM%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%UOM%DM (JROF,JLEV) = YDVARS%UOM%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%UOM%DL (JROF,JLEV) = YDVARS%UOM%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%UAL%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%UAL%DM (JROF,JLEV) = YDVARS%UAL%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%UAL%DL (JROF,JLEV) = YDVARS%UAL%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%DOM%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%DOM%DM (JROF,JLEV) = YDVARS%DOM%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%DOM%DL (JROF,JLEV) = YDVARS%DOM%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%DAL%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%DAL%DM (JROF,JLEV) = YDVARS%DAL%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%DAL%DL (JROF,JLEV) = YDVARS%DAL%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%UEN%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%UEN%DM (JROF,JLEV) = YDVARS%UEN%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%UEN%DL (JROF,JLEV) = YDVARS%UEN%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%UNEBH%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%UNEBH%DM (JROF,JLEV) = YDVARS%UNEBH%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%UNEBH%DL (JROF,JLEV) = YDVARS%UNEBH%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF
IF (YDVARS%FSD%LCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      YDVARS%FSD%DM (JROF,JLEV) = YDVARS%FSD%DM (JROF,JLEV) * PGM (JROF)
      YDVARS%FSD%DL (JROF,JLEV) = YDVARS%FSD%DL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF

IF (LHOOK) CALL DR_HOOK("GPMPFC_EXPL_PART2",1,ZHOOK)

END SUBROUTINE
