
SUBROUTINE LATTEX_EXPL_3TL (YDGEOMETRY, YDCPG_BNDS, YDML_GCONF, YDML_DYN, PGFL, YDCPG_SL1, YDVARS)

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK, ONLY : LHOOK, DR_HOOK

USE GEOMETRY_MOD           , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE MODEL_DYNAMICS_MOD     , ONLY : MODEL_DYNAMICS_TYPE
USE CPG_TYPE_MOD           , ONLY : CPG_SL1_TYPE
USE FIELD_VARIABLES_MOD,ONLY : FIELD_VARIABLES


IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE)   ,INTENT(IN)   :: YDCPG_BNDS
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN):: YDML_GCONF
TYPE(MODEL_DYNAMICS_TYPE),INTENT(IN):: YDML_DYN
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_GCONF%YGFL%NDIM)
TYPE(CPG_SL1_TYPE),INTENT(INOUT) :: YDCPG_SL1
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS


LOGICAL :: LLTDIABLIN
INTEGER (KIND=JPIM) :: IPX
INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('LATTEX_EXPL_3TL',0,ZHOOK_HANDLE)

IF(YDML_GCONF%YGFL%YQ%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%Q(JROF,JLEV)=YDCPG_SL1%Q(JROF,JLEV)+YDVARS%Q%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YQ%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%Q(JROF,JLEV)=YDCPG_SL1%Q(JROF,JLEV)+YDCPG_SL1%Q_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YI%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%I(JROF,JLEV)=YDCPG_SL1%I(JROF,JLEV)+YDVARS%I%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YI%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%I(JROF,JLEV)=YDCPG_SL1%I(JROF,JLEV)+YDCPG_SL1%I_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YL%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%L(JROF,JLEV)=YDCPG_SL1%L(JROF,JLEV)+YDVARS%L%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YL%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%L(JROF,JLEV)=YDCPG_SL1%L(JROF,JLEV)+YDCPG_SL1%L_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YLCONV%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%LCONV(JROF,JLEV)=YDCPG_SL1%LCONV(JROF,JLEV)+YDVARS%LCONV%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YLCONV%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%LCONV(JROF,JLEV)=YDCPG_SL1%LCONV(JROF,JLEV)+YDCPG_SL1%LCONV_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YICONV%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%ICONV(JROF,JLEV)=YDCPG_SL1%ICONV(JROF,JLEV)+YDVARS%ICONV%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YICONV%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%ICONV(JROF,JLEV)=YDCPG_SL1%ICONV(JROF,JLEV)+YDCPG_SL1%ICONV_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YRCONV%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%RCONV(JROF,JLEV)=YDCPG_SL1%RCONV(JROF,JLEV)+YDVARS%RCONV%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YRCONV%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%RCONV(JROF,JLEV)=YDCPG_SL1%RCONV(JROF,JLEV)+YDCPG_SL1%RCONV_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YSCONV%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%SCONV(JROF,JLEV)=YDCPG_SL1%SCONV(JROF,JLEV)+YDVARS%SCONV%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YSCONV%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%SCONV(JROF,JLEV)=YDCPG_SL1%SCONV(JROF,JLEV)+YDCPG_SL1%SCONV_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YIRAD%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%IRAD(JROF,JLEV)=YDCPG_SL1%IRAD(JROF,JLEV)+YDVARS%IRAD%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YIRAD%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%IRAD(JROF,JLEV)=YDCPG_SL1%IRAD(JROF,JLEV)+YDCPG_SL1%IRAD_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YLRAD%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%LRAD(JROF,JLEV)=YDCPG_SL1%LRAD(JROF,JLEV)+YDVARS%LRAD%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YLRAD%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%LRAD(JROF,JLEV)=YDCPG_SL1%LRAD(JROF,JLEV)+YDCPG_SL1%LRAD_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YS%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%S(JROF,JLEV)=YDCPG_SL1%S(JROF,JLEV)+YDVARS%S%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YS%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%S(JROF,JLEV)=YDCPG_SL1%S(JROF,JLEV)+YDCPG_SL1%S_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YR%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%R(JROF,JLEV)=YDCPG_SL1%R(JROF,JLEV)+YDVARS%R%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YR%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%R(JROF,JLEV)=YDCPG_SL1%R(JROF,JLEV)+YDCPG_SL1%R_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YG%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%G(JROF,JLEV)=YDCPG_SL1%G(JROF,JLEV)+YDVARS%G%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YG%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%G(JROF,JLEV)=YDCPG_SL1%G(JROF,JLEV)+YDCPG_SL1%G_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YH%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%H(JROF,JLEV)=YDCPG_SL1%H(JROF,JLEV)+YDVARS%H%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YH%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%H(JROF,JLEV)=YDCPG_SL1%H(JROF,JLEV)+YDCPG_SL1%H_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YTKE%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%TKE(JROF,JLEV)=YDCPG_SL1%TKE(JROF,JLEV)+YDVARS%TKE%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YTKE%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%TKE(JROF,JLEV)=YDCPG_SL1%TKE(JROF,JLEV)+YDCPG_SL1%TKE_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YTTE%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%TTE(JROF,JLEV)=YDCPG_SL1%TTE(JROF,JLEV)+YDVARS%TTE%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YTTE%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%TTE(JROF,JLEV)=YDCPG_SL1%TTE(JROF,JLEV)+YDCPG_SL1%TTE_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YEFB1%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%EFB1(JROF,JLEV)=YDCPG_SL1%EFB1(JROF,JLEV)+YDVARS%EFB1%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YEFB1%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%EFB1(JROF,JLEV)=YDCPG_SL1%EFB1(JROF,JLEV)+YDCPG_SL1%EFB1_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YEFB2%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%EFB2(JROF,JLEV)=YDCPG_SL1%EFB2(JROF,JLEV)+YDVARS%EFB2%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YEFB2%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%EFB2(JROF,JLEV)=YDCPG_SL1%EFB2(JROF,JLEV)+YDCPG_SL1%EFB2_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YEFB3%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%EFB3(JROF,JLEV)=YDCPG_SL1%EFB3(JROF,JLEV)+YDVARS%EFB3%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YEFB3%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%EFB3(JROF,JLEV)=YDCPG_SL1%EFB3(JROF,JLEV)+YDCPG_SL1%EFB3_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YA%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%A(JROF,JLEV)=YDCPG_SL1%A(JROF,JLEV)+YDVARS%A%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YA%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%A(JROF,JLEV)=YDCPG_SL1%A(JROF,JLEV)+YDCPG_SL1%A_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YO3%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%O3(JROF,JLEV)=YDCPG_SL1%O3(JROF,JLEV)+YDVARS%O3%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YO3%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%O3(JROF,JLEV)=YDCPG_SL1%O3(JROF,JLEV)+YDCPG_SL1%O3_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YSRC%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%SRC(JROF,JLEV)=YDCPG_SL1%SRC(JROF,JLEV)+YDVARS%SRC%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YSRC%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%SRC(JROF,JLEV)=YDCPG_SL1%SRC(JROF,JLEV)+YDCPG_SL1%SRC_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YMXL%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%MXL(JROF,JLEV)=YDCPG_SL1%MXL(JROF,JLEV)+YDVARS%MXL%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YMXL%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%MXL(JROF,JLEV)=YDCPG_SL1%MXL(JROF,JLEV)+YDCPG_SL1%MXL_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YSHTUR%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%SHTUR(JROF,JLEV)=YDCPG_SL1%SHTUR(JROF,JLEV)+YDVARS%SHTUR%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YSHTUR%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%SHTUR(JROF,JLEV)=YDCPG_SL1%SHTUR(JROF,JLEV)+YDCPG_SL1%SHTUR_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YFQTUR%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%FQTUR(JROF,JLEV)=YDCPG_SL1%FQTUR(JROF,JLEV)+YDVARS%FQTUR%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YFQTUR%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%FQTUR(JROF,JLEV)=YDCPG_SL1%FQTUR(JROF,JLEV)+YDCPG_SL1%FQTUR_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YFSTUR%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%FSTUR(JROF,JLEV)=YDCPG_SL1%FSTUR(JROF,JLEV)+YDVARS%FSTUR%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YFSTUR%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%FSTUR(JROF,JLEV)=YDCPG_SL1%FSTUR(JROF,JLEV)+YDCPG_SL1%FSTUR_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YCPF%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%CPF(JROF,JLEV)=YDCPG_SL1%CPF(JROF,JLEV)+YDVARS%CPF%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YCPF%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%CPF(JROF,JLEV)=YDCPG_SL1%CPF(JROF,JLEV)+YDCPG_SL1%CPF_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YSPF%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%SPF(JROF,JLEV)=YDCPG_SL1%SPF(JROF,JLEV)+YDVARS%SPF%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YSPF%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%SPF(JROF,JLEV)=YDCPG_SL1%SPF(JROF,JLEV)+YDCPG_SL1%SPF_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YCVGQ%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%CVGQ(JROF,JLEV)=YDCPG_SL1%CVGQ(JROF,JLEV)+YDVARS%CVGQ%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YCVGQ%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%CVGQ(JROF,JLEV)=YDCPG_SL1%CVGQ(JROF,JLEV)+YDCPG_SL1%CVGQ_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YQVA%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%QVA(JROF,JLEV)=YDCPG_SL1%QVA(JROF,JLEV)+YDVARS%QVA%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YQVA%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%QVA(JROF,JLEV)=YDCPG_SL1%QVA(JROF,JLEV)+YDCPG_SL1%QVA_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YLRCH4%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%LRCH4(JROF,JLEV)=YDCPG_SL1%LRCH4(JROF,JLEV)+YDVARS%LRCH4%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YLRCH4%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%LRCH4(JROF,JLEV)=YDCPG_SL1%LRCH4(JROF,JLEV)+YDCPG_SL1%LRCH4_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YPHYCTY%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%PHYCTY(JROF,JLEV)=YDCPG_SL1%PHYCTY(JROF,JLEV)+YDVARS%PHYCTY%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YPHYCTY%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%PHYCTY(JROF,JLEV)=YDCPG_SL1%PHYCTY(JROF,JLEV)+YDCPG_SL1%PHYCTY_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YRSPEC%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%RSPEC(JROF,JLEV)=YDCPG_SL1%RSPEC(JROF,JLEV)+YDVARS%RSPEC%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YRSPEC%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%RSPEC(JROF,JLEV)=YDCPG_SL1%RSPEC(JROF,JLEV)+YDCPG_SL1%RSPEC_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YSDSAT%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%SDSAT(JROF,JLEV)=YDCPG_SL1%SDSAT(JROF,JLEV)+YDVARS%SDSAT%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YSDSAT%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%SDSAT(JROF,JLEV)=YDCPG_SL1%SDSAT(JROF,JLEV)+YDCPG_SL1%SDSAT_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YCVV%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%CVV(JROF,JLEV)=YDCPG_SL1%CVV(JROF,JLEV)+YDVARS%CVV%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YCVV%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%CVV(JROF,JLEV)=YDCPG_SL1%CVV(JROF,JLEV)+YDCPG_SL1%CVV_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YRKTH%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%RKTH(JROF,JLEV)=YDCPG_SL1%RKTH(JROF,JLEV)+YDVARS%RKTH%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YRKTH%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%RKTH(JROF,JLEV)=YDCPG_SL1%RKTH(JROF,JLEV)+YDCPG_SL1%RKTH_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YRKTQV%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%RKTQV(JROF,JLEV)=YDCPG_SL1%RKTQV(JROF,JLEV)+YDVARS%RKTQV%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YRKTQV%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%RKTQV(JROF,JLEV)=YDCPG_SL1%RKTQV(JROF,JLEV)+YDCPG_SL1%RKTQV_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YRKTQC%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%RKTQC(JROF,JLEV)=YDCPG_SL1%RKTQC(JROF,JLEV)+YDVARS%RKTQC%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YRKTQC%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%RKTQC(JROF,JLEV)=YDCPG_SL1%RKTQC(JROF,JLEV)+YDCPG_SL1%RKTQC_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YUOM%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%UOM(JROF,JLEV)=YDCPG_SL1%UOM(JROF,JLEV)+YDVARS%UOM%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YUOM%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%UOM(JROF,JLEV)=YDCPG_SL1%UOM(JROF,JLEV)+YDCPG_SL1%UOM_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YUAL%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%UAL(JROF,JLEV)=YDCPG_SL1%UAL(JROF,JLEV)+YDVARS%UAL%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YUAL%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%UAL(JROF,JLEV)=YDCPG_SL1%UAL(JROF,JLEV)+YDCPG_SL1%UAL_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YDOM%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%DOM(JROF,JLEV)=YDCPG_SL1%DOM(JROF,JLEV)+YDVARS%DOM%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YDOM%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%DOM(JROF,JLEV)=YDCPG_SL1%DOM(JROF,JLEV)+YDCPG_SL1%DOM_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YDAL%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%DAL(JROF,JLEV)=YDCPG_SL1%DAL(JROF,JLEV)+YDVARS%DAL%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YDAL%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%DAL(JROF,JLEV)=YDCPG_SL1%DAL(JROF,JLEV)+YDCPG_SL1%DAL_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YUEN%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%UEN(JROF,JLEV)=YDCPG_SL1%UEN(JROF,JLEV)+YDVARS%UEN%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YUEN%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%UEN(JROF,JLEV)=YDCPG_SL1%UEN(JROF,JLEV)+YDCPG_SL1%UEN_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YUNEBH%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%UNEBH(JROF,JLEV)=YDCPG_SL1%UNEBH(JROF,JLEV)+YDVARS%UNEBH%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YUNEBH%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%UNEBH(JROF,JLEV)=YDCPG_SL1%UNEBH(JROF,JLEV)+YDCPG_SL1%UNEBH_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF
IF(YDML_GCONF%YGFL%YFSD%LADV) THEN
! IPX=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%FSD(JROF,JLEV)=YDCPG_SL1%FSD(JROF,JLEV)+YDVARS%FSD%T9(JROF,JLEV)
!     YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=
!   & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!   &+PGFL(JROF,JLEV,YDML_GCONF%YGFL%YCOMP(JGFL)%MP9)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YFSD%LTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%FSD(JROF,JLEV)=YDCPG_SL1%FSD(JROF,JLEV)+YDCPG_SL1%FSD_F(JROF,JLEV)
!       YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!     & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)&
!     &+YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9+IPX+JLEV-YDGEOMETRY%YRDIMV%NFLSA)
      ENDDO
    ENDDO
  ENDIF
ENDIF


IF (LHOOK) CALL DR_HOOK('LATTEX_EXPL_3TL',1,ZHOOK_HANDLE)

END SUBROUTINE
