
SUBROUTINE LAVABO_EXPL_LPHY (YDGEOMETRY, KST, KPROF, YGFL, YDCPG_SL1)

! ** NEVER TESTED **

USE PARKIND1     , ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE CPG_TYPE_MOD , ONLY : CPG_SL1_TYPE
USE YOM_YGFL     , ONLY : TYPE_GFLD

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF
TYPE(TYPE_GFLD)   ,INTENT(IN)    :: YGFL
TYPE(CPG_SL1_TYPE),INTENT(INOUT) :: YDCPG_SL1

INTEGER(KIND=JPIM) :: ISLB1GFLP9

REAL(KIND=JPRB) :: ZHOOK_HANDLE

INTEGER (KIND=JPIM) :: JGFL




IF (LHOOK) CALL DR_HOOK('LAVABO_EXPL_LPHY',0,ZHOOK_HANDLE)

IF (YGFL%YQ%LPHY) THEN
  YDCPG_SL1%Q_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%Q_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YI%LPHY) THEN
  YDCPG_SL1%I_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%I_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YL%LPHY) THEN
  YDCPG_SL1%L_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%L_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YLCONV%LPHY) THEN
  YDCPG_SL1%LCONV_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%LCONV_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YICONV%LPHY) THEN
  YDCPG_SL1%ICONV_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%ICONV_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YRCONV%LPHY) THEN
  YDCPG_SL1%RCONV_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RCONV_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YSCONV%LPHY) THEN
  YDCPG_SL1%SCONV_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SCONV_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YIRAD%LPHY) THEN
  YDCPG_SL1%IRAD_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%IRAD_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YLRAD%LPHY) THEN
  YDCPG_SL1%LRAD_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%LRAD_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YS%LPHY) THEN
  YDCPG_SL1%S_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%S_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YR%LPHY) THEN
  YDCPG_SL1%R_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%R_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YG%LPHY) THEN
  YDCPG_SL1%G_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%G_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YH%LPHY) THEN
  YDCPG_SL1%H_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%H_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YTKE%LPHY) THEN
  YDCPG_SL1%TKE_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%TKE_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YTTE%LPHY) THEN
  YDCPG_SL1%TTE_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%TTE_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YEFB1%LPHY) THEN
  YDCPG_SL1%EFB1_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%EFB1_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YEFB2%LPHY) THEN
  YDCPG_SL1%EFB2_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%EFB2_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YEFB3%LPHY) THEN
  YDCPG_SL1%EFB3_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%EFB3_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YA%LPHY) THEN
  YDCPG_SL1%A_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%A_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YO3%LPHY) THEN
  YDCPG_SL1%O3_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%O3_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YSRC%LPHY) THEN
  YDCPG_SL1%SRC_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SRC_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YMXL%LPHY) THEN
  YDCPG_SL1%MXL_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%MXL_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YSHTUR%LPHY) THEN
  YDCPG_SL1%SHTUR_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SHTUR_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YFQTUR%LPHY) THEN
  YDCPG_SL1%FQTUR_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%FQTUR_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YFSTUR%LPHY) THEN
  YDCPG_SL1%FSTUR_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%FSTUR_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YCPF%LPHY) THEN
  YDCPG_SL1%CPF_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%CPF_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YSPF%LPHY) THEN
  YDCPG_SL1%SPF_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SPF_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YCVGQ%LPHY) THEN
  YDCPG_SL1%CVGQ_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%CVGQ_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YQVA%LPHY) THEN
  YDCPG_SL1%QVA_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%QVA_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YLRCH4%LPHY) THEN
  YDCPG_SL1%LRCH4_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%LRCH4_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YPHYCTY%LPHY) THEN
  YDCPG_SL1%PHYCTY_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%PHYCTY_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YRSPEC%LPHY) THEN
  YDCPG_SL1%RSPEC_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RSPEC_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YSDSAT%LPHY) THEN
  YDCPG_SL1%SDSAT_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SDSAT_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YCVV%LPHY) THEN
  YDCPG_SL1%CVV_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%CVV_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YRKTH%LPHY) THEN
  YDCPG_SL1%RKTH_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RKTH_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YRKTQV%LPHY) THEN
  YDCPG_SL1%RKTQV_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RKTQV_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YRKTQC%LPHY) THEN
  YDCPG_SL1%RKTQC_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RKTQC_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YUOM%LPHY) THEN
  YDCPG_SL1%UOM_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UOM_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YUAL%LPHY) THEN
  YDCPG_SL1%UAL_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UAL_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YDOM%LPHY) THEN
  YDCPG_SL1%DOM_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%DOM_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YDAL%LPHY) THEN
  YDCPG_SL1%DAL_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%DAL_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YUEN%LPHY) THEN
  YDCPG_SL1%UEN_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UEN_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YUNEBH%LPHY) THEN
  YDCPG_SL1%UNEBH_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UNEBH_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF
IF (YGFL%YFSD%LPHY) THEN
  YDCPG_SL1%FSD_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%FSD_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

! DO JGFL=1,YGFL%NUMFLDS
!   IF(YGFL%YCOMP(JGFL)%LPHY) THEN
!     ISLB1GFLP9=YDPTRSLB1%MSLB1GFLP9+(JGFL-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
!     YDCPG_SL1%ZVIEW(KST:KPROF,ISLB1GFLP9)=0.0_JPRB
!     YDCPG_SL1%ZVIEW(KST:KPROF,ISLB1GFLP9+YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
!   ENDIF
! ENDDO

IF (LHOOK) CALL DR_HOOK('LAVABO_EXPL_LPHY',1,ZHOOK_HANDLE)

END SUBROUTINE
