SUBROUTINE LAVABO_PGFL_LPHY (YDGEOMETRY, YGFL, YDPTRSLB1, KST, KPROF, YDCPG_SL1)

USE PARKIND1     , ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOM_YGFL     , ONLY : TYPE_GFLD
USE PTRSLB1      , ONLY : TPTRSLB1
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE CPG_TYPE_MOD , ONLY : CPG_SL1_TYPE

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TYPE_GFLD)   ,INTENT(IN)    :: YGFL
TYPE(TPTRSLB1)    ,INTENT(IN)    :: YDPTRSLB1
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF
TYPE(CPG_SL1_TYPE),INTENT(INOUT) :: YDCPG_SL1

INTEGER(KIND=JPIM) :: ISLB1GFLP9

REAL(KIND=JPRB) :: ZHOOK_HANDLE

INTEGER (KIND=JPIM) :: JGFL

IF (LHOOK) CALL DR_HOOK('LAVABO_PGFL_LPHY',0,ZHOOK_HANDLE)

DO JGFL=1,YGFL%NUMFLDS
  IF(YGFL%YCOMP(JGFL)%LPHY) THEN
    ISLB1GFLP9=YDPTRSLB1%MSLB1GFLP9+(JGFL-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
    YDCPG_SL1%ZVIEW(KST:KPROF,ISLB1GFLP9)=0.0_JPRB
    YDCPG_SL1%ZVIEW(KST:KPROF,ISLB1GFLP9+YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO

IF (LHOOK) CALL DR_HOOK('LAVABO_PGFL_LPHY',1,ZHOOK_HANDLE)

END SUBROUTINE
