SUBROUTINE LAVABO(YDDYNA, YDGEOMETRY,YDCPG_BNDS,YDCPG_OPTS,YDCPG_SL1,YGFL,YDDYN,YDPTRSLB1,LD2TLFF1,LDSLPHY)

!**** *LAVABO*   Semi-Lagrangian scheme.
!                VAlues at the BOundaries: Upper and lower extrapolations.

!     Purpose.
!     --------
!          This subroutine do upper and lower extrapolations of
!          semi-lagrangian quantities for extra-levels JLEV=0
!          and JLEV=NFLEVG+1.
!          Abbreviation "vwv" stands for "vertical wind variable".

!**   Interface.
!     ----------
!        *CALL* *LAVABO(......)

!        Explicit arguments :
!        --------------------

!        INPUT:
!          KST      : first element of work.
!          KPROF    : depth of work.
!          LD2TLFF1 : .T./.F.: Refined treatement of (2*Omega Vec r) at
!                    the origin point when there is t-dt (or t in SL2TL)
!                    physics / Other cases.

!        INPUT/OUTPUT:
!          PB1      : "SLBUF1" buffer for interpolations.

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!         None
!         Called by LACDYN.

!     Reference.
!     ----------
!         Arpege documentation Part I  Chapter 3
!                              Part II Chapter 5 and 6
!         Documentation about semi-Lagrangian scheme.

!     Author.
!     -------
!      K. YESSAD (METEO FRANCE/CNRM/GMAP) after routine
!        CPLGDY1 coded by Maurice IMBARD.
!      Original : APRIL 1992.

! Modifications
! -------------
!   N. Wedi and K. Yessad (Jan 2008): different dev for NH model and PC scheme
!   K. Yessad Aug 2008: rationalisation of dummy argument interfaces
!   F. Vana   15-Oct-2009 : option NSPLTHOI
!   K. Yessad (Nov 2009): prune lpc_old.
!   F. Vana   15-Oct-2009 : diffusion of phys. tendencies (NSPLTHOI=1)
!   K. Yessad (July 2014): Rename some variables.
!   K. Yessad (Dec 2016): Prune obsolete options.
!   K. Yessad (June 2017): Introduce NHQE model.
!   F. Vana    21-Nov-2017: Option LSLDP_CURV + bugfix on SL physics
!   K. Yessad (Feb 2018): remove deep-layer formulations.
!   F. Vana July 2018: RK4 scheme for trajectory research.
! End Modifications
!------------------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE YOMDYNA      , ONLY : TDYNA
USE YOMDYN       , ONLY : TDYN
USE PTRSLB1      , ONLY : TPTRSLB1
USE YOM_YGFL     , ONLY : TYPE_GFLD
USE CPG_TYPE_MOD , ONLY : CPG_SL1_TYPE
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE (TDYNA), INTENT (IN) :: YDDYNA
TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE),INTENT(IN)   :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_SL1_TYPE),INTENT(INOUT) :: YDCPG_SL1
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
TYPE(TPTRSLB1)    ,INTENT(IN)    :: YDPTRSLB1
TYPE(TYPE_GFLD)   ,INTENT(IN)    :: YGFL
 
 
LOGICAL           ,INTENT(IN)    :: LD2TLFF1 
LOGICAL           ,INTENT(IN)    :: LDSLPHY

#include "lavabo_laitvspcqm_part1.intfb.h"
#include "lavabo_laitvspcqm_part2.intfb.h"
#include "lavabo_lphy.intfb.h"

INTEGER (KIND=JPIM) :: JLEV1, JLEV2

!     ------------------------------------------------------------------

REAL(KIND=JPRB) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('LAVABO',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV)
ASSOCIATE(NFLEVG=>YDDIMV%NFLEVG, LSPLTHOIGFL=>YDDYN%LSPLTHOIGFL, NSPDLAG=>YDDYN%NSPDLAG,   NSPLTHOI=>YDDYN%NSPLTHOI,    &
& NSVDLAG=>YDDYN%NSVDLAG, NTLAG=>YDDYN%NTLAG,   NVLAG=>YDDYN%NVLAG, NWLAG=>YDDYN%NWLAG, LSLDP_CURV=>YDDYN%LSLDP_CURV,   &
& LSLDP_RK=>YDDYN%LSLDP_RK)
!     ------------------------------------------------------------------

JLEV1 = 0
JLEV2 = NFLEVG+1

!*       1.    UPPER AND LOWER LATERAL BOUNDARIES CONDITIONS SET TO 0.
!              --------------------------------------------------------

! * P[X]RL0 and P[X]RL9 for [X]=U,V,W:
YDCPG_SL1%UR0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
YDCPG_SL1%UR0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
YDCPG_SL1%VR0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
YDCPG_SL1%VR0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
IF (LSLDP_CURV) THEN
  YDCPG_SL1%ZR0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%ZR0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
ENDIF
YDCPG_SL1%WR0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
YDCPG_SL1%WR0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
IF (LSLDP_RK) THEN
  YDCPG_SL1%UR00(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%UR00(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  YDCPG_SL1%VR00(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%VR00(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  IF (LSLDP_CURV) THEN
    YDCPG_SL1%ZR00(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
    YDCPG_SL1%ZR00(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  ENDIF
  YDCPG_SL1%WR00(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%WR00(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
ENDIF
IF (LD2TLFF1) THEN
  YDCPG_SL1%UR9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%UR9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  YDCPG_SL1%VR9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%VR9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
ENDIF

! * P[X]L0 and P[X]L9 for [X]=U,V,T,advected GFL:
YDCPG_SL1%U9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
YDCPG_SL1%U9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
YDCPG_SL1%V9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
YDCPG_SL1%V9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
YDCPG_SL1%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
YDCPG_SL1%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB

CALL LAVABO_LAITVSPCQM_PART1 (YDGEOMETRY, YGFL, YDPTRSLB1, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_SL1%ZVIEW)

IF (NSPLTHOI /= 0) THEN
  YDCPG_SL1%UF9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%UF9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  YDCPG_SL1%VF9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%VF9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  YDCPG_SL1%TF9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%TF9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
ENDIF

IF (NSPLTHOI /= 0.OR.LSPLTHOIGFL) THEN
  CALL LAVABO_LAITVSPCQM_PART2 (YDGEOMETRY, YGFL, YDPTRSLB1, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_SL1%ZVIEW)
ENDIF

IF (NWLAG /= 2) THEN
  YDCPG_SL1%U0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%U0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  YDCPG_SL1%V0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%V0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
ENDIF
IF (NTLAG /= 2) THEN
  YDCPG_SL1%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
ENDIF

! * P[X]L0 and P[X]L9 for [X]=SPD:
IF (YDCPG_OPTS%LNHEE) THEN
  YDCPG_SL1%PD9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1) = 0.0_JPRB
  YDCPG_SL1%PD9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2) = 0.0_JPRB
  IF (NSPDLAG /= 2) THEN
    YDCPG_SL1%PD0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1) = 0.0_JPRB
    YDCPG_SL1%PD0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2) = 0.0_JPRB
  ENDIF
ENDIF

! * P[X]L0 and P[X]L9 for [X]=SVD,NHX:
IF (YDCPG_OPTS%LNHDYN) THEN
  YDCPG_SL1%VD9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1) = 0.0_JPRB
  YDCPG_SL1%VD9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2) = 0.0_JPRB
  IF (NSPLTHOI /= 0) THEN
    YDCPG_SL1%VDF9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1) = 0.0_JPRB
    YDCPG_SL1%VDF9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2) = 0.0_JPRB
  ENDIF
  IF (YDDYNA%NVDVAR == 4 .OR. YDDYNA%NVDVAR ==5) THEN
    YDCPG_SL1%NHX9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1) = 0.0_JPRB
    YDCPG_SL1%NHX9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2) = 0.0_JPRB
  ENDIF
  IF (NSVDLAG /= 2) THEN
    YDCPG_SL1%VD0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1) = 0.0_JPRB
    YDCPG_SL1%VD0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2) = 0.0_JPRB
  ENDIF
ENDIF

! * P[X]L0 and P[X]L9 for [X]=C (continuity equation):
IF (NVLAG == 2.OR.NVLAG == 3) THEN
  YDCPG_SL1%C9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%C9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  IF (YDDYNA%LSLINLC2) YDCPG_SL1%C9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  IF (YDDYNA%LSLINLC2) YDCPG_SL1%C9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
ENDIF

! * P[X]LP9 for [X]=U,V,T and GFL:
IF( LDSLPHY ) THEN
  ! ky: is it JGFL or YCOMP(JGFL)%MP_SL1 in ISLB1GFLP9?
  ! fv: Yes, it should be JGFL (see the corresponding code in LARCINB). 
  YDCPG_SL1%UP9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%UP9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  YDCPG_SL1%VP9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%VP9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  YDCPG_SL1%TP9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%TP9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB

  CALL LAVABO_LPHY (YDGEOMETRY, YGFL, YDPTRSLB1, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_SL1)

ENDIF

! * P[X]L9_SI (GMV equations):
IF (YDDYNA%LSLINL) THEN
  YDCPG_SL1%U9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%U9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  YDCPG_SL1%V9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%V9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  YDCPG_SL1%T9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%T9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  YDCPG_SL1%VD9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
  YDCPG_SL1%VD9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  IF (YDCPG_OPTS%LNHEE) THEN
    YDCPG_SL1%PD9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV1)=0.0_JPRB
    YDCPG_SL1%PD9_SI(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,JLEV2)=0.0_JPRB
  ENDIF
ENDIF 

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('LAVABO',1,ZHOOK_HANDLE)
END SUBROUTINE LAVABO

