!OPTIONS XOPT(NOEVAL)
SUBROUTINE RECMWF_DUM(YDDIMV,YDMODEL,                     &
 & KIDIA   , KFDIA   , KLON     , KLEV     ,           &
 & PALBD   , PALBP   , PAPRS    , PAPRSF   ,           &
 & PNEB    , PQO3    , PAER     , PDELP    , PEMIS   , &
 & PMU0M   , PQ      , PQSAT    , PQICE    , PQLIQ   , &
 & PS      , PRR     , PLSM     , PT       , PTS     , &
 & PGP2DSPP      , PEZDIAG_POS,&
 & PEMTD   , PEMTU   , PTRSO    , PLWFC    , PLWFT   , &
 & PSWFC   , PSWFT   , PSFSWDIR , PSFSWDIF , PFSDNN  , &
 & PFSDNV  , PCTRSO  , PCEMTR   , PTRSOD   , PTRSODIR, &
 & PTRSODIF,PPIZA_DST,PCGA_DST  ,PTAUREL_DST,&
 & PAERINDS, PGELAM, PGEMU, PGPAR , &
 & PMU0LU , PALB, PVRMOON)

USE TYPE_MODEL , ONLY : MODEL
USE YOMDIMV    , ONLY : TDIMV
USE YOMLSFORC  , ONLY : LMUSCLFA , NMUSCLFA  ! <== Pour MUSC
USE PARKIND1   , ONLY : JPIM     ,JPRB
USE YOMCST     , ONLY : RMD , RMCH4 , RMNO2 , RMN2O  ! RMO3 , RMCO2 , RMCH4 , RMCO, RMHCHO , RMSO2, RMSO4
USE YOMHOOK    , ONLY : LHOOK,   DR_HOOK
USE SPP_MOD    , ONLY : YSPP,    YSPP_CONFIG

IMPLICIT NONE

TYPE(TDIMV)       ,INTENT(IN)    :: YDDIMV
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGELAM(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGEMU(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PALBD(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PALBP(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRS(KLON,KLEV+1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRSF(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNEB(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQO3(KLON,0:KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAER(KLON,KLEV,6) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAERINDS(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDELP(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PEMIS(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMU0M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQ(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQICE(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQLIQ(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLSM(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PT(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTS(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGP2DSPP(KLON,YSPP%N2D)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PEZDIAG_POS(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PPIZA_DST(KLON,KLEV,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCGA_DST(KLON,KLEV,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTAUREL_DST(KLON,KLEV,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PEMTD(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PEMTU(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTRSO(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCTRSO(KLON,2) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCEMTR(KLON,2) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTRSOD(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PLWFC(KLON,2) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PLWFT(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSWFC(KLON,2) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSWFT(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSFSWDIR(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSFSWDIF(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFSDNN(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFSDNV(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTRSODIR(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTRSODIF(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PS(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRR(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGPAR(KLON,YDMODEL%YRML_PHY_MF%YRPARAR%NGPAR+1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMU0LU(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PALB(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PVRMOON(KLON)
END SUBROUTINE RECMWF_DUM
